# CUI // SP-CTI
"""Migration 20260802222900 rollback — drop idp_scorecard_history.

The table is derived data: every row can be regenerated by re-running the
scorecard, minus the historical points themselves. Nothing references it by
foreign key; the only readers are ``tools/idp/score_history.py`` and the
scheduled recorder reflex, both of which degrade to "no history yet" when the
table is absent.
"""
from __future__ import annotations

from tools.db.storage import get_connection


def down(conn=None) -> dict:
    own = conn is None
    conn = conn or get_connection()
    try:
        conn.execute("DROP TABLE IF EXISTS idp_scorecard_history")
        conn.commit()
    finally:
        if own:
            conn.close()
    return {"status": "rolled_back", "dropped": ["idp_scorecard_history"]}


if __name__ == "__main__":
    print(down())
