# CUI // SP-CTI
"""GNS3 Simulation Training Exporter — Phase 2 Pipeline.

Scans data/studio_artifacts/<canvas>/training/*/training_pair.json produced by
gns3_sim.py and ingests them into ft_datasets / ft_dataset_examples for
fine-tuning via /finetune/datasets.

One dataset per canvas (name: icdev-<canvas>-sim) is created or reused.
Each training_pair.json becomes one ft_dataset_examples row (deduped by
content hash).  Quality score: PASS=1.0, WARN=0.7, FAIL≤0.3.

Usage (standalone):
    python tools/studio/sim/training_exporter.py --canvas ddc --json
    python tools/studio/sim/training_exporter.py --all --json
    python tools/studio/sim/training_exporter.py --all --promote-ready --json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_ROOT))

_ARTIFACTS_BASE = _ROOT / "data" / "studio_artifacts"

_CANVAS_SYSTEM_PROMPTS: dict[str, str] = {
    "ddc": "You are an ICDEV™ data infrastructure design AI for the DDC (Data Design Canvas). Given a data topology specification with database nodes, ETL pipelines, and object storage, predict the optimal virtual infrastructure layout, expected probe outcomes, and gate result.",
    "ndc": "You are an ICDEV™ network design AI for the NDC (Network Design Canvas). Given a network topology specification with routers, switches, and firewalls, predict routing convergence, link stability, and probe outcomes.",
    "sdc": "You are an ICDEV™ security design AI for the SDC (Security Design Canvas). Given a security zone topology, predict STIG compliance, attack-path traversal results, and SIEM probe outcomes.",
    "bdc": "You are an ICDEV™ boundary design AI for the BDC (Boundary Design Canvas). Given an enclave topology with ISA enforcement points, predict boundary enforcement probe outcomes and ATO gate results.",
    "pdc": "You are an ICDEV™ pipeline design AI for the PDC (Pipeline Design Canvas). Given a CI/CD pipeline topology, predict build stage connectivity, artifact registry reachability, and deployment probe outcomes.",
    "odc": "You are an ICDEV™ observability design AI for the ODC (Observability Design Canvas). Given a monitoring topology with collectors and dashboards, predict signal flow, alert latency, and SLO probe outcomes.",
    "idc": "You are an ICDEV™ infrastructure design AI for the IDC (Infrastructure Design Canvas). Given a cloud infrastructure topology, predict CSP service availability, IaC apply outcomes, and connectivity probe results.",
    "qdc": "You are an ICDEV™ quality design AI for the QDC (Quality Design Canvas). Given a test environment topology, predict test runner reachability, coverage gate thresholds, and DORA metric probe results.",
    "mdc": "You are an ICDEV™ migration design AI for the MDC (Migration Design Canvas). Given a source/target migration topology, predict wave cut-over feasibility, data fidelity probe outcomes, and migration gate results.",
    "aadc": "You are an ICDEV™ agentic AI design AI for the AADC (Agentic AI Design Canvas). Given an agent workflow topology with LLM endpoints and tool sandboxes, predict agent chain execution outcomes and safety probe results.",
    "aimc": "You are an ICDEV™ ML pipeline design AI for the AIMC (AI Model Canvas). Given a training pipeline topology, predict model registry reachability, evaluation harness probe outcomes, and deployment gate results.",
    "ohc": "You are an ICDEV™ operations design AI for the OHC (Operations Health Canvas). Given an ops topology with runbook executors and SLA monitors, predict incident response time probes and ops gate results.",
}

_DEFAULT_SYSTEM_PROMPT = (
    "You are an ICDEV™ Studio simulation AI. Given a canvas topology specification, "
    "predict the virtual infrastructure layout, probe outcomes, and gate result."
)


def _quality_score(gate: str) -> float:
    return {"PASS": 1.0, "WARN": 0.7}.get(gate, 0.3)


def _find_training_pairs(canvas: str) -> list[Path]:
    base = _ARTIFACTS_BASE / canvas / "training"
    if not base.exists():
        return []
    return sorted(base.rglob("training_pair.json"))


def _get_or_create_dataset(canvas: str, run_id: str = "") -> str:
    """Return dataset_id for the canvas sim dataset, creating it if needed."""
    from tools.finetune.dataset_manager import list_datasets, create_dataset
    name = f"icdev-{canvas}-sim"
    existing = list_datasets()
    for ds in existing.get("datasets", []):
        if ds["name"] == name:
            return ds["id"]
    result = create_dataset(
        name=name,
        purpose="general",
        description=f"GNS3+Cloud simulation training pairs for the {canvas.upper()} canvas. "
                    f"Auto-generated by tools/studio/sim/training_exporter.py.",
        base_model="qwen3:latest",
        classification="CUI",
        created_by="gns3_sim_exporter",
    )
    if not result.get("success"):
        raise RuntimeError(f"Failed to create dataset for {canvas}: {result.get('error')}")
    return result["dataset_id"]


def export_canvas(canvas: str, promote_ready: bool = False) -> dict[str, Any]:
    pairs = _find_training_pairs(canvas)
    if not pairs:
        return {"canvas": canvas, "pairs_found": 0, "examples_added": 0, "skipped": 0}

    from tools.finetune.dataset_manager import add_example
    ds_id = _get_or_create_dataset(canvas)
    system_prompt = _CANVAS_SYSTEM_PROMPTS.get(canvas, _DEFAULT_SYSTEM_PROMPT)

    added = skipped = errors = 0
    for pair_path in pairs:
        try:
            pair = json.loads(pair_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            errors += 1
            continue

        gate = pair.get("gate", "FAIL")
        topology_input = pair.get("input", {})
        output_data = pair.get("output", {})

        user_input = json.dumps(topology_input, separators=(",", ":"))
        expected_output = json.dumps({
            "gate": gate,
            "probes": output_data.get("probes", []),
            # `emulator` since flx-sim-01; `localstack` is the pre-rename key
            # and is still READ so training pairs already on disk keep parsing.
            # An artifact is a record of a run that happened -- rewriting the
            # reader is the only way to keep it readable, and dropping the old
            # key would silently export `{}` for every historical pair.
            "emulator": output_data.get("emulator",
                                        output_data.get("localstack", {})),
        }, separators=(",", ":"))

        result = add_example(
            dataset_id=ds_id,
            user_input=user_input,
            expected_output=expected_output,
            system_prompt=system_prompt,
            source="rag_auto_generated",
            source_chunk_id=pair.get("uid", ""),
            source_document_id=pair_path.relative_to(_ROOT).as_posix(),
            classification="CUI",
        )
        if result.get("success"):
            added += 1
        elif "Duplicate" in result.get("error", ""):
            skipped += 1
        else:
            errors += 1

    # Sync example_count and optionally promote to ready
    if added > 0 or skipped > 0:
        _sync_example_count(ds_id)
    if promote_ready:
        try:
            from tools.finetune.dataset_manager import get_dataset, update_dataset_status
            ds = get_dataset(ds_id)
            if ds.get("success") and ds["dataset"].get("example_count", 0) >= 5:
                update_dataset_status(ds_id, "ready")
        except Exception:
            pass

    return {
        "canvas": canvas,
        "dataset_id": ds_id,
        "pairs_found": len(pairs),
        "examples_added": added,
        "skipped_duplicate": skipped,
        "errors": errors,
    }


def _sync_example_count(dataset_id: str) -> None:
    """Update ft_datasets.example_count to match the actual row count."""
    try:
        from tools.db.storage import get_connection
        conn = get_connection()
        conn.execute(
            """UPDATE ft_datasets
               SET example_count = (
                   SELECT COUNT(*) FROM ft_dataset_examples
                   WHERE dataset_id = %s
               ), updated_at = datetime('now')
               WHERE id = %s""",
            (dataset_id, dataset_id),
        )
        conn.commit()
        conn.close()
    except Exception:
        pass


def export_all(promote_ready: bool = False) -> list[dict[str, Any]]:
    canvases = [p.name for p in _ARTIFACTS_BASE.iterdir()
                if p.is_dir() and (p / "training").exists()]
    results = []
    for canvas in sorted(canvases):
        results.append(export_canvas(canvas, promote_ready=promote_ready))
    return results


def main() -> None:
    parser = argparse.ArgumentParser(description="GNS3 Simulation Training Exporter")
    parser.add_argument("--canvas", default="", help="Single canvas to export (e.g. ddc)")
    parser.add_argument("--all", action="store_true", help="Export all canvases")
    parser.add_argument("--promote-ready", action="store_true",
                        help="Set dataset status=ready when example_count >= 5")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    if args.canvas:
        result = export_canvas(args.canvas, promote_ready=args.promote_ready)
        print(json.dumps(result, indent=2))
    elif getattr(args, "all"):
        results = export_all(promote_ready=args.promote_ready)
        total_added = sum(r["examples_added"] for r in results)
        print(json.dumps({"canvases": len(results), "total_added": total_added, "detail": results}, indent=2))
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
