# CUI // SP-CTI
"""SIPA — Software Integrity & Provenance Assessor — Provenance linkage (sipa-prov-01).

After scoring, every assessment is recorded in the W3C PROV graph (D287) and the
unified source-citation registry so its disposition is queryable cross-subsystem
and auditable end-to-end. :func:`record_assessment_provenance` writes, threaded on
the engine's single RLS-aware connection:

  * a **prov_entity** (``entity_type='report'``, ``content_hash=dir_digest``) — the
    assessment *report* artifact, fingerprinted by the staged-tree digest so the
    provenance node is tamper-anchored to the exact bytes that were assessed;
  * a **prov_activity** (``activity_type='integrity_assessment'``) — the assessment
    *run* that produced the verdict;
  * a **wasGeneratedBy** relation (report ``wasGeneratedBy`` assessment) — the
    verdict's provenance edge (the report entity was generated by the assessment
    activity); and
  * a **source_citation_registry** row (``citation_type='prov_entity'``) pointing at
    the prov_entity, carrying a **trust score** derived from the verdict / risk
    score, so the assessment participates in trust-weighted provenance queries.

**Mode A (provenance-aware) only** — for every *authorized* capability the
reconciler matched to an intake requirement, a **wasDerivedFrom** relation links
the exercised capability to the authorizing ``requirement_id``
(``capability wasDerivedFrom requirement``). Combined with the ``integrity_capabilities``
rows (file_path -> capability_type, the *code -> capability* leg), the full chain
``code -> capability -> requirement`` becomes queryable via ``prov_relations``.

This mirrors :class:`tools.observability.provenance.prov_recorder.ProvRecorder` and
:mod:`tools.provenance.registry` exactly — same tables, same columns, same
entity/activity/relation shapes. When **no connection is supplied** (standalone /
CLI use) it delegates to ``ProvRecorder`` + ``register_citation`` (each opening its
own RLS-aware connection against the real DB); when the **engine threads its
connection** the identical rows are written on that connection so the provenance
commits in the same transaction / tenant context as the findings.

Static-only and best-effort: provenance recording never executes the target and a
failure here (a missing prov table, a digest hiccup) is swallowed by the engine so
it can never abort an assessment — the verdict already stands on the append-only
``integrity_verdicts`` row.
"""
from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

# Reuse ingest's caller-context helper so prov rows carry the same classification
# the findings do (prov_* / registry have no tenant_id column — RLS-free, like the
# core D287 tables — so only classification + project_id are stamped).
from tools.integrity.ingest import _caller_context

from tools.logging.icdev_logger import get_logger

logger = get_logger("icdev.integrity.provenance")

# PROV vocabulary tokens (D287 — mirror ProvRecorder's documented enums).
ENTITY_TYPE = "report"               # the assessment report artifact
ACTIVITY_TYPE = "integrity_assessment"  # the assessment run
REL_GENERATED_BY = "wasGeneratedBy"  # report wasGeneratedBy assessment
REL_DERIVED_FROM = "wasDerivedFrom"  # capability wasDerivedFrom requirement (Mode A)

# Registry citation type — the assessment is registered as the prov_entity it
# produced (matches source_citation_registry's CHECK + registry.index_existing).
CITATION_TYPE = "prov_entity"

# Stable URN prefixes for the Mode A capability -> requirement edges. The capability
# node is keyed by (assessment_id, capability_type) so the edge is unambiguous even
# when the same requirement authorizes several capabilities.
_CAP_URN = "urn:icdev:integrity:capability"
_REQ_URN = "urn:icdev:integrity:requirement"


# --------------------------------------------------------------------------- #
# Backend helpers (mirror the sibling modules' handling)
# --------------------------------------------------------------------------- #
def _backend_of(conn: Any) -> str:
    """Resolve the backend ('postgresql' | 'sqlite') for a live connection."""
    declared = getattr(conn, "_backend", None)
    if declared:
        return "postgresql" if str(declared).lower().startswith(("postgre", "pg")) else "sqlite"
    backend = os.environ.get("ICDEV_STORAGE_BACKEND", "postgresql").lower()
    return "postgresql" if backend in ("postgresql", "postgres", "pg") else "sqlite"


def _q(conn: Any, sql: str) -> str:
    """Translate ``?`` placeholders to ``%s`` for the PostgreSQL backend."""
    return sql.replace("?", "%s") if _backend_of(conn) == "postgresql" else sql


# SQLite-flavored DDL for the D287 prov tables + the citation registry. Only run
# on the SQLite backend (tests / air-gap) — on PostgreSQL these are provisioned by
# tools/db/init_icdev_db.py (and migration 149 for the registry), so we never issue
# this DDL there (the SQLite ``AUTOINCREMENT`` syntax would not parse on PG).
_SQLITE_DDL = """
CREATE TABLE IF NOT EXISTS prov_entities (
    id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    label TEXT,
    content_hash TEXT,
    content TEXT,
    attributes TEXT,
    trace_id TEXT,
    span_id TEXT,
    agent_id TEXT,
    project_id TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS prov_activities (
    id TEXT PRIMARY KEY,
    activity_type TEXT NOT NULL,
    label TEXT,
    start_time TEXT,
    end_time TEXT,
    attributes TEXT,
    trace_id TEXT,
    span_id TEXT,
    agent_id TEXT,
    project_id TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS prov_relations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    relation_type TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    object_id TEXT NOT NULL,
    attributes TEXT,
    trace_id TEXT,
    project_id TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS source_citation_registry (
    id TEXT PRIMARY KEY,
    citation_type TEXT NOT NULL,
    source_table TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_doc TEXT,
    source_hash TEXT NOT NULL,
    anchor_hash TEXT,
    merkle_root TEXT,
    blockchain_tx_id TEXT,
    classification TEXT DEFAULT 'CUI',
    project_id TEXT,
    trust_score REAL DEFAULT 0.0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
"""


def _ensure_tables(conn: Any) -> None:
    """Create the prov + registry tables on SQLite; no-op on PostgreSQL.

    On the real PostgreSQL backend these tables already exist (init_icdev_db /
    migration 149); on the in-memory SQLite used by tests / air-gap we provision
    the minimal compatible schema so the threaded writes land.
    """
    if _backend_of(conn) != "sqlite":
        return
    cur = conn.cursor()
    for stmt in _SQLITE_DDL.split(";"):
        stmt = stmt.strip()
        if stmt:
            cur.execute(stmt)
    conn.commit()


# --------------------------------------------------------------------------- #
# Trust score — verdict / risk -> [0, 1] confidence the artifact is benign
# --------------------------------------------------------------------------- #
def trust_score_for(verdict: Optional[str], risk_score: Optional[float]) -> float:
    """Map a verdict + 0–100 risk score to a [0, 1] trust score for the registry.

    Higher == more trustworthy. The base is ``1 - risk/100`` (a clean ALLOW with a
    low risk score approaches 1.0); the verdict then caps it so a REVIEW can never
    register as highly trusted and a QUARANTINE is always low-trust regardless of a
    gamed-down numeric score:

        allow      -> base (no cap)
        review     -> min(base, 0.60)
        quarantine -> min(base, 0.20)

    Returns a value clamped to ``[0.0, 1.0]`` and rounded to 4 dp.
    """
    try:
        risk = float(risk_score) if risk_score is not None else 0.0
    except (TypeError, ValueError):
        risk = 0.0
    base = 1.0 - (risk / 100.0)
    v = (verdict or "").strip().lower()
    if v == "quarantine":
        base = min(base, 0.20)
    elif v == "review":
        base = min(base, 0.60)
    return round(max(0.0, min(1.0, base)), 4)


# --------------------------------------------------------------------------- #
# Mode A — authorized-capability -> requirement edges
# --------------------------------------------------------------------------- #
def _authorized_edges(
    assessment_id: int, allowed_capabilities: Optional[dict]
) -> list[dict]:
    """Build the ``capability wasDerivedFrom requirement`` edges for Mode A.

    ``allowed_capabilities`` is the reconciler's
    ``{capability_type: [{"requirement_id", "phrases"}, ...]}`` map (the authorizing
    requirement(s) per capability). One edge is emitted per (capability, requirement)
    pair so the chain ``code -> capability -> requirement`` is fully traversable.
    Requirements with a null id are skipped (nothing concrete to link to).
    """
    edges: list[dict] = []
    for cap_type, authorizers in (allowed_capabilities or {}).items():
        for auth in authorizers or []:
            req_id = (auth or {}).get("requirement_id")
            if req_id is None:
                continue
            edges.append(
                {
                    "subject_id": f"{_CAP_URN}:{assessment_id}:{cap_type}",
                    "object_id": f"{_REQ_URN}:{req_id}",
                    "attributes": {
                        "assessment_id": assessment_id,
                        "capability_type": cap_type,
                        "requirement_id": str(req_id),
                        "phrases": (auth or {}).get("phrases"),
                        "relation": "authorized_by",
                    },
                }
            )
    return edges


# --------------------------------------------------------------------------- #
# Threaded (engine-connection) inserts — identical shape to ProvRecorder/registry
# --------------------------------------------------------------------------- #
_ENTITY_SQL = (
    "INSERT INTO prov_entities "
    "(id, entity_type, label, content_hash, content, attributes, trace_id, "
    "span_id, agent_id, project_id, classification) "
    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
)
_ACTIVITY_SQL = (
    "INSERT INTO prov_activities "
    "(id, activity_type, label, start_time, end_time, attributes, trace_id, "
    "span_id, agent_id, project_id, classification) "
    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
)
_RELATION_SQL = (
    "INSERT INTO prov_relations "
    "(relation_type, subject_id, object_id, attributes, trace_id, project_id, classification) "
    "VALUES (?, ?, ?, ?, ?, ?, ?)"
)
_REGISTRY_SQL = (
    "INSERT INTO source_citation_registry "
    "(id, citation_type, source_table, source_record_id, source_doc, source_hash, "
    "anchor_hash, merkle_root, blockchain_tx_id, classification, project_id, trust_score, created_at) "
    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
)


def _record_threaded(
    conn: Any,
    assessment_id: int,
    dir_digest: Optional[str],
    verdict: str,
    risk_score: float,
    mode: str,
    project_id: Optional[str],
    trust: float,
    edges: list[dict],
) -> dict:
    """Write the prov entity/activity/relations + registry row on ``conn``."""
    _ensure_tables(conn)
    _tenant, classification, _created_by = _caller_context()
    now = datetime.now(timezone.utc).isoformat()

    entity_id = str(uuid.uuid4())
    activity_id = str(uuid.uuid4())
    label = f"integrity assessment {assessment_id} -> {verdict}"
    attrs = json.dumps(
        {
            "assessment_id": assessment_id,
            "verdict": verdict,
            "risk_score": risk_score,
            "mode": mode,
        }
    )

    # prov_entity — the report artifact, fingerprinted by the staged-tree digest.
    conn.execute(
        _q(conn, _ENTITY_SQL),
        (
            entity_id, ENTITY_TYPE, label, dir_digest, None, attrs,
            None, None, "integrity_engine", project_id, classification,
        ),
    )
    # prov_activity — the assessment run.
    conn.execute(
        _q(conn, _ACTIVITY_SQL),
        (
            activity_id, ACTIVITY_TYPE, label, now, now, attrs,
            None, None, "integrity_engine", project_id, classification,
        ),
    )
    # wasGeneratedBy — the report (verdict) was generated by the assessment run.
    conn.execute(
        _q(conn, _RELATION_SQL),
        (REL_GENERATED_BY, entity_id, activity_id, attrs, None, project_id, classification),
    )

    # Mode A: capability wasDerivedFrom requirement edges (code -> cap -> requirement).
    for edge in edges:
        conn.execute(
            _q(conn, _RELATION_SQL),
            (
                REL_DERIVED_FROM,
                edge["subject_id"],
                edge["object_id"],
                json.dumps(edge["attributes"]),
                None,
                project_id,
                classification,
            ),
        )

    # source_citation_registry — register the prov_entity with the trust score.
    registry_id = f"scr-{uuid.uuid4().hex[:16]}"
    conn.execute(
        _q(conn, _REGISTRY_SQL),
        (
            registry_id, CITATION_TYPE, "prov_entities", entity_id,
            f"integrity_assessment:{assessment_id}", dir_digest or entity_id,
            None, None, None, classification, project_id, trust, now,
        ),
    )
    conn.commit()

    return {
        "entity_id": entity_id,
        "activity_id": activity_id,
        "registry_id": registry_id,
        "trust_score": trust,
        "authorized_edges": len(edges),
    }


def _record_standalone(
    assessment_id: int,
    dir_digest: Optional[str],
    verdict: str,
    risk_score: float,
    mode: str,
    project_id: Optional[str],
    trust: float,
    edges: list[dict],
) -> dict:
    """Own-connection path: drive ProvRecorder + register_citation against the real DB.

    Used when the engine does not thread a connection (direct / CLI use). Produces
    the identical rows as :func:`_record_threaded`, but each helper opens its own
    RLS-aware connection (ProvRecorder / register_citation defaults).
    """
    from tools.observability.provenance.prov_recorder import ProvRecorder
    from tools.provenance.registry import register_citation

    recorder = ProvRecorder(agent_id="integrity_engine", project_id=project_id)
    label = f"integrity assessment {assessment_id} -> {verdict}"
    attrs = {
        "assessment_id": assessment_id,
        "verdict": verdict,
        "risk_score": risk_score,
        "mode": mode,
    }
    entity_id = recorder.record_entity(
        ENTITY_TYPE, label, content_hash=dir_digest, attributes=attrs
    )
    activity_id = recorder.record_activity(ACTIVITY_TYPE, label, attributes=attrs)
    if entity_id and activity_id:
        recorder.record_relation(REL_GENERATED_BY, entity_id, activity_id, attributes=attrs)
        for edge in edges:
            recorder.record_relation(
                REL_DERIVED_FROM, edge["subject_id"], edge["object_id"],
                attributes=edge["attributes"],
            )

    registry_id = ""
    if entity_id:
        registry_id = register_citation(
            citation_type=CITATION_TYPE,
            source_table="prov_entities",
            source_record_id=entity_id,
            source_hash=dir_digest or entity_id,
            source_doc=f"integrity_assessment:{assessment_id}",
            project_id=project_id,
            trust_score=trust,
        )

    return {
        "entity_id": entity_id,
        "activity_id": activity_id,
        "registry_id": registry_id,
        "trust_score": trust,
        "authorized_edges": len(edges),
    }


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #
def record_assessment_provenance(
    assessment_id: int,
    dir_digest: Optional[str],
    verdict: str,
    risk_score: float,
    mode: str,
    project_id: Optional[str] = None,
    allowed_capabilities: Optional[dict] = None,
    conn: Any = None,
) -> dict:
    """Record an assessment + verdict in the PROV graph and citation registry.

    Writes a ``prov_entity`` (the report, ``content_hash=dir_digest``), a
    ``prov_activity`` (the ``integrity_assessment`` run), a ``wasGeneratedBy``
    relation (report wasGeneratedBy assessment), and a ``source_citation_registry``
    row (``citation_type='prov_entity'``) with a trust score derived from
    ``verdict`` / ``risk_score``. In ``provenance_aware`` (Mode A) every authorized
    capability in ``allowed_capabilities`` also gets a ``wasDerivedFrom`` edge to
    its authorizing ``requirement_id`` so ``code -> capability -> requirement`` is
    queryable.

    Args:
        assessment_id: the ``integrity_assessments`` row this provenance describes.
        dir_digest: the SHA-256 staged-tree digest — the report entity's
            ``content_hash`` and the citation's ``source_hash`` (tamper anchor).
        verdict: the canonical lowercase verdict token (allow / review / quarantine).
        risk_score: the 0–100 risk score (drives the trust score).
        mode: the resolved assessment mode (``provenance_aware`` /
            ``provenance_blind``); only the aware mode emits requirement edges.
        project_id: provenance handle stamped on every prov / registry row.
        allowed_capabilities: Mode A reconciler map
            ``{capability_type: [{"requirement_id", "phrases"}, ...]}`` — the
            authorizing requirement(s) per capability (ignored in Mode B).
        conn: optional engine connection to thread (prov rows commit in the same
            transaction / tenant context as the findings); when ``None`` the
            ProvRecorder / register_citation own-connection path runs against the
            real DB.

    Returns:
        ``{"entity_id", "activity_id", "registry_id", "trust_score",
        "authorized_edges"}``.
    """
    trust = trust_score_for(verdict, risk_score)
    edges = (
        _authorized_edges(assessment_id, allowed_capabilities)
        if str(mode).strip().lower() == "provenance_aware"
        else []
    )

    if conn is not None:
        return _record_threaded(
            conn, assessment_id, dir_digest, verdict, risk_score, mode,
            project_id, trust, edges,
        )
    return _record_standalone(
        assessment_id, dir_digest, verdict, risk_score, mode, project_id, trust, edges,
    )
