#!/usr/bin/env python3
# CUI // SP-CTI
"""Auto-generated tests for tools.builder.forge_validator.

Generated by Genesis Test Reflex using api_surface_extractor.
Tests validate importability, function signatures, return types,
and basic invocation patterns.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pytest


# --- Module Import ---

def test_forge_validator_imports():
    """Verify module can be imported without errors."""
    try:
        import tools.builder.forge_validator  # noqa: F401
    except ImportError as e:
        pytest.skip(f"Import dependency missing: {e}")


# --- Function Signature Tests ---

def test_forge_validator_validate_exists():
    """Verify validate exists and is callable."""
    try:
        from tools.builder.forge_validator import validate
        assert callable(validate), 'validate is not callable'
    except ImportError:
        pytest.skip("Module not importable")

def test_forge_validator_validate_signature():
    """Verify validate accepts expected parameters."""
    import inspect
    try:
        from tools.builder.forge_validator import validate
        sig = inspect.signature(validate)
        params = list(sig.parameters.keys())
        assert "project_dir" in params, f"Missing parameter \"project_dir\" in {params}"
    except ImportError:
        pytest.skip("Module not importable")

def test_forge_validator_main_exists():
    """Verify main exists and is callable."""
    try:
        from tools.builder.forge_validator import main
        assert callable(main), 'main is not callable'
    except ImportError:
        pytest.skip("Module not importable")


# --- Class Tests ---

def test_forge_validator_GotchaCheck_exists():
    """Verify class GotchaCheck exists."""
    try:
        from tools.builder.forge_validator import GotchaCheck
        assert isinstance(GotchaCheck, type), 'GotchaCheck is not a class'
    except ImportError:
        pytest.skip("Module not importable")

def test_forge_validator_GotchaCheck_methods():
    """Verify GotchaCheck has expected public methods."""
    try:
        from tools.builder.forge_validator import GotchaCheck
        assert hasattr(GotchaCheck, "to_dict"), "Missing method to_dict"
    except ImportError:
        pytest.skip("Module not importable")

def test_forge_validator_GotchaReport_exists():
    """Verify class GotchaReport exists."""
    try:
        from tools.builder.forge_validator import GotchaReport
        assert isinstance(GotchaReport, type), 'GotchaReport is not a class'
    except ImportError:
        pytest.skip("Module not importable")

def test_forge_validator_GotchaReport_methods():
    """Verify GotchaReport has expected public methods."""
    try:
        from tools.builder.forge_validator import GotchaReport
        assert hasattr(GotchaReport, "to_dict"), "Missing method to_dict"
    except ImportError:
        pytest.skip("Module not importable")
