#!/usr/bin/env python3
# CUI // SP-CTI
"""Auto-generated tests for tools.modernization.migration_report_generator.

Generated by Genesis Test Reflex using api_surface_extractor.
Tests validate importability, function signatures, return types,
and basic invocation patterns.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pytest


# --- Module Import ---


def test_migration_report_generator_imports():
    """Verify module can be imported without errors."""
    try:
        import tools.modernization.migration_report_generator  # noqa: F401
    except ImportError as e:
        pytest.skip(f"Import dependency missing: {e}")


# --- Function Signature Tests ---


def test_migration_report_generator_generate_assessment_report_exists():
    """Verify generate_assessment_report exists and is callable."""
    try:
        from tools.modernization.migration_report_generator import generate_assessment_report

        assert callable(generate_assessment_report), "generate_assessment_report is not callable"
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_assessment_report_signature():
    """Verify generate_assessment_report accepts expected parameters."""
    import inspect

    try:
        from tools.modernization.migration_report_generator import generate_assessment_report

        sig = inspect.signature(generate_assessment_report)
        params = list(sig.parameters.keys())
        assert "app_id" in params, f'Missing parameter "app_id" in {params}'
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_progress_report_exists():
    """Verify generate_progress_report exists and is callable."""
    try:
        from tools.modernization.migration_report_generator import generate_progress_report

        assert callable(generate_progress_report), "generate_progress_report is not callable"
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_progress_report_signature():
    """Verify generate_progress_report accepts expected parameters."""
    import inspect

    try:
        from tools.modernization.migration_report_generator import generate_progress_report

        sig = inspect.signature(generate_progress_report)
        params = list(sig.parameters.keys())
        assert "plan_id" in params, f'Missing parameter "plan_id" in {params}'
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_ato_impact_report_exists():
    """Verify generate_ato_impact_report exists and is callable."""
    try:
        from tools.modernization.migration_report_generator import generate_ato_impact_report

        assert callable(generate_ato_impact_report), "generate_ato_impact_report is not callable"
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_ato_impact_report_signature():
    """Verify generate_ato_impact_report accepts expected parameters."""
    import inspect

    try:
        from tools.modernization.migration_report_generator import generate_ato_impact_report

        sig = inspect.signature(generate_ato_impact_report)
        params = list(sig.parameters.keys())
        assert "plan_id" in params, f'Missing parameter "plan_id" in {params}'
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_executive_summary_exists():
    """Verify generate_executive_summary exists and is callable."""
    try:
        from tools.modernization.migration_report_generator import generate_executive_summary

        assert callable(generate_executive_summary), "generate_executive_summary is not callable"
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_executive_summary_signature():
    """Verify generate_executive_summary accepts expected parameters."""
    import inspect

    try:
        from tools.modernization.migration_report_generator import generate_executive_summary

        sig = inspect.signature(generate_executive_summary)
        params = list(sig.parameters.keys())
        assert "app_id" in params, f'Missing parameter "app_id" in {params}'
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_all_reports_exists():
    """Verify generate_all_reports exists and is callable."""
    try:
        from tools.modernization.migration_report_generator import generate_all_reports

        assert callable(generate_all_reports), "generate_all_reports is not callable"
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_generate_all_reports_signature():
    """Verify generate_all_reports accepts expected parameters."""
    import inspect

    try:
        from tools.modernization.migration_report_generator import generate_all_reports

        sig = inspect.signature(generate_all_reports)
        params = list(sig.parameters.keys())
        assert "app_id" in params, f'Missing parameter "app_id" in {params}'
    except ImportError:
        pytest.skip("Module not importable")


def test_migration_report_generator_main_exists():
    """Verify main exists and is callable."""
    try:
        from tools.modernization.migration_report_generator import main

        assert callable(main), "main is not callable"
    except ImportError:
        pytest.skip("Module not importable")


# --- Constants ---


def test_migration_report_generator_constants():
    """Verify module exports expected constants."""
    try:
        import tools.modernization.migration_report_generator as mod

        assert hasattr(mod, "CUI_BANNER_TEXT"), "Missing constant CUI_BANNER_TEXT"
        assert hasattr(mod, "DISTRIBUTION_STMT"), "Missing constant DISTRIBUTION_STMT"
    except ImportError:
        pytest.skip("Module not importable")
