#!/usr/bin/env python3
# CUI // SP-CTI
"""Auto-generated tests for tools.builder.claude_md_generator.

Generated by Genesis Test Reflex using api_surface_extractor.
Tests validate importability, function signatures, return types,
and basic invocation patterns.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pytest


# --- Module Import ---


def test_claude_md_generator_imports():
    """Verify module can be imported without errors."""
    try:
        import tools.builder.claude_md_generator  # noqa: F401
    except ImportError as e:
        pytest.skip(f"Import dependency missing: {e}")


# --- Function Signature Tests ---


def test_claude_md_generator_audit_log_event_exists():
    """Verify audit_log_event exists and is callable."""
    try:
        from tools.builder.claude_md_generator import audit_log_event

        assert callable(audit_log_event), "audit_log_event is not callable"
    except ImportError:
        pytest.skip("Module not importable")


def test_claude_md_generator_generate_claude_md_exists():
    """Verify generate_claude_md exists and is callable."""
    try:
        from tools.builder.claude_md_generator import generate_claude_md

        assert callable(generate_claude_md), "generate_claude_md is not callable"
    except ImportError:
        pytest.skip("Module not importable")


def test_claude_md_generator_generate_claude_md_signature():
    """Verify generate_claude_md accepts expected parameters."""
    import inspect

    try:
        from tools.builder.claude_md_generator import generate_claude_md

        sig = inspect.signature(generate_claude_md)
        params = list(sig.parameters.keys())
        assert "blueprint" in params, f'Missing parameter "blueprint" in {params}'
    except ImportError:
        pytest.skip("Module not importable")


def test_claude_md_generator_main_exists():
    """Verify main exists and is callable."""
    try:
        from tools.builder.claude_md_generator import main

        assert callable(main), "main is not callable"
    except ImportError:
        pytest.skip("Module not importable")


# --- Constants ---


def test_claude_md_generator_constants():
    """Verify module exports expected constants."""
    try:
        import tools.builder.claude_md_generator as mod

        assert hasattr(mod, "CLAUDE_MD_TEMPLATE"), "Missing constant CLAUDE_MD_TEMPLATE"
    except ImportError:
        pytest.skip("Module not importable")
