#!/usr/bin/env python3
# CUI // SP-CTI
"""Auto-generated tests for tools.ai_augmentation.pattern_classifier.

Generated by Genesis Test Reflex using api_surface_extractor.
Tests validate importability, function signatures, return types,
and basic invocation patterns.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pytest


# --- Module Import ---

def test_pattern_classifier_imports():
    """Verify module can be imported without errors."""
    try:
        import tools.ai_augmentation.pattern_classifier  # noqa: F401
    except ImportError as e:
        pytest.skip(f"Import dependency missing: {e}")


# --- Function Signature Tests ---

def test_pattern_classifier_detect_patterns_exists():
    """Verify detect_patterns exists and is callable."""
    try:
        from tools.ai_augmentation.pattern_classifier import detect_patterns
        assert callable(detect_patterns), 'detect_patterns is not callable'
    except ImportError:
        pytest.skip("Module not importable")

def test_pattern_classifier_detect_patterns_signature():
    """Verify detect_patterns accepts expected parameters."""
    import inspect
    try:
        from tools.ai_augmentation.pattern_classifier import detect_patterns
        sig = inspect.signature(detect_patterns)
        params = list(sig.parameters.keys())
        assert "target_path" in params, f"Missing parameter \"target_path\" in {params}"
    except ImportError:
        pytest.skip("Module not importable")


# --- Constants ---

def test_pattern_classifier_constants():
    """Verify module exports expected constants."""
    try:
        import tools.ai_augmentation.pattern_classifier as mod
        assert hasattr(mod, "_JAVA_MIN_IF_DEPTH"), "Missing constant _JAVA_MIN_IF_DEPTH"
    except ImportError:
        pytest.skip("Module not importable")


# --- Anomaly Detection helpers ---

def test_parse_cs_numeric_basic():
    """_parse_cs_numeric strips C# type suffixes and returns float."""
    try:
        from tools.ai_augmentation.pattern_classifier import _parse_cs_numeric
    except ImportError:
        pytest.skip("Module not importable")
    assert _parse_cs_numeric("42") == 42.0
    assert _parse_cs_numeric("3.14f") == pytest.approx(3.14)
    assert _parse_cs_numeric("100L") == 100.0
    assert _parse_cs_numeric("notanumber") is None


def test_cs_collect_numeric_thresholds_regex_basic():
    """_cs_collect_numeric_thresholds_regex extracts constants from comparison lines."""
    try:
        from tools.ai_augmentation.pattern_classifier import _cs_collect_numeric_thresholds_regex
    except ImportError:
        pytest.skip("Module not importable")
    lines = [
        "if (score > 90) {",
        "// comment > 999",
        "if (count <= 5) {",
        "var x = 1 + 2;",          # not a comparison op — not captured
    ]
    values = _cs_collect_numeric_thresholds_regex(lines)
    assert 90.0 in values
    assert 5.0 in values
    assert 999.0 not in values     # commented-out line skipped


def test_java_collect_numeric_thresholds_basic():
    """_java_collect_numeric_thresholds collects PageRequest and static int values."""
    try:
        from tools.ai_augmentation.pattern_classifier import _java_collect_numeric_thresholds
    except ImportError:
        pytest.skip("Module not importable")
    lines = [
        "PageRequest.of(page, 20);",
        "private static final int MAX_RETRY = 5;",
        "// PageRequest.of(page, 999);",  # comment — skipped
    ]
    values = _java_collect_numeric_thresholds(lines)
    assert 20.0 in values
    assert 5.0 in values
    assert 999.0 not in values


def test_cs_detect_via_regex_hardcoded_threshold_anomaly_filtered():
    """C# regex fallback only emits threshold hits that are statistical outliers."""
    try:
        from tools.ai_augmentation.pattern_classifier import _cs_detect_via_regex, _AD_ENABLED
    except ImportError:
        pytest.skip("Module not importable")
    if not _AD_ENABLED:
        pytest.skip("Anomaly detection disabled in config")

    # 9 identical values + 1 extreme outlier → only the outlier is anomalous
    normal_val = "5"
    outlier_val = "9999"
    lines = [f"if (x > {normal_val}) {{}}" for _ in range(9)]
    lines.append(f"if (x > {outlier_val}) {{}}")
    source = "\n".join(lines)
    hits = _cs_detect_via_regex("test.cs", source)
    threshold_hits = [h for h in hits if h["pattern_type"] == "hardcoded_threshold"]
    constants = [c for h in threshold_hits for c in h["pattern_detail"]["constants"]]
    assert outlier_val in constants, "Outlier should be flagged"
    assert constants.count(normal_val) < 9, "Normal repeated value should be filtered"


def test_java_detect_via_regex_hardcoded_threshold_anomaly_filtered():
    """Java regex fallback only emits threshold hits that are statistical outliers."""
    try:
        from tools.ai_augmentation.pattern_classifier import _java_detect_via_regex, _AD_ENABLED
    except ImportError:
        pytest.skip("Module not importable")
    if not _AD_ENABLED:
        pytest.skip("Anomaly detection disabled in config")

    # 9 lines with page size=20, 1 line with page size=9999 (outlier)
    lines = ["PageRequest.of(page, 20);" for _ in range(9)]
    lines.append("PageRequest.of(page, 9999);")
    source = "\n".join(lines)
    hits = _java_detect_via_regex("test.java", source)
    threshold_hits = [h for h in hits if h["pattern_type"] == "hardcoded_threshold"]
    page_sizes = [h["pattern_detail"].get("page_size") for h in threshold_hits]
    assert 9999 in page_sizes, "Outlier page size should be flagged"
    assert page_sizes.count(20) < 9, "Normal repeated page size should be filtered"


def test_is_threshold_anomalous_z_score():
    """_is_threshold_anomalous flags statistical outliers via z-score."""
    try:
        from tools.ai_augmentation.pattern_classifier import _is_threshold_anomalous
    except ImportError:
        pytest.skip("Module not importable")
    # population: 5 values close to 10; 9999 is clearly anomalous
    pop = [10.0, 10.5, 9.5, 10.2, 9.8]
    assert _is_threshold_anomalous(9999.0, pop) is True
    assert _is_threshold_anomalous(10.1, pop) is False
