# CUI // SP-CTI
"""tools/ace/persona_generator.py -- on-the-fly domain-expert persona
generation: normalization, generation, caching/reuse, and the SOUL.md
artifact shape. Mocks the LLM router so no real API calls are made.
"""
from __future__ import annotations

import json
from unittest.mock import MagicMock, patch

import pytest

from tools.ace import persona_generator


@pytest.fixture(autouse=True)
def _isolate_roles_dir(tmp_path, monkeypatch):
    """Persona generation writes real files -- point at a temp directory so
    tests never touch the real tools/ace/roles/ tree.

    Uses ``ICDEV_ACE_ROLES_DIR`` rather than patching module constants. The
    directory is now resolved through ``soul_manager._roles_dir()`` at call
    time, because resolving it from ``__file__`` wrote to whichever half of the
    tools/ <-> icdev/tools/ mirror happened to be imported and desynchronised
    the two trees on the first generated persona. The env var is the supported
    override and is honoured by every consumer.
    """
    roles_dir = tmp_path / "roles"
    monkeypatch.setenv("ICDEV_ACE_ROLES_DIR", str(roles_dir))
    yield


def _fake_router(label_response: str, soul_response: str):
    """Return a MagicMock LLMRouter whose .invoke() answers the domain-label
    normalization call first, then the SOUL.md generation call."""
    router = MagicMock()
    responses = iter([
        MagicMock(content=label_response),
        MagicMock(content=soul_response),
    ])
    router.invoke.side_effect = lambda function, req: next(responses)
    return router


def test_get_or_generate_persona_requires_domain_description():
    with pytest.raises(ValueError, match="domain_description"):
        persona_generator.get_or_generate_persona("")


def test_get_or_generate_persona_writes_soul_md_and_indexes_it():
    soul_text = "# Legal Tech Specialist — Identity & Values\n\n## Core Values\n- Ground advice in real case law."
    with patch("icdev.tools.llm.router.LLMRouter", return_value=_fake_router("legal tech", soul_text)):
        result = persona_generator.get_or_generate_persona("a contract review SaaS for law firms")

    assert result["status"] == "generated"
    role_id = result["role_id"]
    assert role_id == "legal_tech"

    soul_path = persona_generator._soul_path(role_id)
    assert soul_path.exists()
    written = soul_path.read_text(encoding="utf-8")
    assert "Legal Tech Specialist" in written
    assert "Auto-generated by tools.ace.persona_generator" in written
    assert "Not yet reviewed by a human" in written

    index = json.loads(persona_generator._generated_index_path().read_text(encoding="utf-8"))
    assert role_id in index
    assert index[role_id]["domain_label"] == "legal tech"


def test_get_or_generate_persona_reuses_cached_persona_without_a_new_llm_call():
    soul_text = "# Legal Tech Specialist — Identity & Values\n\n## Core Values\n- Ground advice in real case law."
    with patch("icdev.tools.llm.router.LLMRouter", return_value=_fake_router("legal tech", soul_text)):
        first = persona_generator.get_or_generate_persona("a contract review SaaS for law firms")
        assert first["status"] == "generated"

    # Second call for a DIFFERENTLY-WORDED but same-domain description --
    # normalization must converge on the same slug (simulated here by the
    # label call returning the same "legal tech" label), and since the
    # SOUL.md already exists, generation must not be invoked a second time.
    second_router = MagicMock()
    second_router.invoke.return_value = MagicMock(content="legal tech")
    with patch("icdev.tools.llm.router.LLMRouter", return_value=second_router):
        second = persona_generator.get_or_generate_persona("legal tech contract tooling for small firms")

    # Only the normalization call happened (needed to compute the slug to
    # check against the cache) -- exactly one invoke(), not a second
    # (expensive) SOUL.md generation call.
    assert second_router.invoke.call_count == 1
    assert second["role_id"] == first["role_id"]
    assert second["status"] == "cached"


def test_normalize_domain_label_falls_back_to_raw_text_on_llm_failure():
    with patch("icdev.tools.llm.router.LLMRouter", side_effect=RuntimeError("boom")):
        label = persona_generator._normalize_domain_label("some raw domain text")
    assert label == "some raw domain text"


def test_generate_soul_text_raises_on_empty_llm_response():
    router = MagicMock()
    router.invoke.return_value = MagicMock(content="")
    with patch("icdev.tools.llm.router.LLMRouter", return_value=router):
        with pytest.raises(ValueError, match="empty SOUL.md"):
            persona_generator._generate_soul_text("legal tech", "a contract review SaaS")


def test_slug_normalizes_display_names():
    assert persona_generator._slug("Legal Tech!!  Specialist") == "legal_tech_specialist"
    assert persona_generator._slug("") == "custom_specialist"
