# CUI // SP-CTI
"""IDC IaC Generator — Terraform, CloudFormation, Pulumi, Ansible, Helm emitters.

Pure deterministic functions. Input: IDC graph dict {nodes: [...], edges: [...]}.
Each node carries: {id, type, label, data?: {region, instance_type, ...}}.

Supported CSPs: AWS GovCloud, Azure Government, GCP, OCI, IBM Cloud, On-Premises.
Phase 1 of the IDC twin (brief: digital-twin-market-canvas-implementation-plan.md §7).
"""

import io
import re
import zipfile
from datetime import datetime, timezone

# ── Helpers ────────────────────────────────────────────────────────────────────

_CUI_BANNER = """\
# CUI // SP-CTI
# CONTROLLED UNCLASSIFIED INFORMATION
# Generated by ICDEV IDC IaC Generator — {emitter}
# Timestamp: {ts}
# Classification: CUI — Authorized for internal project use only
# DO NOT distribute outside authorized channels
"""


def _ts() -> str:
    return datetime.now(timezone.utc).isoformat()


def _cui(emitter: str) -> str:
    return _CUI_BANNER.format(emitter=emitter, ts=_ts())


def _slug(label: str) -> str:
    """Sanitize a node label into a valid identifier."""
    s = re.sub(r"[^a-zA-Z0-9_]", "_", str(label).strip())
    s = re.sub(r"_+", "_", s).strip("_").lower()
    return s or "resource"


def _detect_csps(nodes: list) -> set:
    csps: set = set()
    for n in nodes:
        t = n.get("type", "")
        if t.startswith("aws"):
            csps.add("aws")
        elif t.startswith("az-"):
            csps.add("azure")
        elif t.startswith("gcp-"):
            csps.add("gcp")
        elif t.startswith("oci-"):
            csps.add("oci")
        elif t.startswith("ibm-"):
            csps.add("ibm")
        elif t.startswith("op-"):
            csps.add("onprem")
    return csps


def _node_data(node: dict, key: str, default):
    return (node.get("data") or {}).get(key, default)


# ── Terraform ─────────────────────────────────────────────────────────────────

_TF_PROVIDER_AWS = """\
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  backend "s3" {
    bucket         = "icdev-tf-state"
    key            = "infra/terraform.tfstate"
    region         = "us-gov-west-1"
    encrypt        = true
    dynamodb_table = "icdev-tf-locks"
  }
}

provider "aws" {
  region = "us-gov-west-1"
  default_tags {
    tags = {
      Classification = "CUI"
      ManagedBy      = "ICDEV"
    }
  }
}
"""

_TF_PROVIDER_AZURE = """\
provider "azurerm" {
  features {}
  environment = "usgovernment"
}

variable "resource_group_name" { default = "icdev-rg" }
variable "azure_region"        { default = "usgovvirginia" }
variable "tenant_id"           {}
variable "disk_encryption_set_id" { default = "" }
variable "db_admin_login"      { default = "icdevadmin" }
variable "db_admin_password"   { sensitive = true }
"""

_TF_PROVIDER_GCP = """\
provider "google" {
  project = var.gcp_project_id
  region  = "us-central1"
}

variable "gcp_project_id"      {}
variable "kms_crypto_key"      {}
variable "gcp_service_account" {}
"""

_TF_PROVIDER_OCI = """\
provider "oci" {
  region = var.oci_region
}

variable "oci_region"        { default = "us-ashburn-1" }
variable "oci_compartment_id" {}
variable "oci_subnet_id"     {}
variable "oci_vcn_id"        {}
variable "oci_image_id"      {}
variable "kms_key_id"        {}
"""

_TF_PROVIDER_IBM = """\
provider "ibm" {
  region           = var.ibm_region
  ibmcloud_api_key = var.ibm_api_key
}

variable "ibm_region"              { default = "us-south" }
variable "ibm_api_key"             { sensitive = true }
variable "ibm_vpc_id"              {}
variable "ibm_subnet_id"           {}
variable "ibm_image_id"            {}
variable "ibm_ssh_key_id"          {}
variable "ibm_kp_key_crn"          {}
variable "ibm_activity_tracker_crn" {}
"""

_TF_VARS_COMMON = """\
variable "ami_id"              { default = "ami-0abcdef1234567890" }
variable "kms_key_arn"         {}
variable "private_subnet_ids"  { type = list(string) }
variable "db_master_username"  { default = "icdevadmin" }
variable "db_master_password"  { sensitive = true }
"""


def _tf_block(node: dict) -> str:
    """Return a Terraform resource block for a single IDC node."""
    ntype = node.get("type", "")
    label = node.get("label", ntype)
    n = _slug(label)

    # ── AWS ──────────────────────────────────────────────────────────────────
    if ntype in ("aws-ec2", "aws-ec2-spot", "aws-ec2-dedicated"):
        spot_line = '  spot_price = "0.05"\n' if "spot" in ntype else ""
        return (
            f'resource "aws_instance" "{n}" {{\n'
            f"  ami           = var.ami_id\n"
            f'  instance_type = "{_node_data(node, "instance_type", "t3.medium")}"\n'
            f"{spot_line}"
            f"  root_block_device {{\n"
            f"    encrypted   = true\n"
            f"    volume_type = \"gp3\"\n"
            f"  }}\n"
            f"  metadata_options {{\n"
            f'    http_tokens = "required"\n'
            f"  }}\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype == "aws-ec2-asg":
        return (
            f'resource "aws_autoscaling_group" "{n}" {{\n'
            f'  min_size         = {_node_data(node, "min_size", 1)}\n'
            f'  max_size         = {_node_data(node, "max_size", 3)}\n'
            f'  desired_capacity = {_node_data(node, "desired", 2)}\n'
            f"  vpc_zone_identifier = var.private_subnet_ids\n"
            f"  launch_template {{ id = aws_launch_template.{n}.id; version = \"$Latest\" }}\n"
            f"  tag {{ key = \"Classification\"; value = \"CUI\"; propagate_at_launch = true }}\n"
            f"}}\n"
        )

    if ntype in ("aws-s3", "aws-s3-glacier", "aws-s3-intelligent", "aws-s3-outposts"):
        bucket = _node_data(node, "bucket_name", f"{n}-bucket")
        return (
            f'resource "aws_s3_bucket" "{n}" {{\n'
            f'  bucket = "{bucket}"\n'
            f"  tags   = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
            f'resource "aws_s3_bucket_server_side_encryption_configuration" "{n}_enc" {{\n'
            f"  bucket = aws_s3_bucket.{n}.id\n"
            f"  rule {{\n"
            f"    apply_server_side_encryption_by_default {{\n"
            f'      sse_algorithm     = "aws:kms"\n'
            f"      kms_master_key_id = var.kms_key_arn\n"
            f"    }}\n"
            f"  }}\n"
            f"}}\n"
            f'resource "aws_s3_bucket_public_access_block" "{n}_pab" {{\n'
            f"  bucket                  = aws_s3_bucket.{n}.id\n"
            f"  block_public_acls       = true\n"
            f"  block_public_policy     = true\n"
            f"  ignore_public_acls      = true\n"
            f"  restrict_public_buckets = true\n"
            f"}}\n"
            f'resource "aws_s3_bucket_versioning" "{n}_ver" {{\n'
            f"  bucket = aws_s3_bucket.{n}.id\n"
            f"  versioning_configuration {{ status = \"Enabled\" }}\n"
            f"}}\n"
        )

    if ntype in ("aws-rds", "aws-rds-mssql", "aws-rds-oracle", "aws-rds-postgres"):
        engine = "sqlserver-se" if "mssql" in ntype else ("oracle-se2" if "oracle" in ntype else "postgres")
        return (
            f'resource "aws_db_instance" "{n}" {{\n'
            f'  identifier              = "{n}"\n'
            f'  engine                  = "{_node_data(node, "engine", engine)}"\n'
            f'  instance_class          = "{_node_data(node, "instance_class", "db.t3.medium")}"\n'
            f'  allocated_storage       = {_node_data(node, "storage_gb", 100)}\n'
            f"  storage_encrypted       = true\n"
            f"  kms_key_id              = var.kms_key_arn\n"
            f"  multi_az                = {str(_node_data(node, 'multi_az', True)).lower()}\n"
            f"  publicly_accessible     = false\n"
            f"  deletion_protection     = true\n"
            f'  skip_final_snapshot     = false\n'
            f'  final_snapshot_identifier = "{n}-final-snapshot"\n'
            f'  backup_retention_period = {_node_data(node, "backup_days", 7)}\n'
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype == "aws-rds-aurora":
        return (
            f'resource "aws_rds_cluster" "{n}" {{\n'
            f'  cluster_identifier      = "{n}"\n'
            f'  engine                  = "aurora-postgresql"\n'
            f'  database_name           = "{_node_data(node, "database", "icdev")}"\n'
            f"  master_username         = var.db_master_username\n"
            f"  master_password         = var.db_master_password\n"
            f"  storage_encrypted       = true\n"
            f"  kms_key_id              = var.kms_key_arn\n"
            f"  deletion_protection     = true\n"
            f'  backup_retention_period = {_node_data(node, "backup_days", 7)}\n'
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype in ("aws-eks", "aws-eks-managed", "aws-eks-fargate"):
        return (
            f'resource "aws_eks_cluster" "{n}" {{\n'
            f'  name     = "{n}"\n'
            f"  role_arn = aws_iam_role.{n}_cluster.arn\n"
            f'  version  = "{_node_data(node, "k8s_version", "1.29")}"\n'
            f"  vpc_config {{\n"
            f"    subnet_ids              = var.private_subnet_ids\n"
            f"    endpoint_private_access = true\n"
            f"    endpoint_public_access  = false\n"
            f"  }}\n"
            f"  encryption_config {{\n"
            f"    provider {{ key_arn = var.kms_key_arn }}\n"
            f'    resources = ["secrets"]\n'
            f"  }}\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype in ("aws-ecs", "aws-fargate"):
        return (
            f'resource "aws_ecs_cluster" "{n}" {{\n'
            f'  name = "{n}"\n'
            f'  setting {{ name = "containerInsights"; value = "enabled" }}\n'
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype == "aws-ecr":
        return (
            f'resource "aws_ecr_repository" "{n}" {{\n'
            f'  name                 = "{n}"\n'
            f'  image_tag_mutability = "IMMUTABLE"\n'
            f'  encryption_configuration {{ encryption_type = "KMS"; kms_key = var.kms_key_arn }}\n'
            f"  image_scanning_configuration {{ scan_on_push = true }}\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype == "aws-lambda":
        return (
            f'resource "aws_lambda_function" "{n}" {{\n'
            f'  function_name = "{n}"\n'
            f"  role          = aws_iam_role.{n}_exec.arn\n"
            f'  runtime       = "{_node_data(node, "runtime", "python3.12")}"\n'
            f'  handler       = "{_node_data(node, "handler", "lambda_function.lambda_handler")}"\n'
            f'  filename      = "{_node_data(node, "filename", "lambda.zip")}"\n'
            f"  kms_key_arn   = var.kms_key_arn\n"
            f"  environment {{ variables = {{ CLASSIFICATION = \"CUI\" }} }}\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype == "aws-kms":
        return (
            f'resource "aws_kms_key" "{n}" {{\n'
            f'  description             = "{label} KMS Key"\n'
            f"  deletion_window_in_days = 30\n"
            f"  enable_key_rotation     = true\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
            f'resource "aws_kms_alias" "{n}_alias" {{\n'
            f'  name          = "alias/{n}"\n'
            f"  target_key_id = aws_kms_key.{n}.key_id\n"
            f"}}\n"
        )

    if ntype in ("aws-elb", "aws-alb", "aws-nlb"):
        lb_type = "network" if "nlb" in ntype else "application"
        return (
            f'resource "aws_lb" "{n}" {{\n'
            f'  name               = "{n}"\n'
            f"  internal           = true\n"
            f'  load_balancer_type = "{lb_type}"\n'
            f"  subnets            = var.private_subnet_ids\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    # ── Azure ────────────────────────────────────────────────────────────────
    if ntype in ("az-vm", "az-spot", "az-dedicated"):
        return (
            f'resource "azurerm_linux_virtual_machine" "{n}" {{\n'
            f'  name                            = "{n}"\n'
            f"  resource_group_name             = var.resource_group_name\n"
            f"  location                        = var.azure_region\n"
            f'  size                            = "{_node_data(node, "vm_size", "Standard_D2s_v3")}"\n'
            f'  admin_username                  = "azureadmin"\n'
            f"  disable_password_authentication = true\n"
            f"  network_interface_ids           = [azurerm_network_interface.{n}.id]\n"
            f"  os_disk {{\n"
            f'    caching                = "ReadWrite"\n'
            f'    storage_account_type   = "Premium_LRS"\n'
            f"    disk_encryption_set_id = var.disk_encryption_set_id\n"
            f"  }}\n"
            f"  source_image_reference {{\n"
            f'    publisher = "RedHat"; offer = "RHEL"; sku = "8-LVM"; version = "latest"\n'
            f"  }}\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype == "az-aks":
        return (
            f'resource "azurerm_kubernetes_cluster" "{n}" {{\n'
            f'  name                = "{n}"\n'
            f"  location            = var.azure_region\n"
            f"  resource_group_name = var.resource_group_name\n"
            f'  dns_prefix          = "{n}"\n'
            f'  kubernetes_version  = "{_node_data(node, "k8s_version", "1.29")}"\n'
            f"  default_node_pool {{\n"
            f'    name                = "system"\n'
            f'    node_count          = {_node_data(node, "node_count", 2)}\n'
            f'    vm_size             = "{_node_data(node, "vm_size", "Standard_D4s_v3")}"\n'
            f"    enable_auto_scaling = true\n"
            f'    min_count           = {_node_data(node, "min_nodes", 1)}\n'
            f'    max_count           = {_node_data(node, "max_nodes", 5)}\n'
            f"  }}\n"
            f'  identity {{ type = "SystemAssigned" }}\n'
            f"  key_vault_secrets_provider {{ secret_rotation_enabled = true }}\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype in ("az-blob", "az-files", "az-disk", "az-netapp"):
        acct = _slug(label).replace("_", "")[:24]
        return (
            f'resource "azurerm_storage_account" "{n}" {{\n'
            f'  name                            = "{acct}"\n'
            f"  resource_group_name             = var.resource_group_name\n"
            f"  location                        = var.azure_region\n"
            f'  account_tier                    = "Standard"\n'
            f'  account_replication_type        = "LRS"\n'
            f"  enable_https_traffic_only       = true\n"
            f'  min_tls_version                 = "TLS1_2"\n'
            f"  allow_nested_items_to_be_public = false\n"
            f"  blob_properties {{ versioning_enabled = true }}\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype == "az-keyvault":
        return (
            f'resource "azurerm_key_vault" "{n}" {{\n'
            f'  name                       = "{n[:24]}"\n'
            f"  location                   = var.azure_region\n"
            f"  resource_group_name        = var.resource_group_name\n"
            f"  tenant_id                  = var.tenant_id\n"
            f'  sku_name                   = "premium"\n'
            f"  purge_protection_enabled   = true\n"
            f"  soft_delete_retention_days = 90\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype in ("az-sql", "az-sql-managed", "az-postgresql", "az-mysql"):
        return (
            f'resource "azurerm_mssql_server" "{n}_srv" {{\n'
            f'  name                         = "{n}-srv"\n'
            f"  resource_group_name          = var.resource_group_name\n"
            f"  location                     = var.azure_region\n"
            f'  version                      = "12.0"\n'
            f"  administrator_login          = var.db_admin_login\n"
            f"  administrator_login_password = var.db_admin_password\n"
            f'  minimum_tls_version          = "1.2"\n'
            f"  tags = {{ Classification = \"CUI\" }}\n"
            f"}}\n"
            f'resource "azurerm_mssql_database" "{n}" {{\n'
            f'  name      = "{n}"\n'
            f"  server_id = azurerm_mssql_server.{n}_srv.id\n"
            f'  sku_name  = "{_node_data(node, "sku", "S1")}"\n'
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    if ntype in ("az-acr",):
        acr = _slug(label).replace("_", "")[:50]
        return (
            f'resource "azurerm_container_registry" "{n}" {{\n'
            f'  name                = "{acr}"\n'
            f"  resource_group_name = var.resource_group_name\n"
            f"  location            = var.azure_region\n"
            f'  sku                 = "Premium"\n'
            f"  admin_enabled       = false\n"
            f"  tags = {{ Name = \"{label}\", Classification = \"CUI\" }}\n"
            f"}}\n"
        )

    # ── GCP ──────────────────────────────────────────────────────────────────
    if ntype in ("gcp-gce", "gcp-spot", "gcp-sole"):
        return (
            f'resource "google_compute_instance" "{n}" {{\n'
            f'  name         = "{n}"\n'
            f'  machine_type = "{_node_data(node, "machine_type", "n2-standard-4")}"\n'
            f'  zone         = "{_node_data(node, "zone", "us-central1-a")}"\n'
            f"  boot_disk {{\n"
            f"    initialize_params {{\n"
            f'      image = "{_node_data(node, "image", "rhel-cloud/rhel-8")}"\n'
            f'      type  = "pd-ssd"\n'
            f"    }}\n"
            f"    kms_key_self_link = var.kms_crypto_key\n"
            f"  }}\n"
            f"  shielded_instance_config {{\n"
            f"    enable_secure_boot          = true\n"
            f"    enable_vtpm                 = true\n"
            f"    enable_integrity_monitoring = true\n"
            f"  }}\n"
            f'  labels = {{ classification = "cui", managed_by = "icdev" }}\n'
            f"}}\n"
        )

    if ntype in ("gcp-gke", "gcp-anthos"):
        return (
            f'resource "google_container_cluster" "{n}" {{\n'
            f'  name                     = "{n}"\n'
            f'  location                 = "{_node_data(node, "region", "us-central1")}"\n'
            f'  min_master_version       = "{_node_data(node, "k8s_version", "1.29")}"\n'
            f"  remove_default_node_pool = true\n"
            f"  initial_node_count       = 1\n"
            f"  workload_identity_config {{ workload_pool = \"${{var.gcp_project_id}}.svc.id.goog\" }}\n"
            f"  database_encryption {{ state = \"ENCRYPTED\"; key_name = var.kms_crypto_key }}\n"
            f"  master_auth {{ client_certificate_config {{ issue_client_certificate = false }} }}\n"
            f'  resource_labels = {{ classification = "cui", managed_by = "icdev" }}\n'
            f"}}\n"
        )

    if ntype in ("gcp-gcs",):
        return (
            f'resource "google_storage_bucket" "{n}" {{\n'
            f'  name          = "{n}-${{var.gcp_project_id}}"\n'
            f'  location      = "{_node_data(node, "location", "US")}"\n'
            f"  force_destroy = false\n"
            f"  uniform_bucket_level_access = true\n"
            f"  versioning {{ enabled = true }}\n"
            f"  encryption {{ default_kms_key_name = var.kms_crypto_key }}\n"
            f'  labels = {{ classification = "cui", managed_by = "icdev" }}\n'
            f"}}\n"
        )

    if ntype == "gcp-kms":
        return (
            f'resource "google_kms_key_ring" "{n}_ring" {{\n'
            f'  name     = "{n}-ring"\n'
            f'  location = "{_node_data(node, "location", "us-central1")}"\n'
            f"}}\n"
            f'resource "google_kms_crypto_key" "{n}" {{\n'
            f'  name            = "{n}"\n'
            f"  key_ring        = google_kms_key_ring.{n}_ring.id\n"
            f'  rotation_period = "2592000s"\n'
            f'  purpose         = "ENCRYPT_DECRYPT"\n'
            f'  labels          = {{ classification = "cui" }}\n'
            f"}}\n"
        )

    if ntype in ("gcp-cloudrun",):
        return (
            f'resource "google_cloud_run_service" "{n}" {{\n'
            f'  name     = "{n}"\n'
            f'  location = "{_node_data(node, "region", "us-central1")}"\n'
            f"  template {{\n"
            f"    spec {{\n"
            f"      service_account_name = var.gcp_service_account\n"
            f"      containers {{\n"
            f'        image = "{_node_data(node, "image", "gcr.io/PROJECT/IMAGE:latest")}"\n'
            f"      }}\n"
            f"    }}\n"
            f"    metadata {{ labels = {{ classification = \"cui\" }} }}\n"
            f"  }}\n"
            f"}}\n"
        )

    # ── OCI ──────────────────────────────────────────────────────────────────
    if ntype in ("oci-compute", "oci-preemptible", "oci-bm", "oci-dedicated-host"):
        return (
            f'resource "oci_core_instance" "{n}" {{\n'
            f"  compartment_id      = var.oci_compartment_id\n"
            f"  availability_domain = data.oci_identity_availability_domains.ads.availability_domains[0].name\n"
            f'  shape               = "{_node_data(node, "shape", "VM.Standard.E4.Flex")}"\n'
            f'  display_name        = "{label}"\n'
            f"  source_details {{\n"
            f'    source_type             = "image"\n'
            f"    source_id               = var.oci_image_id\n"
            f'    boot_volume_size_in_gbs = {_node_data(node, "boot_volume_gb", 100)}\n'
            f"    kms_key_id              = var.kms_key_id\n"
            f"  }}\n"
            f"  create_vnic_details {{ subnet_id = var.oci_subnet_id; assign_public_ip = false }}\n"
            f'  freeform_tags = {{ Classification = "CUI", ManagedBy = "ICDEV" }}\n'
            f"}}\n"
        )

    if ntype in ("oci-os",):
        return (
            f'resource "oci_objectstorage_bucket" "{n}" {{\n'
            f"  compartment_id = var.oci_compartment_id\n"
            f"  namespace      = data.oci_objectstorage_namespace.ns.namespace\n"
            f'  name           = "{n}"\n'
            f'  access_type    = "NoPublicAccess"\n'
            f'  versioning     = "Enabled"\n'
            f"  kms_key_id     = var.kms_key_id\n"
            f'  freeform_tags  = {{ Classification = "CUI", ManagedBy = "ICDEV" }}\n'
            f"}}\n"
        )

    if ntype == "oci-oke":
        return (
            f'resource "oci_containerengine_cluster" "{n}" {{\n'
            f"  compartment_id     = var.oci_compartment_id\n"
            f'  kubernetes_version = "{_node_data(node, "k8s_version", "v1.29.0")}"\n'
            f'  name               = "{n}"\n'
            f"  vcn_id             = var.oci_vcn_id\n"
            f"  options {{\n"
            f'    kubernetes_network_config {{ pods_cidr = "10.244.0.0/16"; services_cidr = "10.96.0.0/16" }}\n'
            f"  }}\n"
            f'  freeform_tags = {{ Classification = "CUI", ManagedBy = "ICDEV" }}\n'
            f"}}\n"
        )

    if ntype in ("oci-vault",):
        return (
            f'resource "oci_kms_vault" "{n}" {{\n'
            f"  compartment_id = var.oci_compartment_id\n"
            f'  display_name   = "{label}"\n'
            f'  vault_type     = "DEFAULT"\n'
            f'  freeform_tags  = {{ Classification = "CUI" }}\n'
            f"}}\n"
        )

    # ── IBM Cloud ────────────────────────────────────────────────────────────
    if ntype in ("ibm-vsi", "ibm-bm"):
        return (
            f'resource "ibm_is_instance" "{n}" {{\n'
            f'  name    = "{n}"\n'
            f"  vpc     = var.ibm_vpc_id\n"
            f'  zone    = "{_node_data(node, "zone", "us-south-1")}"\n'
            f'  profile = "{_node_data(node, "profile", "bx2-4x16")}"\n'
            f"  image   = var.ibm_image_id\n"
            f"  keys    = [var.ibm_ssh_key_id]\n"
            f"  primary_network_interface {{ subnet = var.ibm_subnet_id }}\n"
            f'  tags    = ["classification:cui", "managed-by:icdev"]\n'
            f"}}\n"
        )

    if ntype == "ibm-cos":
        return (
            f'resource "ibm_resource_instance" "{n}" {{\n'
            f'  name     = "{n}"\n'
            f'  service  = "cloud-object-storage"\n'
            f'  plan     = "standard"\n'
            f'  location = "global"\n'
            f'  tags     = ["classification:cui"]\n'
            f"}}\n"
            f'resource "ibm_cos_bucket" "{n}_bucket" {{\n'
            f'  bucket_name          = "{n}-bucket"\n'
            f"  resource_instance_id = ibm_resource_instance.{n}.id\n"
            f'  region_location      = "{_node_data(node, "region", "us-south")}"\n'
            f'  storage_class        = "standard"\n'
            f"  key_protect          = var.ibm_kp_key_crn\n"
            f"}}\n"
        )

    if ntype == "ibm-iks":
        return (
            f'resource "ibm_container_cluster" "{n}" {{\n'
            f'  name         = "{n}"\n'
            f'  datacenter   = "{_node_data(node, "datacenter", "dal10")}"\n'
            f'  machine_type = "{_node_data(node, "machine_type", "b3c.4x16")}"\n'
            f'  hardware     = "shared"\n'
            f'  worker_num   = {_node_data(node, "worker_count", 2)}\n'
            f'  kube_version = "{_node_data(node, "k8s_version", "1.29")}"\n'
            f'  tags         = ["classification:cui"]\n'
            f"}}\n"
        )

    # ── On-Premises ──────────────────────────────────────────────────────────
    if ntype in ("op-server", "op-hypervisor", "op-vm", "op-hci"):
        host = _node_data(node, "hostname", n)
        return (
            f"# On-premises resource: {label} — managed by Ansible (see playbook)\n"
            f'resource "null_resource" "{n}" {{\n'
            f'  triggers = {{ hostname = "{host}", classification = "CUI" }}\n'
            f"}}\n"
        )

    if ntype in ("op-k8s-cluster", "op-k8s-node"):
        return (
            f"# On-premises Kubernetes — managed by Ansible/kubeadm\n"
            f'resource "null_resource" "{n}_k8s" {{\n'
            f'  triggers = {{ cluster = "{_node_data(node, "cluster_name", n)}", classification = "CUI" }}\n'
            f"}}\n"
        )

    if ntype in ("op-san", "op-nas", "op-s3-compat"):
        return (
            f"# On-premises storage: {label}\n"
            f'resource "null_resource" "{n}_storage" {{\n'
            f'  triggers = {{ type = "{ntype}", host = "{_node_data(node, "host", n)}", classification = "CUI" }}\n'
            f"}}\n"
        )

    # Generic fallback
    return (
        f"# [{ntype}] {label} — no Terraform mapping defined; add manually\n"
        f"# resource \"PROVIDER_RESOURCE_TYPE\" \"{n}\" {{ ... }}\n\n"
    )


def generate_terraform(graph: dict) -> str:
    """Emit Terraform HCL for all nodes in an IDC graph."""
    nodes = graph.get("nodes", [])
    csps = _detect_csps(nodes)

    parts = [_cui("Terraform")]

    # Provider blocks
    if "aws" in csps:
        parts.append(_TF_PROVIDER_AWS)
    if "azure" in csps:
        parts.append(_TF_PROVIDER_AZURE)
    if "gcp" in csps:
        parts.append(_TF_PROVIDER_GCP)
    if "oci" in csps:
        parts.append(_TF_PROVIDER_OCI)
    if "ibm" in csps:
        parts.append(_TF_PROVIDER_IBM)

    parts.append(_TF_VARS_COMMON)
    parts.append("\n# ── Resources ────────────────────────────────────────────────────────────────\n\n")

    for node in nodes:
        parts.append(_tf_block(node))

    if not nodes:
        parts.append("# No resources in graph — add nodes in the IDC canvas to generate IaC.\n")

    return "\n".join(parts)


# ── CloudFormation ────────────────────────────────────────────────────────────

_CF_RESOURCE_MAP = {
    # Compute
    "aws-ec2": ("AWS::EC2::Instance", {"InstanceType": "t3.medium", "ImageId": "!Ref AmiId"}),
    "aws-ec2-asg": ("AWS::AutoScaling::AutoScalingGroup", {"MinSize": "1", "MaxSize": "3"}),
    "aws-eks": ("AWS::EKS::Cluster", {"Version": "1.29"}),
    "aws-ecs": ("AWS::ECS::Cluster", {}),
    "aws-fargate": ("AWS::ECS::Cluster", {}),
    "aws-ecr": ("AWS::ECR::Repository", {"ImageTagMutability": "IMMUTABLE", "EncryptionConfiguration": {"EncryptionType": "KMS"}}),
    "aws-lambda": ("AWS::Lambda::Function", {"Runtime": "python3.12", "Handler": "lambda_function.lambda_handler"}),
    # Storage
    "aws-s3": ("AWS::S3::Bucket", {"VersioningConfiguration": {"Status": "Enabled"}, "BucketEncryption": {"ServerSideEncryptionConfiguration": [{"ServerSideEncryptionByDefault": {"SSEAlgorithm": "aws:kms"}}]}, "PublicAccessBlockConfiguration": {"BlockPublicAcls": True, "BlockPublicPolicy": True, "IgnorePublicAcls": True, "RestrictPublicBuckets": True}}),
    "aws-ebs": ("AWS::EC2::Volume", {"Encrypted": True, "VolumeType": "gp3"}),
    "aws-efs": ("AWS::EFS::FileSystem", {"Encrypted": True}),
    # Database
    "aws-rds": ("AWS::RDS::DBInstance", {"DBInstanceClass": "db.t3.medium", "StorageEncrypted": True, "MultiAZ": True, "PubliclyAccessible": False, "DeletionProtection": True}),
    "aws-rds-aurora": ("AWS::RDS::DBCluster", {"StorageEncrypted": True, "DeletionProtection": True}),
    "aws-dynamodb": ("AWS::DynamoDB::Table", {"SSESpecification": {"SSEEnabled": True}}),
    # Security / KMS
    "aws-kms": ("AWS::KMS::Key", {"EnableKeyRotation": True, "PendingWindowInDays": 30}),
    # Networking
    "aws-elb": ("AWS::ElasticLoadBalancingV2::LoadBalancer", {"Scheme": "internal", "Type": "application"}),
    "aws-alb": ("AWS::ElasticLoadBalancingV2::LoadBalancer", {"Scheme": "internal", "Type": "application"}),
    "aws-nlb": ("AWS::ElasticLoadBalancingV2::LoadBalancer", {"Scheme": "internal", "Type": "network"}),
}


def _cf_resource_block(node: dict) -> str:
    """Return a CloudFormation resource entry (YAML block) for an IDC node."""
    ntype = node.get("type", "")
    label = node.get("label", ntype)
    logical_id = re.sub(r"[^a-zA-Z0-9]", "", label.title()) or "Resource"

    mapping = _CF_RESOURCE_MAP.get(ntype)
    if not mapping:
        return f"  # {logical_id}: [{ntype}] — no CloudFormation mapping; add manually\n"

    cf_type, props = mapping
    lines = [f"  {logical_id}:"]
    lines.append(f"    Type: {cf_type}")
    lines.append("    Properties:")

    def _emit_props(d: dict, indent: int) -> list:
        result = []
        pad = " " * indent
        for k, v in d.items():
            if isinstance(v, dict):
                result.append(f"{pad}{k}:")
                result.extend(_emit_props(v, indent + 2))
            elif isinstance(v, list):
                result.append(f"{pad}{k}:")
                for item in v:
                    if isinstance(item, dict):
                        first = True
                        for ik, iv in item.items():
                            prefix = "- " if first else "  "
                            result.append(f"{pad}  {prefix}{ik}: {iv}")
                            first = False
                    else:
                        result.append(f"{pad}  - {item}")
            else:
                result.append(f"{pad}{k}: {v}")
        return result

    lines.extend(_emit_props(props, 6))
    lines.append("      Tags:")
    lines.append("        - Key: Name")
    lines.append(f"          Value: {label}")
    lines.append("        - Key: Classification")
    lines.append("          Value: CUI")
    lines.append("")
    return "\n".join(lines) + "\n"


def generate_cloudformation(graph: dict) -> str:
    """Emit CloudFormation YAML template for AWS nodes in an IDC graph."""
    nodes = graph.get("nodes", [])
    aws_nodes = [n for n in nodes if n.get("type", "").startswith("aws")]

    lines = [
        _cui("CloudFormation"),
        "AWSTemplateFormatVersion: '2010-09-09'",
        "Description: >",
        "  ICDEV IDC — Generated CloudFormation template (CUI // SP-CTI)",
        "",
        "Parameters:",
        "  AmiId:",
        "    Type: AWS::EC2::Image::Id",
        "    Description: AMI ID for EC2 instances",
        "  KmsKeyArn:",
        "    Type: String",
        "    Description: KMS key ARN for encryption",
        "  PrivateSubnetIds:",
        "    Type: List<AWS::EC2::Subnet::Id>",
        "    Description: Private subnet IDs",
        "",
        "Resources:",
    ]

    if not aws_nodes:
        lines.append("  # No AWS resources in graph — add AWS nodes in the IDC canvas.")
    else:
        for node in aws_nodes:
            lines.append(_cf_resource_block(node))

    lines.extend([
        "",
        "Outputs:",
        "  GeneratedBy:",
        "    Value: ICDEV-IDC-IaC-Generator",
        "    Description: Template generated by ICDEV IDC IaC Generator",
    ])

    return "\n".join(lines)


# ── Pulumi ────────────────────────────────────────────────────────────────────

_PULUMI_IMPORTS = {
    "aws": "import pulumi_aws as aws",
    "azure": "import pulumi_azure_native as azure",
    "gcp": "import pulumi_gcp as gcp",
    "oci": "import pulumi_oci as oci",
    "ibm": "import pulumi_ibm as ibm",
}

_PULUMI_OPTS = """\
import pulumi

config = pulumi.Config()
classification = "CUI"
managed_by = "ICDEV"
tags = {"Classification": classification, "ManagedBy": managed_by}
"""


def _pulumi_block(node: dict) -> str:
    """Return a Pulumi Python resource declaration for an IDC node."""
    ntype = node.get("type", "")
    label = node.get("label", ntype)
    n = _slug(label)

    # ── AWS ──────────────────────────────────────────────────────────────────
    if ntype in ("aws-ec2", "aws-ec2-spot", "aws-ec2-dedicated"):
        return (
            f'{n} = aws.ec2.Instance("{n}",\n'
            f'    ami=config.require("ami_id"),\n'
            f'    instance_type="{_node_data(node, "instance_type", "t3.medium")}",\n'
            f"    root_block_device=aws.ec2.InstanceRootBlockDeviceArgs(encrypted=True, volume_type=\"gp3\"),\n"
            f"    metadata_options=aws.ec2.InstanceMetadataOptionsArgs(http_tokens=\"required\"),\n"
            f"    tags={{**tags, \"Name\": \"{label}\"}},\n"
            f")\n"
        )

    if ntype in ("aws-s3", "aws-s3-glacier", "aws-s3-intelligent"):
        return (
            f'{n} = aws.s3.BucketV2("{n}", tags={{**tags, "Name": "{label}"}})\n'
            f'{n}_enc = aws.s3.BucketServerSideEncryptionConfigurationV2("{n}_enc",\n'
            f"    bucket={n}.id,\n"
            f"    rules=[aws.s3.BucketServerSideEncryptionConfigurationV2RuleArgs(\n"
            f"        apply_server_side_encryption_by_default=aws.s3.BucketServerSideEncryptionConfigurationV2RuleApplyServerSideEncryptionByDefaultArgs(\n"
            f'            sse_algorithm="aws:kms",\n'
            f'            kms_master_key_id=config.require("kms_key_arn"),\n'
            f"        ),\n"
            f"    )],\n"
            f")\n"
            f'{n}_pab = aws.s3.BucketPublicAccessBlock("{n}_pab",\n'
            f"    bucket={n}.id,\n"
            f"    block_public_acls=True, block_public_policy=True,\n"
            f"    ignore_public_acls=True, restrict_public_buckets=True,\n"
            f")\n"
        )

    if ntype in ("aws-rds", "aws-rds-postgres", "aws-rds-mssql", "aws-rds-oracle"):
        engine = "sqlserver-se" if "mssql" in ntype else ("oracle-se2" if "oracle" in ntype else "postgres")
        return (
            f'{n} = aws.rds.Instance("{n}",\n'
            f'    identifier="{n}",\n'
            f'    engine="{_node_data(node, "engine", engine)}",\n'
            f'    instance_class="{_node_data(node, "instance_class", "db.t3.medium")}",\n'
            f'    allocated_storage={_node_data(node, "storage_gb", 100)},\n'
            f"    storage_encrypted=True,\n"
            f'    kms_key_id=config.require("kms_key_arn"),\n'
            f"    multi_az={str(_node_data(node, 'multi_az', True))},\n"
            f"    publicly_accessible=False,\n"
            f"    deletion_protection=True,\n"
            f"    tags={{**tags, \"Name\": \"{label}\"}},\n"
            f")\n"
        )

    if ntype in ("aws-eks", "aws-eks-managed", "aws-eks-fargate"):
        return (
            f'{n} = aws.eks.Cluster("{n}",\n'
            f'    role_arn="{n}_cluster_role_arn",\n'
            f'    version="{_node_data(node, "k8s_version", "1.29")}",\n'
            f"    vpc_config=aws.eks.ClusterVpcConfigArgs(\n"
            f'        subnet_ids=config.require_object("private_subnet_ids"),\n'
            f"        endpoint_private_access=True,\n"
            f"        endpoint_public_access=False,\n"
            f"    ),\n"
            f"    encryption_configs=[aws.eks.ClusterEncryptionConfigArgs(\n"
            f'        provider=aws.eks.ClusterEncryptionConfigProviderArgs(key_arn=config.require("kms_key_arn")),\n'
            f'        resources=["secrets"],\n'
            f"    )],\n"
            f"    tags={{**tags, \"Name\": \"{label}\"}},\n"
            f")\n"
        )

    if ntype == "aws-kms":
        return (
            f'{n} = aws.kms.Key("{n}",\n'
            f'    description="{label} KMS Key",\n'
            f"    deletion_window_in_days=30,\n"
            f"    enable_key_rotation=True,\n"
            f"    tags={{**tags, \"Name\": \"{label}\"}},\n"
            f")\n"
            f'{n}_alias = aws.kms.Alias("{n}_alias", name="alias/{n}", target_key_id={n}.key_id)\n'
        )

    # ── Azure ────────────────────────────────────────────────────────────────
    if ntype in ("az-vm", "az-spot"):
        return (
            f'{n} = azure.compute.VirtualMachine("{n}",\n'
            f'    resource_group_name=config.require("resource_group_name"),\n'
            f'    location=config.get("azure_region") or "usgovvirginia",\n'
            f'    vm_size="{_node_data(node, "vm_size", "Standard_D2s_v3")}",\n'
            f"    tags={{**tags, \"Name\": \"{label}\"}},\n"
            f")\n"
        )

    if ntype == "az-aks":
        return (
            f'{n} = azure.containerservice.ManagedCluster("{n}",\n'
            f'    resource_group_name=config.require("resource_group_name"),\n'
            f'    location=config.get("azure_region") or "usgovvirginia",\n'
            f'    kubernetes_version="{_node_data(node, "k8s_version", "1.29")}",\n'
            f"    agent_pool_profiles=[azure.containerservice.ManagedClusterAgentPoolProfileArgs(\n"
            f'        name="system",\n'
            f'        count={_node_data(node, "node_count", 2)},\n'
            f'        vm_size="{_node_data(node, "vm_size", "Standard_D4s_v3")}",\n'
            f"    )],\n"
            f"    tags={{**tags, \"Name\": \"{label}\"}},\n"
            f")\n"
        )

    if ntype in ("az-blob", "az-files"):
        return (
            f'{n} = azure.storage.StorageAccount("{n}",\n'
            f'    resource_group_name=config.require("resource_group_name"),\n'
            f'    location=config.get("azure_region") or "usgovvirginia",\n'
            f'    sku=azure.storage.SkuArgs(name="Standard_LRS"),\n'
            f'    kind="StorageV2",\n'
            f"    enable_https_traffic_only=True,\n"
            f"    allow_blob_public_access=False,\n"
            f"    tags={{**tags, \"Name\": \"{label}\"}},\n"
            f")\n"
        )

    # ── GCP ──────────────────────────────────────────────────────────────────
    if ntype in ("gcp-gce", "gcp-spot"):
        return (
            f'{n} = gcp.compute.Instance("{n}",\n'
            f'    machine_type="{_node_data(node, "machine_type", "n2-standard-4")}",\n'
            f'    zone="{_node_data(node, "zone", "us-central1-a")}",\n'
            f"    boot_disk=gcp.compute.InstanceBootDiskArgs(\n"
            f"        initialize_params=gcp.compute.InstanceBootDiskInitializeParamsArgs(\n"
            f'            image="{_node_data(node, "image", "rhel-cloud/rhel-8")}",\n'
            f'            type="pd-ssd",\n'
            f"        ),\n"
            f'        kms_key_self_link=config.require("kms_crypto_key"),\n'
            f"    ),\n"
            f'    shielded_instance_config=gcp.compute.InstanceShieldedInstanceConfigArgs(enable_secure_boot=True, enable_vtpm=True),\n'
            f'    labels={{**{{k: v.lower() for k, v in tags.items()}}, "name": "{n}"}},\n'
            f")\n"
        )

    if ntype == "gcp-gke":
        return (
            f'{n} = gcp.container.Cluster("{n}",\n'
            f'    location="{_node_data(node, "region", "us-central1")}",\n'
            f'    min_master_version="{_node_data(node, "k8s_version", "1.29")}",\n'
            f"    remove_default_node_pool=True,\n"
            f"    initial_node_count=1,\n"
            f"    workload_identity_config=gcp.container.ClusterWorkloadIdentityConfigArgs(\n"
            f'        workload_pool=f"{{config.require(\'gcp_project_id\')}}.svc.id.goog",\n'
            f"    ),\n"
            f'    resource_labels={{**{{k: v.lower() for k, v in tags.items()}}, "name": "{n}"}},\n'
            f")\n"
        )

    if ntype == "gcp-gcs":
        return (
            f'{n} = gcp.storage.Bucket("{n}",\n'
            f'    location="{_node_data(node, "location", "US")}",\n'
            f"    uniform_bucket_level_access=True,\n"
            f"    versioning=gcp.storage.BucketVersioningArgs(enabled=True),\n"
            f"    encryption=gcp.storage.BucketEncryptionArgs(\n"
            f'        default_kms_key_name=config.require("kms_crypto_key"),\n'
            f"    ),\n"
            f'    labels={{**{{k: v.lower() for k, v in tags.items()}}, "name": "{n}"}},\n'
            f")\n"
        )

    # ── OCI ──────────────────────────────────────────────────────────────────
    if ntype in ("oci-compute", "oci-preemptible"):
        return (
            f'{n} = oci.core.Instance("{n}",\n'
            f'    compartment_id=config.require("oci_compartment_id"),\n'
            f'    shape="{_node_data(node, "shape", "VM.Standard.E4.Flex")}",\n'
            f'    display_name="{label}",\n'
            f"    freeform_tags={{**tags}},\n"
            f")\n"
        )

    if ntype == "oci-oke":
        return (
            f'{n} = oci.containerengine.Cluster("{n}",\n'
            f'    compartment_id=config.require("oci_compartment_id"),\n'
            f'    kubernetes_version="{_node_data(node, "k8s_version", "v1.29.0")}",\n'
            f'    name="{n}",\n'
            f'    vcn_id=config.require("oci_vcn_id"),\n'
            f"    freeform_tags={{**tags}},\n"
            f")\n"
        )

    # ── On-Prem ──────────────────────────────────────────────────────────────
    if ntype.startswith("op-"):
        return (
            f"# On-premises resource: {label} — no Pulumi provider; manage via Ansible\n"
            f'# {n} = pulumi.ComponentResource("icdev:onprem:Resource", "{n}", {{"tags": tags}})\n\n'
        )

    # Fallback
    return f"# [{ntype}] {label} — no Pulumi mapping defined; add manually\n"


def generate_pulumi(graph: dict) -> str:
    """Emit a Pulumi Python program for all nodes in an IDC graph."""
    nodes = graph.get("nodes", [])
    csps = _detect_csps(nodes)

    imports = ["# /// script"]
    for csp in sorted(csps):
        imp = _PULUMI_IMPORTS.get(csp)
        if imp:
            imports.append(imp)

    parts = [
        _cui("Pulumi Python"),
        "\n".join(imports),
        "",
        _PULUMI_OPTS,
        "# ── Resources ────────────────────────────────────────────────────────────────\n",
    ]

    for node in nodes:
        parts.append(_pulumi_block(node))

    if not nodes:
        parts.append("# No resources in graph — add nodes in the IDC canvas to generate IaC.\n")

    # Export resource IDs
    parts.append("\n# ── Outputs ──────────────────────────────────────────────────────────────────")
    for node in nodes:
        n = _slug(node.get("label", node.get("type", "res")))
        ntype = node.get("type", "")
        if not ntype.startswith("op-"):
            parts.append(f'pulumi.export("{n}_id", {n}.id if hasattr({n}, "id") else "{n}")')

    return "\n".join(parts)


# ── Ansible ───────────────────────────────────────────────────────────────────

_ANSIBLE_HEADER = """\
---
# CUI // SP-CTI — ICDEV IDC Ansible Playbook
# Generated by ICDEV IDC IaC Generator
# Classification: CUI — Authorized for internal project use only
# Timestamp: {ts}
#
# This playbook performs post-provisioning configuration for IDC resources.
# Run AFTER Terraform/Pulumi apply completes.
# Usage: ansible-playbook site.yml -i inventory/ --vault-password-file .vault_pass
"""

_ANSIBLE_STIG_ROLE = """\
  roles:
    - role: hardening
      vars:
        stig_profile: rhel8
        audit_enabled: true
        ssh_permit_root: "no"
        ssh_protocol: "2"
        password_min_days: 1
        password_max_days: 60
        classification: CUI
"""


def _ansible_task(node: dict) -> str:
    """Return Ansible task YAML for a single IDC node."""
    ntype = node.get("type", "")
    label = node.get("label", ntype)

    # VM/server nodes get STIG hardening tasks
    if ntype in ("aws-ec2", "aws-ec2-spot", "az-vm", "az-spot", "gcp-gce", "gcp-spot",
                  "oci-compute", "oci-preemptible", "ibm-vsi", "op-server", "op-vm"):
        host = _node_data(node, "hostname", _slug(label))
        return (
            f"    # --- {label} ---\n"
            f"    - name: Apply STIG hardening — {label}\n"
            f"      ansible.builtin.include_role:\n"
            f"        name: hardening\n"
            f"      vars:\n"
            f'        target_host: "{host}"\n'
            f'        classification: "CUI"\n'
            f"\n"
            f"    - name: Enable auditd — {label}\n"
            f"      ansible.builtin.service:\n"
            f"        name: auditd\n"
            f"        state: started\n"
            f"        enabled: true\n"
            f"\n"
            f"    - name: Disable unnecessary services — {label}\n"
            f"      ansible.builtin.service:\n"
            f"        name: '{{ item }}'\n"
            f"        state: stopped\n"
            f"        enabled: false\n"
            f"      loop: [bluetooth, cups, avahi-daemon]\n"
            f"      ignore_errors: true\n\n"
        )

    # K8s clusters get kubeadm/kubectl post-setup
    if ntype in ("aws-eks", "aws-eks-managed", "az-aks", "gcp-gke", "oci-oke", "ibm-iks",
                  "op-k8s-cluster"):
        return (
            f"    # --- {label} (K8s) ---\n"
            f"    - name: Apply PodSecurityAdmission labels — {label}\n"
            f"      ansible.builtin.shell: |\n"
            f"        kubectl label namespace default \\\n"
            f'          pod-security.kubernetes.io/enforce=restricted \\\n'
            f'          pod-security.kubernetes.io/warn=restricted\n'
            f"      ignore_errors: true\n"
            f"\n"
            f"    - name: Apply network policy deny-all baseline — {label}\n"
            f"      kubernetes.core.k8s:\n"
            f"        state: present\n"
            f"        definition:\n"
            f"          apiVersion: networking.k8s.io/v1\n"
            f"          kind: NetworkPolicy\n"
            f"          metadata:\n"
            f'            name: deny-all\n'
            f'            namespace: default\n'
            f"          spec:\n"
            f"            podSelector: {{}}\n"
            f"            policyTypes: [Ingress, Egress]\n\n"
        )

    # Storage nodes — verify encryption
    if ntype in ("aws-s3", "aws-ebs", "aws-efs", "az-blob", "az-files", "az-disk",
                  "gcp-gcs", "oci-os", "ibm-cos", "op-san", "op-nas", "op-s3-compat"):
        return (
            f"    # --- {label} (storage) ---\n"
            f"    - name: Verify encryption for {label}\n"
            f"      ansible.builtin.debug:\n"
            f'        msg: "Storage {label} provisioned — verify KMS encryption in cloud console"\n\n'
        )

    # Database nodes — verify encryption + backup
    if "rds" in ntype or "sql" in ntype or "cosmos" in ntype or "postgres" in ntype or "mysql" in ntype:
        return (
            f"    # --- {label} (database) ---\n"
            f"    - name: Verify database encryption — {label}\n"
            f"      ansible.builtin.debug:\n"
            f'        msg: "Database {label} — confirm encryption-at-rest and automated backups in cloud console"\n\n'
        )

    # Generic placeholder
    return (
        f"    # --- {label} [{ntype}] ---\n"
        f"    - name: Post-provisioning check — {label}\n"
        f"      ansible.builtin.debug:\n"
        f'        msg: "Resource {label} ({ntype}) provisioned — verify configuration"\n\n'
    )


def generate_ansible(graph: dict) -> str:
    """Emit an Ansible site.yml playbook for all nodes in an IDC graph."""
    nodes = graph.get("nodes", [])

    parts = [_ANSIBLE_HEADER.format(ts=_ts())]

    # Inventory group detection
    k8s_nodes = [n for n in nodes if "eks" in n.get("type", "") or "aks" in n.get("type", "")
                 or "gke" in n.get("type", "") or "oke" in n.get("type", "")
                 or "iks" in n.get("type", "") or "k8s" in n.get("type", "")]
    # Play 1: Common hardening for all managed hosts
    parts.append(
        "- name: ICDEV IDC — Common Security Baseline\n"
        "  hosts: all\n"
        "  gather_facts: true\n"
        "  become: true\n"
        "  vars:\n"
        "    classification: CUI\n"
        "    icdev_managed: true\n"
        "  pre_tasks:\n"
        "    - name: Verify CUI classification tag\n"
        "      ansible.builtin.assert:\n"
        "        that: classification == 'CUI'\n"
        "        fail_msg: 'Classification must be CUI'\n"
        "  tasks:\n"
        "    - name: Update all packages (security patches)\n"
        "      ansible.builtin.package:\n"
        "        name: '*'\n"
        "        state: latest\n"
        "      when: ansible_os_family in ['RedHat', 'Debian']\n"
        "\n"
        "    - name: Install required packages\n"
        "      ansible.builtin.package:\n"
        "        name:\n"
        "          - aide\n"
        "          - audit\n"
        "          - firewalld\n"
        "          - openscap-scanner\n"
        "        state: present\n"
        "      when: ansible_os_family == 'RedHat'\n"
        "      ignore_errors: true\n\n"
    )

    # Play 2: Per-resource configuration
    if nodes:
        parts.append(
            "- name: ICDEV IDC — Per-Resource Post-Provisioning\n"
            "  hosts: all\n"
            "  gather_facts: false\n"
            "  become: true\n"
            "  tasks:\n"
        )
        for node in nodes:
            parts.append(_ansible_task(node))

    # Play 3: K8s-specific (if any K8s nodes)
    if k8s_nodes:
        parts.append(
            "- name: ICDEV IDC — Kubernetes Security Baseline\n"
            "  hosts: k8s_masters\n"
            "  gather_facts: false\n"
            "  tasks:\n"
        )
        for node in k8s_nodes:
            parts.append(_ansible_task(node))

    if not nodes:
        parts.append(
            "- name: ICDEV IDC — No resources configured\n"
            "  hosts: all\n"
            "  tasks:\n"
            "    - name: Placeholder\n"
            "      ansible.builtin.debug:\n"
            "        msg: 'No IDC resources — add nodes in the canvas'\n"
        )

    return "\n".join(parts)


# ── Helm Chart ────────────────────────────────────────────────────────────────

def _helm_chart_yaml(name: str) -> str:
    return (
        f"# CUI // SP-CTI — ICDEV IDC Helm Chart\n"
        f"apiVersion: v2\n"
        f"name: {name}\n"
        f"description: >\n"
        f"  ICDEV IDC generated Helm chart — CUI // SP-CTI\n"
        f"  Generated by ICDEV IDC IaC Generator\n"
        f"type: application\n"
        f"version: 0.1.0\n"
        f"appVersion: '1.0'\n"
        f"keywords:\n"
        f"  - icdev\n"
        f"  - cui\n"
        f"  - govcloud\n"
    )


def _helm_values_yaml(nodes: list) -> str:
    container_nodes = [n for n in nodes if any(
        n.get("type", "").startswith(p) for p in
        ("aws-eks", "aws-ecs", "az-aks", "gcp-gke", "oci-oke", "ibm-iks", "op-k8s")
    )]
    workload_name = _slug(container_nodes[0].get("label", "app")) if container_nodes else "app"

    lines = [
        "# CUI // SP-CTI — ICDEV IDC Helm Values",
        f"# Generated: {_ts()}",
        "",
        "replicaCount: 2",
        "",
        "image:",
        "  repository: your-registry/your-image",
        "  pullPolicy: Always",
        '  tag: "latest"',
        "",
        "nameOverride: ''",
        "fullnameOverride: ''",
        "",
        "serviceAccount:",
        "  create: true",
        "  automount: true",
        "  annotations: {}",
        f"  name: {workload_name}-sa",
        "",
        "podAnnotations:",
        '  classification: "CUI"',
        '  managed-by: "ICDEV"',
        "",
        "podLabels:",
        '  classification: "cui"',
        '  managed-by: "icdev"',
        "",
        "podSecurityContext:",
        "  runAsNonRoot: true",
        "  runAsUser: 1000",
        "  fsGroup: 2000",
        "  seccompProfile:",
        '    type: RuntimeDefault',
        "",
        "securityContext:",
        "  allowPrivilegeEscalation: false",
        "  readOnlyRootFilesystem: true",
        "  runAsNonRoot: true",
        "  runAsUser: 1000",
        "  capabilities:",
        "    drop:",
        '      - ALL',
        "",
        "service:",
        '  type: ClusterIP',
        "  port: 8080",
        "",
        "ingress:",
        "  enabled: true",
        '  className: "nginx"',
        "  annotations:",
        '    nginx.ingress.kubernetes.io/ssl-redirect: "true"',
        "  hosts:",
        '    - host: app.icdev.local',
        "      paths:",
        '        - path: /',
        '          pathType: Prefix',
        "  tls:",
        '    - secretName: app-tls',
        "      hosts:",
        '        - app.icdev.local',
        "",
        "resources:",
        "  limits:",
        "    cpu: 500m",
        "    memory: 512Mi",
        "  requests:",
        "    cpu: 100m",
        "    memory: 128Mi",
        "",
        "autoscaling:",
        "  enabled: true",
        "  minReplicas: 2",
        "  maxReplicas: 10",
        "  targetCPUUtilizationPercentage: 70",
        "",
        "networkPolicy:",
        "  enabled: true",
        "",
        "classification: CUI",
        "environment: production",
        "",
        "env:",
        "  - name: CLASSIFICATION",
        '    value: "CUI"',
        "  - name: MANAGED_BY",
        '    value: "ICDEV"',
    ]
    return "\n".join(lines)


def _helm_deployment_yaml() -> str:
    return """\
# CUI // SP-CTI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    classification: {{ .Values.classification }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
"""


def _helm_service_yaml() -> str:
    return """\
# CUI // SP-CTI
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
"""


def _helm_hpa_yaml() -> str:
    return """\
# CUI // SP-CTI
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
"""


def _helm_netpol_yaml() -> str:
    return """\
# CUI // SP-CTI
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chart.fullname" . }}-deny-all
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              allow-ingress: "true"
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
{{- end }}
"""


def _helm_helpers_tpl() -> str:
    return """\
{{/*
CUI // SP-CTI — ICDEV IDC Helm helpers
Expand the name of the chart.
*/}}
{{- define "chart.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "chart.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- printf "%s" $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}

{{- define "chart.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "chart.labels" -}}
helm.sh/chart: {{ include "chart.chart" . }}
{{ include "chart.selectorLabels" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
classification: {{ .Values.classification }}
{{- end }}

{{- define "chart.selectorLabels" -}}
app.kubernetes.io/name: {{ include "chart.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "chart.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "chart.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
"""


def generate_helm(graph: dict) -> bytes:
    """Emit a Helm chart ZIP archive for K8s workloads in an IDC graph.

    Returns raw ZIP bytes. Caller base64-encodes and sets filename to
    <name>.tgz or <name>-helm.zip.
    """
    nodes = graph.get("nodes", [])
    chart_name = "icdev-infra"
    # Derive chart name from first K8s or container node
    for n in nodes:
        t = n.get("type", "")
        if any(t.startswith(p) for p in ("aws-eks", "az-aks", "gcp-gke", "oci-oke", "ibm-iks", "op-k8s")):
            chart_name = _slug(n.get("label", "infra"))
            break

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        prefix = f"{chart_name}/"
        zf.writestr(prefix + "Chart.yaml", _helm_chart_yaml(chart_name))
        zf.writestr(prefix + "values.yaml", _helm_values_yaml(nodes))
        zf.writestr(prefix + "templates/_helpers.tpl", _helm_helpers_tpl())
        zf.writestr(prefix + "templates/deployment.yaml", _helm_deployment_yaml())
        zf.writestr(prefix + "templates/service.yaml", _helm_service_yaml())
        zf.writestr(prefix + "templates/hpa.yaml", _helm_hpa_yaml())
        zf.writestr(prefix + "templates/networkpolicy.yaml", _helm_netpol_yaml())
        # README
        readme = (
            f"# {chart_name} Helm Chart\n\n"
            f"CUI // SP-CTI — Generated by ICDEV IDC IaC Generator\n\n"
            f"Generated: {_ts()}\n\n"
            f"## Install\n\n"
            f"```bash\nhelm install {chart_name} ./{chart_name}/ \\\n"
            f"  --namespace {chart_name} --create-namespace \\\n"
            f"  --set image.repository=your-registry/your-image \\\n"
            f"  --set image.tag=latest\n```\n\n"
            f"## Security\n\n"
            f"- Pods run as non-root (UID 1000)\n"
            f"- Read-only root filesystem\n"
            f"- All capabilities dropped\n"
            f"- NetworkPolicy deny-all by default\n"
            f"- PodSecurityContext with seccomp RuntimeDefault\n"
        )
        zf.writestr(prefix + "README.md", readme)

    return buf.getvalue()
