# CUI // SP-CTI
"""GEPA Optimizer Genesis Reflex — closes the skill self-improvement flywheel.

Runs every 24 hours via the genesis daemon. Reads agent_improvement_artifacts
generated by the reflexion_agent, identifies artifacts that meaningfully exceed
their baseline score, patches the relevant skill file, and seeds a human review
kanban card.

Gate: only fires when harness eval gates pass (composite_score > baseline + 0.05
enforced inside gepa_optimizer.run()).
"""
from __future__ import annotations

import logging
from typing import Any, Dict

logger = logging.getLogger(__name__)

IMPLEMENTATION_STATUS = "full"


def run(config: Dict[str, Any], trust: Any) -> Dict[str, Any]:
    """Execute one GEPA optimization cycle."""
    try:
        from tools.skills.gepa_optimizer import run as gepa_run
        summary = gepa_run(dry_run=False)
        applied = len(summary.get("applied", []))
        skipped = len(summary.get("skipped", []))
        errors = len(summary.get("errors", []))
        logger.info(
            "gepa_optimizer reflex: applied=%d skipped=%d errors=%d",
            applied, skipped, errors,
        )
        if applied:
            print(
                f"  GEPA: updated {applied} skill file(s) "
                f"(skipped={skipped}, errors={errors})"
            )
        return {
            "status": "ok" if not errors else "partial",
            "applied": applied,
            "skipped": skipped,
            "errors": errors,
            "details": summary,
        }
    except Exception as exc:
        logger.error("gepa_optimizer reflex: unhandled error: %s", exc)
        return {"status": "error", "error": str(exc)}
