# CUI // SP-CTI
"""Genesis Reflex: Skill Security Monitor — periodic SkillSpector scan of ICDEV skills.

Runs on the Genesis daemon cadence. For each ``icdev-*`` skill directory, it calls
``tools.kanban.skill_promotion_gate.assess_skill_for_promotion``, which is backed by
``tools.integrity.skillspector_cache`` so unchanged SKILL.md files are skipped
automatically. When a skill is blocked (``allowed=False``) or carries a high/critical
risk severity, the reflex opens exactly one Kanban remediation card, deduped by skill
name + ``dispatch_source`` so re-runs never flood the board.

Daemon contract: ``run(config, context)`` is dispatched by ``GenesisDaemon``. The
second positional argument is the trust kernel; a real DB connection is accepted only
when the injected object exposes ``.execute`` (tests). Returns a status dict carrying
``success`` / ``scanned`` / ``flagged`` / ``cards_created`` / ``details``.

CLI:
    python tools/genesis/reflexes/skill_security_monitor.py             # scan .agents/skills
    python tools/genesis/reflexes/skill_security_monitor.py --dry-run # no cards
"""
from __future__ import annotations

import argparse
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from tools.logging.icdev_logger import get_logger

logger = get_logger(__name__)

IMPLEMENTATION_STATUS = "full"
CADENCE_HOURS = 6

# Repo root: tools/genesis/reflexes/skill_security_monitor.py -> repo root is 3 up.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
SKILLS_DIR = BASE_DIR / ".agents" / "skills"

# Kanban statuses that mean "already open" for dedupe purposes.
_OPEN_STATUSES = ("backlog", "scheduled", "in_progress", "suggested")

# Severity levels that cause a card to be opened.
_CARD_SEVERITIES = {"critical", "high"}

# Map gate risk severity to Kanban priority.
_SEVERITY_TO_PRIORITY = {
    "critical": "critical",
    "high": "high",
    "medium": "medium",
    "low": "low",
    "info": "low",
}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _card_id() -> str:
    return f"skill-sec-{uuid.uuid4().hex[:10]}"


def _discover_skills(config: Dict[str, Any]) -> List[Path]:
    """Return the list of skill directories to scan.

    If ``config["skills"]`` is provided, treat it as an explicit list of paths.
    Otherwise fall back to ``.agents/skills/icdev-*``.
    """
    explicit = config.get("skills")
    if explicit:
        return [Path(s).resolve() for s in explicit]

    skills: List[Path] = []
    if SKILLS_DIR.is_dir():
        for d in sorted(SKILLS_DIR.iterdir()):
            if d.is_dir() and d.name.startswith("icdev-"):
                skills.append(d.resolve())
    return skills


def _assess_skill(skill_dir: Path) -> Dict[str, Any]:
    """Call the promotion gate for one skill directory and return a compact result."""
    from tools.kanban.skill_promotion_gate import assess_skill_for_promotion

    return assess_skill_for_promotion(str(skill_dir))


def _should_flag(result: Dict[str, Any]) -> bool:
    """Return True when the skill result warrants a Kanban card."""
    if not result.get("allowed", True):
        return True
    return result.get("risk_severity", "none") in _CARD_SEVERITIES


def _card_title(skill_dir: Path, result: Dict[str, Any]) -> str:
    """Deterministic card title used for open-card dedupe."""
    severity = result.get("risk_severity", "unknown")
    return f"[SKILL-SECURITY] {skill_dir.name}: {severity} risk score {result.get('risk_score', 0)}"


def _card_description(skill_dir: Path, result: Dict[str, Any]) -> str:
    lines = [
        f"AUTO-GENERATED by the Genesis skill_security_monitor reflex ({CADENCE_HOURS}h cadence).",
        "",
        "SkillSpector assessed this ICDEV skill directory and found blocking or high-risk patterns.",
        "",
        f"Skill directory: {skill_dir}",
        f"Risk score:      {result.get('risk_score', 0)}",
        f"Risk severity:   {result.get('risk_severity', 'unknown')}",
        f"Findings count:  {result.get('findings_count', 0)}",
        f"Gate allowed:    {result.get('allowed', False)}",
        "",
        f"Reason: {result.get('reason', 'No reason provided.')}",
        "",
        "Investigation:",
        "  1. Review the SKILL.md and any source files in the skill directory.",
        "  2. Run: python tools/kanban/skill_promotion_gate.py <skill-dir> --full --json",
        "  3. Remediate findings, then POST the kanban task to 'done' when cleared.",
    ]
    return "\n".join(lines)


def _open_card_exists(conn: Any, title: str, dispatch_source: str) -> bool:
    """Return True if an open card with the same title/source already exists."""
    try:
        row = conn.execute(
            "SELECT 1 FROM kanban_tasks WHERE title = ? AND dispatch_source = ? "
            "AND status IN ({}) LIMIT 1".format(
                ", ".join(["?"] * len(_OPEN_STATUSES))
            ),
            (title[:120], dispatch_source, *_OPEN_STATUSES),
        ).fetchone()
        return row is not None
    except Exception as exc:  # noqa: BLE001 — missing table during bootstrap is not a dup
        logger.debug("skill_security_monitor: open-card dedupe query failed: %s", exc)
        return False


def _create_card(
    conn: Any,
    skill_dir: Path,
    result: Dict[str, Any],
    dry_run: bool,
) -> Optional[str]:
    """Insert a suggested Kanban card for a blocked/high-risk skill. Returns task id or None."""
    title = _card_title(skill_dir, result)[:120]
    dispatch_source = "skill_security_monitor"

    if _open_card_exists(conn, title, dispatch_source):
        return None

    if dry_run:
        return f"dry-run-{skill_dir.name}"

    task_id = _card_id()
    now = _now_iso()
    try:
        conn.execute(
            "INSERT INTO kanban_tasks "
            "(id, task_type, title, description, status, priority, "
            " dispatch_source, created_at, updated_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
            (
                task_id,
                "fix",
                title,
                _card_description(skill_dir, result)[:500],
                "suggested",
                _SEVERITY_TO_PRIORITY.get(result.get("risk_severity", "medium").lower(), "medium"),
                dispatch_source,
                now,
                now,
            ),
        )
        conn.commit()
        return task_id
    except Exception as exc:  # noqa: BLE001 — never let a card write abort the cycle
        logger.warning("skill_security_monitor: card insert failed for %r: %s", title, exc)
        try:
            conn.rollback()
        except Exception:
            pass
        return None


def run(config: Optional[Dict[str, Any]] = None, context: Any = None) -> Dict[str, Any]:
    """Scan skill directories and open Kanban cards for security findings.

    Args:
        config: reflex context. Recognized keys:
            ``skills`` (list of skill directory paths to scan; default auto-discover),
            ``dry_run`` (compute findings without opening cards),
            ``risk_threshold`` (unused — kept for forward compatibility).
        context: trust kernel passed by Genesis daemon. Ignored for DB operations
            unless it exposes ``.execute``, in which case it is treated as an
            injected test connection.

    Returns:
        Dict with daemon keys (``success`` / ``metric_value`` / ``details``) plus
        reflex-spec keys (``scanned`` / ``flagged`` / ``cards_created`` / ``status``).
    """
    ctx = config or {}
    dry_run = bool(ctx.get("dry_run", False))

    result: Dict[str, Any] = {
        "success": False,
        "metric_value": 0.0,
        "status": "ok",
        "scanned": 0,
        "flagged": 0,
        "cards_created": 0,
        "cadence_hours": CADENCE_HOURS,
        "details": {
            "skills_dir": str(SKILLS_DIR),
            "dry_run": dry_run,
            "cards": [],
            "deduped": 0,
            "errors": [],
        },
    }
    details = result["details"]

    db_injected = context is not None and hasattr(context, "execute")
    db = context if db_injected else None
    own_conn = not db_injected

    try:
        if own_conn:
            from tools.db.storage import get_connection

            db = get_connection()
            # kanban_tasks has no classification/tenant_id columns; RLS bypass is safe.
            if hasattr(db, "set_security_context"):
                db.set_security_context(None)  # rls-bypass: kanban_tasks has no classification/tenant_id columns

        skills = _discover_skills(ctx)
        result["scanned"] = len(skills)

        for skill_dir in skills:
            try:
                assessment = _assess_skill(skill_dir)
                if not _should_flag(assessment):
                    continue

                title = _card_title(skill_dir, assessment)[:120]
                if _open_card_exists(db, title, "skill_security_monitor"):
                    details["deduped"] += 1
                    details["cards"].append({"title": title, "deduped": True})
                    continue

                if dry_run:
                    details["cards"].append({"title": title, "dry_run": True})
                    result["flagged"] += 1
                    continue

                task_id = _create_card(db, skill_dir, assessment, dry_run=False)
                if task_id:
                    result["cards_created"] += 1
                    result["flagged"] += 1
                    details["cards"].append(
                        {
                            "task_id": task_id,
                            "title": title,
                            "skill": skill_dir.name,
                            "risk_score": assessment.get("risk_score", 0),
                            "risk_severity": assessment.get("risk_severity", "unknown"),
                        }
                    )
                else:
                    details["errors"].append(f"card insert failed for {skill_dir.name}")
            except Exception as exc:  # noqa: BLE001 — keep scanning other skills
                logger.warning("skill_security_monitor: scan failed for %s: %s", skill_dir, exc)
                details["errors"].append(f"{skill_dir.name}: {exc}")

        result["metric_value"] = float(result["flagged"])
        result["success"] = not details["errors"]
        logger.info(
            "skill_security_monitor: %d skill(s) scanned, %d flagged, %d card(s) created, %d deduped",
            result["scanned"],
            result["flagged"],
            result["cards_created"],
            details["deduped"],
        )
    except Exception as exc:  # noqa: BLE001 — surface as a failed cycle, never crash daemon
        logger.exception("skill_security_monitor reflex error: %s", exc)
        result["status"] = "error"
        result["success"] = False
        details["errors"].append(str(exc))
    finally:
        if own_conn and db is not None:
            try:
                db.close()
            except Exception:
                pass

    return result


if __name__ == "__main__":
    # Load THIS repo's .env so a direct CLI run uses the same board/PG config as the
    # GenesisDaemon. override=True: a pip-installed ICDEV in site-packages may have
    # already loaded a different checkout's .env at import. Repo root via __file__, not cwd.
    try:
        from pathlib import Path as _EnvPath
        from dotenv import load_dotenv as _load_dotenv
        _load_dotenv(_EnvPath(__file__).resolve().parents[3] / ".env", override=True)
    except ImportError:
        pass
    parser = argparse.ArgumentParser(
        prog="skill_security_monitor",
        description="Genesis reflex — SkillSpector security scan of ICDEV skills",
    )
    parser.add_argument("--dry-run", action="store_true", help="Compute findings without opening cards")
    parser.add_argument("--skill", action="append", dest="skills", help="Specific skill directory to scan")
    args = parser.parse_args()

    out = run({"skills": args.skills, "dry_run": args.dry_run})
    print(json.dumps(out, indent=2, ensure_ascii=False, default=str))
