#!/usr/bin/env python3
# CUI // SP-CTI
"""Genesis Test Reflex — identify under-tested tools, generate and run tests.

Scans tools/ for modules with low or missing test coverage, generates
basic test stubs, runs them in a sandbox, and commits passing tests.

YELLOW tier (reversible writes — new test files only, worktree sandbox).
Scanner-tier only (zero Claude tokens).
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(BASE_DIR))


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _find_untested_modules(max_results: int = 10) -> List[Dict[str, Any]]:
    """Find Python modules in tools/ that lack corresponding test files."""
    tools_dir = BASE_DIR / "tools"
    tests_dir = BASE_DIR / "tests"

    untested = []
    for py_file in tools_dir.rglob("*.py"):
        if py_file.name.startswith("_"):
            continue
        if py_file.name in ("__init__.py", "setup.py"):
            continue

        # Derive expected test file name
        rel = py_file.relative_to(tools_dir)
        test_name = f"test_{rel.parts[-1]}"
        # Check common test locations
        has_test = False
        for test_dir in [tests_dir, tests_dir / "unit", tests_dir / "integration"]:
            if (test_dir / test_name).exists():
                has_test = True
                break
            # Also check nested structure
            nested = test_dir
            for part in rel.parts[:-1]:
                nested = nested / part
            if (nested / test_name).exists():
                has_test = True
                break

        if not has_test:
            untested.append({
                "module": str(rel).replace("\\", "/"),
                "path": str(py_file),
                "name": py_file.stem,
            })

    # Sort by directory depth (shallower = more important)
    untested.sort(key=lambda x: x["module"].count("/"))
    return untested[:max_results]


def _generate_test_stub(module_info: Dict[str, Any]) -> Optional[str]:
    """Generate a basic test stub for a module (deterministic, no LLM)."""
    module_path = module_info["module"]  # e.g., "pulse/db.py"
    module_name = module_info["name"]

    # Convert path to import
    import_path = "tools." + module_path.replace("/", ".").replace(".py", "")

    test_code = f'''#!/usr/bin/env python3
# CUI // SP-CTI
"""Auto-generated test stub for {import_path}.

Generated by Genesis Test Reflex.  Validates basic importability
and function signatures.
"""

import sys
from pathlib import Path

# Ensure project root is on path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pytest


def test_{module_name}_imports():
    """Verify module can be imported without errors."""
    try:
        import {import_path}
    except ImportError as e:
        pytest.skip(f"Import dependency missing: {{e}}")


def test_{module_name}_has_expected_attributes():
    """Verify module exposes expected public API."""
    try:
        mod = __import__("{import_path}", fromlist=["{module_name}"])
        # Check that module has at least one public callable
        public = [a for a in dir(mod) if not a.startswith("_") and callable(getattr(mod, a, None))]
        assert len(public) > 0, f"Module has no public callables: {{dir(mod)}}"
    except ImportError:
        pytest.skip("Module not importable")
'''
    return test_code


def _run_test(test_file: Path, timeout: int = 60) -> Dict[str, Any]:
    """Run a single test file via pytest."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pytest", str(test_file), "-v", "--tb=short"],
            capture_output=True, text=True, timeout=timeout,
            cwd=str(BASE_DIR),
            env={**os.environ, "PYTHONPATH": str(BASE_DIR)},
        )
        passed = result.returncode == 0
        return {
            "passed": passed,
            "returncode": result.returncode,
            "stdout": result.stdout[-1000:] if result.stdout else "",
            "stderr": result.stderr[-500:] if result.stderr else "",
        }
    except subprocess.TimeoutExpired:
        return {"passed": False, "error": "timeout"}
    except Exception as e:
        return {"passed": False, "error": str(e)}


def run(config: Dict[str, Any], trust: Any) -> Dict[str, Any]:
    """Execute the Test Reflex."""
    max_tests = config.get("max_tests_per_run", 10)

    # Find untested modules
    untested = _find_untested_modules(max_results=max_tests)
    if not untested:
        return {
            "success": True,
            "metric_value": 0.0,
            "details": {"status": "all_modules_have_tests"},
        }

    tests_dir = BASE_DIR / "tests" / "genesis_auto"
    tests_dir.mkdir(parents=True, exist_ok=True)

    results = []
    tests_passing = 0

    for module_info in untested[:max_tests]:
        test_code = _generate_test_stub(module_info)
        if not test_code:
            continue

        test_file = tests_dir / f"test_{module_info['name']}.py"
        test_file.write_text(test_code, encoding="utf-8")

        # Run the test
        print(f"  Test: {module_info['module']}")
        result = _run_test(test_file)

        if result.get("passed"):
            tests_passing += 1
            results.append({
                "module": module_info["module"],
                "test_file": str(test_file.relative_to(BASE_DIR)),
                "status": "passed",
            })
        else:
            # Remove failing test stubs (don't litter)
            test_file.unlink(missing_ok=True)
            results.append({
                "module": module_info["module"],
                "status": "failed",
                "error": result.get("error", result.get("stderr", "")[:200]),
            })

    return {
        "success": tests_passing > 0,
        "metric_value": float(tests_passing),
        "details": {
            "untested_modules_found": len(untested),
            "tests_generated": len(results),
            "tests_passing": tests_passing,
            "results": results,
        },
    }
