"""Network IaC Generator — NDC Workflow Step 3.

Generates Terraform, Ansible, and validation artifacts for the network design
canvas. Produces:
  data/studio_artifacts/ndc/terraform/main_<uid>.tf
  data/studio_artifacts/ndc/terraform/variables.tf
  data/studio_artifacts/ndc/terraform/terraform.tfvars.example
  data/studio_artifacts/ndc/ansible_playbook_<uid>.yml
  data/studio_artifacts/ndc/validate_<uid>.py
  data/studio_artifacts/ndc/iac_report_<uid>.md

Outputs JSON contract to stdout.
"""
import argparse
import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_ROOT))

_CANVAS = "ndc"
_ARTIFACTS_DIR = _ROOT / "data" / "studio_artifacts" / _CANVAS

# ── Terraform template ────────────────────────────────────────────────────────

_TF_MAIN = '''\
# Network Infrastructure — Generated by ICDEV™ NDC Workflow
# Canvas: ndc
# Generated: {ts}
# DO NOT EDIT — regenerate via NDC Workflow
# Approval role: network_architect

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
  required_version = ">= 1.6.0"
}}

locals {{
  common_tags = {{
    ManagedBy      = "icdev-ndc"
    Canvas         = "ndc"
    Classification = "CUI"
    Environment    = var.environment
  }}
}}

# ── VPC ───────────────────────────────────────────────────────────────────────

resource "aws_vpc" "main" {{
  cidr_block           = var.vpc_cidr
  enable_dns_support   = true
  enable_dns_hostnames = true
  tags = merge(local.common_tags, {{ Name = "icdev-vpc-${{var.environment}}" }})
}}

# ── Subnets ───────────────────────────────────────────────────────────────────

resource "aws_subnet" "public" {{
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.1.0/24"
  availability_zone       = var.az_primary
  map_public_ip_on_launch = false
  tags = merge(local.common_tags, {{ Name = "icdev-public-subnet", Tier = "public" }})
}}

resource "aws_subnet" "private" {{
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.2.0/24"
  availability_zone = var.az_secondary
  tags = merge(local.common_tags, {{ Name = "icdev-private-subnet", Tier = "private" }})
}}

# ── Internet Gateway ──────────────────────────────────────────────────────────

resource "aws_internet_gateway" "igw" {{
  vpc_id = aws_vpc.main.id
  tags   = merge(local.common_tags, {{ Name = "icdev-igw" }})
}}

# ── NAT Gateway ───────────────────────────────────────────────────────────────

resource "aws_eip" "nat" {{
  domain = "vpc"
  tags   = merge(local.common_tags, {{ Name = "icdev-nat-eip" }})
}}

resource "aws_nat_gateway" "nat" {{
  allocation_id = aws_eip.nat.id
  subnet_id     = aws_subnet.public.id
  tags          = merge(local.common_tags, {{ Name = "icdev-nat-gw" }})
  depends_on    = [aws_internet_gateway.igw]
}}

# ── Route Tables ─────────────────────────────────────────────────────────────

resource "aws_route_table" "public" {{
  vpc_id = aws_vpc.main.id
  route {{
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.igw.id
  }}
  tags = merge(local.common_tags, {{ Name = "icdev-public-rt" }})
}}

resource "aws_route_table" "private" {{
  vpc_id = aws_vpc.main.id
  route {{
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.nat.id
  }}
  tags = merge(local.common_tags, {{ Name = "icdev-private-rt" }})
}}

resource "aws_route_table_association" "public" {{
  subnet_id      = aws_subnet.public.id
  route_table_id = aws_route_table.public.id
}}

resource "aws_route_table_association" "private" {{
  subnet_id      = aws_subnet.private.id
  route_table_id = aws_route_table.private.id
}}

# ── Security Groups ───────────────────────────────────────────────────────────

resource "aws_security_group" "app_tier" {{
  name        = "icdev-app-tier-${{var.environment}}"
  description = "App tier — HTTPS/HTTP inbound, all outbound"
  vpc_id      = aws_vpc.main.id

  ingress {{
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
    description = "HTTPS from private network"
  }}

  ingress {{
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
    description = "HTTP from private network (redirect to HTTPS)"
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "All outbound"
  }}

  tags = merge(local.common_tags, {{ Name = "icdev-app-tier-sg" }})
}}

resource "aws_security_group" "data_tier" {{
  name        = "icdev-data-tier-${{var.environment}}"
  description = "Data tier — PostgreSQL inbound from app tier only"
  vpc_id      = aws_vpc.main.id

  ingress {{
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [aws_security_group.app_tier.id]
    description     = "PostgreSQL from app tier only"
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "All outbound"
  }}

  tags = merge(local.common_tags, {{ Name = "icdev-data-tier-sg" }})
}}

# ── Network ACL ───────────────────────────────────────────────────────────────

resource "aws_network_acl" "private" {{
  vpc_id     = aws_vpc.main.id
  subnet_ids = [aws_subnet.private.id]

  ingress {{
    rule_no    = 100
    action     = "allow"
    protocol   = "tcp"
    cidr_block = "10.0.1.0/24"
    from_port  = 0
    to_port    = 65535
  }}

  ingress {{
    rule_no    = 32766
    action     = "deny"
    protocol   = "-1"
    cidr_block = "0.0.0.0/0"
    from_port  = 0
    to_port    = 0
  }}

  egress {{
    rule_no    = 100
    action     = "allow"
    protocol   = "-1"
    cidr_block = "0.0.0.0/0"
    from_port  = 0
    to_port    = 0
  }}

  tags = merge(local.common_tags, {{ Name = "icdev-private-nacl" }})
}}

# ── SSM Parameter (VPC ID store) ─────────────────────────────────────────────

resource "aws_ssm_parameter" "vpc_id" {{
  name  = "/icdev/${{var.environment}}/network/vpc_id"
  type  = "String"
  value = aws_vpc.main.id
  tags  = local.common_tags
}}
'''

_TF_VARIABLES = '''\
# variables.tf — Generated by ICDEV™ NDC Workflow

variable "vpc_cidr" {{
  type        = string
  description = "CIDR block for the VPC"
  default     = "10.0.0.0/16"
}}

variable "vpc_id" {{
  type        = string
  description = "Existing VPC ID (leave empty to create new VPC)"
  default     = ""
}}

variable "private_subnet_ids" {{
  type        = list(string)
  description = "Existing private subnet IDs (leave empty to create new subnets)"
  default     = []
}}

variable "artifacts_bucket" {{
  type        = string
  description = "S3 bucket for Terraform state and artifacts"
}}

variable "db_password" {{
  type        = string
  description = "Database password (injected via TFVARS_DEFAULTS)"
  sensitive   = true
  default     = ""
}}

variable "dw_password" {{
  type        = string
  description = "Data warehouse password (injected via TFVARS_DEFAULTS)"
  sensitive   = true
  default     = ""
}}

variable "environment" {{
  type        = string
  description = "Deployment environment"
  default     = "dev"
}}

variable "az_primary" {{
  type        = string
  description = "Primary availability zone"
  default     = "us-east-1a"
}}

variable "az_secondary" {{
  type        = string
  description = "Secondary availability zone"
  default     = "us-east-1b"
}}

variable "aws_region" {{
  type    = string
  default = "us-gov-west-1"
}}
'''

_TFVARS_EXAMPLE = '''\
# terraform.tfvars.example — NDC Network Infrastructure
# Copy to terraform.tfvars and fill in real values before terraform apply

aws_region       = "us-gov-west-1"
vpc_cidr         = "10.0.0.0/16"
artifacts_bucket = "icdev-network-artifacts-ACCOUNT_ID"
environment      = "dev"
az_primary       = "us-gov-west-1a"
az_secondary     = "us-gov-west-1b"
# vpc_id and private_subnet_ids: leave empty to create new, or fill in existing
# db_password and dw_password injected via CI/CD TFVARS_DEFAULTS
'''

def _build_ansible_playbook_ndc(ts: str) -> str:
    # Written as a function to avoid .format() conflicts with Jinja2 {{ }} syntax
    return (
        "---\n"
        "# Ansible Playbook — NDC Network Device Configuration\n"
        "# Generated: " + ts + "\n"
        "# Run after: terraform apply\n"
        "\n"
        "- name: NDC Network Post-Provisioning Configuration\n"
        "  hosts: network_devices\n"
        "  become: true\n"
        "  gather_facts: true\n"
        "\n"
        "  vars:\n"
        "    ntp_servers:\n"
        "      - 169.254.169.123  # AWS Time Sync Service (GovCloud)\n"
        "    syslog_server: \"{{ syslog_endpoint | default('localhost') }}\"\n"
        "\n"
        "  tasks:\n"
        "    - name: Configure NTP servers\n"
        "      ansible.builtin.copy:\n"
        "        dest: /etc/chrony.conf\n"
        "        content: |\n"
        "          {% for ntp in ntp_servers %}\n"
        "          server {{ ntp }} iburst\n"
        "          {% endfor %}\n"
        "          driftfile /var/lib/chrony/drift\n"
        "          makestep 1.0 3\n"
        "          rtcsync\n"
        "          logdir /var/log/chrony\n"
        "        mode: \"0644\"\n"
        "      notify: restart chronyd\n"
        "\n"
        "    - name: Configure rsyslog for centralized logging\n"
        "      ansible.builtin.copy:\n"
        "        dest: /etc/rsyslog.d/50-remote.conf\n"
        "        content: |\n"
        "          *.* @{{ syslog_server }}:514\n"
        "          $ActionQueueType LinkedList\n"
        "          $ActionQueueMaxDiskSpace 1g\n"
        "          $ActionQueueSaveOnShutdown on\n"
        "          $ActionResumeRetryCount -1\n"
        "        mode: \"0644\"\n"
        "      notify: restart rsyslog\n"
        "\n"
        "    - name: Apply network kernel hardening parameters\n"
        "      ansible.posix.sysctl:\n"
        "        name: \"{{ item.name }}\"\n"
        "        value: \"{{ item.value }}\"\n"
        "        sysctl_set: true\n"
        "        state: present\n"
        "        reload: true\n"
        "      loop:\n"
        "        - { name: \"net.ipv4.conf.all.rp_filter\", value: \"1\" }\n"
        "        - { name: \"net.ipv4.conf.default.rp_filter\", value: \"1\" }\n"
        "        - { name: \"net.ipv4.conf.all.accept_redirects\", value: \"0\" }\n"
        "        - { name: \"net.ipv4.conf.default.accept_redirects\", value: \"0\" }\n"
        "        - { name: \"net.ipv4.conf.all.secure_redirects\", value: \"0\" }\n"
        "        - { name: \"net.ipv4.conf.default.secure_redirects\", value: \"0\" }\n"
        "        - { name: \"net.ipv4.icmp_echo_ignore_broadcasts\", value: \"1\" }\n"
        "\n"
        "    - name: Verify VPC ID stored in SSM\n"
        "      ansible.builtin.command:\n"
        "        cmd: aws ssm get-parameter --name \"/icdev/{{ lookup('env','ENVIRONMENT') | default('dev') }}/network/vpc_id\"\n"
        "      register: vpc_ssm_check\n"
        "      changed_when: false\n"
        "      ignore_errors: true\n"
        "\n"
        "    - name: Report SSM VPC ID status\n"
        "      ansible.builtin.debug:\n"
        "        msg: \"SSM VPC ID parameter: {{ 'OK' if vpc_ssm_check.rc == 0 else 'MISSING' }}\"\n"
        "\n"
        "  handlers:\n"
        "    - name: restart chronyd\n"
        "      ansible.builtin.systemd:\n"
        "        name: chronyd\n"
        "        state: restarted\n"
        "\n"
        "    - name: restart rsyslog\n"
        "      ansible.builtin.systemd:\n"
        "        name: rsyslog\n"
        "        state: restarted\n"
    )

_VALIDATION_SCRIPT = '''\
#!/usr/bin/env python3
"""NDC Network Infrastructure Validation Script — Generated by ICDEV™ NDC Workflow
Generated: {ts}

Run after `terraform apply` to verify all NDC resources are provisioned correctly.
Usage:
  pip install boto3
  python validate_{uid}.py --region us-gov-west-1 [--profile <aws-profile>]
"""
import argparse
import sys

try:
    import boto3
except ImportError:
    print("boto3 is required. Run: pip install boto3")
    sys.exit(1)


def check(label, ok, detail=""):
    status = "PASS" if ok else "FAIL"
    msg = "  [" + status + "] " + str(label)
    if detail:
        msg += " -- " + str(detail)
    print(msg)
    return ok


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--region", default="us-gov-west-1")
    parser.add_argument("--profile", default=None)
    parser.add_argument("--env", default="dev")
    parser.add_argument("--vpc-cidr", default="10.0.0.0/16")
    args = parser.parse_args()

    session = boto3.Session(region_name=args.region, profile_name=args.profile)
    passed = 0
    failed = 0

    print("\\n=== NDC Validation: Network Infrastructure ===\\n")

    # Check VPC
    try:
        ec2 = session.client("ec2")
        vpcs = ec2.describe_vpcs(Filters=[
            {{"Name": "cidr-block", "Values": [args.vpc_cidr]}},
            {{"Name": "tag:ManagedBy", "Values": ["icdev-ndc"]}},
        ])["Vpcs"]
        ok = check("VPC (CIDR: " + args.vpc_cidr + ")", len(vpcs) > 0, f"{{len(vpcs)}} VPC(s)")
        passed += ok; failed += not ok
    except Exception as e:
        ok = check("VPC", False, str(e))
        passed += ok; failed += not ok

    # Check subnets
    try:
        ec2 = session.client("ec2")
        subnets = ec2.describe_subnets(Filters=[
            {{"Name": "tag:ManagedBy", "Values": ["icdev-ndc"]}},
        ])["Subnets"]
        has_public = any(s.get("Tags") and any(t["Key"] == "Tier" and t["Value"] == "public" for t in s.get("Tags", [])) for s in subnets)
        has_private = any(s.get("Tags") and any(t["Key"] == "Tier" and t["Value"] == "private" for t in s.get("Tags", [])) for s in subnets)
        ok = check("Subnets (public + private)", has_public and has_private, f"{{len(subnets)}} subnet(s)")
        passed += ok; failed += not ok
    except Exception as e:
        ok = check("Subnets", False, str(e))
        passed += ok; failed += not ok

    # Check route tables
    try:
        ec2 = session.client("ec2")
        rts = ec2.describe_route_tables(Filters=[
            {{"Name": "tag:ManagedBy", "Values": ["icdev-ndc"]}},
        ])["RouteTables"]
        ok = check("Route Tables", len(rts) >= 2, f"{{len(rts)}} route table(s)")
        passed += ok; failed += not ok
    except Exception as e:
        ok = check("Route Tables", False, str(e))
        passed += ok; failed += not ok

    # Check security groups
    try:
        ec2 = session.client("ec2")
        sgs = ec2.describe_security_groups(Filters=[
            {{"Name": "tag:ManagedBy", "Values": ["icdev-ndc"]}},
        ])["SecurityGroups"]
        ok = check("Security Groups", len(sgs) >= 2, f"{{len(sgs)}} SG(s)")
        passed += ok; failed += not ok
    except Exception as e:
        ok = check("Security Groups", False, str(e))
        passed += ok; failed += not ok

    # Check SSM VPC ID parameter
    try:
        ssm = session.client("ssm")
        ssm.get_parameter(Name=f"/icdev/{{args.env}}/network/vpc_id")
        ok = check("SSM VPC ID parameter", True)
        passed += ok; failed += not ok
    except Exception as e:
        ok = check("SSM VPC ID parameter", False, str(e))
        passed += ok; failed += not ok

    print(f"\\n=== Result: {{passed}} passed, {{failed}} failed ===\\n")
    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
'''

_IAC_REPORT = '''\
# NDC IaC Generation Report
**Generated:** {ts}
**Canvas:** ndc
**Approval Role:** network_architect

## Generated Artifacts

| Artifact | Path | Type |
|----------|------|------|
| Terraform Main | `{tf_main}` | tf |
| Terraform Variables | `{tf_vars}` | tf |
| Terraform tfvars example | `{tf_tfvars}` | tf |
| Ansible Playbook | `{ansible_pb}` | yml |
| Validation Script | `{validate_py}` | py |
| IaC Report | `{iac_report}` | md |

## Apply Instructions

```bash
cp terraform.tfvars.example terraform.tfvars
# Fill in: artifacts_bucket, az_primary, az_secondary
terraform init
terraform plan -var-file=terraform.tfvars
terraform apply -var-file=terraform.tfvars
```

## Post-Apply Steps

```bash
# Configure network devices
ansible-playbook -i inventory.ini ansible_playbook_*.yml

# Run validation
python validate_*.py --region us-gov-west-1
```

## Resources Provisioned

- `aws_vpc` — VPC (10.0.0.0/16, DNS enabled)
- `aws_subnet` (x2) — Public (10.0.1.0/24) and private (10.0.2.0/24)
- `aws_internet_gateway` — Internet gateway attached to VPC
- `aws_eip` — Elastic IP for NAT gateway
- `aws_nat_gateway` — NAT gateway in public subnet
- `aws_route_table` (x2) — Public (IGW) and private (NAT) route tables
- `aws_route_table_association` (x2) — Subnet associations
- `aws_security_group` — App tier (443/80 in, all out)
- `aws_security_group` — Data tier (5432 from app tier only)
- `aws_network_acl` — Private subnet NACL (deny 0.0.0.0/0)
- `aws_ssm_parameter` — VPC ID store

## Sign-off

| Role | Name | Signature | Date |
|------|------|-----------|------|
| Network Architect | | | |
| Security Officer | | | |
'''


def main():
    parser = argparse.ArgumentParser(description="NDC IaC Generator — Step 3")
    parser.add_argument("--project-id", default="default")
    parser.add_argument("--run-id", default="")
    parser.add_argument("--canvas", default=_CANVAS)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    try:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        uid = uuid.uuid4().hex[:8]

        _ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
        tf_dir = _ARTIFACTS_DIR / "terraform"
        tf_dir.mkdir(parents=True, exist_ok=True)

        tf_main_path = tf_dir / f"main_{uid}.tf"
        tf_vars_path = tf_dir / "variables.tf"
        tf_tfvars_path = tf_dir / "terraform.tfvars.example"
        ansible_path = _ARTIFACTS_DIR / f"ansible_playbook_{uid}.yml"
        validate_path = _ARTIFACTS_DIR / f"validate_{uid}.py"
        report_path = _ARTIFACTS_DIR / f"iac_report_{uid}.md"

        tf_main_path.write_text(_TF_MAIN.format(ts=ts), encoding="utf-8", newline="")
        tf_vars_path.write_text(_TF_VARIABLES, encoding="utf-8", newline="")
        tf_tfvars_path.write_text(_TFVARS_EXAMPLE, encoding="utf-8", newline="")
        ansible_path.write_text(_build_ansible_playbook_ndc(ts), encoding="utf-8", newline="")
        validate_path.write_text(_VALIDATION_SCRIPT.format(ts=ts, uid=uid), encoding="utf-8", newline="")
        report_path.write_text(_IAC_REPORT.format(
            ts=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            tf_main=tf_main_path.relative_to(_ROOT).as_posix(),
            tf_vars=tf_vars_path.relative_to(_ROOT).as_posix(),
            tf_tfvars=tf_tfvars_path.relative_to(_ROOT).as_posix(),
            ansible_pb=ansible_path.relative_to(_ROOT).as_posix(),
            validate_py=validate_path.relative_to(_ROOT).as_posix(),
            iac_report=report_path.relative_to(_ROOT).as_posix(),
        ), encoding="utf-8", newline="")

        output = {
            "gate": "PASS",
            "canvas": args.canvas,
            "artifacts": [
                {
                    "name": "Terraform Main",
                    "path": tf_main_path.relative_to(_ROOT).as_posix(),
                    "type": "tf",
                },
                {
                    "name": "Terraform Variables",
                    "path": tf_vars_path.relative_to(_ROOT).as_posix(),
                    "type": "tf",
                },
                {
                    "name": "Terraform tfvars example",
                    "path": tf_tfvars_path.relative_to(_ROOT).as_posix(),
                    "type": "tf",
                },
                {
                    "name": "Ansible Network Config Playbook",
                    "path": ansible_path.relative_to(_ROOT).as_posix(),
                    "type": "yml",
                },
                {
                    "name": "Validation Script",
                    "path": validate_path.relative_to(_ROOT).as_posix(),
                    "type": "py",
                },
                {
                    "name": "IaC Generation Report",
                    "path": report_path.relative_to(_ROOT).as_posix(),
                    "type": "md",
                },
            ],
        }
        print(json.dumps(output))
        sys.exit(0)
    except Exception as exc:
        print(json.dumps({"status": "failed", "error": str(exc)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
