#!/usr/bin/env python3
# CUI // SP-CTI
"""Generate MCP configuration files for different AI coding tools.

ADR D196: MCP is the primary integration protocol — tools with MCP support
get full ICDEV capability through the same 14 MCP servers.

Reads .mcp.json (Claude Code format, source of truth) and generates
tool-specific MCP config formats for Codex, Gemini, Amazon Q, Cline, etc.

Usage:
    python tools/dx/mcp_config_generator.py --all --write --json
    python tools/dx/mcp_config_generator.py --platform codex --dry-run
    python tools/dx/mcp_config_generator.py --platform amazon_q --write
"""

import argparse
import json
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

try:
    import yaml as _yaml
    def _load_yaml(path):
        with open(path, encoding="utf-8") as f:
            return _yaml.safe_load(f)
except ImportError:
    _yaml = None  # type: ignore[assignment]
    def _load_yaml(path):
        with open(path, encoding="utf-8") as f:
            return json.loads(f.read())


REGISTRY_PATH = BASE_DIR / "args" / "companion_registry.yaml"


def _load_mcp_servers(directory):
    """Load server definitions from .mcp.json."""
    mcp_path = Path(directory) / ".mcp.json"
    if not mcp_path.exists():
        return {}
    with open(mcp_path, encoding="utf-8") as f:
        data = json.loads(f.read())
    return data.get("mcpServers", {})


def _generate_codex_toml(servers):
    """Generate [mcp] section for .codex/config.toml."""
    lines = ["# ICDEV MCP servers for Codex CLI", "# Generated by ICDEV Companion", ""]
    for name, cfg in servers.items():
        cmd = cfg.get("command", "python")
        args_list = cfg.get("args", [])
        env = cfg.get("env", {})

        lines.append(f"[mcp.servers.{name}]")
        lines.append(f'command = "{cmd}"')
        args_str = ", ".join(f'"{a}"' for a in args_list)
        lines.append(f"args = [{args_str}]")
        if env:
            lines.append("[mcp.servers.{}.env]".format(name))
            for k, v in env.items():
                lines.append(f'  {k} = "{v}"')
        lines.append("")

    return "\n".join(lines)


def _generate_amazon_q_json(servers):
    """Generate .amazonq/mcp.json format (same structure as Claude's)."""
    return json.dumps({"mcpServers": servers}, indent=2)


def _generate_gemini_json(servers):
    """Generate .gemini/settings.json mcpServers section."""
    settings = {"mcpServers": servers}
    return json.dumps(settings, indent=2)


def _generate_cline_json(servers):
    """Generate Cline MCP settings format."""
    # Cline uses a slightly different structure with disabled flag
    cline_servers = {}
    for name, cfg in servers.items():
        cline_servers[name] = {
            "command": cfg.get("command", "python"),
            "args": cfg.get("args", []),
            "env": cfg.get("env", {}),
            "disabled": False,
        }
    return json.dumps({"mcpServers": cline_servers}, indent=2)


def _generate_setup_instructions(platform, servers):
    """Generate IDE-specific MCP setup instructions for Cursor/Windsurf/JetBrains."""
    server_list = "\n".join(
        f"  - **{name}**: `{cfg.get('command', 'python')} {' '.join(cfg.get('args', []))}`"
        for name, cfg in servers.items()
    )

    instructions = {
        "cursor": f"""# Cursor MCP Setup for ICDEV

## Steps
1. Open Cursor Settings (Cmd/Ctrl + ,)
2. Search for "MCP"
3. Add each server below:

## Servers
{server_list}

## Quick Setup
Copy `.mcp.json` to your Cursor MCP configuration. Cursor uses the same
JSON format as Claude Code for MCP server definitions.

## Environment Variables
Set for each server:
- `ICDEV_DB_PATH`: `data/icdev.db`
- `ICDEV_PROJECT_ROOT`: `.`
""",
        "windsurf": f"""# Windsurf MCP Setup for ICDEV

## Steps
1. Open Windsurf Settings > Cascade > MCP
2. Add each server below:

## Servers
{server_list}

## Environment Variables
- `ICDEV_DB_PATH`: `data/icdev.db`
- `ICDEV_PROJECT_ROOT`: `.`
""",
        "junie": f"""# JetBrains MCP Setup for ICDEV

## Steps
1. Open Settings > Tools > AI Assistant > Model Context Protocol (MCP)
2. Click "+" to add each server
3. Select "stdio" transport

## Servers
{server_list}

## Environment Variables
- `ICDEV_DB_PATH`: `data/icdev.db`
- `ICDEV_PROJECT_ROOT`: `.`
""",
    }
    return instructions.get(platform, f"# MCP Setup for {platform}\n\nUse `.mcp.json` format.")


# ── Config format mapping ──────────────────────────────────────────────

FORMAT_GENERATORS = {
    "codex_toml": ("codex", _generate_codex_toml, ".codex/config.toml"),
    "amazon_q": ("amazon_q", _generate_amazon_q_json, ".amazonq/mcp.json"),
    "gemini": ("gemini", _generate_gemini_json, ".gemini/settings.json"),
    "cline": ("cline", _generate_cline_json, ".cline/mcp_settings.json"),
}

IDE_PLATFORMS = {"cursor", "windsurf", "junie"}


def generate_mcp_config(directory=None, platforms=None,
                        write=False, dry_run=False):
    """Generate MCP configs for each platform from .mcp.json.

    Returns:
        dict: {platform: {path, content, format, written}}
    """
    directory = Path(directory) if directory else Path.cwd()
    servers = _load_mcp_servers(directory)

    if not servers:
        return {"error": "No .mcp.json found or empty mcpServers"}

    registry = _load_yaml(str(REGISTRY_PATH)) if REGISTRY_PATH.exists() else {}
    companions = registry.get("companions", {})

    # Resolve platforms
    all_mcp_platforms = ["codex", "amazon_q", "gemini", "cline",
                         "cursor", "windsurf", "junie"]
    if platforms is None or platforms == ["all"]:
        platforms = all_mcp_platforms
    elif isinstance(platforms, str):
        platforms = [p.strip() for p in platforms.split(",")]

    results = {}

    for platform in platforms:
        companion_cfg = companions.get(platform, {})
        if not companion_cfg.get("mcp_support", False) and platform not in all_mcp_platforms:
            results[platform] = {"error": f"{platform} does not support MCP"}
            continue

        mcp_format = companion_cfg.get("mcp_config_format", "ide_settings")

        if platform in IDE_PLATFORMS:
            content = _generate_setup_instructions(platform, servers)
            output_path = f".{platform}/mcp-setup.md"
        elif platform == "codex":
            content = _generate_codex_toml(servers)
            output_path = ".codex/mcp-config.toml"
        elif platform == "amazon_q":
            content = _generate_amazon_q_json(servers)
            output_path = ".amazonq/mcp.json"
        elif platform == "gemini":
            content = _generate_gemini_json(servers)
            output_path = ".gemini/mcp-settings.json"
        elif platform == "cline":
            content = _generate_cline_json(servers)
            output_path = ".cline/mcp_settings.json"
        else:
            content = json.dumps({"mcpServers": servers}, indent=2)
            output_path = f".{platform}/mcp.json"

        full_path = directory / output_path
        written = False

        if write and not dry_run:
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")
            written = True

        results[platform] = {
            "path": output_path,
            "full_path": str(full_path),
            "content": content,
            "format": mcp_format,
            "written": written,
            "server_count": len(servers),
            "display_name": companion_cfg.get("display_name", platform),
        }

    return results


def main():
    parser = argparse.ArgumentParser(
        description="Generate MCP configuration for AI coding tools"
    )
    parser.add_argument("--dir", help="Project directory")
    parser.add_argument("--platform", help="Comma-separated platform IDs")
    parser.add_argument("--all", action="store_true", help="All MCP-capable platforms")
    parser.add_argument("--write", action="store_true", help="Write files to disk")
    parser.add_argument("--dry-run", action="store_true", help="Preview")
    parser.add_argument("--json", action="store_true", help="Output JSON")
    args = parser.parse_args()

    platforms = ["all"] if args.all else (
        [p.strip() for p in args.platform.split(",")] if args.platform else None
    )

    results = generate_mcp_config(
        directory=args.dir, platforms=platforms,
        write=args.write, dry_run=args.dry_run,
    )

    if args.json:
        out = {}
        for k, v in results.items():
            if isinstance(v, dict) and "content" in v:
                entry = {kk: vv for kk, vv in v.items() if kk != "content"}
                out[k] = entry
            else:
                out[k] = v
        print(json.dumps(out, indent=2))
    else:
        if "error" in results:
            print(f"ERROR: {results['error']}")
            sys.exit(1)
        for platform, info in results.items():
            if "error" in info:
                print(f"ERROR [{platform}]: {info['error']}")
                continue
            status = "WRITTEN" if info["written"] else "PREVIEW"
            print(f"[{status}] {info['display_name']}: {info['path']} ({info['server_count']} servers)")


if __name__ == "__main__":
    main()
