# CUI // SP-CTI
"""ICDEV™ git CLI helper for the CI/CD workflow scripts.

A thin, safety-conscious wrapper around the local ``git`` binary plus
the platform-agnostic VCS abstraction in ``tools.ci.modules.vcs``. The
workflow scripts under ``tools/ci/workflows/icdev_*.py`` use this
module to branch, commit, push, and open or update a PR/MR without
caring whether the remote is GitHub or GitLab.

Implements the contract documented in
``docs/rewrite/adw/specs/tools/ci/modules/git_ops.md`` (OPT-75 Phase 3
clean-room rewrite).
"""
from __future__ import annotations
from tools.logging.icdev_logger import get_logger

import os
import subprocess
from pathlib import Path
from typing import Any, List, Optional, Sequence, Tuple


PROJECT_ROOT: Path = Path(__file__).resolve().parents[3]

_module_logger = get_logger(__name__)


# ────────────────────────────────────────────────────────────────────────────
# Internal helper
# ────────────────────────────────────────────────────────────────────────────


def _run_git(
    args: Sequence[str],
    cwd: Optional[str] = None,
) -> Tuple[str, str, int]:
    """Run ``git`` with the given args and return ``(stdout, stderr, rc)``.

    Output is captured, decoded as text, and stripped of trailing
    whitespace. ``cwd`` defaults to the repo root.
    """
    completed = subprocess.run(
        ["git", *list(args)],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        cwd=cwd or str(PROJECT_ROOT),
    )
    return (
        (completed.stdout or "").strip(),
        (completed.stderr or "").strip(),
        completed.returncode,
    )


# ────────────────────────────────────────────────────────────────────────────
# Branch / commit / push primitives
# ────────────────────────────────────────────────────────────────────────────


def create_branch(branch_name: str) -> Tuple[bool, Optional[str]]:
    """Check out ``branch_name``, creating it if necessary.

    Tries ``git checkout -b <branch>`` first. If that fails (typically
    because the branch already exists), tries a plain ``git checkout
    <branch>`` as the fallback. Returns ``(True, None)`` on success or
    ``(False, reason)`` on failure.
    """
    _, create_err, create_rc = _run_git(["checkout", "-b", branch_name])
    if create_rc == 0:
        return True, None

    _, _, switch_rc = _run_git(["checkout", branch_name])
    if switch_rc == 0:
        return True, None

    return False, f"Failed to create branch '{branch_name}': {create_err}"


def commit_changes(
    message: str,
    paths: Optional[List[str]] = None,
) -> Tuple[bool, Optional[str]]:
    """Stage changes and create a commit.

    Staging is intentionally narrow:

    * If ``paths`` is supplied, only those paths are added (``git add --
      <paths>``).
    * Otherwise the helper uses ``git add -u`` so only tracked, modified
      files are staged. We deliberately avoid ``git add -A`` because it
      would also pick up untracked files such as ``.env`` or credential
      blobs that the developer never intended to commit.

    A clean working tree is treated as a successful no-op, not an error.
    """
    if paths:
        _, add_err, add_rc = _run_git(["add", "--", *paths])
    else:
        _, add_err, add_rc = _run_git(["add", "-u"])
    if add_rc != 0:
        return False, f"git add failed: {add_err}"

    porcelain, _, _ = _run_git(["status", "--porcelain"])
    if not porcelain.strip():
        return True, None

    _, commit_err, commit_rc = _run_git(["commit", "-m", message])
    if commit_rc != 0:
        return False, f"git commit failed: {commit_err}"

    return True, None


def push_branch(branch_name: str) -> Tuple[bool, Optional[str]]:
    """Push ``branch_name`` to ``origin`` with upstream tracking."""
    _, push_err, push_rc = _run_git(["push", "-u", "origin", branch_name])
    if push_rc != 0:
        return False, f"git push failed: {push_err}"
    return True, None


def get_current_branch() -> Optional[str]:
    """Return the name of the currently-checked-out branch, or ``None``
    on error."""
    branch, _, rc = _run_git(["branch", "--show-current"])
    if rc != 0:
        return None
    return branch or None


# ────────────────────────────────────────────────────────────────────────────
# Workflow finaliser
# ────────────────────────────────────────────────────────────────────────────


def _bot_comment(text: str) -> str:
    return f"[ICDEV™-BOT] {text}"


def _build_pr_body(run_id: str, issue_number: Optional[Any]) -> str:
    parts: List[str] = ["## Summary",
                        f"Automated by ICDEV™ workflow run `{run_id}`",
                        ""]
    if issue_number:
        parts.append(f"Closes #{issue_number}")
        parts.append("")
    parts.append("## CUI // SP-CTI")
    parts.append("Generated by ICDEV™ CI/CD system.")
    return "\n".join(parts) + "\n"


def _build_pr_title(run_id: str, issue_number: Optional[Any]) -> str:
    if issue_number:
        return f"ICDEV™-{run_id}: Issue #{issue_number}"
    return f"ICDEV™-{run_id}"


def run_review_loop_preflight(state: Any, log: Any) -> None:
    """Self-green the branch with review_loop BEFORE pushing / opening a PR.

    Runs the diff-scoped review loop (ruff + changed-files coherence + SIPA)
    over the task's branch diff, applies deterministic autofixes, and commits
    them so the PR opens already-green — reducing pr_watcher (OPT-70) resume
    cycles downstream. Non-blocking and best-effort: any failure (or a
    not-green verdict) logs and returns; the push proceeds regardless. The
    fix_brief of non-deterministic findings is logged for the agent / reviewer.

    Disabled by setting ``ICDEV_REVIEW_LOOP_PREFLIGHT=0``.
    """
    if os.environ.get("ICDEV_REVIEW_LOOP_PREFLIGHT", "1").strip().lower() in ("0", "false", "no", "off"):
        return
    try:
        from tools.quality.review_loop import preflight, render_summary
    except Exception as exc:
        log.warning("review_loop preflight: import failed (%s) — skipping", exc)
        return

    base = "origin/main"
    if hasattr(state, "get"):
        base = state.get("base_branch") or state.get("base_ref") or base
    try:
        report = preflight(base=base, autofix=True, coherence_scope="changed", audit=True)
    except Exception as exc:
        log.warning("review_loop preflight: run failed (%s) — skipping", exc)
        return

    # Commit any deterministic autofixes the loop applied, so the PR is green.
    if _has_uncommitted_changes():
        _run_git(["add", "-A"])
        _, commit_err, rc = _run_git([
            "commit", "-m",
            "chore(review-loop): apply pre-PR autofixes (ruff/coherence)",
            "--no-verify",
        ])
        if rc == 0:
            log.info("review_loop preflight: committed autofixes")
        else:
            log.warning("review_loop preflight: autofix commit failed: %s", commit_err)

    if report.green:
        log.info("review_loop preflight: GREEN — all blocking gates pass")
    else:
        log.warning(
            "review_loop preflight: NOT green (%s) — %d open finding(s) left for review:\n%s",
            report.reason, len(report.fix_brief), render_summary(report),
        )


def _has_uncommitted_changes() -> bool:
    out, _, _ = _run_git(["status", "--porcelain"])
    return bool(out.strip())


def finalize_git_operations(state: Any, logger: Any, vcs: Any = None) -> None:
    """Push the current branch and ensure a PR/MR exists for it.

    This is the tail of every ``tools/ci/workflows/icdev_*.py`` script.
    Best-effort by design — every failure path logs and returns rather
    than raising. Tests can inject a fake ``vcs`` object that quacks
    like ``tools.ci.modules.vcs.VCS``.
    """
    log = logger if logger is not None else _module_logger

    branch_name = state.get("branch_name") if hasattr(state, "get") else None
    issue_number = state.get("issue_number") if hasattr(state, "get") else None
    run_id = state.get("run_id") if hasattr(state, "get") else None
    if not run_id:
        run_id = "unknown"

    if not branch_name:
        log.warning("finalize_git_operations: state has no branch_name")
        return

    if vcs is None:
        try:
            from tools.ci.modules.vcs import VCS  # lazy import
            vcs = VCS()
        except Exception as exc:
            log.error("finalize_git_operations: cannot init VCS: %s", exc)
            return

    # Pre-PR self-green: apply review_loop autofixes + commit before pushing.
    try:
        run_review_loop_preflight(state, log)
    except Exception as exc:  # never let preflight block the push
        log.warning("finalize_git_operations: review_loop preflight raised: %s", exc)

    log.info("finalize_git_operations: pushing %s", branch_name)
    pushed, push_err = push_branch(branch_name)
    if not pushed:
        log.error("finalize_git_operations: push failed: %s", push_err)
        if issue_number:
            try:
                vcs.comment_on_issue(
                    int(issue_number),
                    _bot_comment(f"Push failed: {push_err}"),
                )
            except Exception as exc:
                log.warning(
                    "finalize_git_operations: comment_on_issue raised: %s", exc
                )
        return

    log.info("finalize_git_operations: push ok")

    existing_url: Optional[str]
    try:
        existing_url = vcs.check_pr_exists(branch_name)
    except Exception as exc:
        log.warning(
            "finalize_git_operations: check_pr_exists raised: %s", exc
        )
        existing_url = None

    is_gitlab = bool(getattr(vcs, "is_gitlab", False))
    pr_label_short = "MR" if is_gitlab else "PR"
    pr_label_long = "Merge Request" if is_gitlab else "Pull Request"

    if existing_url:
        log.info(
            "finalize_git_operations: %s already exists at %s",
            pr_label_short, existing_url,
        )
        if issue_number:
            try:
                vcs.comment_on_issue(
                    int(issue_number),
                    _bot_comment(f"Updated existing {pr_label_short}: {existing_url}"),
                )
            except Exception as exc:
                log.warning(
                    "finalize_git_operations: comment_on_issue raised: %s", exc
                )
        return

    log.info("finalize_git_operations: creating new %s", pr_label_short)
    title = _build_pr_title(run_id, issue_number)
    body = _build_pr_body(run_id, issue_number)
    try:
        new_url = vcs.create_pr(title=title, body=body, head=branch_name)
    except Exception as exc:
        log.error("finalize_git_operations: create_pr raised: %s", exc)
        return

    if new_url:
        log.info(
            "finalize_git_operations: %s created at %s", pr_label_long, new_url
        )
        if issue_number:
            try:
                vcs.comment_on_issue(
                    int(issue_number),
                    _bot_comment(f"Created {pr_label_long}: {new_url}"),
                )
            except Exception as exc:
                log.warning(
                    "finalize_git_operations: comment_on_issue raised: %s",
                    exc,
                )
    else:
        log.error("finalize_git_operations: %s create returned no URL",
                  pr_label_short)
