#!/usr/bin/env python3
# CUI // SP-CTI
"""The test-gating census runs at COMMIT time, not only in CI (tsg-policy-02).

WHAT THESE TESTS PIN
--------------------
tsg-policy-01 landed `gated_test_list.py --check-coverage` as a CI step. It works
— it caught two unregistered test files within two hours of existing — but it
caught them in the wrong place: each turned main RED, blocking every open PR, and
each cost a follow-up branch + PR + full CI cycle to add one line.

So the same census now also runs from `tools/testing/pre_commit_check.py`. The
four properties that matter, one test each:

  * a commit that ADDS an unregistered test file is refused, and the message
    names the file and where to register it;
  * a commit that touches NO test file never reaches the census at all (the
    fast path must cost nothing, or it gets ripped out);
  * the hook never edits args/ci_test_files/core.txt itself — auto-appending
    would gate a test nobody has run, which is the failure tsg-policy-01 exists
    to close;
  * a commit that adds a test file AND registers it in the same commit passes,
    which is the workflow the policy actually asks for.

Every case runs against a REAL throwaway git repository with a real staged index,
because the load-bearing assumption of the whole feature is that `git ls-files`
inside a pre-commit hook already sees a file that is staged but not committed. A
test that mocked git would pass whether or not that were true.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from tools.ci import gated_test_list as census_mod
from tools.testing import pre_commit_check

REPO_ROOT = Path(__file__).resolve().parents[2]


GATE_YAML = """\
scope:
  roots:
    - tests/
  patterns:
    - "test_*.py"
    - "*_test.py"
exclusions:
  - pattern: "tests/generated/**"
    reason: generated by a tool, gated at the generator instead
backlog_file: args/ci_test_backlog.txt
backlog_max: 1
"""


def _git(root: Path, *args: str) -> subprocess.CompletedProcess:
    proc = subprocess.run(
        ["git", "-C", str(root), *args], capture_output=True, text=True, check=False
    )
    assert proc.returncode == 0, f"git {' '.join(args)} failed: {proc.stderr}"
    return proc


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n": a trailing CR in an allowlist makes every consumer report
    # "file not found" for a path that plainly exists.
    path.write_text(text, encoding="utf-8", newline="\n")


@pytest.fixture()
def repo(tmp_path: Path) -> Path:
    """A committed repo carrying the policy files, one gated test, one backlog one."""
    root = tmp_path / "checkout"
    root.mkdir()
    _git(root.parent, "init", "-q", str(root))
    _git(root, "config", "user.email", "gate@example.test")
    _git(root, "config", "user.name", "Gate Test")

    _write(root / "args" / "test_gating_gate.yaml", GATE_YAML)
    _write(root / "args" / "ci_test_files" / "core.txt", "tests/test_gated.py\n")
    _write(root / "args" / "ci_test_files" / "windows.txt", "tests/test_gated.py\n")
    _write(root / "args" / "ci_test_backlog.txt", "tests/test_old_debt.py\n")
    _write(root / "tests" / "test_gated.py", "def test_ok():\n    assert True\n")
    _write(root / "tests" / "test_old_debt.py", "def test_ok():\n    assert True\n")
    _write(root / "docs" / "notes.md", "notes\n")
    _write(root / "tools" / "widget.py", "VALUE = 1\n")

    _git(root, "add", "-A")
    _git(root, "commit", "-qm", "baseline")
    return root


def _name_status(root: Path) -> list[tuple[str, str]]:
    return pre_commit_check._get_staged_name_status(root)


# --------------------------------------------------------------------------- #
# 1. Adding an unregistered test file is refused, by name
# --------------------------------------------------------------------------- #
def test_baseline_repo_is_compliant(repo: Path) -> None:
    """Guard the fixture: everything below is meaningless if this starts red."""
    report = census_mod.census(repo)
    assert report["ok"] is True, report["errors"]
    assert report["unlisted"] == []


def test_staged_new_test_file_is_detected(repo: Path) -> None:
    _write(repo / "tests" / "test_brand_new.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "tests/test_brand_new.py")

    assert census_mod.staged_added_or_renamed(repo) == ["tests/test_brand_new.py"]
    assert census_mod.staged_new_test_files(repo) == ["tests/test_brand_new.py"]


def test_staged_new_test_file_fails_the_census_naming_the_file(repo: Path) -> None:
    """A staged-but-uncommitted file must already be visible to the census."""
    _write(repo / "tests" / "test_brand_new.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "tests/test_brand_new.py")

    report = census_mod.census(repo)
    assert report["ok"] is False
    assert report["unlisted"] == ["tests/test_brand_new.py"]
    message = " ".join(report["errors"])
    assert "tests/test_brand_new.py" in message
    assert "args/ci_test_files/core.txt" in message


def test_pre_commit_gate_blocks_and_prints_where_to_register(
    repo: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """End to end through the hook's own entry points, against the real CLI."""
    _write(repo / "tests" / "test_brand_new.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "tests/test_brand_new.py")

    new_tests = pre_commit_check._staged_new_test_files(_name_status(repo), root=repo)
    assert new_tests == ["tests/test_brand_new.py"]

    # The census tool lives in THIS checkout; the repo under test is the target.
    ok = pre_commit_check._run_test_gating_census(new_tests, root=repo)
    out = capsys.readouterr().out
    assert ok is False, out
    assert "tests/test_brand_new.py" in out
    assert "args/ci_test_files/core.txt" in out
    assert "BLOCKED" in out


def test_renamed_test_file_counts_as_new(repo: Path) -> None:
    """A rename lands under a name no allowlist covers — that is a new file."""
    _git(repo, "mv", "tests/test_gated.py", "tests/test_gated_renamed.py")

    assert census_mod.staged_new_test_files(repo) == ["tests/test_gated_renamed.py"]
    report = census_mod.census(repo)
    assert report["unlisted"] == ["tests/test_gated_renamed.py"]


# --------------------------------------------------------------------------- #
# 2. A commit touching no test files never reaches the census
# --------------------------------------------------------------------------- #
def test_commit_touching_no_test_files_skips_the_census(
    repo: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Modifying a tool and a doc must not run — or even load — the census."""
    _write(repo / "tools" / "widget.py", "VALUE = 2\n")
    _write(repo / "docs" / "notes.md", "more notes\n")
    _git(repo, "add", "-A")

    def _boom(*_args, **_kwargs):  # pragma: no cover - the point is it never runs
        raise AssertionError("the census must not load for a commit with no new tests")

    monkeypatch.setattr(pre_commit_check, "_load_census_module", _boom)
    monkeypatch.setattr(pre_commit_check, "_run_test_gating_census", _boom)

    assert pre_commit_check._staged_new_test_files(_name_status(repo), root=repo) == []


def test_adding_a_non_test_file_is_not_gated(repo: Path) -> None:
    """Adding files is fine; only files the census COLLECTS trigger the gate."""
    _write(repo / "tools" / "another.py", "VALUE = 3\n")
    _write(repo / "tests" / "helper_utils.py", "HELPER = 1\n")  # not test_*.py
    _git(repo, "add", "-A")

    assert sorted(census_mod.staged_added_or_renamed(repo)) == [
        "tests/helper_utils.py",
        "tools/another.py",
    ]
    assert census_mod.staged_new_test_files(repo) == []
    assert pre_commit_check._staged_new_test_files(_name_status(repo), root=repo) == []


def test_modifying_an_already_gated_test_file_is_not_new(repo: Path) -> None:
    _write(repo / "tests" / "test_gated.py", "def test_ok():\n    assert 1 == 1\n")
    _git(repo, "add", "-A")

    assert census_mod.staged_added_or_renamed(repo) == []
    assert census_mod.staged_new_test_files(repo) == []


def test_scope_decision_is_read_from_the_policy_not_hardcoded(repo: Path) -> None:
    """Change `scope` in the YAML and the fast path follows it."""
    _write(
        repo / "args" / "test_gating_gate.yaml",
        GATE_YAML.replace('    - "test_*.py"\n', ""),
    )
    config = census_mod.load_gate_config(repo)

    assert census_mod.in_scope("tests/test_brand_new.py", config) is False
    assert census_mod.in_scope("tests/brand_new_test.py", config) is True


# --------------------------------------------------------------------------- #
# 3. The hook never widens the allowlist itself
# --------------------------------------------------------------------------- #
def test_gate_never_edits_core_txt(repo: Path) -> None:
    """Auto-appending would gate a test nobody has run — the original failure."""
    core = repo / "args" / "ci_test_files" / "core.txt"
    backlog = repo / "args" / "ci_test_backlog.txt"
    before = (core.read_bytes(), backlog.read_bytes())

    _write(repo / "tests" / "test_brand_new.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "tests/test_brand_new.py")

    new_tests = pre_commit_check._staged_new_test_files(_name_status(repo), root=repo)
    assert pre_commit_check._run_test_gating_census(new_tests, root=repo) is False

    assert (core.read_bytes(), backlog.read_bytes()) == before
    assert _git(repo, "status", "--porcelain", "args/").stdout.strip() == ""


# --------------------------------------------------------------------------- #
# 4. Register it in the same commit and the gate passes — the sanctioned fix
# --------------------------------------------------------------------------- #
def test_registering_in_the_same_commit_passes(
    repo: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    _write(repo / "tests" / "test_brand_new.py", "def test_x():\n    assert True\n")
    _write(
        repo / "args" / "ci_test_files" / "core.txt",
        "tests/test_gated.py\ntests/test_brand_new.py\n",
    )
    _git(repo, "add", "-A")

    new_tests = pre_commit_check._staged_new_test_files(_name_status(repo), root=repo)
    assert new_tests == ["tests/test_brand_new.py"]
    assert pre_commit_check._run_test_gating_census(new_tests, root=repo) is True
    assert "OK" in capsys.readouterr().out


def test_pre_existing_offender_does_not_block_a_compliant_commit(
    repo: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The tree can be red through no fault of the author — main was, twice.

    Blocking on someone else's ungated file would refuse a commit the author
    cannot fix without stepping on the PR that already owns it, and a hook that
    refuses commits you cannot fix gets --no-verify'd permanently. Report it,
    leave it to CI, and gate only what this commit introduces.
    """
    _write(repo / "tests" / "test_someone_elses.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "an ungated file lands (as if via another PR)")

    _write(repo / "tests" / "test_mine.py", "def test_x():\n    assert True\n")
    _write(
        repo / "args" / "ci_test_files" / "core.txt",
        "tests/test_gated.py\ntests/test_mine.py\n",
    )
    _git(repo, "add", "-A")

    new_tests = pre_commit_check._staged_new_test_files(_name_status(repo), root=repo)
    assert new_tests == ["tests/test_mine.py"]

    # The census itself is still red on the whole tree...
    assert census_mod.census(repo)["unlisted"] == ["tests/test_someone_elses.py"]
    # ...but this commit is clean, so it is allowed, with the other file reported.
    assert pre_commit_check._run_test_gating_census(new_tests, root=repo) is True
    out = capsys.readouterr().out
    assert "tests/test_someone_elses.py" in out
    assert "BLOCKED" not in out


def test_own_offender_blocks_even_when_others_are_red_too(
    repo: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Attribution must not become an excuse: my unregistered file still blocks."""
    _write(repo / "tests" / "test_someone_elses.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "an ungated file lands")

    _write(repo / "tests" / "test_mine.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "-A")

    new_tests = pre_commit_check._staged_new_test_files(_name_status(repo), root=repo)
    assert pre_commit_check._run_test_gating_census(new_tests, root=repo) is False
    out = capsys.readouterr().out
    assert "BLOCKED" in out
    assert "tests/test_mine.py" in out


def test_documented_exclusion_also_passes(repo: Path) -> None:
    """An exclusion WITH A REASON is the other sanctioned answer."""
    _write(repo / "tests" / "generated" / "test_made.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "-A")

    assert census_mod.staged_new_test_files(repo) == ["tests/generated/test_made.py"]
    assert census_mod.census(repo)["ok"] is True


# --------------------------------------------------------------------------- #
# 5. The fast path fails OPEN — CI is the backstop, so it must never false-block
# --------------------------------------------------------------------------- #
def test_unreadable_policy_does_not_block_the_commit(
    repo: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    (repo / "args" / "test_gating_gate.yaml").unlink()
    _write(repo / "tests" / "test_brand_new.py", "def test_x():\n    assert True\n")
    _git(repo, "add", "-A")

    assert pre_commit_check._staged_new_test_files(_name_status(repo), root=repo) == []
    assert "SKIPPED" in capsys.readouterr().out


def test_ci_still_runs_the_census_independently() -> None:
    """The hook is the fast path; deleting the CI step would remove the backstop."""
    workflow = (REPO_ROOT / ".github" / "workflows" / "icdev-ci.yml").read_text(
        encoding="utf-8"
    )
    assert "gated_test_list.py --check-coverage" in workflow
