# CUI // SP-CTI
"""FORGE Academy AI Injection Pattern Library — 8 patterns for modernizing existing apps."""

from __future__ import annotations

INJECTION_PATTERNS = [
    {
        "id": "conversational-wrapper",
        "title": "Conversational Wrapper",
        "icon": "💬",
        "color": "#4A90E2",
        "use_case": "Add natural language chat to any existing CRUD application",
        "when_to_use": [
            "Users need to query or interact with your app in plain language",
            "You have existing REST APIs or a database that's hard to navigate",
            "You want to add a help/support layer without rebuilding the UI",
        ],
        "architecture": "User input → LLM (intent extraction) → existing API/DB → LLM (response synthesis) → user",
        "complexity": "Low",
        "phase": "Phase 1 — Quick Win",
        "phase_tag": "phase1",
        "approach": "Prompt-Only or RAG",
        "aadc_template": "conversational-wrapper",
        "pitfalls": [
            "LLM may hallucinate field names — always validate against your actual schema",
            "Don't pass raw DB query results to the LLM — summarize or paginate first",
            "Session memory accumulates — implement a sliding window or summary strategy",
        ],
        "missions": ["m02-prompt-engineering", "m03-rag-basics", "m-chat-agent-interview"],
        "ops_tools": ["tools/agent/token_tracker.py", "tools/llm/prompt_registry.py"],
        "example": "A legacy HR portal adds 'Ask HR' — employees ask questions about leave policies, benefits, and org chart in plain English. The LLM queries the existing HR database via existing REST APIs.",
        "steps": [
            "Wrap your existing API endpoints with an MCP server",
            "Create a system prompt that describes your data model in natural language",
            "Add a conversation endpoint that routes user input through the LLM to your API",
            "Implement response streaming for perceived responsiveness",
        ],
    },
    {
        "id": "document-intelligence",
        "title": "Document Intelligence",
        "icon": "📄",
        "color": "#00D4FF",
        "use_case": "Enable natural language Q&A over existing document stores, SharePoint, or file shares",
        "when_to_use": [
            "Your org has large volumes of PDFs, Word docs, or reports that are hard to search",
            "Users need to find answers across multiple documents simultaneously",
            "You need to surface knowledge from unstructured content at scale",
        ],
        "architecture": "Documents → chunking & embedding → vector store → RAG retrieval → LLM synthesis → grounded answer with citations",
        "complexity": "Medium",
        "phase": "Phase 1 — Quick Win",
        "phase_tag": "phase1",
        "approach": "RAG",
        "aadc_template": "document-rag",
        "pitfalls": [
            "Chunk size matters — too large loses precision, too small loses context",
            "Always surface source citations — never let the LLM answer without grounding",
            "Stale documents poison the index — implement a re-index trigger on document change",
        ],
        "missions": ["m03-rag-basics", "m-dataops-01-advanced-rag", "m-dataops-02-chromadb-rag"],
        "ops_tools": ["tools/rag/quality_feedback_loop.py", "tools/llm/model_monitor.py"],
        "example": "A DoD program office with 10,000 policy documents adds a RAG layer. Staff ask 'What are the CMMC Level 2 requirements for cloud storage?' and get a grounded answer with paragraph citations.",
        "steps": [
            "Choose a vector store (ChromaDB for local/air-gap, Pinecone for cloud)",
            "Chunk documents at paragraph level with 50-token overlap",
            "Embed with the same model you'll use at query time",
            "Add a citation template to your system prompt — require source + page number",
        ],
    },
    {
        "id": "intelligent-search",
        "title": "Intelligent Search",
        "icon": "🔍",
        "color": "#00FF88",
        "use_case": "Replace keyword search with semantic search across any existing data store",
        "when_to_use": [
            "Your current search returns zero results for natural language queries",
            "Users need to find conceptually related content, not just keyword matches",
            "You have a catalog, knowledge base, or product database with rich text",
        ],
        "architecture": "Query → embedding → cosine similarity against pre-indexed store → ranked results → optional LLM re-ranking",
        "complexity": "Low",
        "phase": "Phase 1 — Quick Win",
        "phase_tag": "phase1",
        "approach": "RAG",
        "aadc_template": "semantic-search",
        "pitfalls": [
            "The query embedding model must match the index embedding model exactly",
            "Semantic search doesn't replace filters — combine with metadata filtering for precision",
            "Re-ranking with LLM adds latency — only use for top-k re-scoring, not full corpus",
        ],
        "missions": ["m03-rag-basics", "m-dataops-02-chromadb-rag"],
        "ops_tools": ["tools/agent/token_tracker.py"],
        "example": "A procurement system replaces its keyword search with semantic search. Searching 'network security gear' now surfaces 'firewall appliances', 'IDS/IPS systems', and 'zero trust hardware' even without those exact words.",
        "steps": [
            "Embed your existing catalog/knowledge base records at build time",
            "Replace the search endpoint to embed the query and run cosine similarity",
            "Return top-k results ranked by similarity score",
            "Add a 'Did you mean?' LLM layer for zero-result queries",
        ],
    },
    {
        "id": "autonomous-background-agent",
        "title": "Autonomous Background Agent",
        "icon": "⚙️",
        "color": "#FF6B35",
        "use_case": "Schedule an AI agent to run over your existing data on a cron-like cadence",
        "when_to_use": [
            "You have a manual review or triage process that runs daily/weekly",
            "Your team monitors feeds, inboxes, or dashboards and takes routine action",
            "You want AI to process data while humans sleep",
        ],
        "architecture": "Trigger (schedule/event) → agent loads data → LLM reasoning loop → structured output → action (update DB / send notification / create ticket)",
        "complexity": "Medium",
        "phase": "Phase 2 — Augmentation",
        "phase_tag": "phase2",
        "approach": "Agentic",
        "aadc_template": "background-agent",
        "pitfalls": [
            "Agents without circuit breakers will retry forever — implement max-iteration limits",
            "Always log every action the agent takes for audit trail compliance",
            "Don't let the agent write to production without a human-review gate on first run",
        ],
        "missions": ["m04-first-agent", "m07-multi-agent", "m-devops-01-pipeline-agent"],
        "ops_tools": ["tools/agent/token_tracker.py", "tools/agentic_ai_canvas/safety_layer.py", "tools/compliance/audit_trail.py"],
        "example": "A compliance team's STIG triage agent runs nightly: ingests scan results, categorizes findings by severity, maps to NIST controls, and creates POA&M entries — before the team arrives in the morning.",
        "steps": [
            "Define the agent's decision loop: what it reads, what it decides, what it writes",
            "Set a circuit breaker: max iterations, max actions per run, human-review threshold",
            "Log all agent actions to the audit trail before executing",
            "Start with read-only mode — validate output quality before enabling write actions",
        ],
    },
    {
        "id": "decision-assist",
        "title": "Decision Assist",
        "icon": "🎯",
        "color": "#9B59B6",
        "use_case": "Put LLM reasoning in the loop for human review workflows without automating the decision",
        "when_to_use": [
            "Humans make repetitive judgment calls over structured data (approvals, classifications, risk ratings)",
            "Reviewers need context assembled from multiple sources before deciding",
            "You want AI to draft a recommendation that a human approves or rejects",
        ],
        "architecture": "Work item arrives → LLM assembles context + drafts recommendation → human reviews → human approves/rejects/edits → outcome logged",
        "complexity": "Low",
        "phase": "Phase 1 — Quick Win",
        "phase_tag": "phase1",
        "approach": "Prompt-Only or RAG",
        "aadc_template": "decision-assist",
        "pitfalls": [
            "Anchoring bias — humans tend to accept AI recommendations; make the override UX frictionless",
            "Track accept/reject rates — if humans override >40%, retune the prompt or model",
            "Never surface confidence scores as certainty — use language like 'Suggested:' not 'Determined:'",
        ],
        "missions": ["m02-prompt-engineering", "m03-rag-basics", "m-isso-01-stig-triage"],
        "ops_tools": ["tools/llm/prompt_registry.py", "tools/compliance/audit_trail.py"],
        "example": "A contract officer receives AI-drafted risk assessments for each incoming proposal. The AI highlights compliance gaps and suggests a risk tier. The CO confirms or overrides with a single click — decision time drops from 45 min to 8 min.",
        "steps": [
            "Identify the top 3 context sources a human needs before deciding",
            "Design a structured output schema: recommendation, confidence level, evidence list",
            "Build the review UI with a clear override mechanism and reason field",
            "Log all decisions with the AI recommendation and human outcome for continuous improvement",
        ],
    },
    {
        "id": "ai-augmented-api",
        "title": "AI-Augmented API",
        "icon": "🔌",
        "color": "#FFB800",
        "use_case": "Add AI post-processing to existing REST endpoints without changing upstream systems",
        "when_to_use": [
            "Your API returns raw data that clients have to interpret manually",
            "You want to add summarization, classification, or enrichment as an API layer",
            "You need a backward-compatible AI upgrade to an existing service",
        ],
        "architecture": "Existing API call → response intercepted → LLM enrichment layer → enhanced response returned to client",
        "complexity": "Low",
        "phase": "Phase 1 — Quick Win",
        "phase_tag": "phase1",
        "approach": "Prompt-Only",
        "aadc_template": "api-augmentation",
        "pitfalls": [
            "The AI layer adds latency — cache enrichments for identical upstream responses",
            "Version your enrichment prompts — a prompt change is a breaking change for downstream consumers",
            "Don't silently degrade — if LLM is unavailable, return the original API response with a flag",
        ],
        "missions": ["m02-prompt-engineering", "m-swe-sdk-typescript", "m-swe-sdk-java"],
        "ops_tools": ["tools/llm/router.py", "tools/agent/token_tracker.py"],
        "example": "A legacy system's /alerts endpoint returns raw SIEM events. An AI augmentation layer adds severity classification, plain-English summaries, and suggested remediation steps — the existing client doesn't change.",
        "steps": [
            "Add a middleware layer between your existing API and the client",
            "Define the enrichment schema: what fields does the AI add?",
            "Implement prompt versioning in your prompt registry",
            "Add a fallback: if AI enrichment fails, return original payload with 'ai_enriched: false'",
        ],
    },
    {
        "id": "workflow-orchestration",
        "title": "Workflow Orchestration",
        "icon": "🔄",
        "color": "#E74C3C",
        "use_case": "Replace manual multi-step workflows with an agent-driven orchestration layer",
        "when_to_use": [
            "A workflow requires multiple systems to be touched in sequence based on conditional logic",
            "Humans spend significant time on coordination and routing (not judgment)",
            "You have a workflow with well-defined steps but variable paths",
        ],
        "architecture": "Trigger event → orchestrator agent → task queue → specialized sub-agents (per system) → aggregated result → notification",
        "complexity": "High",
        "phase": "Phase 3 — Transformation",
        "phase_tag": "phase3",
        "approach": "Agentic",
        "aadc_template": "multi-agent-orchestration",
        "pitfalls": [
            "Orchestration amplifies errors — one bad step cascades. Build compensation logic for rollback.",
            "Idempotency is critical — agents will retry; every action must be safe to repeat",
            "Start with observer mode: shadow the manual process before replacing it",
        ],
        "missions": ["m07-multi-agent", "m08-strands-agents", "m09-langchain"],
        "ops_tools": ["tools/agentic_ai_canvas/safety_layer.py", "tools/compliance/audit_trail.py", "tools/monitor/auto_resolver.py"],
        "example": "An ATO renewal workflow that spans 6 systems (SIEM, STIG scanner, POA&M tracker, SSP editor, reviewer calendar, email) is replaced by an orchestrator agent that routes evidence, tracks status, and escalates blockers automatically.",
        "steps": [
            "Map the current workflow as a directed graph with decision branches",
            "Identify which steps require human judgment vs. pure routing",
            "Build sub-agents for each system integration; orchestrator only routes, doesn't execute",
            "Run in shadow mode for 2 weeks before disabling manual path",
        ],
    },
    {
        "id": "predictive-alert",
        "title": "Predictive Alert",
        "icon": "📡",
        "color": "#1ABC9C",
        "use_case": "Add anomaly detection and drift monitoring as an AI layer over existing metrics",
        "when_to_use": [
            "Your current alerts are threshold-based and miss gradual degradation",
            "You want to detect patterns before they become incidents",
            "You have time-series metrics but no ML pipeline",
        ],
        "architecture": "Metrics stream → baseline model → drift/anomaly detection → LLM context enrichment → prioritized alert with explanation",
        "complexity": "Medium",
        "phase": "Phase 2 — Augmentation",
        "phase_tag": "phase2",
        "approach": "Fine-Tune or RAG",
        "aadc_template": "drift-detector",
        "pitfalls": [
            "Alert fatigue kills adoption — tune sensitivity before going live, target <5 alerts/day initially",
            "Anomaly without context is noise — always pair the alert with an LLM-generated explanation",
            "Your baseline window must exclude known incidents or you'll never detect recurrence",
        ],
        "missions": ["m-sre-01-slo-agent", "m-sre-02-incident-agent", "m-analyst-03-pattern-detection"],
        "ops_tools": ["tools/llm/model_monitor.py", "tools/monitor/auto_resolver.py", "tools/observability/otel_tracer.py"],
        "example": "An infrastructure team replaces 200 static Grafana threshold alerts with a predictive layer. The AI detects gradual memory pressure trends 4 hours before OOM incidents — pages are cut by 60%.",
        "steps": [
            "Establish a baseline on 30 days of clean historical metrics",
            "Define 'normal' bands using rolling statistics (mean ± 2σ, percentile-based)",
            "Pair every anomaly signal with an LLM explanation referencing recent system changes",
            "Implement a feedback loop: engineers mark alerts as signal/noise to tune the model",
        ],
    },
]

PATTERN_BY_ID = {p["id"]: p for p in INJECTION_PATTERNS}
