# CUI // SP-CTI
"""Standalone Sigma rule generator for MITRE ATT&CK techniques (ODC pipeline).

Deterministic — no LLM. Produces well-formed Sigma YAML from a technique ID.
Complements tools/observability_canvas/sigma_generator.py (graph-centric);
this module exposes a single-technique API for the /api/sigma/generate endpoint
and for seeding sigma_template in odc_mitre_techniques.

Public API:
  generate_sigma(technique_id: str) -> str
      Returns Sigma YAML string with title: and detection: keys.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

import yaml

# ---------------------------------------------------------------------------
# Technique detection templates (logsource, detection, tactic, name) and the
# tactic fallback map are derived from the single source of truth in
# tools/observability_canvas/mitre_catalog.py. Both names are preserved for
# backward compatibility.
# ---------------------------------------------------------------------------
from tools.observability_canvas.mitre_catalog import (
    build_obs_detections as _build_obs_detections,
    build_tactic_map as _build_tactic_map,
)

_DETECTIONS: dict[str, dict] = _build_obs_detections()

# Tactic map for techniques not in _DETECTIONS (hyphen form, primary tactic).
_TACTIC_MAP: dict[str, str] = _build_tactic_map()


def generate_sigma(technique_id: str) -> str:
    """Generate a Sigma YAML detection rule for a MITRE ATT&CK technique.

    Args:
        technique_id: MITRE ATT&CK technique ID (e.g. 'T1055', 'T1059.001').

    Returns:
        Sigma YAML string containing at minimum title: and detection: keys.

    Raises:
        ValueError: if technique_id is empty or does not start with 'T'.
    """
    tid = technique_id.strip().upper()
    if not tid or not tid.startswith("T"):
        raise ValueError(f"Invalid technique_id: {technique_id!r}")

    parent_tid = tid.split(".")[0]
    tmpl = _DETECTIONS.get(tid) or _DETECTIONS.get(parent_tid)

    if tmpl:
        logsource = dict(tmpl["logsource"])
        detection = dict(tmpl["detection"])
        tactic = tmpl["tactic"]
        name = tmpl["name"]
    else:
        logsource = {"category": "process_creation"}
        detection = {
            "selection": {"Keywords|contains": [tid, tid.replace(".", "/")]},
            "condition": "selection",
        }
        tactic = _TACTIC_MAP.get(tid) or _TACTIC_MAP.get(parent_tid, "defense-evasion")
        name = tid

    rule = {
        "title": f"Detect MITRE ATT&CK {tid} — {name}",
        "id": str(uuid.uuid4()),
        "status": "experimental",
        "description": (
            f"Detects {tid} ({name}) activity. "
            "Generated by ICDEV ODC pipeline."
        ),
        "references": [f"https://attack.mitre.org/techniques/{tid.replace('.', '/')}/"],
        "author": "ICDEV ODC pipeline",
        "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "tags": [
            f"attack.{tid.lower().replace('.', '_')}",
            f"attack.{tactic}",
        ],
        "logsource": logsource,
        "detection": detection,
        "falsepositives": ["Legitimate administrative activity"],
        "level": "medium",
    }

    return yaml.dump(rule, default_flow_style=False, sort_keys=False, allow_unicode=True)
