#!/usr/bin/env python3
# CUI // SP-CTI
"""ICDEV™ Migration Workflow — Discovery Scanner.

Reads the migration canvas DB, produces a structured discovery report,
generates a Markdown discovery document, and persists a snapshot to
mc_assessments.

Artifacts generated:
  data/studio_artifacts/migration/01_discovery_report.md

Usage (workflow runner):
  python tools/migration/discovery_scanner.py --project-id default --json
"""
from __future__ import annotations

import argparse
import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from tools.logging.icdev_logger import get_logger

logger = get_logger("icdev.migration.discovery_scanner")

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

_ARTIFACTS_DIR = _ROOT / "data" / "studio_artifacts" / "migration"

_STRATEGY_LABELS = {
    "rehost": "Rehost (Lift & Shift)",
    "replatform": "Replatform",
    "refactor": "Refactor",
    "rearchitect": "Rearchitect",
    "retire": "Retire",
    "retain": "Retain",
}
_CRIT_ORDER = {"mission_critical": 0, "critical": 1, "high": 2, "medium": 3, "low": 4}


def _conn():
    from tools.migration_canvas.db.init_db import get_connection
    return get_connection()


def _table_exists(conn, name):
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=%s", (name,)
    ).fetchone())


def _now():
    return datetime.now(timezone.utc).isoformat()


def _generate_report(data: dict) -> str:
    proj = data["projects"][0] if data["projects"] else {}
    apps = data["apps"]
    srv = data["server_inventory"]
    waves = data["waves"]
    checks = data["readiness_checks"]
    score = data["readiness_score"]

    lines = [
        "# Migration Discovery Report",
        f"> Generated: {data['timestamp']}  |  Project: **{proj.get('name', 'Unknown')}**  |  Readiness: **{score}%**",
        "",
        "---",
        "",
        "## 1. Project Overview",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Name | {proj.get('name', '—')} |",
        f"| Customer | {proj.get('customer', '—')} |",
        f"| Status | {proj.get('status', '—')} |",
        f"| Classification | {proj.get('classification', 'CUI')} |",
        f"| Impact Level | {proj.get('impact_level', 'IL4')} |",
        "",
        "## 2. Readiness Assessment",
        "",
    ]
    for check, passed in checks.items():
        icon = "✅" if passed else "❌"
        lines.append(f"- {icon} {check.replace('_', ' ').title()}")

    lines += [
        "",
        f"**Overall Readiness Score: {score}%**",
        "",
        "## 3. Application Inventory",
        "",
        "| Application | Type | Strategy | Criticality | Environment |",
        "|-------------|------|----------|-------------|-------------|",
    ]
    for app in sorted(apps, key=lambda a: _CRIT_ORDER.get(a.get("criticality", ""), 5)):
        lines.append(
            f"| {app['name']} | {app.get('app_type','—')} | "
            f"{_STRATEGY_LABELS.get(app.get('migration_strategy',''), app.get('migration_strategy','—'))} | "
            f"{app.get('criticality','—')} | {app.get('environment','—')} |"
        )

    lines += [
        "",
        "## 4. Server / Infrastructure Inventory",
        "",
        f"- **Servers:** {srv['count']}",
        f"- **Total vCPUs:** {srv['total_vcpus']}",
        f"- **Total RAM:** {srv['total_ram_gb']} GB",
        f"- **Total Storage:** {srv['total_disk_tb']} TB",
        f"- **Disk Types:** {', '.join(srv['disk_types']) or '—'}",
        "",
        "## 5. Migration Wave Plan",
        "",
        "| Wave | Name | Strategy | Status |",
        "|------|------|----------|--------|",
    ]
    for w in waves:
        lines.append(
            f"| {w.get('wave','—')} | {w.get('name','—')} | "
            f"{_STRATEGY_LABELS.get(w.get('strategy',''), w.get('strategy','—'))} | "
            f"{w.get('status','planned')} |"
        )

    lines += [
        "",
        "## 6. Migration Strategy Breakdown",
        "",
    ]
    strategy_counts: dict = {}
    for app in apps:
        s = app.get("migration_strategy", "unknown")
        strategy_counts[s] = strategy_counts.get(s, 0) + 1
    for s, count in sorted(strategy_counts.items()):
        lines.append(f"- **{_STRATEGY_LABELS.get(s, s)}**: {count} application(s)")

    lines += [
        "",
        "---",
        "*Generated by ICDEV™ Migration Workflow — Discovery Scanner*",
        f"*CUI // SP-CTI — {proj.get('classification', 'CUI')}*",
    ]
    return "\n".join(lines)


def run(project_id: str = "default") -> dict:
    conn = _conn()
    try:
        projects = [dict(r) for r in conn.execute(
            "SELECT id, name, customer, status, classification, impact_level, description FROM mc_projects"
        ).fetchall()]

        designs = [dict(r) for r in conn.execute(
            "SELECT id, name, migration_type, classification, created_at FROM migration_designs ORDER BY created_at DESC"
        ).fetchall()]

        apps = [dict(r) for r in conn.execute(
            "SELECT id, name, migration_strategy, environment, criticality, language, framework, app_type "
            "FROM mc_app_inventory"
        ).fetchall()] if _table_exists(conn, "mc_app_inventory") else []

        srv_rows = conn.execute("SELECT vcpus, ram_gb, total_disk_gb, disk_type FROM mc_srv_inventory").fetchall() \
            if _table_exists(conn, "mc_srv_inventory") else []
        srv_summary = {
            "count": len(srv_rows),
            "total_vcpus": sum(r[0] or 0 for r in srv_rows),
            "total_ram_gb": round(sum(r[1] or 0 for r in srv_rows), 1),
            "total_disk_tb": round(sum(r[2] or 0 for r in srv_rows) / 1024, 2),
            "disk_types": list({r[3] for r in srv_rows if r[3]}),
        }

        waves = [dict(r) for r in conn.execute(
            "SELECT wave_number AS wave, name, strategy, status FROM mc_wave_plans ORDER BY wave_number"
        ).fetchall()] if _table_exists(conn, "mc_wave_plans") else []

        checks = {
            "has_project": len(projects) > 0,
            "has_design": len(designs) > 0,
            "has_inventory": srv_summary["count"] > 0 or len(apps) > 0,
            "has_wave_plan": len(waves) > 0,
            "classified": any(p.get("classification") for p in projects),
        }
        readiness = round(sum(checks.values()) / len(checks) * 100)

        data = {
            "status": "success",
            "timestamp": _now(),
            "project_id": project_id,
            "readiness_score": readiness,
            "readiness_checks": checks,
            "projects": projects,
            "designs": designs,
            "apps": apps,
            "server_inventory": srv_summary,
            "waves": waves,
        }

        # ── Generate Markdown report ──────────────────────────────────────────
        _ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
        report_path = _ARTIFACTS_DIR / "01_discovery_report.md"
        report_path.write_text(_generate_report(data), encoding="utf-8")

        # ── Persist to mc_assessments ─────────────────────────────────────────
        design_id = designs[0]["id"] if designs else "default"
        try:
            conn.execute(
                """INSERT INTO mc_assessments
                   (id, design_id, assessment_type, findings_json, score, grade,
                    cat1_findings, cat2_findings, cat3_findings, readiness_score, created_at)
                   VALUES (%s, %s, 'discovery', %s, %s, %s, 0, 0, 0, %s, %s)""",
                (
                    f"disc-{uuid.uuid4().hex[:10]}",
                    design_id,
                    json.dumps({"apps": len(apps), "servers": srv_summary["count"], "waves": len(waves)}),
                    readiness,
                    "A" if readiness >= 90 else "B" if readiness >= 80 else "C" if readiness >= 70 else "D" if readiness >= 60 else "F",
                    readiness,
                    _now(),
                ),
            )
            conn.commit()
        except Exception as exc:  # noqa: BLE001 - best-effort persistence; logged, never raised
            # assessment save is non-blocking
            logger.warning("run: best-effort INSERT into mc_assessments failed (non-blocking): %s", exc)

        data["summary"] = (
            f"Discovered {len(projects)} project(s), {len(designs)} design(s), "
            f"{len(apps)} app(s), {srv_summary['count']} server(s), {len(waves)} wave(s). "
            f"Readiness: {readiness}%."
        )
        data["artifacts"] = [
            {"name": "Discovery Report", "path": report_path.relative_to(_ROOT).as_posix(), "type": "markdown"},
        ]
        return data
    finally:
        conn.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-id", default="default")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    result = run(args.project_id)
    print(json.dumps(result, indent=2, default=str))
    sys.exit(0 if result.get("status") == "success" else 1)


if __name__ == "__main__":
    main()
