#!/usr/bin/env python3
# CUI // SP-CTI
# Controlled by: Department of Defense
# CUI Category: CTI
# Distribution: D
# POC: System Administrator
"""Initialize the ninjaflow-ai database.

Auto-generated by ICDEV db_init_generator on 2026-03-03T02:12:28.195917+00:00.
Decision D27: Minimal DB + migration -- core tables first, expand as capabilities activate.

Enabled capabilities at generation time: ai_security, code_intelligence, compliance, devsecops_zta, observability, ricoas, simulation, supply_chain

Usage:
    python init_ninjaflow_ai_db.py [--db-path DATA/icdev.db] [--reset]
"""

import argparse
import sqlite3
import sys
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent / "data" / "icdev.db"


# ------------------------------------------------------------
# PATTERN: Define CHECK constraint values as Python constants
# so SQL and Python stay in sync.  Example:
#
#   ENTITY_TYPES = ('person', 'organization', 'location')
#   _entity_check = ','.join(repr(t) for t in ENTITY_TYPES)
#
#   Then in SQL:
#   CHECK (entity_type IN ({_entity_check}))
#
# This avoids CHECK constraint mismatches when adding new types.
# ------------------------------------------------------------


# ============================================================
# CORE SQL -- always created
# ============================================================
CORE_SQL = """
-- ============================================================
-- CORE TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT,
    status TEXT DEFAULT 'active',
    classification TEXT DEFAULT 'CUI',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agents (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    agent_type TEXT NOT NULL,
    port INTEGER,
    status TEXT DEFAULT 'inactive',
    last_health_check TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS a2a_tasks (
    id TEXT PRIMARY KEY,
    source_agent TEXT,
    target_agent TEXT,
    task_type TEXT NOT NULL,
    payload TEXT,
    status TEXT DEFAULT 'pending',
    result TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_trail (
    id TEXT PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    event_type TEXT NOT NULL,
    actor TEXT,
    action TEXT NOT NULL,
    project_id TEXT,
    details TEXT,
    classification TEXT DEFAULT 'CUI'
);

CREATE TABLE IF NOT EXISTS knowledge_patterns (
    id TEXT PRIMARY KEY,
    pattern_type TEXT NOT NULL,
    pattern_signature TEXT NOT NULL,
    description TEXT,
    solution TEXT,
    confidence REAL DEFAULT 0.0,
    occurrences INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS self_healing_events (
    id TEXT PRIMARY KEY,
    pattern_id TEXT REFERENCES knowledge_patterns(id),
    trigger_type TEXT NOT NULL,
    action_taken TEXT,
    result TEXT,
    confidence REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    priority TEXT DEFAULT 'medium',
    assigned_agent TEXT,
    project_id TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deployments (
    id TEXT PRIMARY KEY,
    project_id TEXT,
    environment TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    artifacts TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metric_snapshots (
    id TEXT PRIMARY KEY,
    metric_type TEXT NOT NULL,
    metric_value REAL,
    project_id TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
    id TEXT PRIMARY KEY,
    alert_type TEXT NOT NULL,
    severity TEXT DEFAULT 'info',
    message TEXT,
    project_id TEXT,
    acknowledged INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS code_reviews (
    id TEXT PRIMARY KEY,
    project_id TEXT,
    reviewer TEXT,
    status TEXT DEFAULT 'pending',
    findings TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS maintenance_audits (
    id TEXT PRIMARY KEY,
    project_id TEXT,
    audit_type TEXT NOT NULL,
    score REAL,
    findings TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

"""


# ============================================================
# OPTIONAL CAPABILITY SQL BLOCKS
# ============================================================
COMPLIANCE_SQL = """
-- ============================================================
-- COMPLIANCE TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS compliance_controls (
    id TEXT PRIMARY KEY,
    family TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    impact_level TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_controls (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    control_id TEXT NOT NULL REFERENCES compliance_controls(id),
    implementation_status TEXT DEFAULT 'planned',
    implementation_description TEXT,
    evidence_path TEXT,
    last_assessed TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, control_id)
);

CREATE TABLE IF NOT EXISTS ssp_documents (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    version TEXT NOT NULL,
    system_name TEXT NOT NULL,
    content TEXT NOT NULL,
    file_path TEXT,
    classification TEXT DEFAULT 'CUI',
    status TEXT DEFAULT 'draft',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS poam_items (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    weakness_id TEXT NOT NULL,
    weakness_description TEXT NOT NULL,
    severity TEXT NOT NULL,
    control_id TEXT REFERENCES compliance_controls(id),
    status TEXT DEFAULT 'open',
    corrective_action TEXT,
    milestone_date DATE,
    responsible_party TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stig_findings (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    stig_id TEXT NOT NULL,
    rule_id TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Open',
    assessed_by TEXT,
    assessed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sbom_records (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    version TEXT NOT NULL,
    format TEXT DEFAULT 'cyclonedx',
    file_path TEXT NOT NULL,
    component_count INTEGER,
    vulnerability_count INTEGER,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fedramp_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    baseline TEXT NOT NULL,
    control_id TEXT NOT NULL,
    status TEXT DEFAULT 'not_assessed',
    evidence_description TEXT,
    evidence_path TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, baseline, control_id)
);

CREATE TABLE IF NOT EXISTS cmmc_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    level INTEGER NOT NULL,
    practice_id TEXT NOT NULL,
    domain TEXT NOT NULL,
    status TEXT DEFAULT 'not_assessed',
    evidence_description TEXT,
    evidence_path TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, practice_id)
);

CREATE TABLE IF NOT EXISTS oscal_artifacts (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    artifact_type TEXT NOT NULL,
    oscal_version TEXT DEFAULT '1.1.2',
    format TEXT DEFAULT 'json',
    file_path TEXT NOT NULL,
    file_hash TEXT,
    schema_valid INTEGER DEFAULT 0,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    classification TEXT DEFAULT 'CUI',
    UNIQUE(project_id, artifact_type, format)
);

CREATE TABLE IF NOT EXISTS cato_evidence (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    control_id TEXT NOT NULL,
    evidence_type TEXT NOT NULL,
    evidence_source TEXT NOT NULL,
    evidence_path TEXT,
    evidence_hash TEXT,
    collected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    is_fresh INTEGER DEFAULT 1,
    status TEXT DEFAULT 'current',
    UNIQUE(project_id, control_id, evidence_type, evidence_source)
);

CREATE TABLE IF NOT EXISTS cssp_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    functional_area TEXT NOT NULL,
    requirement_id TEXT NOT NULL,
    status TEXT DEFAULT 'not_assessed',
    evidence_description TEXT,
    evidence_path TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, requirement_id)
);

CREATE TABLE IF NOT EXISTS ivv_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    process_area TEXT NOT NULL,
    verification_type TEXT NOT NULL,
    requirement_id TEXT NOT NULL,
    status TEXT DEFAULT 'not_assessed',
    evidence_description TEXT,
    evidence_path TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, requirement_id)
);

CREATE TABLE IF NOT EXISTS sbd_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    domain TEXT NOT NULL,
    requirement_id TEXT NOT NULL,
    status TEXT DEFAULT 'not_assessed',
    evidence_description TEXT,
    evidence_path TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, requirement_id)
);

CREATE TABLE IF NOT EXISTS control_crosswalk (
    id TEXT PRIMARY KEY,
    nist_800_53_id TEXT NOT NULL,
    framework_id TEXT NOT NULL,
    framework_control_id TEXT NOT NULL,
    mapping_type TEXT DEFAULT 'equivalent',
    notes TEXT,
    UNIQUE(nist_800_53_id, framework_id)
);

CREATE TABLE IF NOT EXISTS pi_compliance_tracking (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    pi_number TEXT NOT NULL,
    pi_start_date TEXT,
    pi_end_date TEXT,
    compliance_score_start REAL,
    compliance_score_end REAL,
    controls_implemented INTEGER DEFAULT 0,
    controls_remaining INTEGER DEFAULT 0,
    poam_items_closed INTEGER DEFAULT 0,
    poam_items_opened INTEGER DEFAULT 0,
    findings_remediated INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, pi_number)
);

"""

MBSE_SQL = """
-- ============================================================
-- MBSE TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS sysml_elements (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    xmi_id TEXT NOT NULL,
    element_type TEXT NOT NULL,
    name TEXT NOT NULL,
    qualified_name TEXT,
    parent_id TEXT REFERENCES sysml_elements(id),
    stereotype TEXT,
    description TEXT,
    properties TEXT,
    source_file TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, xmi_id)
);

CREATE TABLE IF NOT EXISTS sysml_relationships (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    source_element_id TEXT NOT NULL REFERENCES sysml_elements(id),
    target_element_id TEXT NOT NULL REFERENCES sysml_elements(id),
    relationship_type TEXT NOT NULL,
    name TEXT,
    properties TEXT,
    source_file TEXT,
    UNIQUE(project_id, source_element_id, target_element_id, relationship_type)
);

CREATE TABLE IF NOT EXISTS doors_requirements (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    doors_id TEXT NOT NULL,
    module_name TEXT,
    requirement_type TEXT,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT,
    status TEXT DEFAULT 'active',
    source_file TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, doors_id)
);

CREATE TABLE IF NOT EXISTS digital_thread_links (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    link_type TEXT NOT NULL,
    confidence REAL DEFAULT 1.0,
    evidence TEXT,
    created_by TEXT DEFAULT 'system',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, source_type, source_id, target_type, target_id, link_type)
);

CREATE TABLE IF NOT EXISTS model_imports (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    import_type TEXT NOT NULL,
    source_file TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    elements_imported INTEGER DEFAULT 0,
    relationships_imported INTEGER DEFAULT 0,
    errors INTEGER DEFAULT 0,
    error_details TEXT,
    status TEXT DEFAULT 'completed',
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS model_snapshots (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    pi_number TEXT,
    snapshot_type TEXT NOT NULL,
    element_count INTEGER DEFAULT 0,
    relationship_count INTEGER DEFAULT 0,
    requirement_count INTEGER DEFAULT 0,
    thread_link_count INTEGER DEFAULT 0,
    content_hash TEXT NOT NULL,
    snapshot_data TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, pi_number, snapshot_type)
);

CREATE TABLE IF NOT EXISTS model_code_mappings (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    sysml_element_id TEXT NOT NULL REFERENCES sysml_elements(id),
    code_path TEXT NOT NULL,
    code_type TEXT NOT NULL,
    mapping_direction TEXT DEFAULT 'model_to_code',
    sync_status TEXT DEFAULT 'synced',
    last_synced TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    model_hash TEXT,
    code_hash TEXT,
    UNIQUE(project_id, sysml_element_id, code_path)
);

CREATE TABLE IF NOT EXISTS des_compliance (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    requirement_id TEXT NOT NULL,
    requirement_title TEXT NOT NULL,
    category TEXT NOT NULL,
    status TEXT DEFAULT 'not_assessed',
    evidence TEXT,
    automation_result TEXT,
    assessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    UNIQUE(project_id, requirement_id)
);

"""

RICOAS_SQL = """
-- ============================================================
-- RICOAS TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS intake_sessions (
    id TEXT PRIMARY KEY,
    project_id TEXT REFERENCES projects(id),
    customer_name TEXT NOT NULL,
    customer_org TEXT,
    session_status TEXT DEFAULT 'active'
        CHECK(session_status IN ('active', 'paused', 'completed', 'abandoned', 'approved')),
    classification TEXT DEFAULT 'CUI',
    impact_level TEXT DEFAULT 'IL5'
        CHECK(impact_level IN ('IL2', 'IL4', 'IL5', 'IL6')),
    readiness_score REAL DEFAULT 0.0,
    readiness_breakdown TEXT,
    gap_count INTEGER DEFAULT 0,
    ambiguity_count INTEGER DEFAULT 0,
    total_requirements INTEGER DEFAULT 0,
    decomposed_count INTEGER DEFAULT 0,
    context_summary TEXT,
    source_documents TEXT,
    resumed_from TEXT REFERENCES intake_sessions(id),
    created_by TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS intake_requirements (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    source_turn INTEGER,
    raw_text TEXT NOT NULL,
    refined_text TEXT,
    requirement_type TEXT DEFAULT 'functional'
        CHECK(requirement_type IN ('functional', 'non_functional', 'interface',
            'security', 'performance', 'compliance', 'data', 'constraint',
            'operational', 'transitional')),
    priority TEXT DEFAULT 'medium'
        CHECK(priority IN ('critical', 'high', 'medium', 'low')),
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'clarified', 'validated', 'approved', 'rejected',
            'decomposed', 'deferred')),
    clarity_score REAL DEFAULT 0.0,
    completeness_score REAL DEFAULT 0.0,
    testability_score REAL DEFAULT 0.0,
    feasibility_score REAL DEFAULT 0.0,
    compliance_impact TEXT,
    gaps TEXT,
    ambiguities TEXT,
    acceptance_criteria TEXT,
    source_document TEXT,
    source_section TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS safe_decomposition (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    parent_id TEXT REFERENCES safe_decomposition(id),
    level TEXT NOT NULL
        CHECK(level IN ('epic', 'capability', 'feature', 'story', 'enabler')),
    title TEXT NOT NULL,
    description TEXT,
    acceptance_criteria TEXT,
    story_points INTEGER,
    t_shirt_size TEXT CHECK(t_shirt_size IN ('XS', 'S', 'M', 'L', 'XL', 'XXL')),
    pi_target TEXT,
    team TEXT,
    wsjf_score REAL,
    source_requirement_ids TEXT,
    nist_controls TEXT,
    ato_impact_tier TEXT CHECK(ato_impact_tier IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'refined', 'approved', 'committed', 'in_progress', 'done', 'rejected')),
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS readiness_scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    turn_number INTEGER,
    overall_score REAL NOT NULL,
    completeness REAL NOT NULL,
    clarity REAL NOT NULL,
    feasibility REAL NOT NULL,
    compliance REAL NOT NULL,
    testability REAL NOT NULL,
    gap_count INTEGER DEFAULT 0,
    ambiguity_count INTEGER DEFAULT 0,
    requirement_count INTEGER DEFAULT 0,
    scored_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ato_system_registry (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    system_name TEXT NOT NULL,
    system_acronym TEXT,
    ato_type TEXT CHECK(ato_type IN ('ato', 'iato', 'dato', 'cato')),
    ato_date TEXT,
    ato_expiry TEXT,
    authorizing_official TEXT,
    accreditation_boundary TEXT,
    impact_level TEXT CHECK(impact_level IN ('IL2', 'IL4', 'IL5', 'IL6')),
    data_types TEXT,
    interconnections TEXT,
    baseline_controls TEXT,
    component_inventory TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, system_name)
);

CREATE TABLE IF NOT EXISTS boundary_impact_assessments (
    id TEXT PRIMARY KEY,
    session_id TEXT REFERENCES intake_sessions(id),
    project_id TEXT NOT NULL REFERENCES projects(id),
    system_id TEXT NOT NULL REFERENCES ato_system_registry(id),
    requirement_id TEXT REFERENCES intake_requirements(id),
    impact_tier TEXT NOT NULL CHECK(impact_tier IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
    impact_category TEXT NOT NULL,
    impact_description TEXT NOT NULL,
    affected_controls TEXT,
    affected_components TEXT,
    remediation_required TEXT,
    alternative_approach TEXT,
    risk_score REAL DEFAULT 0.0,
    assessed_by TEXT DEFAULT 'icdev-requirements-analyst',
    assessed_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS supply_chain_vendors (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    vendor_name TEXT NOT NULL,
    vendor_type TEXT CHECK(vendor_type IN ('cots', 'gots', 'oss', 'saas', 'paas', 'iaas', 'contractor', 'subcontractor')),
    country_of_origin TEXT,
    scrm_risk_tier TEXT CHECK(scrm_risk_tier IN ('low', 'moderate', 'high', 'critical')),
    section_889_status TEXT CHECK(section_889_status IN ('compliant', 'under_review', 'prohibited', 'exempt')),
    dod_approved INTEGER DEFAULT 0,
    contact_info TEXT,
    isa_required INTEGER DEFAULT 0,
    last_assessed TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, vendor_name)
);

CREATE TABLE IF NOT EXISTS supply_chain_dependencies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL REFERENCES projects(id),
    source_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    dependency_type TEXT NOT NULL,
    criticality TEXT DEFAULT 'medium'
        CHECK(criticality IN ('critical', 'high', 'medium', 'low')),
    isa_id TEXT,
    metadata TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS isa_agreements (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    agreement_type TEXT NOT NULL CHECK(agreement_type IN ('isa', 'mou', 'moa', 'sla', 'ila')),
    partner_system TEXT NOT NULL,
    partner_org TEXT,
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'review', 'signed', 'active', 'expiring', 'expired', 'terminated')),
    signed_date TEXT,
    expiry_date TEXT,
    data_types_shared TEXT,
    ports_protocols TEXT,
    security_controls TEXT,
    poc_name TEXT,
    poc_email TEXT,
    review_cadence_days INTEGER DEFAULT 365,
    next_review_date TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS scrm_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    vendor_id TEXT REFERENCES supply_chain_vendors(id),
    package_name TEXT,
    assessment_type TEXT NOT NULL
        CHECK(assessment_type IN ('vendor', 'component', 'aggregate', 'supply_chain_event')),
    risk_score REAL DEFAULT 0.0,
    likelihood TEXT CHECK(likelihood IN ('very_low', 'low', 'moderate', 'high', 'very_high')),
    impact TEXT CHECK(impact IN ('very_low', 'low', 'moderate', 'high', 'very_high')),
    mitigations TEXT,
    residual_risk TEXT CHECK(residual_risk IN ('low', 'moderate', 'high', 'critical')),
    assessed_by TEXT DEFAULT 'icdev-supply-chain-agent',
    assessed_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS cve_triage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL REFERENCES projects(id),
    cve_id TEXT NOT NULL,
    package_name TEXT NOT NULL,
    package_version TEXT,
    severity TEXT CHECK(severity IN ('critical', 'high', 'medium', 'low')),
    cvss_score REAL,
    triage_decision TEXT CHECK(triage_decision IN ('remediate', 'mitigate', 'accept_risk', 'defer', 'false_positive', 'not_applicable')),
    triage_rationale TEXT,
    sla_deadline TEXT,
    triaged_by TEXT,
    triaged_at TEXT DEFAULT (datetime('now')),
    remediated_at TEXT,
    UNIQUE(project_id, cve_id, package_name)
);

CREATE TABLE IF NOT EXISTS simulation_scenarios (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    session_id TEXT REFERENCES intake_sessions(id),
    scenario_name TEXT NOT NULL,
    scenario_type TEXT DEFAULT 'what_if'
        CHECK(scenario_type IN ('what_if', 'trade_study', 'risk_analysis', 'optimization', 'baseline')),
    modifications TEXT,
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'running', 'completed', 'failed', 'archived')),
    results TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS coa_records (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    coa_type TEXT NOT NULL
        CHECK(coa_type IN ('speed', 'balanced', 'comprehensive', 'alternative')),
    title TEXT NOT NULL,
    description TEXT,
    scope TEXT,
    estimated_pis TEXT,
    estimated_cost TEXT,
    risk_level TEXT CHECK(risk_level IN ('low', 'moderate', 'high', 'very_high')),
    simulation_results TEXT,
    selected INTEGER DEFAULT 0,
    selected_by TEXT,
    selection_rationale TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now'))
);

"""

SUPPLY_CHAIN_SQL = """
-- ============================================================
-- SUPPLY_CHAIN TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS intake_sessions (
    id TEXT PRIMARY KEY,
    project_id TEXT REFERENCES projects(id),
    customer_name TEXT NOT NULL,
    customer_org TEXT,
    session_status TEXT DEFAULT 'active'
        CHECK(session_status IN ('active', 'paused', 'completed', 'abandoned', 'approved')),
    classification TEXT DEFAULT 'CUI',
    impact_level TEXT DEFAULT 'IL5'
        CHECK(impact_level IN ('IL2', 'IL4', 'IL5', 'IL6')),
    readiness_score REAL DEFAULT 0.0,
    readiness_breakdown TEXT,
    gap_count INTEGER DEFAULT 0,
    ambiguity_count INTEGER DEFAULT 0,
    total_requirements INTEGER DEFAULT 0,
    decomposed_count INTEGER DEFAULT 0,
    context_summary TEXT,
    source_documents TEXT,
    resumed_from TEXT REFERENCES intake_sessions(id),
    created_by TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS intake_requirements (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    source_turn INTEGER,
    raw_text TEXT NOT NULL,
    refined_text TEXT,
    requirement_type TEXT DEFAULT 'functional'
        CHECK(requirement_type IN ('functional', 'non_functional', 'interface',
            'security', 'performance', 'compliance', 'data', 'constraint',
            'operational', 'transitional')),
    priority TEXT DEFAULT 'medium'
        CHECK(priority IN ('critical', 'high', 'medium', 'low')),
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'clarified', 'validated', 'approved', 'rejected',
            'decomposed', 'deferred')),
    clarity_score REAL DEFAULT 0.0,
    completeness_score REAL DEFAULT 0.0,
    testability_score REAL DEFAULT 0.0,
    feasibility_score REAL DEFAULT 0.0,
    compliance_impact TEXT,
    gaps TEXT,
    ambiguities TEXT,
    acceptance_criteria TEXT,
    source_document TEXT,
    source_section TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS safe_decomposition (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    parent_id TEXT REFERENCES safe_decomposition(id),
    level TEXT NOT NULL
        CHECK(level IN ('epic', 'capability', 'feature', 'story', 'enabler')),
    title TEXT NOT NULL,
    description TEXT,
    acceptance_criteria TEXT,
    story_points INTEGER,
    t_shirt_size TEXT CHECK(t_shirt_size IN ('XS', 'S', 'M', 'L', 'XL', 'XXL')),
    pi_target TEXT,
    team TEXT,
    wsjf_score REAL,
    source_requirement_ids TEXT,
    nist_controls TEXT,
    ato_impact_tier TEXT CHECK(ato_impact_tier IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'refined', 'approved', 'committed', 'in_progress', 'done', 'rejected')),
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS readiness_scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    turn_number INTEGER,
    overall_score REAL NOT NULL,
    completeness REAL NOT NULL,
    clarity REAL NOT NULL,
    feasibility REAL NOT NULL,
    compliance REAL NOT NULL,
    testability REAL NOT NULL,
    gap_count INTEGER DEFAULT 0,
    ambiguity_count INTEGER DEFAULT 0,
    requirement_count INTEGER DEFAULT 0,
    scored_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ato_system_registry (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    system_name TEXT NOT NULL,
    system_acronym TEXT,
    ato_type TEXT CHECK(ato_type IN ('ato', 'iato', 'dato', 'cato')),
    ato_date TEXT,
    ato_expiry TEXT,
    authorizing_official TEXT,
    accreditation_boundary TEXT,
    impact_level TEXT CHECK(impact_level IN ('IL2', 'IL4', 'IL5', 'IL6')),
    data_types TEXT,
    interconnections TEXT,
    baseline_controls TEXT,
    component_inventory TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, system_name)
);

CREATE TABLE IF NOT EXISTS boundary_impact_assessments (
    id TEXT PRIMARY KEY,
    session_id TEXT REFERENCES intake_sessions(id),
    project_id TEXT NOT NULL REFERENCES projects(id),
    system_id TEXT NOT NULL REFERENCES ato_system_registry(id),
    requirement_id TEXT REFERENCES intake_requirements(id),
    impact_tier TEXT NOT NULL CHECK(impact_tier IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
    impact_category TEXT NOT NULL,
    impact_description TEXT NOT NULL,
    affected_controls TEXT,
    affected_components TEXT,
    remediation_required TEXT,
    alternative_approach TEXT,
    risk_score REAL DEFAULT 0.0,
    assessed_by TEXT DEFAULT 'icdev-requirements-analyst',
    assessed_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS supply_chain_vendors (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    vendor_name TEXT NOT NULL,
    vendor_type TEXT CHECK(vendor_type IN ('cots', 'gots', 'oss', 'saas', 'paas', 'iaas', 'contractor', 'subcontractor')),
    country_of_origin TEXT,
    scrm_risk_tier TEXT CHECK(scrm_risk_tier IN ('low', 'moderate', 'high', 'critical')),
    section_889_status TEXT CHECK(section_889_status IN ('compliant', 'under_review', 'prohibited', 'exempt')),
    dod_approved INTEGER DEFAULT 0,
    contact_info TEXT,
    isa_required INTEGER DEFAULT 0,
    last_assessed TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, vendor_name)
);

CREATE TABLE IF NOT EXISTS supply_chain_dependencies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL REFERENCES projects(id),
    source_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    dependency_type TEXT NOT NULL,
    criticality TEXT DEFAULT 'medium'
        CHECK(criticality IN ('critical', 'high', 'medium', 'low')),
    isa_id TEXT,
    metadata TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS isa_agreements (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    agreement_type TEXT NOT NULL CHECK(agreement_type IN ('isa', 'mou', 'moa', 'sla', 'ila')),
    partner_system TEXT NOT NULL,
    partner_org TEXT,
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'review', 'signed', 'active', 'expiring', 'expired', 'terminated')),
    signed_date TEXT,
    expiry_date TEXT,
    data_types_shared TEXT,
    ports_protocols TEXT,
    security_controls TEXT,
    poc_name TEXT,
    poc_email TEXT,
    review_cadence_days INTEGER DEFAULT 365,
    next_review_date TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS scrm_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    vendor_id TEXT REFERENCES supply_chain_vendors(id),
    package_name TEXT,
    assessment_type TEXT NOT NULL
        CHECK(assessment_type IN ('vendor', 'component', 'aggregate', 'supply_chain_event')),
    risk_score REAL DEFAULT 0.0,
    likelihood TEXT CHECK(likelihood IN ('very_low', 'low', 'moderate', 'high', 'very_high')),
    impact TEXT CHECK(impact IN ('very_low', 'low', 'moderate', 'high', 'very_high')),
    mitigations TEXT,
    residual_risk TEXT CHECK(residual_risk IN ('low', 'moderate', 'high', 'critical')),
    assessed_by TEXT DEFAULT 'icdev-supply-chain-agent',
    assessed_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS cve_triage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL REFERENCES projects(id),
    cve_id TEXT NOT NULL,
    package_name TEXT NOT NULL,
    package_version TEXT,
    severity TEXT CHECK(severity IN ('critical', 'high', 'medium', 'low')),
    cvss_score REAL,
    triage_decision TEXT CHECK(triage_decision IN ('remediate', 'mitigate', 'accept_risk', 'defer', 'false_positive', 'not_applicable')),
    triage_rationale TEXT,
    sla_deadline TEXT,
    triaged_by TEXT,
    triaged_at TEXT DEFAULT (datetime('now')),
    remediated_at TEXT,
    UNIQUE(project_id, cve_id, package_name)
);

CREATE TABLE IF NOT EXISTS simulation_scenarios (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    session_id TEXT REFERENCES intake_sessions(id),
    scenario_name TEXT NOT NULL,
    scenario_type TEXT DEFAULT 'what_if'
        CHECK(scenario_type IN ('what_if', 'trade_study', 'risk_analysis', 'optimization', 'baseline')),
    modifications TEXT,
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'running', 'completed', 'failed', 'archived')),
    results TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS coa_records (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    coa_type TEXT NOT NULL
        CHECK(coa_type IN ('speed', 'balanced', 'comprehensive', 'alternative')),
    title TEXT NOT NULL,
    description TEXT,
    scope TEXT,
    estimated_pis TEXT,
    estimated_cost TEXT,
    risk_level TEXT CHECK(risk_level IN ('low', 'moderate', 'high', 'very_high')),
    simulation_results TEXT,
    selected INTEGER DEFAULT 0,
    selected_by TEXT,
    selection_rationale TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now'))
);

"""

SIMULATION_SQL = """
-- ============================================================
-- SIMULATION TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS intake_sessions (
    id TEXT PRIMARY KEY,
    project_id TEXT REFERENCES projects(id),
    customer_name TEXT NOT NULL,
    customer_org TEXT,
    session_status TEXT DEFAULT 'active'
        CHECK(session_status IN ('active', 'paused', 'completed', 'abandoned', 'approved')),
    classification TEXT DEFAULT 'CUI',
    impact_level TEXT DEFAULT 'IL5'
        CHECK(impact_level IN ('IL2', 'IL4', 'IL5', 'IL6')),
    readiness_score REAL DEFAULT 0.0,
    readiness_breakdown TEXT,
    gap_count INTEGER DEFAULT 0,
    ambiguity_count INTEGER DEFAULT 0,
    total_requirements INTEGER DEFAULT 0,
    decomposed_count INTEGER DEFAULT 0,
    context_summary TEXT,
    source_documents TEXT,
    resumed_from TEXT REFERENCES intake_sessions(id),
    created_by TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS intake_requirements (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    source_turn INTEGER,
    raw_text TEXT NOT NULL,
    refined_text TEXT,
    requirement_type TEXT DEFAULT 'functional'
        CHECK(requirement_type IN ('functional', 'non_functional', 'interface',
            'security', 'performance', 'compliance', 'data', 'constraint',
            'operational', 'transitional')),
    priority TEXT DEFAULT 'medium'
        CHECK(priority IN ('critical', 'high', 'medium', 'low')),
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'clarified', 'validated', 'approved', 'rejected',
            'decomposed', 'deferred')),
    clarity_score REAL DEFAULT 0.0,
    completeness_score REAL DEFAULT 0.0,
    testability_score REAL DEFAULT 0.0,
    feasibility_score REAL DEFAULT 0.0,
    compliance_impact TEXT,
    gaps TEXT,
    ambiguities TEXT,
    acceptance_criteria TEXT,
    source_document TEXT,
    source_section TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS safe_decomposition (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    parent_id TEXT REFERENCES safe_decomposition(id),
    level TEXT NOT NULL
        CHECK(level IN ('epic', 'capability', 'feature', 'story', 'enabler')),
    title TEXT NOT NULL,
    description TEXT,
    acceptance_criteria TEXT,
    story_points INTEGER,
    t_shirt_size TEXT CHECK(t_shirt_size IN ('XS', 'S', 'M', 'L', 'XL', 'XXL')),
    pi_target TEXT,
    team TEXT,
    wsjf_score REAL,
    source_requirement_ids TEXT,
    nist_controls TEXT,
    ato_impact_tier TEXT CHECK(ato_impact_tier IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'refined', 'approved', 'committed', 'in_progress', 'done', 'rejected')),
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS readiness_scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    turn_number INTEGER,
    overall_score REAL NOT NULL,
    completeness REAL NOT NULL,
    clarity REAL NOT NULL,
    feasibility REAL NOT NULL,
    compliance REAL NOT NULL,
    testability REAL NOT NULL,
    gap_count INTEGER DEFAULT 0,
    ambiguity_count INTEGER DEFAULT 0,
    requirement_count INTEGER DEFAULT 0,
    scored_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ato_system_registry (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    system_name TEXT NOT NULL,
    system_acronym TEXT,
    ato_type TEXT CHECK(ato_type IN ('ato', 'iato', 'dato', 'cato')),
    ato_date TEXT,
    ato_expiry TEXT,
    authorizing_official TEXT,
    accreditation_boundary TEXT,
    impact_level TEXT CHECK(impact_level IN ('IL2', 'IL4', 'IL5', 'IL6')),
    data_types TEXT,
    interconnections TEXT,
    baseline_controls TEXT,
    component_inventory TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, system_name)
);

CREATE TABLE IF NOT EXISTS boundary_impact_assessments (
    id TEXT PRIMARY KEY,
    session_id TEXT REFERENCES intake_sessions(id),
    project_id TEXT NOT NULL REFERENCES projects(id),
    system_id TEXT NOT NULL REFERENCES ato_system_registry(id),
    requirement_id TEXT REFERENCES intake_requirements(id),
    impact_tier TEXT NOT NULL CHECK(impact_tier IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
    impact_category TEXT NOT NULL,
    impact_description TEXT NOT NULL,
    affected_controls TEXT,
    affected_components TEXT,
    remediation_required TEXT,
    alternative_approach TEXT,
    risk_score REAL DEFAULT 0.0,
    assessed_by TEXT DEFAULT 'icdev-requirements-analyst',
    assessed_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS supply_chain_vendors (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    vendor_name TEXT NOT NULL,
    vendor_type TEXT CHECK(vendor_type IN ('cots', 'gots', 'oss', 'saas', 'paas', 'iaas', 'contractor', 'subcontractor')),
    country_of_origin TEXT,
    scrm_risk_tier TEXT CHECK(scrm_risk_tier IN ('low', 'moderate', 'high', 'critical')),
    section_889_status TEXT CHECK(section_889_status IN ('compliant', 'under_review', 'prohibited', 'exempt')),
    dod_approved INTEGER DEFAULT 0,
    contact_info TEXT,
    isa_required INTEGER DEFAULT 0,
    last_assessed TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, vendor_name)
);

CREATE TABLE IF NOT EXISTS supply_chain_dependencies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL REFERENCES projects(id),
    source_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    dependency_type TEXT NOT NULL,
    criticality TEXT DEFAULT 'medium'
        CHECK(criticality IN ('critical', 'high', 'medium', 'low')),
    isa_id TEXT,
    metadata TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS isa_agreements (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    agreement_type TEXT NOT NULL CHECK(agreement_type IN ('isa', 'mou', 'moa', 'sla', 'ila')),
    partner_system TEXT NOT NULL,
    partner_org TEXT,
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'review', 'signed', 'active', 'expiring', 'expired', 'terminated')),
    signed_date TEXT,
    expiry_date TEXT,
    data_types_shared TEXT,
    ports_protocols TEXT,
    security_controls TEXT,
    poc_name TEXT,
    poc_email TEXT,
    review_cadence_days INTEGER DEFAULT 365,
    next_review_date TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS scrm_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    vendor_id TEXT REFERENCES supply_chain_vendors(id),
    package_name TEXT,
    assessment_type TEXT NOT NULL
        CHECK(assessment_type IN ('vendor', 'component', 'aggregate', 'supply_chain_event')),
    risk_score REAL DEFAULT 0.0,
    likelihood TEXT CHECK(likelihood IN ('very_low', 'low', 'moderate', 'high', 'very_high')),
    impact TEXT CHECK(impact IN ('very_low', 'low', 'moderate', 'high', 'very_high')),
    mitigations TEXT,
    residual_risk TEXT CHECK(residual_risk IN ('low', 'moderate', 'high', 'critical')),
    assessed_by TEXT DEFAULT 'icdev-supply-chain-agent',
    assessed_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS cve_triage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL REFERENCES projects(id),
    cve_id TEXT NOT NULL,
    package_name TEXT NOT NULL,
    package_version TEXT,
    severity TEXT CHECK(severity IN ('critical', 'high', 'medium', 'low')),
    cvss_score REAL,
    triage_decision TEXT CHECK(triage_decision IN ('remediate', 'mitigate', 'accept_risk', 'defer', 'false_positive', 'not_applicable')),
    triage_rationale TEXT,
    sla_deadline TEXT,
    triaged_by TEXT,
    triaged_at TEXT DEFAULT (datetime('now')),
    remediated_at TEXT,
    UNIQUE(project_id, cve_id, package_name)
);

CREATE TABLE IF NOT EXISTS simulation_scenarios (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    session_id TEXT REFERENCES intake_sessions(id),
    scenario_name TEXT NOT NULL,
    scenario_type TEXT DEFAULT 'what_if'
        CHECK(scenario_type IN ('what_if', 'trade_study', 'risk_analysis', 'optimization', 'baseline')),
    modifications TEXT,
    status TEXT DEFAULT 'draft'
        CHECK(status IN ('draft', 'running', 'completed', 'failed', 'archived')),
    results TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS coa_records (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES intake_sessions(id),
    project_id TEXT REFERENCES projects(id),
    coa_type TEXT NOT NULL
        CHECK(coa_type IN ('speed', 'balanced', 'comprehensive', 'alternative')),
    title TEXT NOT NULL,
    description TEXT,
    scope TEXT,
    estimated_pis TEXT,
    estimated_cost TEXT,
    risk_level TEXT CHECK(risk_level IN ('low', 'moderate', 'high', 'very_high')),
    simulation_results TEXT,
    selected INTEGER DEFAULT 0,
    selected_by TEXT,
    selection_rationale TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now'))
);

"""

AI_SECURITY_SQL = """
-- ============================================================
-- AI_SECURITY TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS prompt_injection_log (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    text_hash TEXT NOT NULL,
    detected INTEGER NOT NULL DEFAULT 0,
    confidence REAL DEFAULT 0.0,
    action TEXT CHECK(action IN ('allow', 'warn', 'flag', 'block')),
    findings TEXT,
    project_id TEXT,
    user_id TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_telemetry (
    id TEXT PRIMARY KEY,
    model_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    prompt_hash TEXT NOT NULL,
    response_hash TEXT,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    latency_ms INTEGER DEFAULT 0,
    agent_id TEXT,
    user_id TEXT,
    project_id TEXT,
    function TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_bom (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    version TEXT,
    purpose TEXT,
    risk_classification TEXT,
    data_categories TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS atlas_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    framework_version TEXT DEFAULT 'v5.4.0',
    overall_score REAL,
    total_requirements INTEGER DEFAULT 0,
    satisfied INTEGER DEFAULT 0,
    partial INTEGER DEFAULT 0,
    not_satisfied INTEGER DEFAULT 0,
    not_applicable INTEGER DEFAULT 0,
    results_json TEXT,
    assessed_at TEXT NOT NULL DEFAULT (datetime('now')),
    assessed_by TEXT DEFAULT 'automated',
    classification TEXT DEFAULT 'CUI'
);

CREATE TABLE IF NOT EXISTS atlas_red_team_results (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    technique_id TEXT NOT NULL,
    technique_name TEXT,
    test_name TEXT NOT NULL,
    result TEXT CHECK(result IN ('pass', 'fail', 'partial', 'error')),
    severity TEXT CHECK(severity IN ('critical', 'high', 'medium', 'low', 'info')),
    details TEXT,
    evidence TEXT,
    remediation TEXT,
    tested_at TEXT NOT NULL DEFAULT (datetime('now')),
    tested_by TEXT DEFAULT 'automated'
);

CREATE TABLE IF NOT EXISTS owasp_llm_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    framework_version TEXT DEFAULT 'v2025',
    overall_score REAL,
    total_requirements INTEGER DEFAULT 0,
    satisfied INTEGER DEFAULT 0,
    partial INTEGER DEFAULT 0,
    not_satisfied INTEGER DEFAULT 0,
    not_applicable INTEGER DEFAULT 0,
    results_json TEXT,
    assessed_at TEXT NOT NULL DEFAULT (datetime('now')),
    assessed_by TEXT DEFAULT 'automated',
    classification TEXT DEFAULT 'CUI'
);

"""

AI_GOVERNANCE_SQL = """
-- ============================================================
-- AI_GOVERNANCE TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS model_cards (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    model_name TEXT NOT NULL,
    card_data TEXT NOT NULL,
    card_hash TEXT,
    version INTEGER DEFAULT 1,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, model_name, version)
);

CREATE TABLE IF NOT EXISTS system_cards (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    card_data TEXT NOT NULL,
    card_hash TEXT,
    version INTEGER DEFAULT 1,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_use_case_inventory (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    name TEXT NOT NULL,
    purpose TEXT,
    risk_level TEXT DEFAULT 'minimal_risk'
        CHECK(risk_level IN ('minimal_risk', 'high_impact', 'safety_impacting')),
    classification TEXT DEFAULT 'CUI',
    deployment_status TEXT DEFAULT 'development',
    responsible_official TEXT,
    oversight_role TEXT,
    last_assessed TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, name)
);

CREATE TABLE IF NOT EXISTS fairness_assessments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    assessment_data TEXT NOT NULL,
    overall_score REAL DEFAULT 0.0,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_oversight_plans (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    plan_name TEXT NOT NULL,
    plan_data TEXT NOT NULL,
    approval_status TEXT DEFAULT 'draft'
        CHECK(approval_status IN ('draft', 'submitted', 'approved', 'rejected')),
    approved_by TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_caio_registry (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    official_name TEXT NOT NULL,
    official_role TEXT NOT NULL DEFAULT 'CAIO',
    organization TEXT,
    designation_date TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_incident_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    incident_type TEXT NOT NULL,
    ai_system TEXT,
    severity TEXT DEFAULT 'medium'
        CHECK(severity IN ('critical', 'high', 'medium', 'low')),
    description TEXT NOT NULL,
    corrective_action TEXT,
    status TEXT DEFAULT 'open'
        CHECK(status IN ('open', 'investigating', 'mitigated', 'resolved', 'closed')),
    reported_by TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_ethics_reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    review_type TEXT NOT NULL,
    ai_system TEXT,
    findings TEXT,
    opt_out_policy INTEGER DEFAULT 0,
    legal_compliance_matrix INTEGER DEFAULT 0,
    pre_deployment_review INTEGER DEFAULT 0,
    reviewer TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ai_reassessment_schedule (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    ai_system TEXT NOT NULL,
    frequency TEXT NOT NULL DEFAULT 'annual'
        CHECK(frequency IN ('quarterly', 'semi_annual', 'annual', 'biennial')),
    next_due TEXT,
    last_completed TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, ai_system)
);

"""

OBSERVABILITY_SQL = """
-- ============================================================
-- OBSERVABILITY TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS otel_spans (
    id TEXT PRIMARY KEY,
    trace_id TEXT NOT NULL,
    parent_span_id TEXT,
    name TEXT NOT NULL,
    kind TEXT DEFAULT 'INTERNAL',
    start_time TEXT NOT NULL,
    end_time TEXT,
    duration_ms INTEGER DEFAULT 0,
    status_code TEXT DEFAULT 'UNSET',
    status_message TEXT,
    attributes TEXT,
    events TEXT,
    agent_id TEXT,
    project_id TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prov_entities (
    id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    label TEXT,
    content_hash TEXT,
    content TEXT,
    attributes TEXT,
    trace_id TEXT,
    span_id TEXT,
    agent_id TEXT,
    project_id TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prov_activities (
    id TEXT PRIMARY KEY,
    activity_type TEXT NOT NULL,
    label TEXT,
    start_time TEXT,
    end_time TEXT,
    attributes TEXT,
    trace_id TEXT,
    span_id TEXT,
    agent_id TEXT,
    project_id TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prov_relations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    relation_type TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    object_id TEXT NOT NULL,
    attributes TEXT,
    trace_id TEXT,
    project_id TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shap_attributions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trace_id TEXT NOT NULL,
    tool_name TEXT NOT NULL,
    shapley_value REAL NOT NULL,
    coalition_size INTEGER,
    confidence_low REAL,
    confidence_high REAL,
    outcome_metric TEXT DEFAULT 'success',
    outcome_value REAL,
    analysis_params TEXT,
    agent_id TEXT,
    project_id TEXT,
    classification TEXT DEFAULT 'CUI',
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS xai_assessments (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    assessment_date TEXT NOT NULL,
    overall_status TEXT NOT NULL DEFAULT 'not_assessed',
    overall_score REAL DEFAULT 0.0,
    checks_json TEXT,
    findings_json TEXT,
    recommendations_json TEXT,
    framework_crosswalk TEXT,
    assessor_version TEXT,
    agent_id TEXT,
    classification TEXT DEFAULT 'CUI',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

"""

CODE_INTELLIGENCE_SQL = """
-- ============================================================
-- CODE_INTELLIGENCE TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS code_quality_metrics (
    id TEXT PRIMARY KEY,
    project_id TEXT,
    file_path TEXT NOT NULL,
    function_name TEXT,
    class_name TEXT,
    language TEXT NOT NULL,
    cyclomatic_complexity INTEGER DEFAULT 0,
    cognitive_complexity INTEGER DEFAULT 0,
    loc INTEGER DEFAULT 0,
    loc_code INTEGER DEFAULT 0,
    loc_comment INTEGER DEFAULT 0,
    parameter_count INTEGER DEFAULT 0,
    nesting_depth INTEGER DEFAULT 0,
    import_count INTEGER DEFAULT 0,
    class_count INTEGER DEFAULT 0,
    function_count INTEGER DEFAULT 0,
    smells_json TEXT DEFAULT '[]',
    smell_count INTEGER DEFAULT 0,
    maintainability_score REAL DEFAULT 0.0,
    content_hash TEXT,
    scan_id TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS runtime_feedback (
    id TEXT PRIMARY KEY,
    project_id TEXT,
    source_file TEXT NOT NULL,
    source_function TEXT,
    test_file TEXT,
    test_function TEXT,
    test_passed INTEGER,
    test_duration_ms REAL,
    error_type TEXT,
    error_message TEXT,
    coverage_pct REAL,
    run_id TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

"""

DEVSECOPS_ZTA_SQL = """
-- ============================================================
-- DEVSECOPS_ZTA TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS devsecops_profiles (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    maturity_level TEXT CHECK(maturity_level IN (
        'level_1_initial', 'level_2_managed', 'level_3_defined',
        'level_4_measured', 'level_5_optimized'
    )),
    active_stages TEXT,
    stage_configs TEXT,
    detected_at TEXT,
    confirmed_by TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id)
);

CREATE TABLE IF NOT EXISTS zta_maturity_scores (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    pillar TEXT NOT NULL CHECK(pillar IN (
        'user_identity', 'device', 'network', 'application_workload',
        'data', 'visibility_analytics', 'automation_orchestration', 'overall'
    )),
    score REAL CHECK(score >= 0.0 AND score <= 1.0),
    maturity_level TEXT CHECK(maturity_level IN ('traditional', 'advanced', 'optimal')),
    evidence TEXT,
    assessed_by TEXT DEFAULT 'icdev-devsecops-agent',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS zta_posture_evidence (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    evidence_type TEXT NOT NULL,
    evidence_data TEXT,
    status TEXT CHECK(status IN ('current', 'stale', 'expired', 'not_collected')),
    collected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS nist_800_207_assessments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id TEXT NOT NULL,
    assessment_date TEXT,
    assessor TEXT DEFAULT 'icdev-devsecops-agent',
    requirement_id TEXT NOT NULL,
    requirement_title TEXT,
    family TEXT,
    status TEXT DEFAULT 'not_assessed' CHECK(status IN (
        'not_assessed', 'satisfied', 'partially_satisfied',
        'not_satisfied', 'not_applicable', 'risk_accepted'
    )),
    evidence_description TEXT,
    nist_800_53_crosswalk TEXT,
    automation_result TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, requirement_id)
);

CREATE TABLE IF NOT EXISTS devsecops_pipeline_audit (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    pipeline_run_id TEXT,
    stage TEXT NOT NULL,
    tool TEXT NOT NULL,
    status TEXT CHECK(status IN ('passed', 'failed', 'skipped', 'warning')),
    findings_count INTEGER DEFAULT 0,
    findings_data TEXT,
    duration_seconds REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

"""


# Mapping from capability name to SQL constant
_CAPABILITY_SQL_MAP = {
    "compliance": COMPLIANCE_SQL,
    "mbse": MBSE_SQL,
    "ricoas": RICOAS_SQL,
    "supply_chain": SUPPLY_CHAIN_SQL,
    "simulation": SIMULATION_SQL,
    "ai_security": AI_SECURITY_SQL,
    "ai_governance": AI_GOVERNANCE_SQL,
    "observability": OBSERVABILITY_SQL,
    "code_intelligence": CODE_INTELLIGENCE_SQL,
    "devsecops_zta": DEVSECOPS_ZTA_SQL,
}


# Combined SQL for test setup (import this in features/environment.py)
SCHEMA_SQL = CORE_SQL + COMPLIANCE_SQL + RICOAS_SQL + SUPPLY_CHAIN_SQL + SIMULATION_SQL + AI_SECURITY_SQL + OBSERVABILITY_SQL + CODE_INTELLIGENCE_SQL + DEVSECOPS_ZTA_SQL


def init_db(db_path=None):
    """Initialize the ninjaflow-ai database with core + enabled capability tables."""
    path = Path(db_path) if db_path else DB_PATH
    path.parent.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(str(path))
    try:
        # Core tables -- always present
        conn.executescript(CORE_SQL)

        # Capability tables enabled at generation time
        conn.executescript(COMPLIANCE_SQL)
        conn.executescript(RICOAS_SQL)
        conn.executescript(SUPPLY_CHAIN_SQL)
        conn.executescript(SIMULATION_SQL)
        conn.executescript(AI_SECURITY_SQL)
        conn.executescript(OBSERVABILITY_SQL)
        conn.executescript(CODE_INTELLIGENCE_SQL)
        conn.executescript(DEVSECOPS_ZTA_SQL)

        conn.commit()
    finally:
        conn.close()

    # Verify
    conn = sqlite3.connect(str(path))
    try:
        cur = conn.cursor()
        cur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        tables = [row[0] for row in cur.fetchall()]
    finally:
        conn.close()

    print(f"Database initialized at {path}")
    print(f"Tables created ({len(tables)}): {', '.join(tables)}")
    return tables


def migrate_add_capability(db_path, capability_name):
    """Add tables for a capability that was not enabled at init time.

    Args:
        db_path: Path to the SQLite database file.
        capability_name: One of ['compliance', 'mbse', 'ricoas', 'supply_chain', 'simulation', 'ai_security', 'ai_governance', 'observability', 'code_intelligence', 'devsecops_zta'].

    Raises:
        ValueError: If capability_name is not recognized.
    """
    if capability_name not in _CAPABILITY_SQL_MAP:
        raise ValueError(
            f"Unknown capability '{capability_name}'. "
            f"Valid options: {list(_CAPABILITY_SQL_MAP.keys())}"
        )

    path = Path(db_path)
    if not path.exists():
        raise FileNotFoundError(f"Database not found: {path}")

    sql = _CAPABILITY_SQL_MAP[capability_name]
    conn = sqlite3.connect(str(path))
    try:
        conn.executescript(sql)
        conn.commit()
    finally:
        conn.close()

    # Verify new tables
    conn = sqlite3.connect(str(path))
    try:
        cur = conn.cursor()
        cur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        tables = [row[0] for row in cur.fetchall()]
    finally:
        conn.close()

    print(f"Capability '{capability_name}' tables added to {path}")
    print(f"Total tables ({len(tables)}): {', '.join(tables)}")
    return tables


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Initialize the ninjaflow-ai database"
    )
    parser.add_argument(
        "--db-path", type=Path, default=DB_PATH,
        help="Database file path (default: %(default)s)"
    )
    parser.add_argument(
        "--reset", action="store_true",
        help="Drop and recreate all tables"
    )
    parser.add_argument(
        "--add-capability", type=str, default=None,
        help="Add tables for a capability post-init (e.g. 'compliance', 'mbse')"
    )
    args = parser.parse_args()

    if args.add_capability:
        migrate_add_capability(args.db_path, args.add_capability)
        return

    if args.reset and args.db_path.exists():
        args.db_path.unlink()
        print(f"Removed existing database: {args.db_path}")

    init_db(args.db_path)


if __name__ == "__main__":
    main()
