#!/usr/bin/env python3
# CUI // SP-CTI
"""ICDEV™ Migration Workflow — Post-Migration Validator.

Validates migration outcomes and generates:
  - VALIDATION_CHECKLIST.md  — human-readable checklist
  - validate.py              — runnable Python validation script
  - Saves findings to mc_assessments

Artifacts:
  data/studio_artifacts/migration/04_validation_checklist.md
  data/studio_artifacts/migration/validate.py

Usage (workflow runner):
  python tools/migration/validator.py --project-id default --json
"""
from __future__ import annotations

import argparse
import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from tools.logging.icdev_logger import get_logger

logger = get_logger("icdev.migration.validator")

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

_ARTIFACTS_DIR = _ROOT / "data" / "studio_artifacts" / "migration"


def _conn():
    from tools.migration_canvas.db.init_db import get_connection
    return get_connection()


def _table_exists(conn, name):
    return bool(conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=%s", (name,)
    ).fetchone())


def _now():
    return datetime.now(timezone.utc).isoformat()


def _pct(num, den):
    return round(num / den * 100) if den else 0


def _checklist_md(categories: dict, apps: list, project: dict) -> str:
    lines = [
        "# Post-Migration Validation Checklist",
        f"> Project: **{project.get('name', 'Unknown')}** | Generated: {_now()}",
        f"> Overall Score: **{sum(c['pct'] for c in categories.values()) // max(len(categories), 1)}%**",
        "",
        "---",
        "",
        "## Automated Validation Status",
        "",
        "| Category | Passed | Total | Score |",
        "|----------|--------|-------|-------|",
    ]
    for cat, data in categories.items():
        icon = "✅" if data["pct"] >= 80 else "⚠️" if data["pct"] >= 50 else "❌"
        lines.append(f"| {icon} {cat} | {data['passed']} | {data['total']} | {data['pct']}% |")

    lines += [
        "",
        "## Manual Validation Steps",
        "",
        "### Application Health",
        "",
    ]
    for app in apps:
        safe = app["name"].lower().replace(" ", "_").replace(".", "_")
        lines += [
            f"#### {app['name']}",
            "",
            f"- [ ] Application responds to health check: `curl -f http://{safe}.internal/health`",
            "- [ ] Verify data integrity (row counts match source)",
            "- [ ] Check error rate in CloudWatch: < 0.1% over 5 min",
            "- [ ] Confirm no rollback triggers in past 30 min",
            "",
        ]

    lines += [
        "### Infrastructure Validation",
        "",
        "- [ ] All EC2/EKS nodes in `running` state",
        "- [ ] Security groups match approved baseline",
        "- [ ] CloudTrail logging active on all resources",
        "- [ ] AWS Config rules passing",
        "- [ ] GuardDuty findings reviewed",
        "- [ ] VPC Flow Logs enabled",
        "",
        "### Performance Baseline",
        "",
        "- [ ] CPU utilisation < 70% (peak)",
        "- [ ] Memory utilisation < 80% (peak)",
        "- [ ] Latency p99 within 10% of pre-migration baseline",
        "- [ ] Throughput matches or exceeds pre-migration baseline",
        "",
        "### Compliance Gate",
        "",
        "- [ ] All STIG controls re-verified on target environment",
        "- [ ] Classification markings applied to all resources",
        "- [ ] Impact Level designations match source environment",
        "- [ ] Audit logging active and forwarding to SIEM",
        "",
        "## Sign-Off",
        "",
        "| Role | Name | Signature | Date |",
        "|------|------|-----------|------|",
        "| Migration Lead | | | |",
        "| ISSO | | | |",
        "| System Owner | | | |",
        "",
        "---",
        "*Generated by ICDEV™ Migration Workflow — Validator*",
        "*CUI // SP-CTI*",
    ]
    return "\n".join(lines)


def _validate_script(apps: list, project: dict) -> str:
    lines = [
        "#!/usr/bin/env python3",
        '"""ICDEV™ Auto-generated Post-Migration Validation Script.',
        "",
        f"Project: {project.get('name', 'Unknown')}",
        f"Generated: {_now()}",
        f"Classification: {project.get('classification', 'CUI')}",
        '"""',
        "import sys, json, urllib.request, urllib.error",
        "",
        "RESULTS = []",
        "",
        "def check(name, fn):",
        "    try:",
        "        passed, detail = fn()",
        "        RESULTS.append({'check': name, 'passed': passed, 'detail': detail})",
        "        status = 'PASS' if passed else 'FAIL'",
        "        print(f'{status:4}  {name}: {detail}')",
        "        return passed",
        "    except Exception as e:",
        "        RESULTS.append({'check': name, 'passed': False, 'detail': str(e)})",
        "        print(f'ERR   {name}: {e}')",
        "        return False",
        "",
    ]
    for app in apps:
        safe = app["name"].lower().replace(" ", "_").replace(".", "_")
        host = f"{safe}.internal"
        lines += [
            f"# {app['name']}",
            f"def check_{safe}_health():",
            "    try:",
            f"        req = urllib.request.urlopen('http://{host}/health', timeout=5)",
            "        return req.status == 200, f'HTTP {req.status}'",
            "    except urllib.error.URLError as e:",
            "        return False, f'Unreachable: {e.reason}'",
            "",
            f"check('{app['name']} health endpoint', check_{safe}_health)",
            "",
        ]
    lines += [
        "# Summary",
        "passed = sum(1 for r in RESULTS if r['passed'])",
        "total  = len(RESULTS)",
        "score  = round(passed / total * 100) if total else 0",
        "print()",
        "print(f'Validation: {passed}/{total} checks passed — {score}%')",
        "print(json.dumps(RESULTS, indent=2))",
        "sys.exit(0 if score >= 80 else 1)",
    ]
    return "\n".join(lines)


def run(project_id: str = "default") -> dict:
    conn = _conn()
    try:
        apps = [dict(r) for r in conn.execute(
            "SELECT id, name, migration_strategy, environment, criticality, framework FROM mc_app_inventory"
        ).fetchall()] if _table_exists(conn, "mc_app_inventory") else []

        project = dict(conn.execute(
            "SELECT id, name, customer, classification, impact_level FROM mc_projects LIMIT 1"
        ).fetchone() or {})

        categories: dict = {}

        if _table_exists(conn, "mc_migration_waves"):
            rows = conn.execute("SELECT status FROM mc_migration_waves").fetchall()
            total, complete = len(rows), sum(1 for r in rows if r[0] == "complete")
            categories["Wave Completion"] = {"passed": complete, "total": total, "pct": _pct(complete, total),
                                             "note": f"{complete}/{total} wave(s) complete"}

        if _table_exists(conn, "mc_srv_post_migration_tests"):
            rows = conn.execute("SELECT status FROM mc_srv_post_migration_tests").fetchall()
            total = len(rows)
            passed = sum(1 for r in rows if (r[0] or "").lower() in ("pass", "passed", "success"))
            categories["Post-Migration Tests"] = {"passed": passed, "total": total, "pct": _pct(passed, total),
                                                  "note": f"{passed}/{total} tests passed"}

        if _table_exists(conn, "mc_compliance_checks"):
            rows = conn.execute("SELECT status FROM mc_compliance_checks").fetchall()
            total = len(rows)
            passed = sum(1 for r in rows if (r[0] or "").lower() in ("pass", "passed", "compliant", "ok"))
            categories["Compliance Checks"] = {"passed": passed, "total": total, "pct": _pct(passed, total),
                                               "note": f"{passed}/{total} checks passing"}

        if _table_exists(conn, "mc_srv_cutover_steps"):
            rows = conn.execute("SELECT status FROM mc_srv_cutover_steps").fetchall()
            total = len(rows)
            done = sum(1 for r in rows if (r[0] or "").lower() in ("complete", "done", "passed", "success"))
            categories["Cutover Steps"] = {"passed": done, "total": total, "pct": _pct(done, total),
                                           "note": f"{done}/{total} cutover steps complete"}

        if _table_exists(conn, "mc_net_config_validation"):
            rows = conn.execute("SELECT status FROM mc_net_config_validation").fetchall()
            total = len(rows)
            passed = sum(1 for r in rows if (r[0] or "").lower() in ("pass", "valid", "ok"))
            categories["Network Validation"] = {"passed": passed, "total": total, "pct": _pct(passed, total),
                                                "note": f"{passed}/{total} network configs validated"}

        if not categories:
            categories["Inventory"] = {"passed": 0, "total": 1, "pct": 0,
                                       "note": "No post-migration data yet — waves not yet executed"}

        total_checks = sum(c["total"] for c in categories.values())
        total_passed = sum(c["passed"] for c in categories.values())
        overall = _pct(total_passed, total_checks)
        grade = "A" if overall >= 90 else "B" if overall >= 80 else "C" if overall >= 70 else "D" if overall >= 60 else "F"

        findings = [{"category": k, "score": v["pct"], "note": v["note"]}
                    for k, v in categories.items() if v["pct"] < 80 and v["total"] > 0]

        # ── Generate artifacts ────────────────────────────────────────────────
        _ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
        checklist_path = _ARTIFACTS_DIR / "04_validation_checklist.md"
        script_path = _ARTIFACTS_DIR / "validate.py"

        checklist_path.write_text(_checklist_md(categories, apps, project), encoding="utf-8", newline="")
        script_path.write_text(_validate_script(apps, project), encoding="utf-8", newline="")

        # ── Persist to mc_assessments ─────────────────────────────────────────
        design_id = conn.execute("SELECT id FROM migration_designs LIMIT 1").fetchone()
        design_id = design_id[0] if design_id else "default"
        try:
            conn.execute(
                """INSERT INTO mc_assessments
                   (id, design_id, assessment_type, findings_json, score, grade,
                    cat1_findings, cat2_findings, cat3_findings, readiness_score, created_at)
                   VALUES (%s, %s, 'validation', %s, %s, %s, %s, %s, 0, %s, %s)""",
                (
                    f"val-{uuid.uuid4().hex[:10]}",
                    design_id,
                    json.dumps(findings),
                    overall, grade,
                    sum(1 for f in findings if f["score"] < 50),
                    sum(1 for f in findings if 50 <= f["score"] < 80),
                    overall, _now(),
                ),
            )
            conn.commit()
        except Exception as exc:  # noqa: BLE001 - best-effort persistence; logged, never raised
            logger.warning("run: best-effort INSERT into mc_assessments failed (non-blocking): %s", exc)

        return {
            "status": "success",
            "timestamp": _now(),
            "project_id": project_id,
            "overall_score": overall,
            "grade": grade,
            "checks_passed": total_passed,
            "checks_total": total_checks,
            "categories": categories,
            "findings": findings,
            "validation_passed": overall >= 80,
            "note": "Score reflects current DB state. Re-run after completing migration waves." if overall < 80 else "Validation passed.",
            "summary": (
                f"Validation score: {overall}% (Grade {grade}). "
                f"{total_passed}/{total_checks} checks passing. "
                f"Checklist and validation script generated."
            ),
            "artifacts": [
                {"name": "Validation Checklist", "path": checklist_path.relative_to(_ROOT).as_posix(), "type": "markdown"},
                {"name": "Validation Script", "path": script_path.relative_to(_ROOT).as_posix(), "type": "python"},
            ],
        }
    finally:
        conn.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-id", default="default")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    result = run(args.project_id)
    print(json.dumps(result, indent=2, default=str))
    sys.exit(0 if result.get("status") == "success" else 1)


if __name__ == "__main__":
    main()
