# [CUI // SP-CTI]
"""ZIG Artifact Generator — generates ZIG gap assessment reports for ATO packages.

Output: Markdown report + JSON summary suitable for POAM integration.
"""

from datetime import datetime, timezone

from tools.security_canvas.zig_assessor import run_zig_assessment
from tools.security_canvas.constants import ZIG_FY2027_DEADLINE


def generate_zig_artifact() -> dict:
    """Generate ZIG gap assessment report.

    Returns:
        {"markdown": str, "json_summary": dict}
    """
    assessment = run_zig_assessment()
    now = datetime.now(timezone.utc)
    agg = assessment["aggregate"]
    pillar_scores = assessment["pillar_scores"]
    gaps = assessment["gaps"]
    fy2027 = assessment["fy2027"]

    # Build Markdown report
    lines = [
        "# NSA ZIG Gap Assessment Report",
        f"> Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}  ",
        "> Classification: CUI // SP-CTI",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Overall ZIG Score | {round(agg['score'] * 100, 1)}% |",
        f"| Maturity Level | {agg['maturity_level'].title()} |",
        f"| FY2027 Readiness | {fy2027['pct_complete']}% |",
        f"| Activities Complete | {fy2027['complete_activities']}/{fy2027['fy2027_target_activities']} |",
        f"| Total Capability Gaps | {len(gaps)} |",
        "",
        "---",
        "",
        "## Pillar Maturity Scores",
        "",
        "| Pillar | Score | Maturity Level | Capabilities | Activities |",
        "|--------|-------|----------------|--------------|------------|",
    ]

    for ps in pillar_scores:
        lines.append(
            f"| {ps['name']} | {round(ps.get('score', 0) * 100, 1)}% | "
            f"{ps.get('maturity_level', 'preparation').title()} | "
            f"{ps.get('implemented_capabilities', 0)}/{ps.get('capability_count', 0)} | "
            f"{ps.get('complete_activities', 0)}/{ps.get('activity_count', 0)} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Capability Gaps",
        "",
        f"The following {len(gaps)} capabilities require implementation to achieve FY2027 Target-level maturity.",
        "",
        "| Priority | Pillar | Capability | Phase | Status |",
        "|----------|--------|------------|-------|--------|",
    ]

    for g in gaps:
        phase_label = g["phase"].replace("phase1", "Phase 1").replace("phase2", "Phase 2").title()
        lines.append(
            f"| P{g['priority']} | {g['pillar_name']} | {g['title']} | {phase_label} | "
            f"{g['status'].replace('_', ' ').title()} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Recommended Next Steps",
        "",
        "1. **Complete Discovery Phase** — Ensure all 14 discovery activities are marked complete.",
        "2. **Prioritize Phase 1** — Focus on 36 foundational activities; target completion by March 2026.",
        "3. **User Pillar First** — MFA and PAM implementation are the highest-impact starting points.",
        "4. **Network Segmentation** — Deploy macro-segmentation before micro-segmentation.",
        "5. **Data Classification** — Publish enterprise data classification policy before tooling.",
        "",
        "---",
        "",
        "## Reference Documents",
        "",
        "- [ZIG Primer (Jan 2026)](https://media.defense.gov/2026/Jan/08/2003852320/-1/-1/0/CTR_ZERO_TRUST_IMPLEMENTATION_GUIDELINE_PRIMER.PDF)",
        "- [ZIG Discovery Phase](https://media.defense.gov/2026/Jan/08/2003852321/-1/-1/0/CTR_ZIG_DISCOVERY_PHASE.PDF)",
        "- [ZIG Phase One](https://media.defense.gov/2026/Jan/30/2003868308/-1/-1/0/CTR_ZIG_PHASE_ONE.PDF)",
        "- [ZIG Phase Two](https://media.defense.gov/2026/Jan/30/2003868302/-1/-1/0/CTR_ZIG_PHASE_TWO.PDF)",
        "- [NSA ZIG Interactive Resource](https://www.nsa.gov/Cybersecurity/ZIG/)",
        "",
        "---",
        "*CUI // SP-CTI — Report generated by ICDEV™ Security Canvas*",
    ]

    markdown = "\n".join(lines)

    json_summary = {
        "report_date": now.isoformat(),
        "classification": "CUI // SP-CTI",
        "overall_score": agg["score"],
        "maturity_level": agg["maturity_level"],
        "fy2027_readiness_pct": fy2027["pct_complete"],
        "total_gaps": len(gaps),
        "pillar_scores": [
            {"pillar": ps["slug"], "score": ps.get("score", 0), "maturity_level": ps.get("maturity_level", "preparation")}
            for ps in pillar_scores
        ],
        "top_gaps": gaps[:10],
        "fy2027_deadline": ZIG_FY2027_DEADLINE,
    }

    return {"markdown": markdown, "json_summary": json_summary}
