# CUI // SP-CTI
"""AADC Ops Config Generator — Design → Runtime Bridge (Track B).

Given an AADC design_id, reads the canvas node inventory, maps each node type
to its corresponding runtime tool via args/aadc_node_tool_map.yaml, and outputs:

  1. data/aadc_ops_config/ops_config_<design_id>.yaml  — tool activation config + thresholds
  2. A list of Kanban task dicts ready to create via the Kanban API

This is NOT a runtime execution engine. It generates configuration and tasks;
the dev team wires the tools. FORGE OPS RUNTIME (Track C) builds the runtime.
"""

from __future__ import annotations
from tools.logging.icdev_logger import get_logger

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

_log = get_logger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_NODE_MAP_PATH = _PROJECT_ROOT / "args" / "aadc_node_tool_map.yaml"
# Generated ops configs are runtime output, not source-controlled input: write
# them under data/ (overridable via AADC_OPS_CONFIG_DIR), never into args/.
_OUTPUT_DIR = Path(
    os.environ.get("AADC_OPS_CONFIG_DIR", str(_PROJECT_ROOT / "data" / "aadc_ops_config"))
)


# ---------------------------------------------------------------------------
# Load the node → tool mapping (hot-reloadable from YAML)
# ---------------------------------------------------------------------------

def _load_node_map() -> dict[str, dict]:
    try:
        raw = yaml.safe_load(_NODE_MAP_PATH.read_text(encoding="utf-8"))
        return raw.get("node_tool_map", {})
    except Exception as e:
        _log.warning("Could not load aadc_node_tool_map.yaml: %s", e)
        return {}


# ---------------------------------------------------------------------------
# Core generator
# ---------------------------------------------------------------------------

def generate_ops_config(design_id: str) -> dict[str, Any]:
    """Generate an ops config for an AADC design.

    Returns a dict with:
      - config_path: str — path of the written YAML file
      - config: dict — the full config dict
      - kanban_tasks: list[dict] — task dicts (not yet created in DB)
      - matched_nodes: list[str] — node types that had a tool mapping
      - unmatched_nodes: list[str] — node types with no mapping
    """
    # penta-aadc-02: aadc_designs is a canvas table with no tenant_id/
    # classification columns, so the RLS-enforcing tools.db.storage
    # get_connection() injects a predicate that raises UndefinedColumn on PG.
    # Use the canvas connection factory, which wraps get_canvas_connection()
    # (RLS disabled) on PG and points at the canvas .db file on SQLite.
    from tools.agentic_ai_canvas.db.init_db import get_connection

    conn = get_connection()
    row = conn.execute(
        "SELECT id, name, graph_json FROM aadc_designs WHERE id=%s", (design_id,)
    ).fetchone()
    if not row:
        raise ValueError(f"AADC design not found: {design_id}")

    design_name = row["name"] if hasattr(row, "__getitem__") else row[1]
    graph_json  = row["graph_json"] if hasattr(row, "__getitem__") else row[2]
    graph = json.loads(graph_json or '{"nodes":[],"edges":[]}')
    nodes = graph.get("nodes", [])

    node_map = _load_node_map()

    # Collect unique node types present in the design
    present_types: list[tuple[str, str]] = []  # (node_id, node_type)
    seen_types: set[str] = set()
    for n in nodes:
        ntype = n.get("type", "")
        nid   = n.get("id", "")
        if ntype and ntype not in seen_types:
            seen_types.add(ntype)
            present_types.append((nid, ntype))

    matched: list[str] = []
    unmatched: list[str] = []
    tool_configs: dict[str, Any] = {}
    kanban_tasks: list[dict] = []

    for node_id, ntype in present_types:
        if ntype in node_map:
            matched.append(ntype)
            entry = node_map[ntype]
            cfg_key = entry.get("config_key", ntype.replace("-", "_"))
            tool_configs[cfg_key] = _default_tool_config(ntype, entry)
            kanban_tasks.append(_make_kanban_task(design_id, design_name, ntype, entry))
        else:
            unmatched.append(ntype)

    now_utc = datetime.now(timezone.utc).isoformat()
    config: dict[str, Any] = {
        "# CUI // SP-CTI": None,
        "generated_at": now_utc,
        "design_id": design_id,
        "design_name": design_name,
        "tools": tool_configs,
        "alert_routing": _default_alert_routing(),
        "monitoring": {
            "scrape_interval_seconds": 60,
            "retention_days": 30,
            "dashboard_url": "/monitoring",
        },
        "notes": (
            f"Generated by AADC Ops Config Generator from design '{design_name}'. "
            "Wire each tool section before deploying. "
            "Track progress via the Kanban tasks created alongside this file."
        ),
    }

    # Strip the comment key (YAML doesn't allow None values for comment keys)
    clean_config = {k: v for k, v in config.items() if v is not None or k == "notes"}

    config_path = _OUTPUT_DIR / f"ops_config_{design_id}.yaml"
    try:
        _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        with open(config_path, "w", encoding="utf-8") as f:
            f.write("# CUI // SP-CTI\n")
            f.write(f"# AADC Ops Config — {design_name}\n")
            f.write(f"# Generated: {now_utc}\n")
            f.write(f"# Design ID: {design_id}\n\n")
            yaml.dump(
                {k: v for k, v in clean_config.items() if k != "# CUI // SP-CTI"},
                f,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
            )
        _log.info("Ops config written to %s", config_path)
    except Exception as e:
        _log.error("Failed to write ops config: %s", e)
        config_path = None

    return {
        "config_path": str(config_path) if config_path else None,
        "config": clean_config,
        "kanban_tasks": kanban_tasks,
        "matched_nodes": matched,
        "unmatched_nodes": unmatched,
        "design_name": design_name,
    }


# ---------------------------------------------------------------------------
# Per-tool default config blocks
# ---------------------------------------------------------------------------

_DRIFT_DEFAULTS = {
    "enabled": True,
    "quality_warning_pct": 15,
    "quality_critical_pct": 30,
    "latency_warning_pct": 20,
    "latency_critical_pct": 50,
    "token_inflation_warning_pct": 15,
    "token_inflation_critical_pct": 30,
    "check_interval_minutes": 60,
    "auto_retrain_on_critical": False,
}

_TOKEN_BUDGET_DEFAULTS = {
    "enabled": True,
    "monthly_budget_usd": 50.0,
    "warning_threshold": 0.80,
    "hard_stop": True,
    "alert_channel": "kanban",
}

_GUARDRAIL_DEFAULTS = {
    "enabled": True,
    "mode": "block",
    "log_all_events": True,
    "injection_detection": True,
    "pii_masking": True,
}

_CIRCUIT_BREAKER_DEFAULTS = {
    "enabled": True,
    "failure_threshold": 5,
    "recovery_timeout_seconds": 60,
    "half_open_max_calls": 3,
}

_AUDIT_DEFAULTS = {
    "enabled": True,
    "log_inputs": True,
    "log_outputs": True,
    "retention_days": 365,
    "classification": "CUI",
}


def _default_tool_config(ntype: str, entry: dict) -> dict:
    defaults = {
        "drift-detector":     _DRIFT_DEFAULTS,
        "baseline-snapshot":  {"enabled": True, "auto_snapshot_on_deploy": True},
        "token-budget":       _TOKEN_BUDGET_DEFAULTS,
        "guardrail":          _GUARDRAIL_DEFAULTS,
        "input-sanitizer":    {**_GUARDRAIL_DEFAULTS, "mode": "sanitize"},
        "circuit-breaker":    _CIRCUIT_BREAKER_DEFAULTS,
        "audit-logger":       _AUDIT_DEFAULTS,
        "compliance-reporter": {**_AUDIT_DEFAULTS, "report_schedule": "monthly"},
        "trace-collector":    {"enabled": True, "otlp_endpoint": "http://localhost:4317", "service_name": "icdev-agent"},
        "span-recorder":      {"enabled": True, "db_path": "data/icdev.db"},
        "retrain-trigger":    {"enabled": True, "trigger_on": "critical", "min_hours_between_retrains": 24},
        "trusted-monitor":    {"enabled": True, "eval_interval_minutes": 30, "min_quality_score": 0.70},
        "prompt-registry":    {"enabled": True, "version_all_prompts": True, "require_approval_for_changes": False},
    }
    cfg = defaults.get(ntype, {"enabled": True})
    cfg["tool_path"] = entry.get("tool_path", "")
    cfg["docs_link"]  = entry.get("docs_link", "")
    return cfg


def _default_alert_routing() -> dict:
    return {
        "info":     "log_only",
        "warning":  "kanban_task",
        "critical": "kanban_task_and_page",
    }


# ---------------------------------------------------------------------------
# Kanban task builder
# ---------------------------------------------------------------------------

def _make_kanban_task(design_id: str, design_name: str, ntype: str, entry: dict) -> dict:
    return {
        "title": entry.get("task_title", f"Wire {ntype} node"),
        "description": (
            f"**AADC Design:** {design_name} (`{design_id}`)\n\n"
            f"**Node type:** `{ntype}`\n\n"
            f"**Tool:** `{entry.get('tool_path', '')}`\n\n"
            f"{entry.get('description', '')}\n\n"
            f"**CLI reference:**\n```bash\n{entry.get('cli_command', '')}\n```\n\n"
            f"**Config key in ops_config_{design_id}.yaml:** `{entry.get('config_key', '')}`\n\n"
            f"**Academy mission:** [{entry.get('docs_link','')}](/academy/mission/{entry.get('docs_link','')})\n\n"
            f"Wire this tool, update the config file with your thresholds, "
            f"then verify by running the health check."
        ),
        "status": "backlog",
        "priority": "medium",
        "tags": ["ops-config", "aadc", ntype],
        "metadata": {
            "design_id": design_id,
            "node_type": ntype,
            "tool_path": entry.get("tool_path", ""),
            "source": "ops_config_generator",
        },
    }


# ---------------------------------------------------------------------------
# Create the Kanban tasks in the DB
# ---------------------------------------------------------------------------

def create_kanban_tasks(kanban_tasks: list[dict]) -> list[int]:
    """Insert the generated tasks into the Kanban DB. Returns list of created task IDs."""
    from tools.db.storage import get_connection
    import uuid

    conn = get_connection()
    ids: list[int] = []
    now = datetime.now(timezone.utc).isoformat()
    for task in kanban_tasks:
        try:
            cur = conn.execute(
                """INSERT INTO kanban_tasks
                   (id, title, description, status, priority,
                    created_at, updated_at, dispatch_source)
                   VALUES (%s,%s,%s,%s,%s,%s,%s,%s)""",
                (
                    str(uuid.uuid4()),
                    task["title"],
                    task["description"],
                    "backlog",
                    task.get("priority", "medium"),
                    now, now,
                    "ops_config_generator",
                ),
            )
            ids.append(cur.lastrowid)
        except Exception as e:
            _log.warning("Failed to create Kanban task '%s': %s", task["title"], e)
    conn.commit()
    return ids


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    import sys

    p = argparse.ArgumentParser(description="Generate ops config from an AADC design")
    p.add_argument("design_id", help="AADC design ID")
    p.add_argument("--create-tasks", action="store_true", help="Create Kanban tasks in DB")
    p.add_argument("--json", action="store_true", help="Output JSON summary")
    args = p.parse_args()

    try:
        result = generate_ops_config(args.design_id)
        if args.create_tasks:
            task_ids = create_kanban_tasks(result["kanban_tasks"])
            result["created_task_ids"] = task_ids
        if args.json:
            import json as _json
            print(_json.dumps({
                "config_path": result["config_path"],
                "matched_nodes": result["matched_nodes"],
                "unmatched_nodes": result["unmatched_nodes"],
                "kanban_tasks_count": len(result["kanban_tasks"]),
                "created_task_ids": result.get("created_task_ids", []),
            }, indent=2))
        else:
            print(f"Ops config: {result['config_path']}")
            print(f"Matched nodes ({len(result['matched_nodes'])}): {', '.join(result['matched_nodes'])}")
            if result["unmatched_nodes"]:
                print(f"Unmatched nodes: {', '.join(result['unmatched_nodes'])}")
            print(f"Kanban tasks generated: {len(result['kanban_tasks'])}")
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
