#!/usr/bin/env python3
# CUI // SP-CTI
"""Proposal Genesis Security Integration — NemoClaw credential broker wrapper.

Provides per-reflex credential isolation for Proposal Genesis reflexes.
Graceful degradation: if credential_broker is not available or not enabled,
all operations succeed silently (backward compatible).

Usage:
    from tools.proposal_genesis.security import request_credential, revoke_credential, verify_cdrl_blueprint

    # Request scoped token for a reflex
    token = request_credential("draft", config)

    # Revoke when reflex completes
    revoke_credential("draft")

    # Verify CDRL output integrity
    result = verify_cdrl_blueprint("/path/to/cdrl/output", "cdrl-001")
"""

from pathlib import Path
from typing import Dict, Optional

# Agent ID prefix for all Proposal Genesis reflexes
_AGENT_PREFIX = "pg-reflex"


def _agent_id(reflex_name: str) -> str:
    """Build agent ID for a Proposal Genesis reflex."""
    return f"{_AGENT_PREFIX}-{reflex_name}"


def request_credential(reflex_name: str, config: dict) -> Optional[str]:
    """Request a scoped credential token for a Proposal Genesis reflex.

    Resolves the reflex name to a broker function via the config's
    ``security.credential_broker.function_mapping`` and requests a
    short-lived token from the NemoClaw CredentialBroker.

    Args:
        reflex_name: Name of the reflex (e.g., "draft", "discover").
        config: The full proposal_genesis_config dict (or its ``security`` sub-dict).

    Returns:
        The scoped token string on success, or ``None`` if the broker is
        disabled, not installed, or the request was denied.
    """
    security_cfg = (
        config.get("security", config)
        if "security" not in config or isinstance(config.get("security"), dict)
        else config
    )
    if "security" in config and isinstance(config["security"], dict):
        security_cfg = config["security"]

    broker_cfg = security_cfg.get("credential_broker", {})
    if not broker_cfg.get("enabled", False):
        return None

    function_mapping = broker_cfg.get("function_mapping", {})
    mapped_function = function_mapping.get(reflex_name)
    if not mapped_function:
        return None

    try:
        from tools.security.credential_broker import CredentialBroker
    except ImportError:
        return None

    try:
        broker = CredentialBroker()
        result = broker.request_credential(
            agent_id=_agent_id(reflex_name),
            function=mapped_function,
        )
        if "error" in result:
            return None
        return result.get("token")
    except Exception:
        return None


def revoke_credential(reflex_name: str) -> bool:
    """Revoke all active tokens for a Proposal Genesis reflex.

    Called after a reflex completes (success or failure) to ensure
    short-lived tokens don't persist beyond their intended scope.

    Args:
        reflex_name: Name of the reflex (e.g., "draft", "discover").

    Returns:
        ``True`` if revocation succeeded or broker is unavailable (graceful),
        ``False`` only on unexpected error.
    """
    try:
        from tools.security.credential_broker import CredentialBroker
    except ImportError:
        return True

    try:
        broker = CredentialBroker()
        broker.revoke_credentials(
            agent_id=_agent_id(reflex_name),
            reason="reflex_completed",
        )
        return True
    except Exception:
        return True


def verify_cdrl_blueprint(output_dir: str, deliverable_id: str) -> Dict:
    """Compute and store a blueprint digest for CDRL output.

    After a CDRL is generated by the ``fulfill`` reflex, this function
    computes a recursive SHA-256 digest of the output directory and
    stores it in the ``blueprint_digests`` table for supply chain
    integrity verification (D-NC-3).

    Args:
        output_dir: Path to the CDRL output directory.
        deliverable_id: Unique identifier for the deliverable (used as entity_id).

    Returns:
        Dict with digest, file_count, total_bytes on success.
        Empty dict if verifier is unavailable or directory is invalid.
    """
    try:
        from tools.security.blueprint_verifier import BlueprintVerifier
    except ImportError:
        return {}

    output_path = Path(output_dir)
    if not output_path.is_dir():
        return {}

    try:
        verifier = BlueprintVerifier()
        result = verifier.store_digest(
            entity_type="cdrl",
            entity_id=deliverable_id,
            directory=output_path,
            computed_by=_agent_id("fulfill"),
        )
        if "error" in result:
            return {}
        return {
            "digest": result.get("digest", ""),
            "file_count": result.get("file_count", 0),
            "total_bytes": result.get("total_bytes", 0),
            "record_id": result.get("record_id", ""),
            "deliverable_id": deliverable_id,
        }
    except Exception:
        return {}
