# [CUI // SP-CTI]
"""ICDEV™ Security Design Canvas — Constants and reference data.

Security object palette, STRIDE threat categories, NIST 800-53 control families,
risk matrix, assessment rules, and NDC→SDC node type mapping.

No external dependencies — stdlib only.
"""

# ── Security Object Palette ──────────────────────────────────────────────────
# Four categories, ~30 total objects for the canvas toolbox.

SECURITY_OBJECTS = {
    "assets": [
        {
            "type": "asset-server",
            "label": "Server / VM",
            "icon": "server",
            "desc": "Compute instance (physical or virtual)",
        },
        {"type": "asset-database", "label": "Database", "icon": "database", "desc": "Relational or NoSQL data store"},
        {"type": "asset-client", "label": "Client / User", "icon": "user", "desc": "End-user device or browser"},
        {"type": "asset-storage", "label": "Storage (S3/Blob)", "icon": "hdd", "desc": "Object or block storage"},
        {
            "type": "asset-network",
            "label": "Network Device",
            "icon": "sitemap",
            "desc": "Router, switch, or load balancer",
        },
        {"type": "asset-container", "label": "Container / Pod", "icon": "cube", "desc": "Docker container or K8s pod"},
        {
            "type": "asset-lambda",
            "label": "Serverless Function",
            "icon": "bolt",
            "desc": "Lambda, Cloud Function, or Azure Function",
        },
        {
            "type": "asset-registry",
            "label": "Container Registry",
            "icon": "archive",
            "desc": "Image registry (ECR, ACR, Harbor)",
        },
        {
            "type": "asset-vdi-host",
            "label": "VDI Session Host",
            "icon": "session-host",
            "desc": "Virtual desktop session host (RDSH/AVD/Citrix VDA)",
            "nist_families": ["SC", "CM", "SI"],
        },
        {
            "type": "asset-thin-client",
            "label": "Thin/Zero Client",
            "icon": "thin-client",
            "desc": "Thin or zero client endpoint (IGEL/Wyse/Teradici)",
            "nist_families": ["IA", "SC", "PE"],
        },
        {
            "type": "asset-profile-store",
            "label": "Profile Store",
            "icon": "profile-store",
            "desc": "User profile container storage (FSLogix/UPM)",
            "nist_families": ["SC", "AC", "MP"],
        },
    ],
    "controls": [
        {
            "type": "ctrl-firewall",
            "label": "Firewall / WAF",
            "icon": "shield-alt",
            "desc": "Network or web application firewall",
        },
        {
            "type": "ctrl-idp",
            "label": "IdP / MFA",
            "icon": "id-badge",
            "desc": "Identity provider with multi-factor authentication",
        },
        {
            "type": "ctrl-kms",
            "label": "KMS / HSM",
            "icon": "key",
            "desc": "Key management service or hardware security module",
        },
        {
            "type": "ctrl-siem",
            "label": "SIEM / SOC",
            "icon": "eye",
            "desc": "Security information and event management",
        },
        {
            "type": "ctrl-ids",
            "label": "IDS / IPS",
            "icon": "exclamation-triangle",
            "desc": "Intrusion detection / prevention system",
        },
        {"type": "ctrl-pam", "label": "PAM", "icon": "user-lock", "desc": "Privileged access management"},
        {
            "type": "ctrl-scanner",
            "label": "Vulnerability Scanner",
            "icon": "search",
            "desc": "SAST, DAST, or infrastructure scanner",
        },
        {
            "type": "ctrl-encryption",
            "label": "Encryptor",
            "icon": "lock",
            "desc": "Encryption appliance or TLS terminator",
        },
        {
            "type": "ctrl-session-policy",
            "label": "Session Policy",
            "icon": "session-policy",
            "desc": "VDI session controls — clipboard, USB, printing, watermark, timeout",
            "nist_controls": ["AC-4", "AC-11", "AC-12", "SC-10"],
        },
        {
            "type": "ctrl-vdi-gateway",
            "label": "VDI Gateway",
            "icon": "vdi-gateway",
            "desc": "Secure remote access gateway for VDI (RD Gateway/Citrix GW/UAG)",
            "nist_controls": ["AC-17", "SC-7", "SC-8"],
        },
        {
            "type": "ctrl-image-hardening",
            "label": "Image Hardening",
            "icon": "image-harden",
            "desc": "Golden image STIG hardening and integrity verification",
            "nist_controls": ["CM-2", "CM-6", "SI-7", "SA-10"],
        },
    ],
    "threats": [
        {
            "type": "threat-actor",
            "label": "Threat Actor",
            "icon": "skull-crossbones",
            "desc": "External attacker or insider threat",
        },
        {"type": "threat-malware", "label": "Malware", "icon": "bug", "desc": "Virus, ransomware, or worm"},
        {
            "type": "threat-phishing",
            "label": "Phishing",
            "icon": "envelope-open",
            "desc": "Social engineering attack via email",
        },
        {
            "type": "threat-exploit",
            "label": "Exploit",
            "icon": "crosshairs",
            "desc": "Known or zero-day vulnerability exploit",
        },
        {"type": "threat-dos", "label": "DoS / DDoS", "icon": "network-wired", "desc": "Denial of service attack"},
        {
            "type": "threat-supply",
            "label": "Supply Chain",
            "icon": "truck",
            "desc": "Compromised dependency or build system",
        },
        {
            "type": "threat-insider",
            "label": "Insider Threat",
            "icon": "user-secret",
            "desc": "Malicious or negligent insider",
        },
        {
            "type": "threat-session-hijack",
            "label": "Session Hijack",
            "icon": "session-hijack",
            "desc": "VDI session takeover via stolen token, credential replay, or MitM",
            "stride": "S",
            "mitre": "T1563",
        },
        {
            "type": "threat-clipboard-exfil",
            "label": "Clipboard Exfil",
            "icon": "clipboard-exfil",
            "desc": "Data exfiltration via clipboard copy/paste from virtual desktop",
            "stride": "I",
            "mitre": "T1115",
        },
        {
            "type": "threat-gpu-escape",
            "label": "GPU/VM Escape",
            "icon": "gpu-escape",
            "desc": "Breakout from virtual desktop via GPU driver or hypervisor vulnerability",
            "stride": "E",
            "mitre": "T1611",
        },
        {
            "type": "threat-profile-tampering",
            "label": "Profile Tamper",
            "icon": "profile-tamper",
            "desc": "Manipulation of roaming profile or FSLogix container to persist malware",
            "stride": "T",
            "mitre": "T1547",
        },
    ],
    "boundaries": [
        {
            "type": "boundary-network",
            "label": "Network Zone",
            "icon": "border-all",
            "desc": "Network segmentation boundary (VLAN, VPC)",
        },
        {"type": "boundary-internet", "label": "Internet", "icon": "globe", "desc": "Public internet / untrusted zone"},
        {"type": "boundary-cloud", "label": "Cloud CSP", "icon": "cloud", "desc": "Cloud service provider boundary"},
        {"type": "boundary-bcap", "label": "BCAP", "icon": "shield", "desc": "DoD Boundary Cloud Access Point"},
        {
            "type": "boundary-authorization",
            "label": "Auth Boundary",
            "icon": "border-style",
            "desc": "FedRAMP authorization boundary",
        },
        {"type": "boundary-enclave", "label": "Enclave", "icon": "lock", "desc": "Classified or isolated enclave"},
        {
            "type": "boundary-dmz",
            "label": "DMZ",
            "icon": "minus-circle",
            "desc": "Demilitarized zone between trust levels",
        },
        {
            "type": "boundary-vdi-session",
            "label": "VDI Session Zone",
            "icon": "vdi-session",
            "desc": "Trust boundary isolating VDI session hosts from infrastructure",
            "classification_levels": ["CUI", "SECRET"],
        },
    ],
    "digital_twin": [
        {
            "type": "twin-attack-graph",
            "label": "Attack Graph Twin",
            "icon": "ag",
            "desc": "BAS-style digital twin — snapshots the STRIDE/attack graph and enumerates all paths from entry points to high-value targets",
        },
        {
            "type": "twin-posture",
            "label": "Security Posture Twin",
            "icon": "sp",
            "desc": "Continuous security posture twin — tracks risk score delta across topology changes with PASS/WARN/FAIL verdict",
        },
        {
            "type": "twin-bas",
            "label": "BAS Replay Engine",
            "icon": "br",
            "desc": "Breach and Attack Simulation replay — maps Caldera ability IDs to ATT&CK technique IDs for automated path validation",
        },
        {
            "type": "twin-mitre-delta",
            "label": "MITRE Delta Detector",
            "icon": "md",
            "desc": "Surfaces new or resolved ATT&CK technique exposures introduced by a proposed topology change",
        },
    ],
}

# ── STRIDE Threat Categories ────────────────────────────────────────────────

STRIDE_CATEGORIES = {
    "S": {
        "name": "Spoofing",
        "description": "Pretending to be something or someone other than yourself.",
        "nist_controls": ["IA-2", "IA-3", "IA-5", "IA-8", "SC-23"],
        "typical_targets": ["asset-client", "ctrl-idp", "asset-server"],
    },
    "T": {
        "name": "Tampering",
        "description": "Modifying data or code without authorization.",
        "nist_controls": ["SI-7", "SC-8", "SC-28", "AU-10", "CM-3"],
        "typical_targets": ["asset-database", "asset-storage", "asset-server"],
    },
    "R": {
        "name": "Repudiation",
        "description": "Claiming to not have performed an action.",
        "nist_controls": ["AU-2", "AU-3", "AU-6", "AU-10", "AU-12"],
        "typical_targets": ["asset-client", "asset-server", "ctrl-siem"],
    },
    "I": {
        "name": "Information Disclosure",
        "description": "Exposing information to unauthorized individuals.",
        "nist_controls": ["SC-8", "SC-13", "SC-28", "AC-3", "AC-4"],
        "typical_targets": ["asset-database", "asset-storage", "ctrl-kms"],
    },
    "D": {
        "name": "Denial of Service",
        "description": "Denying or degrading service to valid users.",
        "nist_controls": ["SC-5", "CP-7", "CP-8", "CP-10", "SI-17"],
        "typical_targets": ["asset-server", "ctrl-firewall", "asset-network"],
    },
    "E": {
        "name": "Elevation of Privilege",
        "description": "Gaining capabilities without proper authorization.",
        "nist_controls": ["AC-6", "AC-2", "CM-5", "CM-7", "SC-4"],
        "typical_targets": ["asset-server", "ctrl-pam", "asset-container"],
    },
}

# ── Risk Matrix (5x5) ───────────────────────────────────────────────────────
# Likelihood × Impact → Risk Score (1–25)

LIKELIHOOD_LEVELS = ["very_low", "low", "medium", "high", "very_high"]
IMPACT_LEVELS = ["very_low", "low", "medium", "high", "very_high"]

RISK_MATRIX = {
    # (likelihood_idx, impact_idx) → risk_score
    (0, 0): 1,
    (0, 1): 2,
    (0, 2): 3,
    (0, 3): 4,
    (0, 4): 5,
    (1, 0): 2,
    (1, 1): 4,
    (1, 2): 6,
    (1, 3): 8,
    (1, 4): 10,
    (2, 0): 3,
    (2, 1): 6,
    (2, 2): 9,
    (2, 3): 12,
    (2, 4): 15,
    (3, 0): 4,
    (3, 1): 8,
    (3, 2): 12,
    (3, 3): 16,
    (3, 4): 20,
    (4, 0): 5,
    (4, 1): 10,
    (4, 2): 15,
    (4, 3): 20,
    (4, 4): 25,
}

# ── NIST 800-53 Control Families ────────────────────────────────────────────

NIST_CONTROL_FAMILIES = {
    "AC": {
        "name": "Access Control",
        "examples": ["AC-2 Account Management", "AC-3 Access Enforcement", "AC-6 Least Privilege"],
    },
    "AU": {
        "name": "Audit and Accountability",
        "examples": ["AU-2 Event Logging", "AU-3 Content of Audit Records", "AU-6 Audit Review"],
    },
    "AT": {"name": "Awareness and Training", "examples": ["AT-2 Literacy Training", "AT-3 Role-Based Training"]},
    "CM": {
        "name": "Configuration Management",
        "examples": ["CM-2 Baseline Configuration", "CM-3 Change Control", "CM-7 Least Functionality"],
    },
    "CP": {
        "name": "Contingency Planning",
        "examples": ["CP-7 Alternate Processing Site", "CP-8 Telecommunications", "CP-10 Recovery"],
    },
    "IA": {
        "name": "Identification and Authentication",
        "examples": ["IA-2 User Identification", "IA-5 Authenticator Mgmt", "IA-8 Non-Org Users"],
    },
    "IR": {
        "name": "Incident Response",
        "examples": ["IR-4 Incident Handling", "IR-5 Incident Monitoring", "IR-6 Incident Reporting"],
    },
    "MA": {"name": "Maintenance", "examples": ["MA-2 Controlled Maintenance", "MA-4 Nonlocal Maintenance"]},
    "MP": {
        "name": "Media Protection",
        "examples": ["MP-2 Media Access", "MP-4 Media Storage", "MP-6 Media Sanitization"],
    },
    "PE": {
        "name": "Physical and Environmental",
        "examples": ["PE-2 Physical Access", "PE-3 Physical Access Control", "PE-6 Monitoring"],
    },
    "PL": {"name": "Planning", "examples": ["PL-2 System Security Plan", "PL-4 Rules of Behavior"]},
    "PM": {"name": "Program Management", "examples": ["PM-1 InfoSec Program Plan", "PM-9 Risk Management Strategy"]},
    "PS": {"name": "Personnel Security", "examples": ["PS-3 Personnel Screening", "PS-4 Personnel Termination"]},
    "RA": {"name": "Risk Assessment", "examples": ["RA-3 Risk Assessment", "RA-5 Vulnerability Monitoring"]},
    "SA": {
        "name": "System and Services Acquisition",
        "examples": ["SA-4 Acquisition Process", "SA-11 Developer Testing"],
    },
    "SC": {
        "name": "System and Communications Protection",
        "examples": ["SC-7 Boundary Protection", "SC-8 Transmission Confidentiality", "SC-13 Cryptographic Protection"],
    },
    "SI": {
        "name": "System and Information Integrity",
        "examples": ["SI-2 Flaw Remediation", "SI-4 System Monitoring", "SI-7 Software Integrity"],
    },
    "SR": {
        "name": "Supply Chain Risk Management",
        "examples": ["SR-2 Supply Chain Risk Plan", "SR-3 Supply Chain Controls"],
    },
    "PT": {
        "name": "PII Processing and Transparency",
        "examples": ["PT-2 Authority to Process PII", "PT-3 PII Processing Purposes"],
    },
    "CA": {
        "name": "Assessment, Authorization, and Monitoring",
        "examples": ["CA-2 Control Assessments", "CA-6 Authorization", "CA-7 Continuous Monitoring"],
    },
}

# ── Security Assessment Rules ───────────────────────────────────────────────
# 35 deterministic checks against design graph data.

SECURITY_ASSESSMENT_RULES = [
    # Authentication (CAT1)
    {
        "id": "SEC-AUTH-001",
        "title": "All data flows must be authenticated",
        "severity": "CAT1",
        "category": "authentication",
        "check": "all_flows_authenticated",
    },
    {
        "id": "SEC-AUTH-002",
        "title": "IdP/MFA required for user-facing assets",
        "severity": "CAT1",
        "category": "authentication",
        "check": "idp_for_user_assets",
    },
    {
        "id": "SEC-AUTH-003",
        "title": "PAM required for privileged access",
        "severity": "CAT2",
        "category": "authentication",
        "check": "pam_for_privileged",
    },
    # Encryption (CAT1)
    {
        "id": "SEC-ENC-001",
        "title": "All boundary-crossing flows must be encrypted",
        "severity": "CAT1",
        "category": "encryption",
        "check": "boundary_flows_encrypted",
    },
    {
        "id": "SEC-ENC-002",
        "title": "KMS/HSM present for key management",
        "severity": "CAT1",
        "category": "encryption",
        "check": "kms_present",
    },
    {
        "id": "SEC-ENC-003",
        "title": "Data at rest encryption for databases",
        "severity": "CAT1",
        "category": "encryption",
        "check": "db_encryption_at_rest",
    },
    # Segmentation (CAT1)
    {
        "id": "SEC-SEG-001",
        "title": "Trust boundaries defined between zones",
        "severity": "CAT1",
        "category": "segmentation",
        "check": "boundaries_defined",
    },
    {
        "id": "SEC-SEG-002",
        "title": "Firewall between internet and internal assets",
        "severity": "CAT1",
        "category": "segmentation",
        "check": "firewall_at_boundary",
    },
    {
        "id": "SEC-SEG-003",
        "title": "No direct internet-to-database flows",
        "severity": "CAT1",
        "category": "segmentation",
        "check": "no_direct_inet_db",
    },
    # Logging & Monitoring (CAT2)
    {
        "id": "SEC-LOG-001",
        "title": "SIEM present in design",
        "severity": "CAT2",
        "category": "logging",
        "check": "siem_present",
    },
    {
        "id": "SEC-LOG-002",
        "title": "All assets send logs to SIEM",
        "severity": "CAT2",
        "category": "logging",
        "check": "all_assets_logged",
    },
    {
        "id": "SEC-LOG-003",
        "title": "Database audit logging enabled",
        "severity": "CAT2",
        "category": "logging",
        "check": "db_audit_logging",
    },
    # Monitoring (CAT2)
    {
        "id": "SEC-MON-001",
        "title": "IDS/IPS present for network monitoring",
        "severity": "CAT2",
        "category": "monitoring",
        "check": "ids_present",
    },
    {
        "id": "SEC-MON-002",
        "title": "Vulnerability scanner in design",
        "severity": "CAT2",
        "category": "monitoring",
        "check": "scanner_present",
    },
    # Access Control (CAT2)
    {
        "id": "SEC-AC-001",
        "title": "Least privilege: no shared admin accounts",
        "severity": "CAT2",
        "category": "access_control",
        "check": "no_shared_admin",
    },
    {
        "id": "SEC-AC-002",
        "title": "Service-to-service authentication (mTLS/tokens)",
        "severity": "CAT2",
        "category": "access_control",
        "check": "s2s_auth",
    },
    # Data Protection (CAT2)
    {
        "id": "SEC-DP-001",
        "title": "Data classification labels on all storage assets",
        "severity": "CAT2",
        "category": "data_protection",
        "check": "data_classification",
    },
    {
        "id": "SEC-DP-002",
        "title": "DLP controls for sensitive data egress",
        "severity": "CAT2",
        "category": "data_protection",
        "check": "dlp_present",
    },
    # Incident Response (CAT2)
    {
        "id": "SEC-IR-001",
        "title": "SIEM connected to alerting pipeline",
        "severity": "CAT2",
        "category": "incident_response",
        "check": "siem_alerting",
    },
    {
        "id": "SEC-IR-002",
        "title": "Incident response runbook referenced",
        "severity": "CAT3",
        "category": "incident_response",
        "check": "ir_runbook",
    },
    # Supply Chain (CAT2)
    {
        "id": "SEC-SC-001",
        "title": "Container registry with admission control",
        "severity": "CAT2",
        "category": "supply_chain",
        "check": "registry_admission",
    },
    {
        "id": "SEC-SC-002",
        "title": "SBOM generation for all deployable artifacts",
        "severity": "CAT2",
        "category": "supply_chain",
        "check": "sbom_present",
    },
    # General (CAT3)
    {
        "id": "SEC-GEN-001",
        "title": "All assets labeled with descriptive names",
        "severity": "CAT3",
        "category": "documentation",
        "check": "assets_labeled",
    },
    {
        "id": "SEC-GEN-002",
        "title": "Design has at least one trust boundary",
        "severity": "CAT3",
        "category": "documentation",
        "check": "has_boundaries",
    },
    {
        "id": "SEC-GEN-003",
        "title": "Threats identified and documented",
        "severity": "CAT3",
        "category": "documentation",
        "check": "threats_documented",
    },
    # Endpoint Protection (CAT2)
    {
        "id": "SEC-EDR-001",
        "title": "EDR/XDR deployed on servers and endpoints",
        "severity": "CAT2",
        "category": "monitoring",
        "check": "edr_present",
    },
    # Cloud Posture (CAT2)
    {
        "id": "SEC-CSPM-001",
        "title": "CSPM scanning cloud infrastructure",
        "severity": "CAT2",
        "category": "monitoring",
        "check": "cspm_present",
    },
    # Backup & DR (CAT2)
    {
        "id": "SEC-DR-001",
        "title": "Backup and disaster recovery strategy present",
        "severity": "CAT2",
        "category": "contingency",
        "check": "backup_present",
    },
    # Secret Management (CAT2)
    {
        "id": "SEC-SECRET-001",
        "title": "Centralized secret management (Vault/KMS)",
        "severity": "CAT2",
        "category": "access_control",
        "check": "secret_mgmt_present",
    },
    # mTLS (CAT1)
    {
        "id": "SEC-MTLS-001",
        "title": "mTLS enforced on service-to-service flows",
        "severity": "CAT1",
        "category": "encryption",
        "check": "mtls_s2s",
    },
    # API Gateway (CAT2)
    {
        "id": "SEC-APIGW-001",
        "title": "API gateway with WAF for external APIs",
        "severity": "CAT2",
        "category": "segmentation",
        "check": "api_gateway_protected",
    },
    # Zero Trust (CAT1)
    {
        "id": "SEC-ZT-001",
        "title": "Zero Trust: all flows both authenticated AND encrypted",
        "severity": "CAT1",
        "category": "authentication",
        "check": "zero_trust_posture",
    },
    # Container Admission (CAT2)
    {
        "id": "SEC-ADMIT-001",
        "title": "Container admission control (Kyverno/OPA)",
        "severity": "CAT2",
        "category": "supply_chain",
        "check": "admission_control_present",
    },
    # Encryption Algorithm Compliance (CAT2)
    {
        "id": "SEC-CRYPTO-001",
        "title": "FIPS 140-2/3 validated cryptographic modules",
        "severity": "CAT2",
        "category": "encryption",
        "check": "fips_crypto_validated",
    },
    # Configuration Hardening (CAT2)
    {
        "id": "SEC-HARDEN-001",
        "title": "OS/platform hardened to CIS/STIG baseline",
        "severity": "CAT2",
        "category": "configuration",
        "check": "hardening_baseline",
    },
    # VDI Security Rules
    {
        "id": "SEC-VDI-001",
        "title": "VDI session policy enforced",
        "severity": "CAT1",
        "category": "vdi_security",
        "description": "All VDI session hosts must have a session policy control (clipboard/USB/print restrictions) — data exfiltration risk without policy enforcement.",
        "check": "vdi_session_policy",
    },
    {
        "id": "SEC-VDI-002",
        "title": "VDI gateway required for external access",
        "severity": "CAT1",
        "category": "vdi_security",
        "description": "External users must connect through a VDI gateway — no direct RDP/PCoIP from internet to session hosts.",
        "check": "vdi_gateway_required",
    },
    {
        "id": "SEC-VDI-003",
        "title": "Session hosts in dedicated trust boundary",
        "severity": "CAT2",
        "category": "vdi_security",
        "description": "VDI session hosts must reside within a dedicated VDI session zone boundary, isolated from general compute.",
        "check": "vdi_boundary_isolation",
    },
    {
        "id": "SEC-VDI-004",
        "title": "Profile store encrypted at rest",
        "severity": "CAT1",
        "category": "vdi_security",
        "description": "FSLogix/UPM profile stores must have KMS/HSM encryption control connected — user profiles contain CUI.",
        "check": "vdi_profile_encrypted",
    },
    {
        "id": "SEC-VDI-005",
        "title": "Thin clients authenticated before VDI access",
        "severity": "CAT2",
        "category": "vdi_security",
        "description": "Thin/zero client assets must have IdP/MFA control connected — unauthenticated endpoints are session hijack vectors.",
        "check": "vdi_endpoint_authenticated",
    },
    {
        "id": "SEC-VDI-006",
        "title": "Golden image integrity verified",
        "severity": "CAT2",
        "category": "vdi_security",
        "description": "VDI session hosts should have image hardening control — ensures STIG-compliant golden images and detects drift.",
        "check": "vdi_image_integrity",
    },
]

# ── NDC → SDC Node Type Mapping ─────────────────────────────────────────────
# Maps Network Design Canvas node types to Security Design Canvas asset types.

NODE_TYPE_MAPPING = {
    # Network devices → assets
    "router": "asset-network",
    "switch-l3": "asset-network",
    "switch-l2": "asset-network",
    "server": "asset-server",
    "wap": "asset-network",
    "mpls-pe": "asset-network",
    "mpls-p": "asset-network",
    "route-reflector": "asset-network",
    # Security devices → controls
    "firewall": "ctrl-firewall",
    "aws-nfw": "ctrl-firewall",
    "az-fw": "ctrl-firewall",
    "gcp-armor": "ctrl-firewall",
    "aws-waf": "ctrl-firewall",
    "az-nsg": "ctrl-firewall",
    "oci-waf": "ctrl-firewall",
    "oci-nsg": "ctrl-firewall",
    "siem": "ctrl-siem",
    "network-tap": "ctrl-ids",
    "hsm": "ctrl-kms",
    # Cloud constructs → boundaries
    "aws-vpc": "boundary-cloud",
    "az-vnet": "boundary-cloud",
    "gcp-vpc": "boundary-cloud",
    "oci-vcn": "boundary-cloud",
    "cloud": "boundary-internet",
    # Encryption
    "fips-140-l1": "ctrl-encryption",
    "fips-140-l2": "ctrl-encryption",
    "fips-140-l3": "ctrl-encryption",
    "fips-140-l4": "ctrl-encryption",
    "type1-encryptor": "ctrl-encryption",
    "kg-175d": "ctrl-encryption",
    "kg-175g": "ctrl-encryption",
    "kg-250": "ctrl-encryption",
    "kg-340": "ctrl-encryption",
    "kg-245x": "ctrl-encryption",
    "kg-255": "ctrl-encryption",
    "macsec": "ctrl-encryption",
    # DNS / Cloud services
    "aws-r53": "asset-server",
    "az-dns": "asset-server",
    "gcp-dns": "asset-server",
    # Transit / hybrid
    "aws-dx": "asset-network",
    "az-er": "asset-network",
    "gcp-ic": "asset-network",
    "oci-fc": "asset-network",
    "aws-tgw": "asset-network",
    "az-vwan": "asset-network",
    "sdwan-overlay": "asset-network",
}

# ── MITRE ATT&CK Techniques ───────────────────────────────────────────────
# Maps tactic keys to tactic metadata and techniques with detection controls.

MITRE_ATTACK_TECHNIQUES = {
    "initial_access": {
        "tactic_id": "TA0001",
        "name": "Initial Access",
        "techniques": [
            {
                "id": "T1190",
                "name": "Exploit Public-Facing Application",
                "detectable_by": ["ctrl-firewall", "ctrl-ids"],
                "severity": "high",
            },
            {"id": "T1566", "name": "Phishing", "detectable_by": ["ctrl-idp"], "severity": "high"},
            {
                "id": "T1133",
                "name": "External Remote Services",
                "detectable_by": ["ctrl-firewall", "ctrl-pam"],
                "severity": "high",
            },
            {
                "id": "T1078",
                "name": "Valid Accounts",
                "detectable_by": ["ctrl-idp", "ctrl-siem"],
                "severity": "critical",
            },
        ],
    },
    "execution": {
        "tactic_id": "TA0002",
        "name": "Execution",
        "techniques": [
            {
                "id": "T1059",
                "name": "Command and Scripting Interpreter",
                "detectable_by": ["ctrl-edr", "ctrl-siem"],
                "severity": "high",
            },
            {
                "id": "T1203",
                "name": "Exploitation for Client Execution",
                "detectable_by": ["ctrl-edr", "ctrl-ids"],
                "severity": "high",
            },
        ],
    },
    "persistence": {
        "tactic_id": "TA0003",
        "name": "Persistence",
        "techniques": [
            {
                "id": "T1098",
                "name": "Account Manipulation",
                "detectable_by": ["ctrl-idp", "ctrl-siem", "ctrl-pam"],
                "severity": "high",
            },
            {"id": "T1136", "name": "Create Account", "detectable_by": ["ctrl-idp", "ctrl-siem"], "severity": "medium"},
        ],
    },
    "privilege_escalation": {
        "tactic_id": "TA0004",
        "name": "Privilege Escalation",
        "techniques": [
            {
                "id": "T1068",
                "name": "Exploitation for Privilege Escalation",
                "detectable_by": ["ctrl-edr", "ctrl-ids"],
                "severity": "critical",
            },
            {"id": "T1078", "name": "Valid Accounts", "detectable_by": ["ctrl-pam", "ctrl-siem"], "severity": "high"},
        ],
    },
    "defense_evasion": {
        "tactic_id": "TA0005",
        "name": "Defense Evasion",
        "techniques": [
            {"id": "T1070", "name": "Indicator Removal", "detectable_by": ["ctrl-siem"], "severity": "high"},
            {
                "id": "T1562",
                "name": "Impair Defenses",
                "detectable_by": ["ctrl-siem", "ctrl-edr"],
                "severity": "critical",
            },
        ],
    },
    "credential_access": {
        "tactic_id": "TA0006",
        "name": "Credential Access",
        "techniques": [
            {"id": "T1110", "name": "Brute Force", "detectable_by": ["ctrl-idp", "ctrl-siem"], "severity": "high"},
            {
                "id": "T1555",
                "name": "Credentials from Password Stores",
                "detectable_by": ["ctrl-pam", "ctrl-dlp"],
                "severity": "critical",
            },
            {
                "id": "T1552",
                "name": "Unsecured Credentials",
                "detectable_by": ["ctrl-scanner", "ctrl-dlp"],
                "severity": "high",
            },
        ],
    },
    "discovery": {
        "tactic_id": "TA0007",
        "name": "Discovery",
        "techniques": [
            {
                "id": "T1046",
                "name": "Network Service Discovery",
                "detectable_by": ["ctrl-ids", "ctrl-siem"],
                "severity": "medium",
            },
            {"id": "T1087", "name": "Account Discovery", "detectable_by": ["ctrl-siem"], "severity": "medium"},
        ],
    },
    "lateral_movement": {
        "tactic_id": "TA0008",
        "name": "Lateral Movement",
        "techniques": [
            {
                "id": "T1021",
                "name": "Remote Services",
                "detectable_by": ["ctrl-pam", "ctrl-ids", "ctrl-firewall"],
                "severity": "high",
            },
            {
                "id": "T1210",
                "name": "Exploitation of Remote Services",
                "detectable_by": ["ctrl-ids", "ctrl-edr"],
                "severity": "critical",
            },
        ],
    },
    "collection": {
        "tactic_id": "TA0009",
        "name": "Collection",
        "techniques": [
            {
                "id": "T1005",
                "name": "Data from Local System",
                "detectable_by": ["ctrl-dlp", "ctrl-edr"],
                "severity": "high",
            },
            {
                "id": "T1530",
                "name": "Data from Cloud Storage",
                "detectable_by": ["ctrl-dlp", "ctrl-cspm"],
                "severity": "high",
            },
        ],
    },
    "exfiltration": {
        "tactic_id": "TA0010",
        "name": "Exfiltration",
        "techniques": [
            {
                "id": "T1041",
                "name": "Exfiltration Over C2 Channel",
                "detectable_by": ["ctrl-firewall", "ctrl-dlp", "ctrl-siem"],
                "severity": "critical",
            },
            {
                "id": "T1048",
                "name": "Exfiltration Over Alternative Protocol",
                "detectable_by": ["ctrl-firewall", "ctrl-ids", "ctrl-dlp"],
                "severity": "critical",
            },
        ],
    },
    "impact": {
        "tactic_id": "TA0040",
        "name": "Impact",
        "techniques": [
            {
                "id": "T1486",
                "name": "Data Encrypted for Impact (Ransomware)",
                "detectable_by": ["ctrl-edr", "ctrl-siem"],
                "severity": "critical",
            },
            {
                "id": "T1485",
                "name": "Data Destruction",
                "detectable_by": ["ctrl-siem", "ctrl-edr"],
                "severity": "critical",
            },
            {
                "id": "T1499",
                "name": "Endpoint Denial of Service",
                "detectable_by": ["ctrl-firewall", "ctrl-ids"],
                "severity": "high",
            },
        ],
    },
}

# ── Compliance Crosswalk (NIST 800-53 → FedRAMP → CMMC L2) ────────────────
# Maps NIST 800-53 controls to equivalent controls in FedRAMP and CMMC.

COMPLIANCE_CROSSWALK = {
    "AC-2": {"fedramp": "AC-2", "cmmc": "AC.L2-3.1.1", "description": "Account Management"},
    "AC-3": {"fedramp": "AC-3", "cmmc": "AC.L2-3.1.2", "description": "Access Enforcement"},
    "AC-6": {"fedramp": "AC-6", "cmmc": "AC.L2-3.1.5", "description": "Least Privilege"},
    "AU-2": {"fedramp": "AU-2", "cmmc": "AU.L2-3.3.1", "description": "Event Logging"},
    "AU-3": {"fedramp": "AU-3", "cmmc": "AU.L2-3.3.1", "description": "Content of Audit Records"},
    "AU-6": {"fedramp": "AU-6", "cmmc": "AU.L2-3.3.5", "description": "Audit Review"},
    "AU-10": {"fedramp": "AU-10", "cmmc": "AU.L2-3.3.2", "description": "Non-Repudiation"},
    "AU-12": {"fedramp": "AU-12", "cmmc": "AU.L2-3.3.1", "description": "Audit Record Generation"},
    "CA-2": {"fedramp": "CA-2", "cmmc": "CA.L2-3.12.1", "description": "Control Assessments"},
    "CA-6": {"fedramp": "CA-6", "cmmc": "CA.L2-3.12.4", "description": "Authorization"},
    "CA-7": {"fedramp": "CA-7", "cmmc": "CA.L2-3.12.3", "description": "Continuous Monitoring"},
    "CM-2": {"fedramp": "CM-2", "cmmc": "CM.L2-3.4.1", "description": "Baseline Configuration"},
    "CM-3": {"fedramp": "CM-3", "cmmc": "CM.L2-3.4.3", "description": "Change Control"},
    "CM-5": {"fedramp": "CM-5", "cmmc": "CM.L2-3.4.5", "description": "Access Restrictions for Change"},
    "CM-7": {"fedramp": "CM-7", "cmmc": "CM.L2-3.4.6", "description": "Least Functionality"},
    "CP-7": {"fedramp": "CP-7", "cmmc": None, "description": "Alternate Processing Site"},
    "CP-8": {"fedramp": "CP-8", "cmmc": None, "description": "Telecommunications Services"},
    "CP-10": {"fedramp": "CP-10", "cmmc": None, "description": "System Recovery and Reconstitution"},
    "IA-2": {"fedramp": "IA-2", "cmmc": "IA.L2-3.5.1", "description": "User Identification and Authentication"},
    "IA-3": {"fedramp": "IA-3", "cmmc": "IA.L2-3.5.2", "description": "Device Identification"},
    "IA-5": {"fedramp": "IA-5", "cmmc": "IA.L2-3.5.7", "description": "Authenticator Management"},
    "IA-8": {"fedramp": "IA-8", "cmmc": "IA.L2-3.5.1", "description": "Non-Organizational User ID"},
    "IR-4": {"fedramp": "IR-4", "cmmc": "IR.L2-3.6.1", "description": "Incident Handling"},
    "IR-5": {"fedramp": "IR-5", "cmmc": "IR.L2-3.6.2", "description": "Incident Monitoring"},
    "IR-6": {"fedramp": "IR-6", "cmmc": "IR.L2-3.6.2", "description": "Incident Reporting"},
    "RA-3": {"fedramp": "RA-3", "cmmc": "RA.L2-3.11.1", "description": "Risk Assessment"},
    "RA-5": {"fedramp": "RA-5", "cmmc": "RA.L2-3.11.2", "description": "Vulnerability Monitoring"},
    "SA-4": {"fedramp": "SA-4", "cmmc": "SA.L2-3.16.1", "description": "Acquisition Process"},
    "SA-11": {"fedramp": "SA-11", "cmmc": "SA.L2-3.16.3", "description": "Developer Testing"},
    "SC-4": {"fedramp": "SC-4", "cmmc": "SC.L2-3.13.4", "description": "Information in Shared Resources"},
    "SC-5": {"fedramp": "SC-5", "cmmc": None, "description": "Denial of Service Protection"},
    "SC-7": {"fedramp": "SC-7", "cmmc": "SC.L2-3.13.1", "description": "Boundary Protection"},
    "SC-8": {"fedramp": "SC-8", "cmmc": "SC.L2-3.13.8", "description": "Transmission Confidentiality"},
    "SC-12": {"fedramp": "SC-12", "cmmc": "SC.L2-3.13.10", "description": "Cryptographic Key Management"},
    "SC-13": {"fedramp": "SC-13", "cmmc": "SC.L2-3.13.11", "description": "Cryptographic Protection"},
    "SC-23": {"fedramp": "SC-23", "cmmc": None, "description": "Session Authenticity"},
    "SC-28": {"fedramp": "SC-28", "cmmc": "SC.L2-3.13.16", "description": "Protection of Information at Rest"},
    "SI-2": {"fedramp": "SI-2", "cmmc": "SI.L2-3.14.1", "description": "Flaw Remediation"},
    "SI-4": {"fedramp": "SI-4", "cmmc": "SI.L2-3.14.6", "description": "System Monitoring"},
    "SI-7": {"fedramp": "SI-7", "cmmc": "SI.L2-3.14.4", "description": "Software Integrity Verification"},
}

# ── NSA ZIG (Zero Trust Implementation Guide) ─────────────────────────────
# Source: NSA ZIG January 2026 — 7 pillars, 42 target capabilities, 91 activities

ZIG_MATURITY_LEVELS = [
    {"slug": "preparation", "label": "Preparation", "score_min": 0.0, "score_max": 0.24,
     "description": "Planning and baseline assessment; no operational ZT capabilities yet."},
    {"slug": "basic", "label": "Basic", "score_min": 0.25, "score_max": 0.49,
     "description": "Foundational ZT capabilities deployed; manual processes predominate."},
    {"slug": "intermediate", "label": "Intermediate", "score_min": 0.50, "score_max": 0.74,
     "description": "Automated controls and cross-pillar integration; enhanced monitoring."},
    {"slug": "advanced", "label": "Advanced", "score_min": 0.75, "score_max": 1.0,
     "description": "AI/ML-driven decisions; fully automated playbooks; continuous adaptation."},
]

ZIG_PHASES = [
    {"slug": "discovery", "label": "Discovery Phase", "activity_count": 14,
     "description": "Identify critical data, apps, assets, and services for ZT prioritization."},
    {"slug": "phase1", "label": "Phase 1 (Target Foundation)", "activity_count": 36,
     "description": "Establish secure foundation for ZT capabilities. 30 capabilities."},
    {"slug": "phase2", "label": "Phase 2 (Target Integration)", "activity_count": 41,
     "description": "Integrate distinct ZT solutions. 34 capabilities. FY2027 target."},
]

ZIG_PILLARS = [
    {
        "slug": "user",
        "name": "User",
        "full_name": "Identity & Access Management (ICAM)",
        "pillar_weight": 0.20,
        "icon": "user-shield",
        "color": "#6366f1",
        "csi_url": "https://media.defense.gov/2023/Mar/09/2003180104/-1/-1/0/CSI_ZERO_TRUST_UPW.PDF",
        "description": "Continuous authentication, assessment, and monitoring of user activity via FICAM.",
        "ficam_components": ["Identity Management", "Credential Management", "Access Management",
                             "Federation", "Governance"],
    },
    {
        "slug": "device",
        "name": "Device",
        "full_name": "Endpoint Security",
        "pillar_weight": 0.15,
        "icon": "laptop",
        "color": "#8b5cf6",
        "csi_url": "https://media.defense.gov/2023/Oct/06/2003312169/-1/-1/0/CSI_ZT_DEVICE_PILLAR.PDF",
        "description": "Evaluating health and trustworthiness of all connected endpoints.",
    },
    {
        "slug": "network",
        "name": "Network & Environment",
        "full_name": "Network Segmentation & Isolation",
        "pillar_weight": 0.15,
        "icon": "network-wired",
        "color": "#06b6d4",
        "csi_url": "https://media.defense.gov/2024/Mar/05/2003405462/-1/-1/0/CSI-ZERO-TRUST-NETWORK-ENVIRONMENT-PILLAR.PDF",
        "description": "Curtailing adversarial lateral movement through granular policy restrictions.",
    },
    {
        "slug": "application",
        "name": "Application & Workload",
        "full_name": "Secure Software Development & Runtime",
        "pillar_weight": 0.15,
        "icon": "code",
        "color": "#10b981",
        "csi_url": "https://media.defense.gov/2023/Sep/28/2003307096/-1/-1/0/CSI_ZT_APPLICATION_WORKLOAD_PILLAR.PDF",
        "description": "Securing applications through lifecycle management and granular runtime controls.",
    },
    {
        "slug": "data",
        "name": "Data",
        "full_name": "Data Protection & Governance",
        "pillar_weight": 0.15,
        "icon": "database",
        "color": "#f59e0b",
        "csi_url": "https://media.defense.gov/2024/Apr/09/2003434442/-1/-1/0/CSI_DATA_PILLAR_ZT.PDF",
        "description": "Protecting data through cataloging, labeling, encryption, and access control.",
    },
    {
        "slug": "visibility",
        "name": "Visibility & Analytics",
        "full_name": "Monitoring & Threat Detection",
        "pillar_weight": 0.10,
        "icon": "chart-bar",
        "color": "#ef4444",
        "csi_url": "https://media.defense.gov/2024/May/30/2003475230/-1/-1/0/CSI-VISIBILITY-AND-ANALYTICS-PILLAR.PDF",
        "description": "Analyzing network/system activity to detect threats; foundation of any ZT strategy.",
    },
    {
        "slug": "automation",
        "name": "Automation & Orchestration",
        "full_name": "Speed, Scale & Orchestrated Response",
        "pillar_weight": 0.10,
        "icon": "robot",
        "color": "#ec4899",
        "csi_url": "https://media.defense.gov/2024/Jul/29/2003513920/-1/-1/0/CSI-ZERO-TRUST-AUTOMATION-AND-ORCHESTRATION-PILLAR.PDF",
        "description": "Automating security actions based on defined processes; enabling consistent threat response.",
    },
]

# 42 target-level capabilities (7 pillars × varying counts = 42 total)
# phase: discovery | phase1 | phase2
# maturity_level: basic | intermediate | advanced
ZIG_CAPABILITIES = [
    # ── User Pillar (7 capabilities) ────────────────────────────────────────
    {"id": "zig-usr-01", "pillar": "user", "title": "Authoritative Identity Establishment",
     "phase": "discovery", "maturity_level": "basic",
     "description": "Establish authoritative identity source for all users, devices, and non-person entities.",
     "nist_controls": ["IA-2", "IA-4", "IA-12"]},
    {"id": "zig-usr-02", "pillar": "user", "title": "Multi-Factor Authentication (MFA) Deployment",
     "phase": "phase1", "maturity_level": "basic",
     "description": "Deploy phishing-resistant MFA (FIDO2/PIV) for all users and privileged accounts.",
     "nist_controls": ["IA-2", "IA-5", "IA-11"]},
    {"id": "zig-usr-03", "pillar": "user", "title": "Privileged Access Management (PAM)",
     "phase": "phase1", "maturity_level": "basic",
     "description": "Implement PAM with just-in-time access, session recording, and least privilege.",
     "nist_controls": ["AC-2", "AC-6", "AC-17"]},
    {"id": "zig-usr-04", "pillar": "user", "title": "Federation and Trust Frameworks",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Establish federation and interoperability with mission partners; FICAM-aligned trust.",
     "nist_controls": ["IA-8", "SC-23", "AC-20"]},
    {"id": "zig-usr-05", "pillar": "user", "title": "Continuous User Assessment and Monitoring",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Continuously assess user risk posture; revoke access on anomaly detection.",
     "nist_controls": ["CA-7", "SI-4", "AC-7"]},
    {"id": "zig-usr-06", "pillar": "user", "title": "Role/Attribute-Based Access Control (RBAC/ABAC)",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Enforce fine-grained RBAC and ABAC; context-aware access decisions.",
     "nist_controls": ["AC-3", "AC-6", "AC-16"]},
    {"id": "zig-usr-07", "pillar": "user", "title": "Identity Governance and Administration",
     "phase": "phase2", "maturity_level": "advanced",
     "description": "Automated access reviews, lifecycle management, entitlement analytics.",
     "nist_controls": ["AC-2", "AC-5", "AU-6"]},
    # ── Device Pillar (7 capabilities) ──────────────────────────────────────
    {"id": "zig-dev-01", "pillar": "device", "title": "Device Inventory",
     "phase": "discovery", "maturity_level": "basic",
     "description": "Real-time, comprehensive discovery and cataloging of all connected devices.",
     "nist_controls": ["CM-8", "CA-7", "SI-2"]},
    {"id": "zig-dev-02", "pillar": "device", "title": "Device Detection and Compliance",
     "phase": "phase1", "maturity_level": "basic",
     "description": "Identify unknown/unauthorized devices; enforce configuration compliance baselines.",
     "nist_controls": ["CM-2", "CM-6", "CM-7"]},
    {"id": "zig-dev-03", "pillar": "device", "title": "Device Authorization with Real-Time Inspection",
     "phase": "phase1", "maturity_level": "basic",
     "description": "Dynamic access decisions based on continuous device health state assessment.",
     "nist_controls": ["AC-3", "CA-7", "IA-3"]},
    {"id": "zig-dev-04", "pillar": "device", "title": "Remote Access Protection",
     "phase": "phase1", "maturity_level": "intermediate",
     "description": "Stringent controls for off-network device connections; VPN replacement with ZT proxy.",
     "nist_controls": ["AC-17", "SC-7", "IA-11"]},
    {"id": "zig-dev-05", "pillar": "device", "title": "Automated Vulnerability and Patch Management",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Systematic, automated patch deployment with mandatory pre-deployment testing.",
     "nist_controls": ["SI-2", "RA-5", "CM-3"]},
    {"id": "zig-dev-06", "pillar": "device", "title": "Centralized Device Management (UEM/MDM)",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Unified endpoint management with TPM enrollment and automated compliance enforcement.",
     "nist_controls": ["CM-2", "CM-6", "SC-28"]},
    {"id": "zig-dev-07", "pillar": "device", "title": "Endpoint Threat Detection and Response (EDR/XDR)",
     "phase": "phase2", "maturity_level": "advanced",
     "description": "Continuous endpoint monitoring for threat activities with automated response and remediation.",
     "nist_controls": ["SI-4", "IR-4", "SI-7"]},
    # ── Network & Environment Pillar (4 capabilities) ────────────────────────
    {"id": "zig-net-01", "pillar": "network", "title": "Data Flow Mapping",
     "phase": "discovery", "maturity_level": "basic",
     "description": "Identify routes data travels across locations/applications; map internal/external nodes.",
     "nist_controls": ["SC-7", "CA-3", "PL-8"]},
    {"id": "zig-net-02", "pillar": "network", "title": "Macro-Segmentation",
     "phase": "phase1", "maturity_level": "basic",
     "description": "High-level segmentation breaking networks into discrete security zones.",
     "nist_controls": ["SC-7", "AC-4", "SC-3"]},
    {"id": "zig-net-03", "pillar": "network", "title": "Micro-Segmentation",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Granular security limiting lateral data flow with strict access policies within departments.",
     "nist_controls": ["SC-7", "AC-4", "CM-7"]},
    {"id": "zig-net-04", "pillar": "network", "title": "Software Defined Networking (SDN)",
     "phase": "phase2", "maturity_level": "advanced",
     "description": "Centralized control, dynamic policy implementation, and unified enforcement via SDN.",
     "nist_controls": ["SC-7", "AC-4", "SI-4"]},
    # ── Application & Workload Pillar (5 capabilities) ───────────────────────
    {"id": "zig-app-01", "pillar": "application", "title": "Application Inventory and SBOM",
     "phase": "discovery", "maturity_level": "basic",
     "description": "Comprehensive catalog of applications/workloads with SBOM and vulnerability tracking.",
     "nist_controls": ["CM-8", "SA-4", "SR-2"]},
    {"id": "zig-app-02", "pillar": "application", "title": "Secure Software Development and Supply Chain",
     "phase": "phase1", "maturity_level": "basic",
     "description": "SAST/SCA for third-party/open-source components; digital application signatures.",
     "nist_controls": ["SA-11", "SR-3", "CM-14"]},
    {"id": "zig-app-03", "pillar": "application", "title": "CI/CD and DevSecOps Integration",
     "phase": "phase1", "maturity_level": "intermediate",
     "description": "Security controls throughout CI/CD; static/dynamic testing in development workflows.",
     "nist_controls": ["SA-11", "CM-4", "SA-15"]},
    {"id": "zig-app-04", "pillar": "application", "title": "Automated Risk-Based Authorization",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Context-based access control (CBAC) with dynamic authorization reflecting real-time risk.",
     "nist_controls": ["AC-3", "RA-3", "CA-7"]},
    {"id": "zig-app-05", "pillar": "application", "title": "Continuous Monitoring and Ongoing Authorization",
     "phase": "phase2", "maturity_level": "advanced",
     "description": "Real-time anomaly detection; automated access revocation when application risks emerge.",
     "nist_controls": ["CA-7", "SI-4", "AC-7"]},
    # ── Data Pillar (7 capabilities) ─────────────────────────────────────────
    {"id": "zig-dat-01", "pillar": "data", "title": "Data Catalog Risk Alignment",
     "phase": "discovery", "maturity_level": "basic",
     "description": "Establish data inventory with risk alignment; NIST-compliant acceptance testing.",
     "nist_controls": ["MP-4", "RA-2", "CM-8"]},
    {"id": "zig-dat-02", "pillar": "data", "title": "Enterprise Data Governance",
     "phase": "phase1", "maturity_level": "basic",
     "description": "Manual data governance policies refined toward automated enforcement.",
     "nist_controls": ["AC-3", "MP-2", "SA-8"]},
    {"id": "zig-dat-03", "pillar": "data", "title": "Data Labeling and Tagging",
     "phase": "phase1", "maturity_level": "basic",
     "description": "Classification-based labeling of data by sensitivity and criticality; hybrid manual/AI.",
     "nist_controls": ["MP-3", "RA-2", "AC-16"]},
    {"id": "zig-dat-04", "pillar": "data", "title": "Data Monitoring and Sensing",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Capture and analyze metadata for threat detection; DLP/DRM integration with SIEM.",
     "nist_controls": ["AU-2", "AU-12", "SI-4"]},
    {"id": "zig-dat-05", "pillar": "data", "title": "Data Encryption and Rights Management",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Encrypt data at rest, in transit, and in use; automated DRM deployment.",
     "nist_controls": ["SC-13", "SC-28", "SC-8"]},
    {"id": "zig-dat-06", "pillar": "data", "title": "Data Loss Prevention (DLP)",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Prevent unauthorized data exfiltration; DLP embedded throughout systems.",
     "nist_controls": ["SC-7", "AC-4", "SI-4"]},
    {"id": "zig-dat-07", "pillar": "data", "title": "Data Access Control (RBAC/ABAC/PBAC)",
     "phase": "phase2", "maturity_level": "advanced",
     "description": "Dynamic, risk-based access controls with granular enforcement across all data stores.",
     "nist_controls": ["AC-3", "AC-16", "AU-10"]},
    # ── Visibility & Analytics Pillar (6 capabilities) ───────────────────────
    {"id": "zig-vis-01", "pillar": "visibility", "title": "Log Collection and Centralization",
     "phase": "discovery", "maturity_level": "basic",
     "description": "Identify relevant log sources and aggregate into a central repository.",
     "nist_controls": ["AU-2", "AU-3", "AU-9"]},
    {"id": "zig-vis-02", "pillar": "visibility", "title": "SIEM Integration",
     "phase": "phase1", "maturity_level": "basic",
     "description": "Aggregate security information; correlate events from different sensor viewpoints.",
     "nist_controls": ["AU-6", "SI-4", "CA-7"]},
    {"id": "zig-vis-03", "pillar": "visibility", "title": "Risk Analytics",
     "phase": "phase1", "maturity_level": "intermediate",
     "description": "Assess infrastructure risk using configuration data, asset inventories, and known vulnerabilities.",
     "nist_controls": ["RA-3", "RA-5", "CA-7"]},
    {"id": "zig-vis-04", "pillar": "visibility", "title": "User and Entity Behavior Analytics (UEBA)",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "ML-driven anomaly detection for unusual network/user activities.",
     "nist_controls": ["SI-4", "AU-6", "IR-4"]},
    {"id": "zig-vis-05", "pillar": "visibility", "title": "Threat Intelligence Integration",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Incorporate external threat indicators, TTPs, and vulnerability data into defenses.",
     "nist_controls": ["SI-5", "RA-5", "IR-4"]},
    {"id": "zig-vis-06", "pillar": "visibility", "title": "Dynamic Policy Automation",
     "phase": "phase2", "maturity_level": "advanced",
     "description": "Policies adapt based on real-time security profiles and threat environments.",
     "nist_controls": ["CA-7", "AC-2", "SI-4"]},
    # ── Automation & Orchestration Pillar (6 capabilities) ───────────────────
    {"id": "zig-aut-01", "pillar": "automation", "title": "Policy Orchestration (PDP/PEP/PIP)",
     "phase": "phase1", "maturity_level": "basic",
     "description": "Decouple Policy Decision Points, Information Points, and Enforcement Points.",
     "nist_controls": ["AC-3", "AC-4", "CA-7"]},
    {"id": "zig-aut-02", "pillar": "automation", "title": "Critical Process Automation (RPA)",
     "phase": "phase1", "maturity_level": "basic",
     "description": "RPA for repetitive security tasks; orchestrated workflows and risk management.",
     "nist_controls": ["AC-2", "CM-3", "SI-2"]},
    {"id": "zig-aut-03", "pillar": "automation", "title": "Artificial Intelligence Integration",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "AI analyzing vast datasets for threat detection beyond human capacity; human audit required.",
     "nist_controls": ["SI-4", "CA-7", "RA-3"]},
    {"id": "zig-aut-04", "pillar": "automation", "title": "Machine Learning Deployment",
     "phase": "phase2", "maturity_level": "intermediate",
     "description": "Predictive models from training data; anomaly detection and automated response.",
     "nist_controls": ["SI-4", "IR-4", "AU-6"]},
    {"id": "zig-aut-05", "pillar": "automation", "title": "Security Orchestration, Automation and Response (SOAR)",
     "phase": "phase2", "maturity_level": "advanced",
     "description": "Collect security data, apply decision logic, execute automated tasks; ingest alerts and trigger response playbooks.",
     "nist_controls": ["IR-4", "IR-5", "SI-4"]},
    {"id": "zig-aut-06", "pillar": "automation", "title": "Data Exchange Standardization",
     "phase": "phase2", "maturity_level": "advanced",
     "description": "Uniform data formats, protocols, and APIs across integrated security systems.",
     "nist_controls": ["SA-8", "SC-8", "CA-3"]},
]

# 91 target-level activities (Discovery=14, Phase1=36, Phase2=41)
# Each maps to a capability and has a NIST control reference
ZIG_ACTIVITIES = [
    # ── Discovery Phase (14 activities) ────────────────────────────────────
    # User
    {"id": "zig-act-d01", "capability_id": "zig-usr-01", "phase": "discovery",
     "title": "Inventory all user accounts and identities",
     "description": "Enumerate all accounts across enterprise systems; identify orphan/shared accounts.",
     "nist_control_ref": "IA-4"},
    {"id": "zig-act-d02", "capability_id": "zig-usr-01", "phase": "discovery",
     "title": "Identify identity providers and authentication methods in use",
     "description": "Document all IdPs, directories, and authentication protocols (LDAP, SAML, OIDC).",
     "nist_control_ref": "IA-2"},
    # Device
    {"id": "zig-act-d03", "capability_id": "zig-dev-01", "phase": "discovery",
     "title": "Conduct full device inventory scan",
     "description": "Discover all managed and unmanaged devices; classify by type, OS, owner.",
     "nist_control_ref": "CM-8"},
    {"id": "zig-act-d04", "capability_id": "zig-dev-01", "phase": "discovery",
     "title": "Assess device security baseline compliance",
     "description": "Measure existing devices against CIS/STIG baselines; identify compliance gaps.",
     "nist_control_ref": "CM-6"},
    # Network
    {"id": "zig-act-d05", "capability_id": "zig-net-01", "phase": "discovery",
     "title": "Map all network data flows",
     "description": "Document all data flows between systems; identify east-west and north-south traffic.",
     "nist_control_ref": "SC-7"},
    {"id": "zig-act-d06", "capability_id": "zig-net-01", "phase": "discovery",
     "title": "Identify critical assets and high-value targets",
     "description": "Classify DAAS (Data, Applications, Assets, Services) by mission criticality.",
     "nist_control_ref": "RA-2"},
    # Application
    {"id": "zig-act-d07", "capability_id": "zig-app-01", "phase": "discovery",
     "title": "Inventory all applications and workloads",
     "description": "Catalog all applications, APIs, microservices, and workloads with ownership.",
     "nist_control_ref": "CM-8"},
    {"id": "zig-act-d08", "capability_id": "zig-app-01", "phase": "discovery",
     "title": "Generate initial SBOM for critical applications",
     "description": "Produce Software Bills of Materials for highest-risk applications.",
     "nist_control_ref": "SR-2"},
    # Data
    {"id": "zig-act-d09", "capability_id": "zig-dat-01", "phase": "discovery",
     "title": "Identify and catalog sensitive data repositories",
     "description": "Locate all data stores containing CUI, PII, or classified information.",
     "nist_control_ref": "RA-2"},
    {"id": "zig-act-d10", "capability_id": "zig-dat-01", "phase": "discovery",
     "title": "Assess current data classification and labeling state",
     "description": "Evaluate existing data classification schemes and identify unlabeled data.",
     "nist_control_ref": "MP-3"},
    # Visibility
    {"id": "zig-act-d11", "capability_id": "zig-vis-01", "phase": "discovery",
     "title": "Inventory all log sources and SIEM ingestion points",
     "description": "Map all existing logging infrastructure; identify gaps in log collection.",
     "nist_control_ref": "AU-2"},
    {"id": "zig-act-d12", "capability_id": "zig-vis-01", "phase": "discovery",
     "title": "Assess current monitoring and detection coverage",
     "description": "Evaluate coverage gaps in threat detection; identify blind spots.",
     "nist_control_ref": "SI-4"},
    # Automation
    {"id": "zig-act-d13", "capability_id": "zig-aut-01", "phase": "discovery",
     "title": "Document existing automation and orchestration tools",
     "description": "Inventory SOAR, RPA, and scripted automation capabilities currently in use.",
     "nist_control_ref": "CA-7"},
    {"id": "zig-act-d14", "capability_id": "zig-aut-01", "phase": "discovery",
     "title": "Identify manual processes eligible for automation",
     "description": "Prioritize high-frequency, low-risk manual security tasks for automation.",
     "nist_control_ref": "CM-3"},
    # ── Phase 1 Activities (36 activities) ─────────────────────────────────
    # User (8)
    {"id": "zig-act-p1-01", "capability_id": "zig-usr-02", "phase": "phase1",
     "title": "Deploy MFA for all privileged and administrative accounts",
     "description": "Enable phishing-resistant MFA (FIDO2/PIV) for all admin accounts immediately.",
     "nist_control_ref": "IA-2"},
    {"id": "zig-act-p1-02", "capability_id": "zig-usr-02", "phase": "phase1",
     "title": "Extend MFA to all standard user accounts",
     "description": "Roll out MFA to all enterprise users; eliminate password-only authentication.",
     "nist_control_ref": "IA-11"},
    {"id": "zig-act-p1-03", "capability_id": "zig-usr-03", "phase": "phase1",
     "title": "Deploy PAM solution for privileged accounts",
     "description": "Implement PAM with session recording, just-in-time access, and vault for credentials.",
     "nist_control_ref": "AC-6"},
    {"id": "zig-act-p1-04", "capability_id": "zig-usr-03", "phase": "phase1",
     "title": "Enforce least privilege across all user roles",
     "description": "Remove excessive privileges; implement role-based access aligned to job functions.",
     "nist_control_ref": "AC-2"},
    {"id": "zig-act-p1-05", "capability_id": "zig-usr-01", "phase": "phase1",
     "title": "Consolidate identity sources to authoritative directory",
     "description": "Rationalize identity stores; establish single authoritative source (AD/LDAP/cloud IdP).",
     "nist_control_ref": "IA-4"},
    {"id": "zig-act-p1-06", "capability_id": "zig-usr-01", "phase": "phase1",
     "title": "Implement automated account lifecycle management",
     "description": "Automate provisioning/deprovisioning tied to HR systems; eliminate orphan accounts.",
     "nist_control_ref": "AC-2"},
    {"id": "zig-act-p1-07", "capability_id": "zig-usr-06", "phase": "phase1",
     "title": "Define and implement RBAC policies for critical systems",
     "description": "Map roles to permissions; enforce role separation for sensitive applications.",
     "nist_control_ref": "AC-3"},
    {"id": "zig-act-p1-08", "capability_id": "zig-vis-02", "phase": "phase1",
     "title": "Enable identity and authentication event logging",
     "description": "Log all authentication events (success/failure) to centralized SIEM.",
     "nist_control_ref": "AU-2"},
    # Device (7)
    {"id": "zig-act-p1-09", "capability_id": "zig-dev-02", "phase": "phase1",
     "title": "Deploy automated device compliance scanning",
     "description": "Implement continuous compliance checks against security baselines on all managed devices.",
     "nist_control_ref": "CM-6"},
    {"id": "zig-act-p1-10", "capability_id": "zig-dev-02", "phase": "phase1",
     "title": "Establish network access control (NAC) for unknown devices",
     "description": "Block or quarantine unmanaged/unknown devices at network entry points.",
     "nist_control_ref": "AC-3"},
    {"id": "zig-act-p1-11", "capability_id": "zig-dev-03", "phase": "phase1",
     "title": "Implement device health attestation for access decisions",
     "description": "Integrate device health signals into access policy enforcement.",
     "nist_control_ref": "IA-3"},
    {"id": "zig-act-p1-12", "capability_id": "zig-dev-04", "phase": "phase1",
     "title": "Replace legacy VPN with Zero Trust Network Access (ZTNA)",
     "description": "Pilot ZTNA for remote access; enforce per-session identity + device verification.",
     "nist_control_ref": "AC-17"},
    {"id": "zig-act-p1-13", "capability_id": "zig-dev-01", "phase": "phase1",
     "title": "Enroll all managed devices in MDM/UEM",
     "description": "Ensure 100% MDM enrollment; enforce policies for BYOD and corporate devices.",
     "nist_control_ref": "CM-8"},
    {"id": "zig-act-p1-14", "capability_id": "zig-dev-05", "phase": "phase1",
     "title": "Establish automated patch management pipeline",
     "description": "Deploy automated patch deployment with testing gates; track patch compliance.",
     "nist_control_ref": "SI-2"},
    {"id": "zig-act-p1-15", "capability_id": "zig-dev-07", "phase": "phase1",
     "title": "Deploy EDR on all managed endpoints",
     "description": "Install EDR agents on all servers and endpoints; integrate alerts with SIEM.",
     "nist_control_ref": "SI-4"},
    # Network (5)
    {"id": "zig-act-p1-16", "capability_id": "zig-net-02", "phase": "phase1",
     "title": "Implement macro-segmentation between business units",
     "description": "Create network segments isolating sub-organizations with access control boundaries.",
     "nist_control_ref": "SC-7"},
    {"id": "zig-act-p1-17", "capability_id": "zig-net-01", "phase": "phase1",
     "title": "Deploy default-deny network policies at perimeter",
     "description": "Establish deny-by-default firewall rules; only permit explicitly approved flows.",
     "nist_control_ref": "SC-7"},
    {"id": "zig-act-p1-18", "capability_id": "zig-net-02", "phase": "phase1",
     "title": "Encrypt all network traffic in transit",
     "description": "Enforce TLS 1.3+ on all internal and external data flows; eliminate plaintext.",
     "nist_control_ref": "SC-8"},
    {"id": "zig-act-p1-19", "capability_id": "zig-net-01", "phase": "phase1",
     "title": "Establish network monitoring with flow logging",
     "description": "Enable NetFlow/IPFIX and packet capture at key network chokepoints.",
     "nist_control_ref": "SI-4"},
    {"id": "zig-act-p1-20", "capability_id": "zig-net-02", "phase": "phase1",
     "title": "Restrict third-party access via least-privilege segmentation",
     "description": "Constrain vendor/partner access to minimum network segments required for operations.",
     "nist_control_ref": "AC-20"},
    # Application (5)
    {"id": "zig-act-p1-21", "capability_id": "zig-app-02", "phase": "phase1",
     "title": "Integrate SAST/SCA into CI/CD pipelines",
     "description": "Add static analysis and dependency scanning to all build pipelines as blocking gates.",
     "nist_control_ref": "SA-11"},
    {"id": "zig-act-p1-22", "capability_id": "zig-app-02", "phase": "phase1",
     "title": "Enforce code signing for all deployable artifacts",
     "description": "Sign all application binaries and containers; reject unsigned artifacts in production.",
     "nist_control_ref": "CM-14"},
    {"id": "zig-act-p1-23", "capability_id": "zig-app-03", "phase": "phase1",
     "title": "Implement container image scanning in registry",
     "description": "Scan all container images for CVEs before admission to production clusters.",
     "nist_control_ref": "SA-11"},
    {"id": "zig-act-p1-24", "capability_id": "zig-aut-01", "phase": "phase1",
     "title": "Deploy Policy Decision Point (PDP) infrastructure",
     "description": "Establish PDP (e.g., OPA, Rego, DISA ICAM) to evaluate access decisions.",
     "nist_control_ref": "AC-3"},
    {"id": "zig-act-p1-25", "capability_id": "zig-aut-02", "phase": "phase1",
     "title": "Automate user provisioning and deprovisioning workflows",
     "description": "Implement RPA for account lifecycle tied to HR events; SLA < 4 hours for terminations.",
     "nist_control_ref": "AC-2"},
    # Data (5)
    {"id": "zig-act-p1-26", "capability_id": "zig-dat-02", "phase": "phase1",
     "title": "Publish enterprise data classification policy",
     "description": "Define data classification scheme (Unclassified/CUI/Secret) with access rules.",
     "nist_control_ref": "MP-3"},
    {"id": "zig-act-p1-27", "capability_id": "zig-dat-03", "phase": "phase1",
     "title": "Apply labels to high-value data repositories",
     "description": "Begin manual/hybrid labeling on highest-risk data stores; prioritize CUI.",
     "nist_control_ref": "MP-3"},
    {"id": "zig-act-p1-28", "capability_id": "zig-dat-02", "phase": "phase1",
     "title": "Enforce data access controls based on classification",
     "description": "Wire classification labels to access control enforcement; block mismatched access.",
     "nist_control_ref": "AC-3"},
    {"id": "zig-act-p1-29", "capability_id": "zig-dat-05", "phase": "phase1",
     "title": "Enable encryption at rest for all sensitive data stores",
     "description": "Encrypt CUI/classified databases and storage with FIPS 140-2/3 validated keys.",
     "nist_control_ref": "SC-28"},
    {"id": "zig-act-p1-30", "capability_id": "zig-dat-05", "phase": "phase1",
     "title": "Implement KMS for centralized key management",
     "description": "Deploy KMS with HSM backing for all encryption key lifecycle management.",
     "nist_control_ref": "SC-12"},
    # Visibility (5)
    {"id": "zig-act-p1-31", "capability_id": "zig-vis-02", "phase": "phase1",
     "title": "Ingest all critical log sources into SIEM",
     "description": "Connect all firewalls, IAM, endpoint, and application logs to centralized SIEM.",
     "nist_control_ref": "AU-6"},
    {"id": "zig-act-p1-32", "capability_id": "zig-vis-03", "phase": "phase1",
     "title": "Configure SIEM correlation rules for ZT events",
     "description": "Create detection rules for authentication anomalies, lateral movement, data exfil.",
     "nist_control_ref": "SI-4"},
    {"id": "zig-act-p1-33", "capability_id": "zig-vis-02", "phase": "phase1",
     "title": "Establish SOC monitoring baseline and alerting",
     "description": "Define alert thresholds, escalation procedures, and baseline normal behavior.",
     "nist_control_ref": "IR-4"},
    {"id": "zig-act-p1-34", "capability_id": "zig-vis-03", "phase": "phase1",
     "title": "Deploy vulnerability scanner covering all assets",
     "description": "Implement credentialed scanning across all network-accessible assets weekly.",
     "nist_control_ref": "RA-5"},
    {"id": "zig-act-p1-35", "capability_id": "zig-vis-01", "phase": "phase1",
     "title": "Implement log integrity protection",
     "description": "Protect log data from tampering; use append-only storage and integrity verification.",
     "nist_control_ref": "AU-9"},
    {"id": "zig-act-p1-36", "capability_id": "zig-aut-02", "phase": "phase1",
     "title": "Automate vulnerability remediation ticketing",
     "description": "Auto-create and assign remediation tickets from scanner findings via SOAR.",
     "nist_control_ref": "SI-2"},
    # ── Phase 2 Activities (41 activities) ─────────────────────────────────
    # User (6)
    {"id": "zig-act-p2-01", "capability_id": "zig-usr-04", "phase": "phase2",
     "title": "Establish federated identity with mission partners",
     "description": "Implement SAML/OIDC federation with external mission partner IdPs.",
     "nist_control_ref": "IA-8"},
    {"id": "zig-act-p2-02", "capability_id": "zig-usr-05", "phase": "phase2",
     "title": "Deploy continuous user risk scoring",
     "description": "Implement real-time user risk score updated by behavioral signals; auto-step-up auth.",
     "nist_control_ref": "CA-7"},
    {"id": "zig-act-p2-03", "capability_id": "zig-usr-06", "phase": "phase2",
     "title": "Implement ABAC with dynamic attribute evaluation",
     "description": "Extend RBAC with attribute-based policies incorporating context (time, location, device).",
     "nist_control_ref": "AC-16"},
    {"id": "zig-act-p2-04", "capability_id": "zig-usr-07", "phase": "phase2",
     "title": "Conduct automated access certification campaigns",
     "description": "Automate quarterly access reviews; auto-revoke uncertified entitlements.",
     "nist_control_ref": "AC-5"},
    {"id": "zig-act-p2-05", "capability_id": "zig-usr-05", "phase": "phase2",
     "title": "Integrate behavioral analytics with access control",
     "description": "Feed UEBA signals into access policy; revoke sessions on anomaly detection.",
     "nist_control_ref": "SI-4"},
    {"id": "zig-act-p2-06", "capability_id": "zig-usr-07", "phase": "phase2",
     "title": "Implement entitlement analytics and drift detection",
     "description": "Detect privilege creep and entitlement drift; auto-generate remediation recommendations.",
     "nist_control_ref": "AC-2"},
    # Device (6)
    {"id": "zig-act-p2-07", "capability_id": "zig-dev-05", "phase": "phase2",
     "title": "Achieve automated patch compliance across all device types",
     "description": "Reach >95% patch compliance within SLA across servers, endpoints, and network devices.",
     "nist_control_ref": "SI-2"},
    {"id": "zig-act-p2-08", "capability_id": "zig-dev-06", "phase": "phase2",
     "title": "Enforce TPM-based device attestation",
     "description": "Require TPM certificates for device identity; block non-attested devices from access.",
     "nist_control_ref": "IA-3"},
    {"id": "zig-act-p2-09", "capability_id": "zig-dev-07", "phase": "phase2",
     "title": "Integrate EDR/XDR telemetry into SIEM and SOAR",
     "description": "Feed endpoint detections into SIEM; trigger automated response playbooks via SOAR.",
     "nist_control_ref": "IR-4"},
    {"id": "zig-act-p2-10", "capability_id": "zig-dev-07", "phase": "phase2",
     "title": "Deploy XDR for cross-domain threat correlation",
     "description": "Extend detection beyond endpoints to network, identity, and cloud telemetry.",
     "nist_control_ref": "SI-4"},
    {"id": "zig-act-p2-11", "capability_id": "zig-dev-06", "phase": "phase2",
     "title": "Automate device compliance remediation",
     "description": "Auto-remediate non-compliant device configurations; quarantine unremediated devices.",
     "nist_control_ref": "CM-3"},
    {"id": "zig-act-p2-12", "capability_id": "zig-dev-04", "phase": "phase2",
     "title": "Extend ZTNA to all remote access use cases",
     "description": "Complete VPN elimination; enforce ZTNA for all remote access scenarios.",
     "nist_control_ref": "AC-17"},
    # Network (6)
    {"id": "zig-act-p2-13", "capability_id": "zig-net-03", "phase": "phase2",
     "title": "Implement workload micro-segmentation in production",
     "description": "Apply K8s NetworkPolicies/Calico rules for workload-level east-west segmentation.",
     "nist_control_ref": "SC-7"},
    {"id": "zig-act-p2-14", "capability_id": "zig-net-03", "phase": "phase2",
     "title": "Deploy identity-based micro-segmentation policies",
     "description": "Enforce network access based on workload identity, not just IP/port.",
     "nist_control_ref": "AC-4"},
    {"id": "zig-act-p2-15", "capability_id": "zig-net-04", "phase": "phase2",
     "title": "Implement service mesh with mTLS enforcement",
     "description": "Deploy Istio/Linkerd with STRICT mTLS mode across all microservices.",
     "nist_control_ref": "SC-8"},
    {"id": "zig-act-p2-16", "capability_id": "zig-net-04", "phase": "phase2",
     "title": "Enable SDN-driven policy enforcement",
     "description": "Use SDN controller for centralized, dynamic network policy enforcement.",
     "nist_control_ref": "SC-7"},
    {"id": "zig-act-p2-17", "capability_id": "zig-net-03", "phase": "phase2",
     "title": "Automate lateral movement detection and containment",
     "description": "Deploy automated network containment policies that activate on lateral movement detection.",
     "nist_control_ref": "IR-4"},
    {"id": "zig-act-p2-18", "capability_id": "zig-net-04", "phase": "phase2",
     "title": "Implement dynamic risk-based network policy adjustment",
     "description": "Network policies adapt based on real-time risk score changes (device health, user risk).",
     "nist_control_ref": "CA-7"},
    # Application (5)
    {"id": "zig-act-p2-19", "capability_id": "zig-app-04", "phase": "phase2",
     "title": "Implement context-based access control for applications",
     "description": "Grant application access based on user+device+network+time context.",
     "nist_control_ref": "AC-3"},
    {"id": "zig-act-p2-20", "capability_id": "zig-app-05", "phase": "phase2",
     "title": "Deploy continuous application security monitoring",
     "description": "Real-time RASP and API security monitoring in production applications.",
     "nist_control_ref": "SI-4"},
    {"id": "zig-act-p2-21", "capability_id": "zig-app-03", "phase": "phase2",
     "title": "Implement DAST and runtime testing gates",
     "description": "Add dynamic application security testing to CI/CD; block on high-severity findings.",
     "nist_control_ref": "SA-11"},
    {"id": "zig-act-p2-22", "capability_id": "zig-app-04", "phase": "phase2",
     "title": "Integrate behavioral analytics into application authorization",
     "description": "Feed application usage anomalies into authorization engine; revoke on risk trigger.",
     "nist_control_ref": "AU-6"},
    {"id": "zig-act-p2-23", "capability_id": "zig-app-05", "phase": "phase2",
     "title": "Achieve automated ongoing authorization for all applications",
     "description": "Eliminate time-based ATO; replace with continuous authorization tied to risk posture.",
     "nist_control_ref": "CA-7"},
    # Data (6)
    {"id": "zig-act-p2-24", "capability_id": "zig-dat-03", "phase": "phase2",
     "title": "Extend automated data labeling to all data stores",
     "description": "Deploy ML-assisted data classification across all repositories; target >90% coverage.",
     "nist_control_ref": "MP-3"},
    {"id": "zig-act-p2-25", "capability_id": "zig-dat-04", "phase": "phase2",
     "title": "Implement DRM for controlled sensitive data sharing",
     "description": "Apply digital rights management to CUI documents; enforce expiration and revocation.",
     "nist_control_ref": "SC-13"},
    {"id": "zig-act-p2-26", "capability_id": "zig-dat-06", "phase": "phase2",
     "title": "Deploy DLP in prevention mode across all egress points",
     "description": "Transition DLP from monitor-only to active prevention on all data egress paths.",
     "nist_control_ref": "SC-7"},
    {"id": "zig-act-p2-27", "capability_id": "zig-dat-04", "phase": "phase2",
     "title": "Integrate data access logs into SIEM for behavioral analysis",
     "description": "Feed all data access metadata into SIEM; enable UEBA on data access patterns.",
     "nist_control_ref": "AU-6"},
    {"id": "zig-act-p2-28", "capability_id": "zig-dat-07", "phase": "phase2",
     "title": "Implement dynamic, risk-based data access controls",
     "description": "Access decisions for sensitive data incorporate real-time risk score of requestor.",
     "nist_control_ref": "AC-16"},
    {"id": "zig-act-p2-29", "capability_id": "zig-dat-06", "phase": "phase2",
     "title": "Achieve encrypt-in-use for highest-sensitivity data",
     "description": "Deploy confidential computing or homomorphic encryption for top-secret data processing.",
     "nist_control_ref": "SC-28"},
    # Visibility (6)
    {"id": "zig-act-p2-30", "capability_id": "zig-vis-04", "phase": "phase2",
     "title": "Deploy UEBA with ML-driven baseline modeling",
     "description": "Implement UEBA with machine learning baselines for all users and service accounts.",
     "nist_control_ref": "SI-4"},
    {"id": "zig-act-p2-31", "capability_id": "zig-vis-05", "phase": "phase2",
     "title": "Integrate commercial threat intelligence feeds into SIEM",
     "description": "Ingest STIX/TAXII threat intel; auto-correlate IOCs with internal telemetry.",
     "nist_control_ref": "SI-5"},
    {"id": "zig-act-p2-32", "capability_id": "zig-vis-06", "phase": "phase2",
     "title": "Implement automated threat response playbooks",
     "description": "Deploy SOAR playbooks that auto-execute containment actions on high-confidence detections.",
     "nist_control_ref": "IR-4"},
    {"id": "zig-act-p2-33", "capability_id": "zig-vis-04", "phase": "phase2",
     "title": "Enable cross-pillar behavioral correlation",
     "description": "Correlate user, device, network, and application behavioral signals for holistic risk.",
     "nist_control_ref": "CA-7"},
    {"id": "zig-act-p2-34", "capability_id": "zig-vis-06", "phase": "phase2",
     "title": "Implement risk-adaptive access policy engine",
     "description": "Policy engine dynamically adjusts access controls based on real-time risk scores.",
     "nist_control_ref": "AC-2"},
    {"id": "zig-act-p2-35", "capability_id": "zig-vis-05", "phase": "phase2",
     "title": "Achieve SOC-wide threat hunting capability",
     "description": "Enable proactive threat hunting using SIEM + UEBA + threat intel for unknown threats.",
     "nist_control_ref": "IR-5"},
    # Automation (6)
    {"id": "zig-act-p2-36", "capability_id": "zig-aut-03", "phase": "phase2",
     "title": "Deploy AI-assisted threat detection",
     "description": "Integrate ML models for anomaly detection beyond rule-based SIEM capabilities.",
     "nist_control_ref": "SI-4"},
    {"id": "zig-act-p2-37", "capability_id": "zig-aut-04", "phase": "phase2",
     "title": "Implement ML-based access decision support",
     "description": "Use predictive models to recommend access decisions; maintain human oversight.",
     "nist_control_ref": "AC-3"},
    {"id": "zig-act-p2-38", "capability_id": "zig-aut-05", "phase": "phase2",
     "title": "Deploy SOAR with automated incident response playbooks",
     "description": "Implement full SOAR platform; automate response for common incident categories.",
     "nist_control_ref": "IR-4"},
    {"id": "zig-act-p2-39", "capability_id": "zig-aut-05", "phase": "phase2",
     "title": "Integrate SOAR with all security tool ecosystem",
     "description": "Connect SOAR to SIEM, EDR, IAM, firewall, and CMDB for bidirectional orchestration.",
     "nist_control_ref": "IR-5"},
    {"id": "zig-act-p2-40", "capability_id": "zig-aut-06", "phase": "phase2",
     "title": "Standardize security data exchange with STIX/TAXII/OpenC2",
     "description": "Adopt standard threat intelligence and response formats across all security tools.",
     "nist_control_ref": "SA-8"},
    {"id": "zig-act-p2-41", "capability_id": "zig-aut-06", "phase": "phase2",
     "title": "Implement self-evaluating automation with feedback loops",
     "description": "Automation systems continuously assess their own effectiveness; self-tune parameters.",
     "nist_control_ref": "CA-7"},
]

# FY compliance deadlines
ZIG_FY2027_DEADLINE = "2027-09-30"
ZIG_FY2032_DEADLINE = "2032-09-30"

_S = "https://icdev.dev/ontology/security#"

SECURITY_ONTOLOGY_MAP: dict[str, str] = {
    # Assets
    "asset-server":             f"{_S}Asset.Server",
    "asset-database":           f"{_S}Asset.Database",
    "asset-client":             f"{_S}Asset.Client",
    "asset-storage":            f"{_S}Asset.Storage",
    "asset-network":            f"{_S}Asset.Network",
    "asset-container":          f"{_S}Asset.Container",
    "asset-lambda":             f"{_S}Asset.Lambda",
    "asset-registry":           f"{_S}Asset.Registry",
    "asset-vdi-host":           f"{_S}Asset.VDIHost",
    "asset-thin-client":        f"{_S}Asset.ThinClient",
    "asset-profile-store":      f"{_S}Asset.ProfileStore",
    # Controls
    "ctrl-firewall":            f"{_S}Control.Firewall",
    "ctrl-idp":                 f"{_S}Control.IDP",
    "ctrl-kms":                 f"{_S}Control.KMS",
    "ctrl-siem":                f"{_S}Control.SIEM",
    "ctrl-ids":                 f"{_S}Control.IDS",
    "ctrl-pam":                 f"{_S}Control.PAM",
    "ctrl-scanner":             f"{_S}Control.Scanner",
    "ctrl-encryption":          f"{_S}Control.Encryption",
    "ctrl-session-policy":      f"{_S}Control.SessionPolicy",
    "ctrl-vdi-gateway":         f"{_S}Control.VDIGateway",
    "ctrl-image-hardening":     f"{_S}Control.ImageHardening",
    # Threats
    "threat-actor":             f"{_S}Threat.Actor",
    "threat-malware":           f"{_S}Threat.Malware",
    "threat-phishing":          f"{_S}Threat.Phishing",
    "threat-exploit":           f"{_S}Threat.Exploit",
    "threat-dos":               f"{_S}Threat.DoS",
    "threat-supply":            f"{_S}Threat.SupplyChain",
    "threat-insider":           f"{_S}Threat.Insider",
    "threat-session-hijack":    f"{_S}Threat.SessionHijack",
    "threat-clipboard-exfil":   f"{_S}Threat.ClipboardExfil",
    "threat-gpu-escape":        f"{_S}Threat.GPUEscape",
    "threat-profile-tampering": f"{_S}Threat.ProfileTampering",
}

# ── ZIG External Evidence Mapping ─────────────────────────────────────────────
# Maps ingest source finding types → ZIG activity IDs for automated completion.

ZIG_EVIDENCE_MAP = {
    "sbom": {
        "cve_critical":       "zig-act-d08",   # Generate initial SBOM for critical apps
        "cve_high":           "zig-act-d08",
        "outdated_dep":       "zig-act-p1-21",  # Integrate SAST/SCA into CI/CD
        "no_sbom":            "zig-act-d08",
        "risky_license":      "zig-act-p1-22",  # Enforce code signing
    },
    "sast": {
        "B105": "zig-act-p1-29",  # hardcoded password → encryption at rest
        "B106": "zig-act-p1-29",  # hardcoded password in funcarg
        "B502": "zig-act-p1-18",  # TLS version → encrypt all traffic in transit
        "B503": "zig-act-p1-18",  # TLS with bad ciphers
        "B608": "zig-act-p1-21",  # SQL injection → SAST/SCA in CI/CD
        "B601": "zig-act-p1-21",  # paramiko shell injection
        "B602": "zig-act-p1-21",  # subprocess shell=True
        "B701": "zig-act-p2-21",  # jinja2 autoescape off → DAST/runtime testing
    },
    "survey": {
        "mfa":          "zig-act-p1-02",  # Extend MFA to all standard user accounts
        "mfa_admin":    "zig-act-p1-01",  # Deploy MFA for privileged accounts
        "rbac":         "zig-act-p1-07",  # Define and implement RBAC policies
        "pam":          "zig-act-p1-03",  # Deploy PAM solution
        "least_priv":   "zig-act-p1-04",  # Enforce least privilege
        "lifecycle":    "zig-act-p1-06",  # Automated account lifecycle management
    },
    "nmap": {
        "http_without_https": "zig-act-p1-18",  # Encrypt all traffic in transit
        "admin_ports_open":   "zig-act-p1-16",  # Macro-segmentation between business units
        "no_tls_on_api":      "zig-act-p2-15",  # Service mesh with mTLS enforcement
        "ssh_exposed":        "zig-act-p1-20",  # Restrict third-party access
        "rdp_exposed":        "zig-act-p1-20",
    },
    "openapi": {
        "no_security_scheme": "zig-act-p2-19",  # Context-based access control for apps
        "http_only":          "zig-act-p1-18",  # Encrypt all traffic in transit
        "no_oauth":           "zig-act-p2-03",  # ABAC with dynamic attribute evaluation
        "bearer_no_tls":      "zig-act-p1-18",
    },
}

ZIG_EXTERNAL_APP_TYPES = [
    {"slug": "web-app",        "label": "Web Application",       "icon": "globe"},
    {"slug": "microservice",   "label": "Microservice",          "icon": "cpu"},
    {"slug": "cloud-native",   "label": "Cloud-Native App",      "icon": "cloud"},
    {"slug": "container",      "label": "Container Workload",    "icon": "box"},
    {"slug": "api",            "label": "API / Service Mesh",    "icon": "zap"},
    {"slug": "legacy",         "label": "Legacy System",         "icon": "server"},
    {"slug": "data-pipeline",  "label": "Data Pipeline",         "icon": "database"},
    {"slug": "ml-model",       "label": "ML / AI Model",         "icon": "brain"},
    {"slug": "general",        "label": "General",               "icon": "shield"},
]

ZIG_INGEST_SOURCE_TYPES = [
    {"slug": "sbom",    "label": "SBOM (CycloneDX JSON)",  "icon": "package", "ext": ".json"},
    {"slug": "sast",    "label": "SAST (Bandit JSON)",     "icon": "code",    "ext": ".json"},
    {"slug": "survey",  "label": "Security Survey (JSON)", "icon": "clipboard", "ext": ".json"},
    {"slug": "nmap",    "label": "Nmap Scan (XML)",        "icon": "scan",    "ext": ".xml"},
    {"slug": "openapi", "label": "OpenAPI Spec (YAML/JSON)", "icon": "api",   "ext": ".yaml"},
]

# Maximum accepted ingest payload size (bytes). Enforced at the route level
# (zig_api_target_ingest) with an HTTP 413 before any parsing runs, to bound
# memory/CPU for external scan uploads (nmap XML, CycloneDX SBOM, SAST JSON,
# survey, OpenAPI). 5 MiB comfortably fits real scan outputs.
ZIG_INGEST_MAX_BYTES = 5 * 1024 * 1024
