#!/usr/bin/env python3
# CUI // SP-CTI
"""Escalation Workflow — auto-create GitHub/GitLab issues for escalated findings (D-RB-14).

Escalated findings (confidence < 0.3 or not auto-fixable critical/high) are
automatically created as issues in the project's VCS for human follow-up.

Usage:
    python tools/review_board/escalation.py --run --json
    python tools/review_board/escalation.py --run --dry-run --json
    python tools/review_board/escalation.py --pending --json
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

BASE_DIR = Path(__file__).resolve().parent.parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from tools.db.storage import get_connection as _raw_get_connection  # noqa: E402
from tools.logging.icdev_logger import get_logger

logger = get_logger("icdev.review_board.escalation")


def _get_connection():
    conn = _raw_get_connection()
    try:
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA busy_timeout=30000")
    except Exception:
        pass
    return conn


def get_escalatable_findings() -> List[Dict]:
    """Get high/critical findings that haven't been escalated yet."""
    conn = _get_connection()
    try:
        rows = conn.execute(
            "SELECT f.* FROM review_board_findings f "
            "WHERE f.severity IN ('critical', 'high') "
            "AND f.fix_applied = 0 "
            "AND f.auto_fixable = 0 "
            "AND NOT EXISTS ("
            "  SELECT 1 FROM review_board_remediation_log r "
            "  WHERE r.finding_id = f.id AND r.tier = 'escalate'"
            ") "
            "ORDER BY "
            "  CASE f.severity WHEN 'critical' THEN 1 ELSE 2 END, "
            "  f.created_at"
        ).fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []
    finally:
        conn.close()


def escalate_to_issue(finding: Dict, dry_run: bool = False) -> Dict[str, Any]:
    """Create a GitHub/GitLab issue for an escalated finding."""
    title = f"[Review Board] [{finding['severity'].upper()}] {finding['title']}"
    body_parts = [
        "## Review Board Finding",
        "",
        f"**Severity:** {finding['severity'].upper()}",
        f"**Persona:** {finding.get('reflex_name', 'unknown').upper()}",
        f"**Category:** {finding.get('category', 'general')}",
        f"**Confidence:** {finding.get('confidence', 0):.0%}",
        f"**Found:** {finding.get('created_at', 'unknown')}",
        "",
        "### Description",
        f"{finding.get('description') or finding.get('title', 'No description')}",
        "",
    ]
    if finding.get("recommendation"):
        body_parts.extend(
            [
                "### Recommendation",
                f"{finding['recommendation']}",
                "",
            ]
        )
    body_parts.extend(
        [
            "---",
            "*Auto-generated by ICDEV™ Engineering Review Board*",
        ]
    )
    body = "\n".join(body_parts)

    if dry_run:
        return {
            "status": "dry_run",
            "title": title,
            "body_preview": body[:300],
        }

    # Try GitHub first, then GitLab
    issue_url = None
    try:
        result = subprocess.run(
            ["gh", "issue", "create", "--title", title, "--body", body, "--label", "review-board,auto-generated"],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=str(BASE_DIR),
            stdin=subprocess.DEVNULL,
        )
        if result.returncode == 0 and result.stdout.strip():
            issue_url = result.stdout.strip()
    except Exception:
        pass

    if not issue_url:
        try:
            result = subprocess.run(
                [
                    "glab",
                    "issue",
                    "create",
                    "--title",
                    title,
                    "--description",
                    body,
                    "--label",
                    "review-board,auto-generated",
                ],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(BASE_DIR),
                stdin=subprocess.DEVNULL,
            )
            if result.returncode == 0 and result.stdout.strip():
                issue_url = result.stdout.strip()
        except Exception:
            pass

    if issue_url:
        # Record escalation in remediation log
        _log_escalation(finding, issue_url)
        return {"status": "created", "issue_url": issue_url, "title": title}

    return {"status": "failed", "reason": "Neither gh nor glab CLI available"}


def _log_escalation(finding: Dict, issue_url: str) -> None:
    """Record escalation in remediation log."""
    import uuid

    conn = _get_connection()
    try:
        from datetime import datetime, timezone

        conn.execute(
            "INSERT INTO review_board_remediation_log "
            "(id, finding_id, reflex_name, category, severity, confidence, "
            "tier, status, fix_description, fix_result, created_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, 'escalate', 'escalated', %s, %s, %s)",
            (
                f"rbr-{uuid.uuid4().hex[:10]}",
                finding.get("id", ""),
                finding.get("reflex_name", ""),
                finding.get("category", ""),
                finding.get("severity", ""),
                finding.get("confidence", 0.0),
                f"Escalated to issue: {issue_url}",
                json.dumps({"issue_url": issue_url}),
                datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            ),
        )
        conn.commit()
    except Exception as exc:  # noqa: BLE001 - best-effort persistence; logged, never raised
        logger.warning(
            "_log_escalation: best-effort INSERT into review_board_remediation_log failed (non-blocking): %s",
            exc,
        )
    finally:
        conn.close()


def run_escalation(dry_run: bool = False) -> Dict[str, Any]:
    """Run escalation on all eligible findings."""
    findings = get_escalatable_findings()
    results = {"total": len(findings), "created": 0, "failed": 0, "details": []}

    for finding in findings[:5]:  # Max 5 issues per run
        result = escalate_to_issue(finding, dry_run=dry_run)
        results["details"].append(result)
        if result.get("status") == "created":
            results["created"] += 1
        elif result.get("status") == "failed":
            results["failed"] += 1

    return results


def main():
    parser = argparse.ArgumentParser(description="Review Board Escalation (D-RB-14)")
    parser.add_argument("--run", action="store_true", help="Escalate pending findings to issues")
    parser.add_argument("--dry-run", action="store_true", help="Preview without creating issues")
    parser.add_argument("--pending", action="store_true", help="List findings eligible for escalation")
    parser.add_argument("--json", action="store_true", help="JSON output")
    args = parser.parse_args()

    if args.run:
        result = run_escalation(dry_run=args.dry_run)
        print(
            json.dumps(result, indent=2) if args.json else f"Escalated: {result['created']}, Failed: {result['failed']}"
        )
    elif args.pending:
        findings = get_escalatable_findings()
        if args.json:
            print(json.dumps({"pending": findings, "count": len(findings)}, indent=2))
        else:
            for f in findings:
                print(f"  [{f['severity']}] {f['reflex_name']}: {f['title']}")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
