# CUI // SP-CTI
"""
Session checkpoint store for agent loop resumption and distributed tracing.

Persists message checkpoints to the agent_loop_checkpoints table so that
run_agent_loop(resume_session_id=...) can replay from a prior turn rather
than starting fresh.  Also stores parent_session_id for distributed tracing.

Table: agent_loop_checkpoints
  session_id        TEXT PK  (agent loop session UUID)
  parent_session_id TEXT     (empty string when no parent — top-level session)
  turn_number       INTEGER  (last completed turn index)
  messages_json     TEXT     (json.dumps(messages) at end of this turn)
  model_id          TEXT
  provider          TEXT
  input_tokens      INTEGER
  output_tokens     INTEGER
  cost_usd          REAL
  updated_at        TEXT     (ISO-8601 UTC)

All public functions are non-fatal: DB errors are logged at WARNING level and
the function returns None / [] so the agent loop never crashes on storage
failures.  Checkpoint persistence is best-effort; the loop remains correct
without it — it just cannot resume from a prior turn.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from tools.logging.icdev_logger import get_logger

logger = get_logger(__name__)

_TABLE = "agent_loop_checkpoints"


def _conn():
    """Return a DB connection using the canonical ICDEV storage layer."""
    from icdev.tools.db.storage import get_connection
    return get_connection()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def save_checkpoint(
    session_id: str,
    turn_number: int,
    messages: list[dict[str, Any]],
    *,
    parent_session_id: str = "",
    model_id: str = "",
    provider: str = "",
    input_tokens: int = 0,
    output_tokens: int = 0,
    cost_usd: float = 0.0,
) -> None:
    """Upsert a turn checkpoint for *session_id*.

    Called at the end of each agent loop turn so that if the process crashes
    or the session is abandoned, resumption can replay from the last saved
    state instead of restarting from scratch.

    Args:
        session_id:        UUID generated by :func:`run_agent_loop` at loop start.
        turn_number:       Index of the just-completed turn (0-based).
        messages:          Full message history at the end of this turn.
        parent_session_id: Session ID of the parent agent that spawned this one;
                           empty string for top-level sessions.
        model_id:          Model that produced the last response.
        provider:          Provider name (e.g. ``"anthropic"``, ``"openai"``).
        input_tokens:      Cumulative input tokens so far.
        output_tokens:     Cumulative output tokens so far.
        cost_usd:          Cumulative cost in USD so far.
    """
    now = datetime.now(timezone.utc).isoformat()
    messages_json = json.dumps(messages, ensure_ascii=False)
    try:
        conn = _conn()
        with conn:
            conn.execute(
                f"""
                INSERT INTO {_TABLE}
                  (session_id, parent_session_id, turn_number, messages_json,
                   model_id, provider, input_tokens, output_tokens, cost_usd, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (session_id) DO UPDATE SET
                  parent_session_id = EXCLUDED.parent_session_id,
                  turn_number       = EXCLUDED.turn_number,
                  messages_json     = EXCLUDED.messages_json,
                  model_id          = EXCLUDED.model_id,
                  provider          = EXCLUDED.provider,
                  input_tokens      = EXCLUDED.input_tokens,
                  output_tokens     = EXCLUDED.output_tokens,
                  cost_usd          = EXCLUDED.cost_usd,
                  updated_at        = EXCLUDED.updated_at
                """,
                (
                    session_id, parent_session_id, turn_number, messages_json,
                    model_id, provider, input_tokens, output_tokens, cost_usd, now,
                ),
            )
    except Exception:
        logger.warning(
            "session_store: failed to save checkpoint %s turn=%d (non-fatal)",
            session_id, turn_number, exc_info=True,
        )


def load_checkpoint(session_id: str) -> dict[str, Any] | None:
    """Return the latest checkpoint for *session_id*, or ``None`` if not found.

    Returned dict keys:
        messages (list[dict]):   Full message history from the last saved turn.
        turn_number (int):       Index of the last completed turn.
        parent_session_id (str): Parent session UUID, or empty string.
        model_id (str):          Model that ran the last turn.
        provider (str):          Provider name.
        input_tokens (int):      Cumulative input tokens at checkpoint.
        output_tokens (int):     Cumulative output tokens at checkpoint.
        cost_usd (float):        Cumulative cost at checkpoint.
    """
    try:
        conn = _conn()
        cur = conn.execute(
            f"""
            SELECT messages_json, turn_number, parent_session_id,
                   model_id, provider, input_tokens, output_tokens, cost_usd
            FROM {_TABLE}
            WHERE session_id = %s
            """,
            (session_id,),
        )
        row = cur.fetchone()
        if row is None:
            return None
        (
            messages_json, turn_number, parent_session_id,
            model_id, provider, input_tokens, output_tokens, cost_usd,
        ) = row
        return {
            "messages":          json.loads(messages_json or "[]"),
            "turn_number":       int(turn_number or 0),
            "parent_session_id": parent_session_id or "",
            "model_id":          model_id or "",
            "provider":          provider or "",
            "input_tokens":      int(input_tokens or 0),
            "output_tokens":     int(output_tokens or 0),
            "cost_usd":          float(cost_usd or 0.0),
        }
    except Exception:
        logger.warning(
            "session_store: failed to load checkpoint %s (non-fatal)",
            session_id, exc_info=True,
        )
        return None


def delete_checkpoint(session_id: str) -> None:
    """Remove the checkpoint for *session_id*.

    Call after a successful loop completion so stale checkpoints do not
    accumulate.  Non-fatal: DB errors are silently logged.
    """
    try:
        conn = _conn()
        with conn:
            conn.execute(
                f"DELETE FROM {_TABLE} WHERE session_id = %s",
                (session_id,),
            )
    except Exception:
        logger.debug(
            "session_store: delete checkpoint %s failed (non-fatal)",
            session_id, exc_info=True,
        )


def list_checkpoints(limit: int = 50) -> list[dict[str, Any]]:
    """Return recent checkpoints ordered by *updated_at* descending.

    Intended for ops dashboards and debug tooling, not the hot path.
    Returns an empty list on any DB error.
    """
    try:
        conn = _conn()
        cur = conn.execute(
            f"""
            SELECT session_id, parent_session_id, turn_number, model_id,
                   provider, input_tokens, output_tokens, cost_usd, updated_at
            FROM {_TABLE}
            ORDER BY updated_at DESC
            LIMIT %s
            """,
            (limit,),
        )
        rows = cur.fetchall()
        keys = [
            "session_id", "parent_session_id", "turn_number", "model_id",
            "provider", "input_tokens", "output_tokens", "cost_usd", "updated_at",
        ]
        return [dict(zip(keys, row)) for row in rows]
    except Exception:
        logger.warning("session_store: list_checkpoints failed (non-fatal)", exc_info=True)
        return []
