#!/usr/bin/env python3
# [TEMPLATE: CUI // SP-CTI]
"""Provider Scaffold — add a new LLM provider in one command.

Usage:
    python tools/llm/provider_scaffold.py --name cohere --type openai_compatible --api_key_env COHERE_API_KEY --base_url https://api.cohere.com/v1 --model_id command-r

    # Interactive mode (no args)
    python tools/llm/provider_scaffold.py

What it does:
    1. Validates inputs
    2. Generates a provider module (custom type only)
    3. Patches router.py _get_provider() factory (custom type only)
    4. Appends provider + model entries to args/llm_config.yaml
    5. Optionally adds the model to a routing chain
    6. Syncs new module to root tools/llm/ (custom type only)
    7. Runs live check_availability() + invoke() test
    8. Runs ruff check
    9. Prints a summary

Types:
    openai_compatible  -> reuses OpenAICompatibleProvider (no new module)
    ollama             -> reuses OllamaProvider (no new module)
    custom             -> generates a full provider class + patches router
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

try:
    import yaml
except ImportError:
    yaml = None

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ICDEV_PKG = REPO_ROOT / "icdev" / "tools" / "llm"
ROOT_TOOLS = REPO_ROOT / "tools" / "llm"
CONFIG_PATH = REPO_ROOT / "args" / "llm_config.yaml"
ROUTER_PATH = ICDEV_PKG / "router.py"

# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------

TYPES = ["openai_compatible", "ollama", "custom"]


def _prompt(text: str, default: str = "") -> str:
    if default:
        out = input(f"{text} [{default}]: ").strip()
        return out if out else default
    return input(f"{text}: ").strip()


def _prompt_choose(text: str, choices: list[str], default: str = "") -> str:
    while True:
        out = _prompt(f"{text} ({', '.join(choices)})", default)
        if out in choices:
            return out
        print(f"  Invalid choice. Must be one of: {', '.join(choices)}")


def _prompt_bool(text: str, default: bool = False) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    out = input(f"{text}{suffix}: ").strip().lower()
    if not out:
        return default
    return out.startswith("y")


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _validate_name(name: str) -> str:
    name = name.strip().lower()
    if not re.match(r"^[a-z][a-z0-9_]*$", name):
        raise ValueError("Provider name must be lowercase a-z, 0-9, underscores. First char must be a-z.")
    return name


def _load_config() -> dict:
    if yaml is None:
        raise RuntimeError("PyYAML required: pip install pyyaml")
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _save_config(cfg: dict) -> None:
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _insert_yaml_block(section_name: str, block_text: str) -> None:
    """Insert a block into a YAML section while preserving comments and order.

    Finds the *section_name* top-level key, then inserts *block_text*
    immediately before the next top-level key (or at end of file).
    """
    lines = CONFIG_PATH.read_text(encoding="utf-8").splitlines(keepends=True)
    in_section = False
    insert_idx = len(lines)
    for i, line in enumerate(lines):
        if not in_section:
            if line.strip().startswith(section_name + ":"):
                in_section = True
            continue
        # Inside section; look for next top-level key (no leading spaces)
        if line and not line.startswith(" ") and not line.startswith("#"):
            insert_idx = i
            break
    lines.insert(insert_idx, block_text)
    CONFIG_PATH.write_text("".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Module generation (custom type only)
# ---------------------------------------------------------------------------

_CUSTOM_PROVIDER_TEMPLATE = '''\
# [TEMPLATE: CUI // SP-CTI]
"""{class_name} LLM Provider.

Auto-generated by provider_scaffold.py for provider "{provider_name}".
"""

import json
import time
from typing import Any, Dict

from tools.llm.provider import LLMProvider, LLMRequest, LLMResponse


class {class_name}(LLMProvider):
    """Custom provider for {provider_name}."""

    def __init__(self, api_key: str = "", base_url: str = ""):
        self._api_key = api_key
        self._base_url = base_url.rstrip("/") if base_url else ""

    @property
    def provider_name(self) -> str:
        return "{provider_name}"

    def invoke(self, request: LLMRequest, model_id: str, model_config: dict) -> LLMResponse:
        start_time = time.time()
        # TODO: implement vendor-specific API call
        # Example placeholder — replace with real integration:
        content = f"[{{self.provider_name}} placeholder response for model {{model_id}}]"
        return LLMResponse(
            content=content,
            provider=self.provider_name,
            model_id=model_id,
            duration_ms=int((time.time() - start_time) * 1000),
        )

    def check_availability(self, model_id: str) -> bool:
        # TODO: implement health check (e.g. GET /health or list models)
        return bool(self._api_key) or bool(self._base_url)
'''


def _generate_custom_module(provider_name: str, class_name: str, module_path: Path) -> None:
    code = _CUSTOM_PROVIDER_TEMPLATE.format(
        class_name=class_name,
        provider_name=provider_name,
    )
    module_path.write_text(code, encoding="utf-8")
    print(f"  Generated {module_path}")


# ---------------------------------------------------------------------------
# Router patching (custom type only)
# ---------------------------------------------------------------------------

def _patch_router(provider_name: str, class_name: str, module_file: str, ptype: str) -> None:
    """Insert a new elif branch into _get_provider()."""
    router_text = ROUTER_PATH.read_text(encoding="utf-8")

    # Check if already present
    if f'ptype == "{ptype}"' in router_text or f'ptype == "{provider_name}"' in router_text:
        print(f"  Router already has branch for {ptype}/{provider_name} — skipping patch")
        return

    # Build the new elif block
    block = f'''
            elif ptype == "{ptype}":
                from tools.llm.{module_file} import {class_name}

                api_key = self._get_byok_key(user_id, provider_name)
                if not api_key:
                    api_key = _expand_env(provider_cfg.get("api_key", ""))
                    if not api_key:
                        api_key_env = provider_cfg.get("api_key_env", "")
                        if api_key_env:
                            api_key = os.environ.get(api_key_env, "")
                base_url = _expand_env(provider_cfg.get("base_url", ""))
                instance = {class_name}(api_key=api_key, base_url=base_url)
'''

    # Insert before the final `else:` in the try block
    # Look for the pattern:            else:
    #                                logger.warning("Unknown provider type: %s", ptype)
    pattern = r'(\n            else:\n                logger\.warning\("Unknown provider type: %s", ptype\)\n                return None)'
    match = re.search(pattern, router_text)
    if not match:
        # Fallback: look for generic else block near end of try
        pattern2 = r'(\n            else:\n                logger\.warning\("Unknown provider type)'
        match = re.search(pattern2, router_text)

    if not match:
        raise RuntimeError("Could not find insertion point in router.py — manual patch required")

    insert_pos = match.start()
    new_router = router_text[:insert_pos] + block + router_text[insert_pos:]
    ROUTER_PATH.write_text(new_router, encoding="utf-8")
    print(f"  Patched {ROUTER_PATH}")


# ---------------------------------------------------------------------------
# Config patching
# ---------------------------------------------------------------------------

def _patch_config(
    provider_name: str,
    ptype: str,
    api_key_env: str,
    base_url: str,
    model_id: str,
    chain_function: Optional[str] = None,
) -> None:
    cfg = _load_config()

    providers = cfg.get("providers", {})
    if provider_name not in providers:
        block_lines = [f"  {provider_name}:\n", f"    type: {ptype}\n"]
        if api_key_env:
            block_lines.append(f"    api_key_env: {api_key_env}\n")
        if base_url:
            block_lines.append(f"    base_url: {base_url}\n")
        block_lines.append("\n")
        _insert_yaml_block("providers", "".join(block_lines))
        print("  Inserted provider block into 'providers:'")
    else:
        print(f"  Provider '{provider_name}' already exists in config -- skipping provider block")

    models = cfg.get("models", {})
    model_name = model_id.split(":")[0].split("/")[-1].replace("-", "_").replace(".", "_")
    original_model_name = model_name
    counter = 1
    while model_name in models:
        model_name = f"{original_model_name}_{counter}"
        counter += 1

    if model_name not in models:
        block_lines = [
            f"  {model_name}:\n",
            f"    provider: {provider_name}\n",
            f'    model_id: "{model_id}"\n',
            "    max_output_tokens: 4096\n",
            "    supports_thinking: false\n",
            "    supports_tools: false\n",
            "    supports_structured_output: false\n",
            "    pricing: {input_per_1k: 0.0, output_per_1k: 0.0}\n",
            "\n",
        ]
        _insert_yaml_block("models", "".join(block_lines))
        print("  Inserted model block into 'models:'")
    else:
        print(f"  Model '{model_name}' already exists -- skipping model block")

    if chain_function:
        cfg = _load_config()
        routing = cfg.setdefault("routing", {})
        route = routing.setdefault(chain_function, {})
        chain = route.setdefault("chain", [])
        if model_name not in chain:
            chain.append(model_name)
            _save_config(cfg)
            print(f"  Added '{model_name}' to routing chain for '{chain_function}'")

    print(f"  Updated {CONFIG_PATH}")
    return model_name


# ---------------------------------------------------------------------------
# Root sync (custom type only)
# ---------------------------------------------------------------------------

def _sync_to_root(module_path: Path) -> None:
    dest = ROOT_TOOLS / module_path.name
    shutil.copy2(module_path, dest)
    print(f"  Synced {module_path.name} to root tools/llm/")


# ---------------------------------------------------------------------------
# Live test
# ---------------------------------------------------------------------------

def _run_live_test(model_name: str, user_id: str = "") -> bool:
    print(f"\n  Live test: probing '{model_name}' ...")
    try:
        # Import via icdev namespace
        sys.path.insert(0, str(REPO_ROOT))
        from icdev.tools.llm.router import LLMRouter
        from icdev.tools.llm.provider import LLMRequest

        router = LLMRouter()
        model_cfg = router._get_model_config(model_name)
        if not model_cfg:
            print(f"    FAIL: model '{model_name}' not found in router config")
            return False

        provider_name = model_cfg.get("provider", "")
        provider = router._get_provider(provider_name, user_id=user_id)
        if provider is None:
            print(f"    FAIL: provider '{provider_name}' could not be instantiated")
            return False

        model_id = model_cfg.get("model_id", "")
        avail = provider.check_availability(model_id)
        print(f"    check_availability('{model_id}') -> {avail}")
        if not avail:
            return False

        req = LLMRequest(messages=[{"role": "user", "content": "Say 'OK'"}])
        req.user_id = user_id
        resp = provider.invoke(req, model_id, model_cfg)
        content = getattr(resp, "content", "")
        print(f"    invoke() -> content length={len(content)} model_id={getattr(resp, 'model_id', '')}")
        if content:
            print("    PASS")
            return True
        print("    FAIL: empty response")
        return False
    except Exception as exc:
        print(f"    FAIL: {exc}")
        return False
    finally:
        try:
            sys.path.remove(str(REPO_ROOT))
        except ValueError:
            pass


# ---------------------------------------------------------------------------
# Ruff check
# ---------------------------------------------------------------------------

def _run_ruff(file_path: Path) -> bool:
    print(f"\n  Running ruff check on {file_path.name} ...")
    try:
        result = subprocess.run(
            [sys.executable, "-m", "ruff", "check", str(file_path)],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
            timeout=60,
        )
        if result.returncode == 0:
            print("    PASS")
            return True
        print(f"    FAIL:\n{result.stdout}\n{result.stderr}")
        return False
    except FileNotFoundError:
        print("    SKIP: ruff not installed")
        return True
    except Exception as exc:
        print(f"    FAIL: {exc}")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _interactive() -> argparse.Namespace:
    print("=" * 60)
    print("  ICDEV™ LLM Provider Scaffold")
    print("=" * 60)
    name = _validate_name(_prompt("Provider name (lowercase, no spaces)"))
    ptype = _prompt_choose("Provider type", TYPES, "openai_compatible")
    api_key_env = _prompt("API key env var (e.g. COHERE_API_KEY)", "")
    base_url = _prompt("Base URL", "")
    model_id = _prompt("Model ID", f"{name}-model")
    add_to_chain = _prompt_bool("Add to a routing chain?", False)
    chain_function = ""
    if add_to_chain:
        chain_function = _prompt("Function name (e.g. code_generation)", "chat_response")
    test = _prompt_bool("Run live test?", True)
    return argparse.Namespace(
        name=name,
        type=ptype,
        api_key_env=api_key_env,
        base_url=base_url,
        model_id=model_id,
        chain_function=chain_function or None,
        test=test,
        interactive=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Add a new LLM provider to ICDEV™")
    parser.add_argument("--name", required=False, help="Provider logical name (lowercase, no spaces)")
    parser.add_argument("--type", choices=TYPES, default="openai_compatible", help="Provider implementation type")
    parser.add_argument("--api_key_env", default="", help="Environment variable name for the API key")
    parser.add_argument("--base_url", default="", help="API base URL")
    parser.add_argument("--model_id", default="", help="Model identifier")
    parser.add_argument("--chain_function", default=None, help="Add model to this routing chain")
    parser.add_argument("--no-test", action="store_true", help="Skip live availability test")
    parser.add_argument("--no-ruff", action="store_true", help="Skip ruff lint check")
    args = parser.parse_args()

    if not args.name:
        args = _interactive()
    else:
        args.name = _validate_name(args.name)
        if not args.model_id:
            args.model_id = f"{args.name}-model"

    provider_name = args.name
    ptype = args.type
    api_key_env = args.api_key_env
    base_url = args.base_url
    model_id = args.model_id
    chain_function = args.chain_function
    do_test = not getattr(args, "no_test", False) and args.test
    do_ruff = not getattr(args, "no_ruff", False)

    print(f"\nScaffolding provider: {provider_name} (type={ptype})")
    print(f"  model_id={model_id} api_key_env={api_key_env or '(none)'} base_url={base_url or '(none)'}")

    # Custom type: generate module + patch router
    module_path: Optional[Path] = None
    if ptype == "custom":
        class_name = "".join(part.capitalize() for part in provider_name.split("_")) + "Provider"
        module_file = f"{provider_name}_provider.py"
        module_path = ICDEV_PKG / module_file
        _generate_custom_module(provider_name, class_name, module_path)
        _patch_router(provider_name, class_name, module_file.replace(".py", ""), ptype)
        _sync_to_root(module_path)
        if do_ruff:
            _run_ruff(module_path)
    else:
        print(f"  Type '{ptype}' reuses existing generic provider — no new module needed")

    # Patch config (all types)
    model_name = _patch_config(provider_name, ptype, api_key_env, base_url, model_id, chain_function)

    # Live test
    test_ok = False
    if do_test:
        test_ok = _run_live_test(model_name)

    # Summary
    print("\n" + "=" * 60)
    print("  SUMMARY")
    print("=" * 60)
    print(f"  Provider name : {provider_name}")
    print(f"  Type          : {ptype}")
    print(f"  Model config  : {model_name} -> {model_id}")
    if module_path:
        print(f"  Module        : {module_path.relative_to(REPO_ROOT)}")
        print(f"  Synced to     : root tools/llm/{module_path.name}")
    if chain_function:
        print(f"  Routing chain : added to '{chain_function}'")
    print(f"  Config file   : {CONFIG_PATH.relative_to(REPO_ROOT)}")
    if do_test:
        print(f"  Live test     : {'PASS' if test_ok else 'FAIL'}")
    print()
    print("  Next steps:")
    print(f"    1. Set your API key: export {api_key_env}=your_key")
    print("    2. Restart the dashboard so the new config is picked up")
    print("    3. Verify: python -c \"from icdev.tools.llm.router import LLMRouter; r=LLMRouter(); print(r.get_chain_for_function('chat_response'))\"")
    print()
    return 0 if (not do_test or test_ok) else 1


if __name__ == "__main__":
    sys.exit(main())
