#!/usr/bin/env python3
# CUI // SP-CTI
"""Generate Platform One / Iron Bank container hardening metadata.

Produces:
  - hardening_manifest.yaml  — IronBank Hardening Manifest v1.x
  - container_approval.json  — DoD Iron Bank approval status record
  - hardening_report.md      — Human-readable hardening summary

Iron Bank is the DoD's centralized repository of secure, hardened container
images. This generator produces the artifacts needed to submit containers for
Iron Bank approval and tracks approval status.

Architecture Decision D350: follows terraform_generator.py pattern.
Air-gap safe — stdlib only, no external requests.

Usage:
    python tools/infra/ironbank_metadata_generator.py --project-id proj-123 --generate --json
    python tools/infra/ironbank_metadata_generator.py --project-id proj-123 --validate --json
    python tools/infra/ironbank_metadata_generator.py --project-id proj-123 --report
"""

import argparse
import json
import sqlite3
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
DB_PATH = BASE_DIR / "data" / "icdev.db"

# ---------------------------------------------------------------------------
# Iron Bank base images — DoD-approved hardened base images
# ---------------------------------------------------------------------------
IRONBANK_BASE_IMAGES = {
    "python": {
        "registry": "registry1.dso.mil/ironbank/opensource/python",
        "tag": "3.11",
        "digest_placeholder": "sha256:<fetch-from-registry>",
        "os": "ubi9",
    },
    "java": {
        "registry": "registry1.dso.mil/ironbank/redhat/openjdk",
        "tag": "17",
        "digest_placeholder": "sha256:<fetch-from-registry>",
        "os": "ubi9",
    },
    "go": {
        "registry": "registry1.dso.mil/ironbank/opensource/go",
        "tag": "1.22",
        "digest_placeholder": "sha256:<fetch-from-registry>",
        "os": "ubi9",
    },
    "node": {
        "registry": "registry1.dso.mil/ironbank/opensource/nodejs/nodejs",
        "tag": "18",
        "digest_placeholder": "sha256:<fetch-from-registry>",
        "os": "ubi9",
    },
    "rust": {
        "registry": "registry1.dso.mil/ironbank/opensource/rust",
        "tag": "1.75",
        "digest_placeholder": "sha256:<fetch-from-registry>",
        "os": "ubi9",
    },
    "dotnet": {
        "registry": "registry1.dso.mil/ironbank/microsoft/dotnet/dotnet-aspnet",
        "tag": "8.0",
        "digest_placeholder": "sha256:<fetch-from-registry>",
        "os": "ubi9",
    },
    "base": {
        "registry": "registry1.dso.mil/ironbank/redhat/ubi/ubi9",
        "tag": "latest",
        "digest_placeholder": "sha256:<fetch-from-registry>",
        "os": "ubi9",
    },
}

# ---------------------------------------------------------------------------
# Hardening manifest template
# ---------------------------------------------------------------------------
HARDENING_MANIFEST_TEMPLATE = """\
# CUI // SP-CTI — Iron Bank Hardening Manifest
# Generated: {timestamp}
# Generator: ICDEV Iron Bank Metadata Generator (D350)
apiVersion: v1
name: "{project_name}"
tags:
  - "{project_name}:latest"
  - "{project_name}:{version}"
args: {{}}

labels:
  org.opencontainers.image.title: "{project_name}"
  org.opencontainers.image.description: "{description}"
  org.opencontainers.image.url: "https://repo1.dso.mil/{project_slug}"
  org.opencontainers.image.version: "{version}"
  org.opencontainers.image.licenses: "Government Purpose Rights"
  mil.dod.impact.level: "{impact_level}"
  mil.dod.classification: "{classification}"

image_author:
  name: "ICDEV Auto-Generator"
  email: "icdev@{project_slug}.mil"

base_image:
  name: "{base_image_registry}"
  tag: "{base_image_tag}"
  pin:
    digest: "{base_image_digest}"

resources: []

package_manager:
  type: {package_manager}

vulnerability_report:
  - url: "{vuln_scan_url}"
    description: "SBOM and vulnerability scan — generated by ICDEV sbom_generator.py"

justifications: []
"""


def _get_connection(db_path: Path = None) -> sqlite3.Connection:
    path = db_path or DB_PATH
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    return conn


def _detect_language(project_dir: str) -> str:
    """Detect primary language from project directory."""
    if not project_dir:
        return "base"
    pdir = Path(project_dir)
    if (pdir / "requirements.txt").exists() or list(pdir.glob("*.py")):
        return "python"
    if (pdir / "pom.xml").exists() or (pdir / "build.gradle").exists():
        return "java"
    if (pdir / "go.mod").exists():
        return "go"
    if (pdir / "package.json").exists():
        return "node"
    if (pdir / "Cargo.toml").exists():
        return "rust"
    if list(pdir.glob("*.csproj")):
        return "dotnet"
    return "base"


def _detect_package_manager(language: str) -> str:
    """Map language to package manager type."""
    mapping = {
        "python": "pip",
        "java": "maven",
        "go": "none",
        "node": "npm",
        "rust": "cargo",
        "dotnet": "nuget",
        "base": "none",
    }
    return mapping.get(language, "none")


def generate_hardening_manifest(
    project_id: str,
    project_dir: str = None,
    db_path: Path = None,
    output_dir: str = None,
) -> dict:
    """Generate Iron Bank hardening manifest YAML for a project.

    Args:
        project_id: Project UUID.
        project_dir: Project source directory (optional, used for language detection).
        db_path: Path to ICDEV database (optional).
        output_dir: Directory to write artifacts (optional).

    Returns:
        dict with manifest_yaml, approval_record, output_paths, metadata.
    """
    db = db_path or DB_PATH
    timestamp = datetime.now(timezone.utc).isoformat()

    # Fetch project info
    project_name = project_id
    description = "ICDEV-generated hardened container"
    impact_level = "IL4"
    classification = "CUI"
    version = "1.0.0"

    try:
        conn = _get_connection(db)
        row = conn.execute(
            "SELECT name, status FROM projects WHERE id = ?",
            (project_id,),
        ).fetchone()
        if row:
            project_name = row["name"] or project_id
        conn.close()
    except Exception:
        pass

    # Detect language
    language = _detect_language(project_dir)
    base_image = IRONBANK_BASE_IMAGES.get(language, IRONBANK_BASE_IMAGES["base"])
    package_manager = _detect_package_manager(language)
    project_slug = project_name.lower().replace(" ", "-").replace("_", "-")

    # Render manifest
    manifest_yaml = HARDENING_MANIFEST_TEMPLATE.format(
        timestamp=timestamp,
        project_name=project_name,
        project_slug=project_slug,
        description=description,
        version=version,
        impact_level=impact_level,
        classification=classification,
        base_image_registry=base_image["registry"],
        base_image_tag=base_image["tag"],
        base_image_digest=base_image["digest_placeholder"],
        package_manager=package_manager,
        vuln_scan_url=f"https://repo1.dso.mil/{project_slug}/security-scans",
    )

    # Build approval record
    approval_id = str(uuid.uuid4())
    approval_record = {
        "id": approval_id,
        "project_id": project_id,
        "project_name": project_name,
        "submission_date": timestamp,
        "status": "pending",
        "iron_bank_url": f"https://ironbank.dso.mil/repomap/{project_slug}",
        "platform_one_mission_id": None,
        "base_image": f"{base_image['registry']}:{base_image['tag']}",
        "language": language,
        "impact_level": impact_level,
        "p1_registry": f"registry1.dso.mil/{project_slug}:{version}",
        "hardening_manifest_generated": True,
        "created_at": timestamp,
    }

    # Write artifacts if output_dir specified
    output_paths = {}
    if output_dir:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        manifest_path = out / "hardening_manifest.yaml"
        manifest_path.write_text(manifest_yaml, encoding="utf-8")
        output_paths["hardening_manifest"] = str(manifest_path)

        approval_path = out / "container_approval.json"
        approval_path.write_text(
            json.dumps(approval_record, indent=2), encoding="utf-8"
        )
        output_paths["container_approval"] = str(approval_path)

    return {
        "project_id": project_id,
        "project_name": project_name,
        "manifest_yaml": manifest_yaml,
        "approval_record": approval_record,
        "output_paths": output_paths,
        "language_detected": language,
        "base_image": f"{base_image['registry']}:{base_image['tag']}",
        "generated_at": timestamp,
    }


def validate_hardening_manifest(project_id: str, manifest_path: str = None) -> dict:
    """Validate Iron Bank hardening manifest against required fields.

    Args:
        project_id: Project UUID.
        manifest_path: Path to existing hardening_manifest.yaml (optional).

    Returns:
        dict with passed, errors, warnings.
    """
    errors = []
    warnings = []

    if manifest_path:
        mp = Path(manifest_path)
        if not mp.exists():
            errors.append(f"Manifest file not found: {manifest_path}")
            return {
                "project_id": project_id,
                "passed": False,
                "error_count": len(errors),
                "warning_count": 0,
                "errors": errors,
                "warnings": warnings,
            }

        content = mp.read_text(encoding="utf-8")

        # Required fields check
        required_fields = [
            "apiVersion:", "name:", "tags:", "labels:",
            "base_image:", "image_author:",
            "mil.dod.impact.level:", "mil.dod.classification:",
        ]
        for field in required_fields:
            if field not in content:
                errors.append(f"Missing required field: {field}")

        # Iron Bank registry check
        if "registry1.dso.mil" not in content:
            errors.append("base_image must reference registry1.dso.mil (Iron Bank registry)")

        # Digest check
        if "sha256:<fetch-from-registry>" in content:
            warnings.append("base_image digest is placeholder — pin to specific digest before submission")

        # CUI marking check
        if "CUI" not in content:
            warnings.append("CUI marking not found in manifest")

    else:
        warnings.append("No manifest path provided — generate manifest first with --generate")

    passed = len(errors) == 0
    return {
        "project_id": project_id,
        "passed": passed,
        "error_count": len(errors),
        "warning_count": len(warnings),
        "errors": errors,
        "warnings": warnings,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Iron Bank hardening manifest generator (D350)"
    )
    parser.add_argument("--project-id", required=True, help="Project UUID")
    parser.add_argument("--project-dir", help="Project directory (language detection)")
    parser.add_argument("--output-dir", help="Directory to write generated artifacts")
    parser.add_argument("--generate", action="store_true", help="Generate hardening manifest")
    parser.add_argument("--validate", action="store_true", help="Validate existing manifest")
    parser.add_argument("--manifest-path", help="Path to manifest for validation")
    parser.add_argument("--list-base-images", action="store_true", help="List supported base images")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    if args.list_base_images:
        result = {
            "base_images": [
                {
                    "language": lang,
                    "registry": info["registry"],
                    "tag": info["tag"],
                    "os": info["os"],
                }
                for lang, info in IRONBANK_BASE_IMAGES.items()
            ]
        }
        print(json.dumps(result, indent=2) if args.json else
              "\n".join(f"  {r['language']}: {r['registry']}:{r['tag']}" for r in result["base_images"]))
        sys.exit(0)

    if args.generate:
        result = generate_hardening_manifest(
            project_id=args.project_id,
            project_dir=args.project_dir,
            output_dir=args.output_dir,
        )
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            print(f"Generated Iron Bank hardening manifest for: {result['project_name']}")
            print(f"  Language detected: {result['language_detected']}")
            print(f"  Base image:        {result['base_image']}")
            if result["output_paths"]:
                for name, path in result["output_paths"].items():
                    print(f"  Written: {path}")

    elif args.validate:
        result = validate_hardening_manifest(
            project_id=args.project_id,
            manifest_path=args.manifest_path,
        )
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            status = "PASS" if result["passed"] else "FAIL"
            print(f"[{status}] Iron Bank manifest validation — {args.project_id}")
            for err in result["errors"]:
                print(f"  ERROR: {err}")
            for warn in result["warnings"]:
                print(f"  WARN:  {warn}")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
