# CUI // SP-CTI
"""What the documents are hiding.

Built fixtures, not borrowed ones. The failure modes are structural — a sheet
that reports A1:A1 can still carry an anchored image in ANY workbook anyone has
ever made — so proving it against a document we constructed is a stronger claim
than proving it against the one corpus we happened to have.
"""
from __future__ import annotations

import pytest

from tests.bom import fixtures
from tools.bom.forensics import _PLACEHOLDER_RE, _xlsx_deleted_sheets, analyze


class TestDeletedSheetDetection:
    def test_a_gap_in_the_sheet_ids_is_a_deletion(self):
        """Excel never reuses a sheetId, so a hole in the run is a removed sheet.

        In a costing workbook that is a category somebody deleted — and the
        surviving subtotals will not tell you whether its money went with it.
        """
        sheets = [{"sheetId": i} for i in (1, 2, 3, 4, 5, 6, 7, 9, 10)]
        assert _xlsx_deleted_sheets(sheets) == [8]

    def test_a_contiguous_run_has_no_deletions(self):
        assert _xlsx_deleted_sheets([{"sheetId": i} for i in (1, 2, 3)]) == []

    def test_no_sheets_is_not_a_deletion(self):
        assert _xlsx_deleted_sheets([]) == []

    def test_end_to_end_on_a_real_package(self, tmp_path):
        p = fixtures.workbook_with_a_deleted_sheet(tmp_path / "wb.xlsx")
        f = analyze(p)
        assert [a.data["sheet_id"] for a in f.of_kind("deleted_sheet")] == [3]


class TestPlaceholderVocabulary:
    @pytest.mark.parametrize(
        "text", ["TBD", "tbd", "To Be Determined", "FIXME", "still to work", "???"]
    )
    def test_unfinished_values_are_caught(self, text):
        assert _PLACEHOLDER_RE.search(text)

    @pytest.mark.parametrize("text", ["Widget A", "$155,000", "Complete"])
    def test_finished_values_are_left_alone(self, text):
        assert not _PLACEHOLDER_RE.search(text)

    def test_the_question_mark_case(self):
        """'???' sits outside the \\b group on purpose.

        '?' is not a word character, so \\b???\\b can never match anything. A
        guard that silently never fires is worse than no guard, because you stop
        looking for the thing it was supposed to catch.
        """
        assert _PLACEHOLDER_RE.search("unit price: ???")


class TestDegradesRatherThanExplodes:
    def test_missing_file(self, tmp_path):
        f = analyze(tmp_path / "nope.xlsx")
        assert f.artifacts == []
        assert any("not found" in w for w in f.warnings)

    def test_unsupported_format_is_silent_not_noisy(self, tmp_path):
        p = tmp_path / "a.txt"
        p.write_text("prose", encoding="utf-8")
        f = analyze(p)
        assert f.artifacts == [] and f.warnings == []


class TestTheSheetThatRendersEmpty:
    """A worksheet reporting zero cells, carrying a picture.

    Excel says it is empty. It opens empty. Nobody scrolling the workbook finds
    it. And it is where somebody pasted a screenshot of the thing that actually
    constrains the project — a constraint that is now invisible to every reader
    and to every tool that reads only cells.
    """

    MESSAGE = "NO APPROVAL ON FILE\nMONITORING AVAILABLE AT COST"

    @pytest.fixture(scope="class")
    def analyzed(self, tmp_path_factory):
        p = tmp_path_factory.mktemp("fx") / "tracker.xlsx"
        fixtures.workbook_with_an_image_on_an_empty_sheet(p, self.MESSAGE)
        return analyze(p)

    def test_the_empty_sheet_is_not_empty(self, analyzed):
        assert [a.sheet for a in analyzed.of_kind("empty_sheet_with_content")] == ["Notes"]

    def test_the_image_is_found(self, analyzed):
        images = analyzed.of_kind("hidden_image")
        assert len(images) == 1
        assert images[0].sheet == "Notes"
        assert images[0].data["bytes"] > 0

    def test_ocr_carries_its_confidence(self, analyzed):
        """OCR is a guess, and it says so.

        The confidence travels with the text because quoting an OCR misread at
        somebody who controls a budget is its own kind of disaster. A finding
        sourced from pixels must be legible AS a finding sourced from pixels.
        """
        img = analyzed.of_kind("hidden_image")[0]
        if not img.data.get("ocr"):
            pytest.skip("no OCR engine available in this environment")
        assert 0.0 < img.confidence < 1.0
        # Normalize before asserting — OCR drops spaces and mangles glyphs, and
        # a test that pretended otherwise would be testing the OCR engine rather
        # than our handling of it.
        recovered = img.text.upper().replace(" ", "")
        assert "COST" in recovered


class TestProvenance:
    def test_a_machine_written_document_is_flagged(self, tmp_path):
        """openpyxl signs its work, and that is worth knowing.

        Not a scandal — but a document generated by a script is a different kind
        of evidence from one a person wrote, and that difference belongs in the
        credibility assessment rather than nowhere.
        """
        p = fixtures.workbook_with_a_zeroed_line(tmp_path / "wb.xlsx")
        f = analyze(p)
        assert f.metadata["creator"] == "openpyxl"
        assert f.machine_generated
        assert f.of_kind("machine_generated")


class TestSpeakerNotes:
    def test_the_talk_track_is_recovered(self, tmp_path):
        """Notes routinely hold the constraint the slide is too polite to show.

        The long-lead item that gates the schedule, the caveat on the estimate,
        the thing that is still TBD — none of it renders, and a reader of the
        deck never sees any of it.
        """
        p = fixtures.deck_with_a_table_that_is_not_a_table(tmp_path / "deck.pptx")
        f = analyze(p)

        notes = f.of_kind("speaker_notes")
        assert len(notes) == 1
        assert "long-lead" in notes[0].text

    def test_unfinished_work_hidden_in_the_notes_is_surfaced(self, tmp_path):
        p = fixtures.deck_with_a_table_that_is_not_a_table(tmp_path / "deck.pptx")
        f = analyze(p)
        assert any(a.kind == "placeholder" for a in f.artifacts)
