# CUI // SP-CTI
"""NOCC MOP generator — LLM-backed Method of Procedure generation."""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from typing import Any


_MOP_STEP_KEYS = {"step", "action", "rollback", "timeout_min", "verification"}

_TEMPLATE_STEPS = [
    {
        "step": 1,
        "action": "Pre-maintenance notification — notify NOC and affected customers",
        "rollback": "Cancel notification; reschedule window",
        "timeout_min": 15,
        "verification": "Confirm notification acknowledgment from stakeholders",
    },
    {
        "step": 2,
        "action": "Verify current state — capture interface/BGP/circuit status before change",
        "rollback": "Document baseline; do not proceed if unexpected state detected",
        "timeout_min": 10,
        "verification": "Baseline captured and stored",
    },
    {
        "step": 3,
        "action": "Execute change per RFC instructions",
        "rollback": "Revert configuration to baseline state",
        "timeout_min": 30,
        "verification": "Change applied without errors",
    },
    {
        "step": 4,
        "action": "Verify post-change state — confirm service restoration",
        "rollback": "Escalate to senior NOC engineer; engage vendor TAC",
        "timeout_min": 15,
        "verification": "All affected circuits/BGP sessions operational",
    },
    {
        "step": 5,
        "action": "Close maintenance window — notify stakeholders of completion",
        "rollback": "N/A",
        "timeout_min": 5,
        "verification": "Maintenance window closed in ticketing system",
    },
]


def generate_mop(rfc: dict, context: str = "") -> dict:
    """Generate MOP steps from RFC metadata.

    Attempts LLM generation; falls back to template skeleton on failure.
    Returns a dict with keys: mop_id, mop_number, steps, generated_by, ai_prompt.
    """
    mop_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)
    mop_number = f"MOP-{now.strftime('%Y-%m%d')}-{mop_id[:6].upper()}"

    prompt = (
        f"Generate a detailed Method of Procedure (MOP) for the following network change.\n"
        f"RFC Title: {rfc.get('title', 'Unnamed change')}\n"
        f"Change Type: {rfc.get('change_type', 'standard')}\n"
        f"Risk Level: {rfc.get('risk_level', 'medium')}\n"
        f"Additional Context: {context}\n\n"
        f"Return a JSON array of steps. Each step must have: "
        f"step (int), action (str), rollback (str), timeout_min (int), verification (str)."
    )

    steps = None
    try:
        from tools.llm.router import LLMRouter
        from tools.llm.provider import LLMRequest
        router = LLMRouter()
        resp = router.invoke(
            "narrative_generation",
            LLMRequest(messages=[{"role": "user", "content": prompt}], max_tokens=1500),
        )
        raw = resp.content or ""
        # Extract JSON array from response
        start = raw.find("[")
        end = raw.rfind("]") + 1
        if start >= 0 and end > start:
            steps = json.loads(raw[start:end])
    except Exception:
        pass

    if not steps:
        steps = _TEMPLATE_STEPS[:]
        generated_by = "ai_template"
    else:
        generated_by = "ai"

    return {
        "mop_id": mop_id,
        "mop_number": mop_number,
        "steps": steps,
        "generated_by": generated_by,
        "ai_prompt": prompt,
    }


def validate_mop_steps(steps: list[dict]) -> list[str]:
    """Return list of validation errors; empty list means valid."""
    errors = []
    required = {"step", "action", "rollback", "timeout_min", "verification"}
    for i, step in enumerate(steps):
        missing = required - set(step.keys())
        if missing:
            errors.append(f"Step {i + 1}: missing keys {missing}")
        if not isinstance(step.get("timeout_min"), (int, float)):
            errors.append(f"Step {i + 1}: timeout_min must be numeric")
    return errors


def mop_to_markdown(mop: dict) -> str:
    """Format a MOP as a structured Markdown document for NOC handoff."""
    lines = [
        f"# {mop.get('title', mop.get('mop_number', 'MOP'))}",
        f"**MOP Number:** {mop.get('mop_number', '')}",
        f"**Generated by:** {mop.get('generated_by', 'manual')}",
        "",
        "## Steps",
        "",
    ]
    steps = mop.get("steps", [])
    if isinstance(steps, str):
        try:
            steps = json.loads(steps)
        except Exception:
            steps = []
    for step in steps:
        lines.append(f"### Step {step.get('step', '?')}: {step.get('action', '')}")
        lines.append(f"- **Timeout:** {step.get('timeout_min', '?')} min")
        lines.append(f"- **Rollback:** {step.get('rollback', 'N/A')}")
        lines.append(f"- **Verification:** {step.get('verification', 'N/A')}")
        lines.append("")
    return "\n".join(lines)


def save_mop(conn: Any, rfc_id: str, mop: dict) -> str:
    """Persist a generated MOP to the DB and return mop_id."""
    steps_str = json.dumps(mop.get("steps", []))
    mop_id = mop["mop_id"]
    mop_number = mop["mop_number"]

    for sql, params in [
        (
            "INSERT INTO noc_mops (id, mop_number, title, rfc_id, steps_json, generated_by, ai_prompt) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s)",
            (mop_id, mop_number, mop.get("title", mop_number),
             rfc_id, steps_str, mop.get("generated_by", "ai"), mop.get("ai_prompt", "")),
        ),
        (
            "INSERT INTO noc_mops (id, mop_number, title, rfc_id, steps_json, generated_by, ai_prompt) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (mop_id, mop_number, mop.get("title", mop_number),
             rfc_id, steps_str, mop.get("generated_by", "ai"), mop.get("ai_prompt", "")),
        ),
    ]:
        try:
            conn.execute(sql, params)
            conn.commit()
            return mop_id
        except Exception:
            continue
    raise RuntimeError("Failed to save MOP")
