# [TEMPLATE: CUI // SP-CTI]
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signalforge-dashboard
  namespace: signalforge
  labels:
    app.kubernetes.io/part-of: signalforge
    classification: CUI
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - signalforge.internal
      secretName: signalforge-tls
  rules:
    - host: signalforge.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signalforge-dashboard
                port:
                  number: 5000
