# CUI // SP-CTI
"""Workflow Forms Canvas — Export Engine.

Converts forms and workflows to PPT, PDF, or DOCX using the existing
slide/presentation infrastructure.

Public API:
    export_form(form_id, fmt, conn)      -> (bytes, filename)
    export_workflow(workflow_id, fmt, conn) -> (bytes, filename)
"""
from __future__ import annotations

import json
import re
import sys
from io import BytesIO
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from tools.slides.pptx_builder import build as build_pptx
from tools.slides.export_pdf import build_pdf


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")


# ── Branding helpers ──────────────────────────────────────────────────────────

def _get_branding(entity_type: str, entity_id: str, conn=None) -> dict:
    """Read branding from the WFC canvas connection — the SAME source
    blueprint._save_branding writes to (get_canvas_connection("ICDEV_WFC_ENABLED")).

    Previously this read via the passed-in main get_connection(), so on a
    SQLite-pinned WFC canvas (where branding is written to a separate .db)
    exports silently lost all branding. The ``conn`` parameter is retained for
    backward compatibility but is no longer used for branding. (cnr-wfc-04)
    """
    from tools.db.storage import get_canvas_connection, sql_placeholder
    cconn = get_canvas_connection("ICDEV_WFC_ENABLED")
    try:
        ph = sql_placeholder(cconn)
        row = cconn.execute(
            f"SELECT * FROM wfc_branding WHERE entity_type={ph} AND entity_id={ph}",
            (entity_type, entity_id),
        ).fetchone()
        return dict(row) if row else {}
    except Exception:
        return {}
    finally:
        try:
            cconn.close()
        except Exception:
            pass


# ── Form → slides conversion ──────────────────────────────────────────────────

def _form_to_slides(form: dict, branding: dict) -> list[dict]:
    schema = json.loads(form.get("schema_json", "{}"))
    fields: list[dict] = schema.get("_fields", [])
    form_name = form.get("name", "Form")
    org_name = branding.get("org_name", "ICDEV™")

    slides: list[dict] = []

    # Title slide
    slides.append({
        "type": "title",
        "title": form_name,
        "subtitle": f"{org_name} — Form Preview",
        "body": form.get("description") or "",
        "speaker_notes": "Generated by ICDEV™ Workflow Forms Canvas",
    })

    # Group fields into batches of 5 per slide
    batch_size = 5
    for i in range(0, len(fields), batch_size):
        batch = fields[i : i + batch_size]
        bullets: list[str] = []
        for f in batch:
            req = " *" if f.get("required") else ""
            ftype = f.get("type", "text")
            opts = f.get("options", [])
            opt_str = f" [{', '.join(opts[:4])}{'…' if len(opts) > 4 else ''}]" if opts else ""
            bullets.append(f"{f.get('label', f.get('id', '?'))} ({ftype}){opt_str}{req}")
        slide_num = i // batch_size + 1
        total = (len(fields) + batch_size - 1) // batch_size
        slides.append({
            "type": "content",
            "title": f"Fields — Part {slide_num}/{total}",
            "bullets": bullets,
            "speaker_notes": "* = required field",
        })

    # Outro / footer slide
    footer = branding.get("footer_html") or "Confidential — CUI"
    slides.append({
        "type": "outro",
        "title": "End of Form Preview",
        "body": footer,
        "speaker_notes": f"Form ID: {form.get('form_id', '')}",
    })

    return slides


# ── Workflow → slides conversion ──────────────────────────────────────────────

def _workflow_to_slides(workflow: dict, branding: dict) -> list[dict]:
    wf_name = workflow.get("name", "Workflow")
    org_name = branding.get("org_name", "ICDEV™")

    try:
        tpl = workflow.get("template_yaml", "{}")
        import yaml  # already in requirements
        wf_def = yaml.safe_load(tpl) if isinstance(tpl, str) else {}
    except Exception:
        wf_def = {}

    steps: list[dict] = wf_def.get("steps", [])

    slides: list[dict] = [
        {
            "type": "title",
            "title": wf_name,
            "subtitle": f"{org_name} — Workflow Pipeline",
            "body": workflow.get("description") or "",
        }
    ]

    if steps:
        bullets = [
            f"{s.get('name', s.get('id', '?'))} — {s.get('tool', 'step')}"
            for s in steps[:20]
        ]
        slides.append({
            "type": "content",
            "title": "Pipeline Steps",
            "bullets": bullets,
        })

    slides.append({
        "type": "outro",
        "title": "End of Workflow Overview",
        "body": branding.get("footer_html") or "Confidential — CUI",
    })

    return slides


# ── DOCX export ───────────────────────────────────────────────────────────────

def _export_docx(slides: list[dict], title: str, branding: dict) -> bytes:
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise RuntimeError("python-docx is required for DOCX export: pip install python-docx")

    doc = Document()
    org_name = branding.get("org_name", "ICDEV™")
    primary_color = branding.get("primary_color", "#1a365d").lstrip("#")
    try:
        r, g, b = int(primary_color[0:2], 16), int(primary_color[2:4], 16), int(primary_color[4:6], 16)
        brand_color = RGBColor(r, g, b)
    except Exception:
        brand_color = RGBColor(0x1a, 0x36, 0x5d)

    # Header paragraph
    header_para = doc.add_paragraph()
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = header_para.add_run(org_name)
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = brand_color

    doc.add_heading(title, level=0)

    for slide in slides:
        stype = slide.get("type", "content")
        if stype == "title":
            if slide.get("subtitle"):
                p = doc.add_paragraph(slide["subtitle"])
                p.runs[0].italic = True
            if slide.get("body"):
                doc.add_paragraph(slide["body"])
        elif stype in ("content",):
            h = doc.add_heading(slide.get("title", ""), level=2)
            h.runs[0].font.color.rgb = brand_color
            for bullet in slide.get("bullets", []):
                doc.add_paragraph(bullet, style="List Bullet")
        elif stype == "outro":
            doc.add_paragraph()
            p = doc.add_paragraph(slide.get("body", ""))
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Footer
    footer_text = branding.get("footer_html") or "CUI — Controlled Unclassified Information"
    section = doc.sections[0]
    footer = section.footer
    fp = footer.paragraphs[0]
    fp.text = footer_text
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── Public API ────────────────────────────────────────────────────────────────

def export_form(form_id: str, fmt: str, conn) -> tuple[bytes, str]:
    """Return (file_bytes, filename) for a form exported in the given format."""
    row = conn.execute("SELECT * FROM studio_forms WHERE form_id=%s", (form_id,)).fetchone()
    if not row:
        raise ValueError(f"Form {form_id} not found")
    form = dict(row)
    branding = _get_branding("form", form_id, conn)
    slides = _form_to_slides(form, branding)
    name_slug = _slug(form.get("name", "form"))

    if fmt == "pptx":
        path = build_pptx(slides, theme="govcon_proposal", title=form.get("name", "Form"))
        return Path(path).read_bytes(), f"{name_slug}.pptx"

    if fmt == "pdf":
        path = build_pdf(slides, theme="govcon_proposal", title=form.get("name", "Form"))
        return Path(path).read_bytes(), f"{name_slug}.pdf"

    if fmt == "docx":
        data = _export_docx(slides, form.get("name", "Form"), branding)
        return data, f"{name_slug}.docx"

    raise ValueError(f"Unsupported format: {fmt}")


def export_workflow(workflow_id: str, fmt: str, conn) -> tuple[bytes, str]:
    """Return (file_bytes, filename) for a workflow exported in the given format."""
    row = conn.execute("SELECT * FROM studio_workflows WHERE workflow_id=%s", (workflow_id,)).fetchone()
    if not row:
        raise ValueError(f"Workflow {workflow_id} not found")
    workflow = dict(row)
    branding = _get_branding("workflow", workflow_id, conn)
    slides = _workflow_to_slides(workflow, branding)
    name_slug = _slug(workflow.get("name", "workflow"))

    if fmt == "pptx":
        path = build_pptx(slides, theme="govcon_proposal", title=workflow.get("name", "Workflow"))
        return Path(path).read_bytes(), f"{name_slug}.pptx"

    if fmt == "pdf":
        path = build_pdf(slides, theme="govcon_proposal", title=workflow.get("name", "Workflow"))
        return Path(path).read_bytes(), f"{name_slug}.pdf"

    if fmt == "docx":
        data = _export_docx(slides, workflow.get("name", "Workflow"), branding)
        return data, f"{name_slug}.docx"

    raise ValueError(f"Unsupported format: {fmt}")
