# CUI // SP-CTI — Auto-generated by ICDEV™ Pipeline Design Canvas
# Layer 1: Network — AWS VPC
# Generated: 2026-08-02T00:58:19.135249+00:00

provider "aws" {
  region = var.region
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "insecure-pipeline-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["us-gov-west-1a", "us-gov-west-1b", "us-gov-west-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Environment   = var.environment
    Project       = "insecure-pipeline"
    ManagedBy     = "terraform"
    Classification = "CUI"
  }
}

output "vpc_id" { value = module.vpc.vpc_id }
output "private_subnet_ids" { value = module.vpc.private_subnets }
output "public_subnet_ids" { value = module.vpc.public_subnets }
