# CUI // SP-CTI
"""Render the promoter's JSON into a commit message and a PR body.

Split out of the workflow on purpose. Multi-line prose built inside a YAML
``run:`` block is how that file became invalid YAML the first time it was
written: a heredoc whose body sits at column 0 terminates the block scalar, and
the failure surfaces as a scanner error a hundred lines away from the mistake.
Rendering here also means the text is testable, which text inside a workflow
never is.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Optional, Sequence


def commit_message(report: dict) -> str:
    promoted = report.get("promoted") or []
    lines = [
        f"chore(ci): promote {len(promoted)} ungated module(s) verified green both ways",
        "",
        "Each module was re-run ALONE and then IN-SUITE with the gated set in one",
        "process. Green-alone is not green-in-suite -- a module that registers onto",
        "a shared singleton passes alone and fails in the full run -- so promoting",
        "on the isolated result is how `main` goes red and the gate gets disabled.",
        "",
    ]
    lines += [f"  {m}" for m in promoted]
    before, after = report.get("backlog_size"), report.get("backlog_size_after")
    if before is not None and after is not None:
        lines += ["", f"Ungated backlog: {before} -> {after}."]
    if report.get("backlog_max"):
        lines.append(f"backlog_max ratcheted to {report['backlog_max']}.")
    lines += ["", "Generated by .github/workflows/gate-promoter.yml"]
    return "\n".join(lines) + "\n"


def pr_body(report: dict) -> str:
    promoted = report.get("promoted") or []
    out = ["Promoted, each verified green **alone** and **in-suite**:", ""]
    out += [f"- `{m}`" for m in promoted]
    before, after = report.get("backlog_size"), report.get("backlog_size_after")
    if before is not None and after is not None:
        out += ["", f"Ungated backlog: **{before} → {after}**."]
    if report.get("backlog_max"):
        out.append(f"`backlog_max` ratcheted to **{report['backlog_max']}**.")
    rejected = report.get("rejected") or []
    if rejected:
        out += ["", f"Not promoted this run ({len(rejected)}):", ""]
        out += [f"- `{r['file']}` — failed **{r['phase']}**" for r in rejected[:15]]
        if len(rejected) > 15:
            out.append(f"- …and {len(rejected) - 15} more")
    out += [
        "",
        "This PR's own CI runs the full gated suite **with these modules in it**, "
        "so the change is proved by the pipeline it modifies.",
    ]
    return "\n".join(out) + "\n"


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--from", dest="src", required=True)
    parser.add_argument("--commit-message", default=None)
    parser.add_argument("--pr-body", default=None)
    args = parser.parse_args(argv)

    report = json.loads(Path(args.src).read_text(encoding="utf-8"))
    if args.commit_message:
        Path(args.commit_message).write_text(commit_message(report),
                                             encoding="utf-8", newline="\n")
    if args.pr_body:
        Path(args.pr_body).write_text(pr_body(report), encoding="utf-8", newline="\n")
    if not (args.commit_message or args.pr_body):
        print(pr_body(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
