# CUI // SP-CTI
"""tools/airgap/npm_mirror_sync — Admin-only npm package vendor for air-gap.

Parallel to ``tools/airgap/wheel_vendor.py`` (PyPI) and
``tools/airgap/driver_vendor.py`` (browser drivers). Snapshots
``node_modules`` and the local npm cache on a connected workstation, stashes
them under ``vendor/npm/{snapshot}/``, and writes an ``SHA256SUM`` manifest
alongside each bundle.

Air-gap hosts rebuild from the snapshot without touching any registry::

    # On air-gap host after unpacking:
    npm install --offline --prefer-offline

Or point npm at the local registry via ``.npmrc``::

    registry=file://./vendor/npm/<snapshot>/registry/
    # generated automatically by --gen-npmrc

.npmrc registry-override pattern
---------------------------------
npm does not support ``file://`` as a registry URL natively, but three
approaches work without a running registry server:

1. **Tarball install (simplest)**::

       # vendor/npm/<snapshot>/install.sh
       npm install --no-package-lock --prefer-offline \
           --cache ./vendor/npm/<snapshot>/cache/

2. **Verdaccio local mirror (full registry)**::

       # .npmrc
       registry=http://localhost:4873/
       # start: npx verdaccio --config vendor/npm/<snapshot>/verdaccio.yaml

3. **Direct tarball paths in package.json**::

       "dependencies": {
           "openapi-typescript": "file:vendor/npm/<snapshot>/tarballs/openapi-typescript-7.8.0.tgz"
       }

Approach 1 (offline cache) is the default generated by ``--gen-npmrc``.

Usage::

    # On connected workstation — snapshot node_modules + cache
    python tools/airgap/npm_mirror_sync.py --pack \
        --source frontend/node_modules --dest vendor/npm

    # With explicit npm cache path
    python tools/airgap/npm_mirror_sync.py --pack \
        --source frontend/node_modules --cache ~/.npm --dest vendor/npm

    # Verify a snapshot
    python tools/airgap/npm_mirror_sync.py --verify --snapshot <name>

    # List all snapshots
    python tools/airgap/npm_mirror_sync.py --list

    # Generate .npmrc for air-gap rebuild (offline-cache strategy)
    python tools/airgap/npm_mirror_sync.py --gen-npmrc --snapshot <name>

    # On air-gap host — unpack a snapshot
    python tools/airgap/npm_mirror_sync.py --unpack --snapshot <name> \
        --dest frontend/node_modules
"""
from __future__ import annotations
from tools.logging.icdev_logger import get_logger

import argparse
import datetime
import hashlib
import json
import logging
import os
import shutil
import sys
import tarfile
from pathlib import Path
from typing import Any

logger = get_logger("icdev.airgap.npm_mirror_sync")

BASE_DIR = Path(__file__).resolve().parent.parent.parent
NPM_VENDOR_DIR = BASE_DIR / "vendor" / "npm"

# Name of the SHA256 manifest written alongside each bundle tarball
_MANIFEST_NAME = "SHA256SUM"

# Default npm cache location per OS
_DEFAULT_NPM_CACHE: dict[str, str] = {
    "win32": str(Path.home() / "AppData" / "Local" / "npm-cache"),
    "darwin": str(Path.home() / "Library" / "Caches" / "npm"),
    "linux": str(Path.home() / ".npm"),
}


# ---------------------------------------------------------------------------
# Safety: refuse to fetch in air-gap
# ---------------------------------------------------------------------------


def _assert_connected() -> None:
    """Hard-fail when invoked in an air-gap environment.

    Prevents accidental pack runs on hosts that would produce empty/partial
    bundles.
    """
    try:
        from tools.airgap.detector import is_airgap  # noqa: PLC0415
        airgap = is_airgap()
    except Exception:
        airgap = os.environ.get("ICDEV_AIRGAP", "").lower() in ("1", "true", "yes")
    if airgap:
        raise RuntimeError(
            "npm_mirror_sync.py --pack refuses to run in air-gap mode. "
            "Run --pack on a connected admin workstation, then transport "
            "vendor/npm/ to the air-gap host before running --unpack."
        )


# ---------------------------------------------------------------------------
# SHA256 helpers
# ---------------------------------------------------------------------------


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_sha256_manifest(directory: Path, pattern: str = "*.tar.gz") -> dict[str, str]:
    """Hash every matching file in directory, write SHA256SUM, return mapping."""
    digests: dict[str, str] = {}
    for artifact in sorted(directory.glob(pattern)):
        digests[artifact.name] = _sha256_file(artifact)
    manifest = directory / _MANIFEST_NAME
    lines = [f"{digest}  {name}\n" for name, digest in sorted(digests.items())]
    manifest.write_text("".join(lines), encoding="utf-8", newline="")
    return digests


def _read_sha256_manifest(directory: Path) -> dict[str, str]:
    manifest = directory / _MANIFEST_NAME
    if not manifest.exists():
        return {}
    result: dict[str, str] = {}
    for line in manifest.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split(None, 1)
        if len(parts) == 2:
            result[parts[1].strip()] = parts[0].strip()
    return result


# ---------------------------------------------------------------------------
# Snapshot naming
# ---------------------------------------------------------------------------


def _snapshot_name(source: Path) -> str:
    """Generate a timestamped snapshot name derived from the source basename."""
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    slug = source.parent.name  # e.g. "frontend" from frontend/node_modules
    return f"{slug}-npm-{ts}"


def _snapshot_dir(snapshot: str) -> Path:
    return NPM_VENDOR_DIR / snapshot


# ---------------------------------------------------------------------------
# Core operations
# ---------------------------------------------------------------------------


def pack(
    source: Path,
    dest: Path,
    npm_cache: Path | None = None,
    snapshot: str | None = None,
) -> dict[str, Any]:
    """Snapshot node_modules (and optionally the npm cache) to a bundle.

    Creates ``dest/<snapshot>/modules.tar.gz`` from *source* and
    ``dest/<snapshot>/cache.tar.gz`` from *npm_cache* (if it exists and is
    non-empty). Writes SHA256SUM for both tarballs.

    Parameters
    ----------
    source:
        Path to node_modules directory (e.g. ``frontend/node_modules``).
    dest:
        Parent vendor directory (e.g. ``vendor/npm``); snapshot sub-dir is
        created automatically.
    npm_cache:
        Path to the npm cache directory.  Defaults to the OS-appropriate
        default (``~/.npm``, ``%APPDATA%\\npm-cache``, etc.).  Pass an empty
        Path or ``None`` to skip cache bundling.
    snapshot:
        Override the auto-generated snapshot name.
    """
    _assert_connected()

    source = source.resolve()
    if not source.exists():
        raise FileNotFoundError(
            f"source not found: {source} — run `npm ci` on the frontend first."
        )

    snap = snapshot or _snapshot_name(source)
    snap_dir = dest / snap
    snap_dir.mkdir(parents=True, exist_ok=True)
    logger.info("Snapshot: %s → %s", source, snap_dir)

    # --- node_modules tarball ---
    modules_tar = snap_dir / "modules.tar.gz"
    logger.info("Archiving node_modules …")
    _create_tar(source, modules_tar, arcname="node_modules")
    modules_bytes = modules_tar.stat().st_size
    logger.info("modules.tar.gz: %.1f MB", modules_bytes / 1_048_576)

    # --- npm cache tarball (optional) ---
    cache_info: dict[str, Any] = {}
    if npm_cache is None:
        npm_cache = Path(_DEFAULT_NPM_CACHE.get(sys.platform, str(Path.home() / ".npm")))
    if npm_cache.exists() and any(npm_cache.iterdir()):
        cache_tar = snap_dir / "cache.tar.gz"
        logger.info("Archiving npm cache from %s …", npm_cache)
        _create_tar(npm_cache, cache_tar, arcname="_npm_cache")
        cache_bytes = cache_tar.stat().st_size
        logger.info("cache.tar.gz: %.1f MB", cache_bytes / 1_048_576)
        cache_info = {"cache_tar": str(cache_tar), "cache_bytes": cache_bytes}
    else:
        logger.warning("npm cache not found or empty at %s — skipping cache bundle", npm_cache)
        cache_info = {"cache_tar": None, "note": f"cache not found: {npm_cache}"}

    # --- package.json snapshot (for version pinning reference) ---
    pkg_json = source.parent / "package.json"
    if pkg_json.exists():
        shutil.copy2(pkg_json, snap_dir / "package.json")

    lock_file = source.parent / "package-lock.json"
    if lock_file.exists():
        shutil.copy2(lock_file, snap_dir / "package-lock.json")

    # --- SHA256 manifest ---
    digests = _write_sha256_manifest(snap_dir, "*.tar.gz")

    # --- README / .npmrc template ---
    _write_npmrc_template(snap_dir, snap)

    return {
        "ok": True,
        "snapshot": snap,
        "snapshot_dir": str(snap_dir),
        "modules_tar": str(modules_tar),
        "modules_bytes": modules_bytes,
        "sha256sum_entries": len(digests),
        **cache_info,
    }


def _create_tar(source: Path, dest_tar: Path, arcname: str) -> None:
    """Create a gzipped tarball of *source* at *dest_tar*."""
    with tarfile.open(dest_tar, "w:gz") as tf:
        tf.add(str(source), arcname=arcname)


def unpack(
    snapshot: str,
    dest: Path,
    vendor_dir: Path | None = None,
) -> dict[str, Any]:
    """Extract a snapshot's modules.tar.gz to *dest*.

    Parameters
    ----------
    snapshot:
        Name of the snapshot sub-directory under ``vendor/npm/``.
    dest:
        Target directory for the extracted ``node_modules``
        (e.g. ``frontend/node_modules``).
    vendor_dir:
        Override the vendor root (default ``vendor/npm/``).
    """
    vdir = vendor_dir or NPM_VENDOR_DIR
    snap_dir = vdir / snapshot
    if not snap_dir.exists():
        raise FileNotFoundError(f"snapshot not found: {snap_dir}")

    modules_tar = snap_dir / "modules.tar.gz"
    if not modules_tar.exists():
        raise FileNotFoundError(f"modules.tar.gz missing in snapshot: {snap_dir}")

    dest = dest.resolve()
    dest.parent.mkdir(parents=True, exist_ok=True)

    logger.info("Extracting %s → %s", modules_tar, dest.parent)
    with tarfile.open(modules_tar, "r:gz") as tf:
        # filter='data' (Py 3.12+) prevents path traversal; fall back to nosec on older runtimes
        if hasattr(tarfile, "data_filter"):
            tf.extractall(str(dest.parent), filter="data")
        else:
            tf.extractall(str(dest.parent))  # nosec B202 — admin-only vendor snapshot, dest validated via .resolve()

    return {
        "ok": True,
        "snapshot": snapshot,
        "extracted_to": str(dest.parent),
        "node_modules": str(dest),
    }


def verify(snapshot: str, vendor_dir: Path | None = None) -> dict[str, Any]:
    """Recompute SHA256 for every tarball in *snapshot* and compare to manifest."""
    vdir = vendor_dir or NPM_VENDOR_DIR
    snap_dir = vdir / snapshot
    if not snap_dir.exists():
        return {"ok": False, "snapshot": snapshot, "error": f"snapshot not found: {snap_dir}"}

    stored = _read_sha256_manifest(snap_dir)
    if not stored:
        return {"ok": False, "snapshot": snapshot, "error": "SHA256SUM missing or empty"}

    verified: list[str] = []
    mismatched: list[dict[str, str]] = []
    missing: list[str] = []

    disk_tars = {p.name for p in snap_dir.glob("*.tar.gz")}
    for name, expected in stored.items():
        path = snap_dir / name
        if not path.exists():
            missing.append(name)
            continue
        actual = _sha256_file(path)
        if actual == expected:
            verified.append(name)
        else:
            mismatched.append({"name": name, "expected": expected, "actual": actual})

    extra = sorted(disk_tars - set(stored.keys()))
    ok = not (mismatched or missing)
    return {
        "ok": ok,
        "snapshot": snapshot,
        "snapshot_dir": str(snap_dir),
        "verified": verified,
        "mismatched": mismatched,
        "missing": missing,
        "extra_on_disk_no_hash": extra,
    }


def list_snapshots(vendor_dir: Path | None = None) -> dict[str, Any]:
    """List every snapshot under vendor/npm/."""
    vdir = vendor_dir or NPM_VENDOR_DIR
    if not vdir.exists():
        return {"npm_vendor_dir": str(vdir), "snapshots": []}
    snapshots: list[dict[str, Any]] = []
    for sub in sorted(vdir.iterdir()):
        if not sub.is_dir() or sub.name.startswith("."):
            continue
        tars = sorted(t.name for t in sub.glob("*.tar.gz"))
        has_manifest = (sub / _MANIFEST_NAME).exists()
        has_npmrc = (sub / ".npmrc").exists()
        total_bytes = sum(t.stat().st_size for t in sub.glob("*.tar.gz"))
        snapshots.append({
            "snapshot": sub.name,
            "tarballs": tars,
            "total_mb": round(total_bytes / 1_048_576, 1),
            "has_manifest": has_manifest,
            "has_npmrc": has_npmrc,
        })
    return {"npm_vendor_dir": str(vdir), "snapshots": snapshots}


def gen_npmrc(
    snapshot: str,
    strategy: str = "offline-cache",
    vendor_dir: Path | None = None,
) -> dict[str, Any]:
    """Print (and optionally write) a .npmrc for air-gap npm installs.

    Strategies
    ----------
    offline-cache (default):
        Point npm at the vendored cache so ``npm install --offline`` works
        without a registry.
    verdaccio:
        Scaffold a minimal Verdaccio config pointing at the tarballs.
    tarball-deps:
        Print a ``dependencies`` block for package.json using
        ``file:`` paths.
    """
    vdir = vendor_dir or NPM_VENDOR_DIR
    snap_dir = vdir / snapshot
    if not snap_dir.exists():
        raise FileNotFoundError(f"snapshot not found: {snap_dir}")

    if strategy == "offline-cache":
        cache_rel = f"vendor/npm/{snapshot}/_npm_cache"
        npmrc = (
            "# .npmrc — air-gap npm registry override\n"
            "# Generated by tools/airgap/npm_mirror_sync.py\n"
            "#\n"
            "# Strategy: offline-cache\n"
            "#   1. Unpack the snapshot:  python tools/airgap/npm_mirror_sync.py\n"
            f"#      --unpack --snapshot {snapshot} --dest frontend/node_modules\n"
            "#   2. Point npm at the vendored cache:\n"
            f"cache={cache_rel}\n"
            "prefer-offline=true\n"
            "# Install without hitting any registry:\n"
            "#   npm install --offline\n"
        )
        verdaccio_note = None
    elif strategy == "verdaccio":
        verdaccio_note = _write_verdaccio_config(snap_dir, snapshot)
        npmrc = (
            "# .npmrc — air-gap npm registry override (Verdaccio)\n"
            "# Generated by tools/airgap/npm_mirror_sync.py\n"
            "#\n"
            "# Strategy: verdaccio local mirror\n"
            "#   1. Start Verdaccio: npx verdaccio\n"
            f"#      --config vendor/npm/{snapshot}/verdaccio.yaml\n"
            "registry=http://localhost:4873/\n"
            "always-auth=false\n"
        )
    elif strategy == "tarball-deps":
        tars = sorted(snap_dir.glob("tarballs/*.tgz"))
        deps_lines = "\n".join(
            f'    "{t.stem.rsplit("-", 1)[0]}": "file:vendor/npm/{snapshot}/tarballs/{t.name}"'
            for t in tars
        )
        npmrc = (
            "// package.json dependencies snippet — air-gap tarball installs\n"
            '{\n  "dependencies": {\n'
            + deps_lines
            + "\n  }\n}\n"
        )
        verdaccio_note = None
    else:
        raise ValueError(f"unknown strategy: {strategy!r} (choose offline-cache, verdaccio, tarball-deps)")

    npmrc_path = snap_dir / ".npmrc"
    npmrc_path.write_text(npmrc, encoding="utf-8", newline="")

    result: dict[str, Any] = {
        "ok": True,
        "snapshot": snapshot,
        "strategy": strategy,
        "npmrc_path": str(npmrc_path),
        "npmrc_content": npmrc,
    }
    if verdaccio_note:
        result["verdaccio_config"] = verdaccio_note
    return result


def _write_npmrc_template(snap_dir: Path, snapshot: str) -> None:
    """Write a default offline-cache .npmrc into the snapshot directory."""
    cache_rel = f"vendor/npm/{snapshot}/_npm_cache"
    content = (
        "# .npmrc — air-gap npm registry override\n"
        "# Generated by tools/airgap/npm_mirror_sync.py\n"
        "#\n"
        "# Strategy: offline-cache (default)\n"
        "#\n"
        "# On the air-gap host:\n"
        "#   1. Unpack node_modules:\n"
        f"#      python tools/airgap/npm_mirror_sync.py --unpack --snapshot {snapshot}\n"
        "#          --dest frontend/node_modules\n"
        "#   2. (Optional) restore npm cache to allow re-installs:\n"
        "#      tar -xzf vendor/npm/{snapshot}/cache.tar.gz -C $(npm config get cache)\n"
        "#   3. Install offline:\n"
        "#      npm install --offline --prefer-offline\n"
        "#\n"
        f"cache={cache_rel}\n"
        "prefer-offline=true\n"
    )
    (snap_dir / ".npmrc").write_text(content, encoding="utf-8", newline="")


def _write_verdaccio_config(snap_dir: Path, snapshot: str) -> str:
    """Write a minimal Verdaccio YAML config for the snapshot."""
    config = (
        "# Verdaccio config — air-gap local npm registry\n"
        "# Generated by tools/airgap/npm_mirror_sync.py\n"
        "storage: ./storage\n"
        "auth:\n"
        "  htpasswd:\n"
        "    file: ./htpasswd\n"
        "uplinks: {}\n"
        "packages:\n"
        "  '**':\n"
        "    access: $all\n"
        "    publish: $all\n"
        "    proxy: ''\n"
        "listen: localhost:4873\n"
        "logs:\n"
        "  - {type: stdout, format: pretty, level: info}\n"
    )
    cfg_path = snap_dir / "verdaccio.yaml"
    cfg_path.write_text(config, encoding="utf-8", newline="")
    return str(cfg_path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    parser = argparse.ArgumentParser(
        description="ICDEV™ air-gap npm mirror sync (admin-only).",
    )
    parser.add_argument(
        "--pack", action="store_true",
        help="Snapshot node_modules + npm cache into vendor/npm/<snapshot>/",
    )
    parser.add_argument(
        "--unpack", action="store_true",
        help="Extract snapshot modules.tar.gz back to --dest",
    )
    parser.add_argument(
        "--verify", action="store_true",
        help="Verify SHA256 manifest for --snapshot",
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List all snapshots in vendor/npm/",
    )
    parser.add_argument(
        "--gen-npmrc", action="store_true",
        help="Generate .npmrc for --snapshot (--strategy selects the approach)",
    )
    parser.add_argument(
        "--source", type=str, default="frontend/node_modules",
        help="node_modules path for --pack (default: frontend/node_modules)",
    )
    parser.add_argument(
        "--dest", type=str, default="vendor/npm",
        help="Vendor root for --pack, or target node_modules parent for --unpack",
    )
    parser.add_argument(
        "--cache", type=str, default=None,
        help="npm cache path for --pack (default: OS default ~/.npm / %%APPDATA%%\\npm-cache)",
    )
    parser.add_argument(
        "--snapshot", type=str, default=None,
        help="Snapshot name (required for --unpack, --verify, --gen-npmrc)",
    )
    parser.add_argument(
        "--strategy", type=str, default="offline-cache",
        choices=["offline-cache", "verdaccio", "tarball-deps"],
        help="Registry override strategy for --gen-npmrc (default: offline-cache)",
    )
    parser.add_argument("--json", action="store_true", help="JSON output")
    args = parser.parse_args()

    try:
        if args.list:
            out = list_snapshots()
        elif args.pack:
            source = (BASE_DIR / args.source).resolve()
            dest = (BASE_DIR / args.dest).resolve()
            cache = Path(args.cache).resolve() if args.cache else None
            out = pack(source=source, dest=dest, npm_cache=cache, snapshot=args.snapshot)
        elif args.unpack:
            if not args.snapshot:
                parser.error("--unpack requires --snapshot")
            dest = (BASE_DIR / args.dest).resolve()
            out = unpack(snapshot=args.snapshot, dest=dest)
        elif args.verify:
            if not args.snapshot:
                parser.error("--verify requires --snapshot")
            out = verify(snapshot=args.snapshot)
        elif args.gen_npmrc:
            if not args.snapshot:
                parser.error("--gen-npmrc requires --snapshot")
            out = gen_npmrc(snapshot=args.snapshot, strategy=args.strategy)
        else:
            parser.print_help()
            return 2
    except Exception as exc:
        if args.json:
            print(json.dumps({"ok": False, "error": str(exc)}, indent=2))
        else:
            print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(out, indent=2, default=str))
    else:
        print(json.dumps(out, indent=2, default=str))
    return 0 if out.get("ok", True) else 1


if __name__ == "__main__":
    sys.exit(_main())
