# CUI // SP-CTI
"""Sigma rule generator for the ODC Digital Twin.

Deterministic — no LLM. For each (technique_id, signal_source) pair with
coverage state=none, emits a well-formed Sigma YAML detection rule.

Public API:
  generate_rules(pairs, design_name="") -> list[str]   — core: (tid,src) → YAML rules
  generate_sigma_rules(graph, design_name="") -> dict   — ODC graph → export bundle
  estimate_log_volume(nodes, retention_days=90) -> dict — ingestion cost projection
"""

from __future__ import annotations

import shutil
import subprocess
import uuid
from datetime import datetime, timezone
import yaml

# ---------------------------------------------------------------------------
# Signal source → Sigma log-source mapping
# ---------------------------------------------------------------------------
_SRC_LOGSOURCE: dict[str, dict] = {
    "src-os-log":        {"category": "process_creation", "product": "windows"},
    "src-wef":           {"category": "process_creation", "product": "windows"},
    "src-endpoint":      {"category": "process_creation"},
    "src-network-log":   {"category": "firewall"},
    "src-cloud-log":     {"category": "cloud", "service": "cloudtrail"},
    "src-container-log": {"category": "container"},
    "src-db-audit":      {"category": "database"},
    "src-app-log":       {"category": "application"},
    "src-flow":          {"category": "network_connection"},
    "src-pcap":          {"category": "network_connection"},
    "src-iam":           {"category": "authentication"},
    "src-metric":        {"category": "metrics"},
    "src-trace":         {"category": "application"},
    "src-vulnerability": {"category": "vulnerability_scan"},
}

# ---------------------------------------------------------------------------
# Technique catalog (single source of truth) — derived legacy views
# ---------------------------------------------------------------------------
# Detection snippets keyed by (tid, logsource category) and the tactic lookup
# map are derived from tools/observability_canvas/mitre_catalog.py so the three
# historically-drifted catalogs stay consolidated. _TECHNIQUE_DETECTIONS keeps
# its public name (imported by replay_verify._sigma_known_ttps).
from tools.observability_canvas.mitre_catalog import (
    DEFAULT_TACTIC as _DEFAULT_TACTIC,
    build_canvas_detections as _build_canvas_detections,
    build_tactic_map as _build_tactic_map,
)

_TECHNIQUE_DETECTIONS: dict[str, dict[str, dict]] = _build_canvas_detections()

# Tactic per technique (MITRE ATT&CK subset, hyphen form) — derived from catalog.
_TECHNIQUE_TACTIC: dict[str, str] = _build_tactic_map()


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_logsource(src: str) -> dict:
    return dict(_SRC_LOGSOURCE.get(src, {"category": "generic"}))


def _get_detection(tid: str, src: str) -> dict:
    """Return detection block for (tid, src). Falls back to a generic presence check."""
    category = _SRC_LOGSOURCE.get(src, {}).get("category", "generic")
    parent_tid = tid.split(".")[0]

    for lookup_tid in (tid, parent_tid):
        tech_dets = _TECHNIQUE_DETECTIONS.get(lookup_tid)
        if tech_dets and category in tech_dets:
            return dict(tech_dets[category])

    return {
        "selection": {"Keywords|contains": [tid, tid.replace(".", "/")]},
        "condition": "selection",
    }


def _get_tactic(tid: str) -> str:
    return _TECHNIQUE_TACTIC.get(tid) or _TECHNIQUE_TACTIC.get(tid.split(".")[0], _DEFAULT_TACTIC)


def _build_rule(tid: str, src: str, design_name: str = "") -> dict:
    """Construct a Sigma rule dict for one (tid, src) pair."""
    logsource = _get_logsource(src)
    detection = _get_detection(tid, src)
    tactic = _get_tactic(tid)
    src_label = src.replace("src-", "").replace("-", " ").title()

    title = f"Detect {tid} via {src_label}"
    if design_name:
        title = f"[{design_name}] {title}"

    return {
        "title": title,
        "id": str(uuid.uuid4()),
        "status": "experimental",
        "description": (
            f"Detects {tid} activity observed through {src_label}. "
            "Generated by ICDEV ODC Digital Twin."
        ),
        "references": [f"https://attack.mitre.org/techniques/{tid.replace('.', '/')}/"],
        "author": "ICDEV ODC Twin",
        "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "tags": [
            f"attack.{tid.lower().replace('.', '_')}",
            f"attack.{tactic}",
        ],
        "logsource": logsource,
        "detection": detection,
        "falsepositives": [
            "Legitimate administrative activity",
            "Authorized security tooling",
        ],
        "level": "medium",
    }


# ---------------------------------------------------------------------------
# Core public API
# ---------------------------------------------------------------------------

def generate_rules(
    pairs: list[tuple[str, str]],
    design_name: str = "",
    validate: bool = False,
) -> list[str]:
    """Accept (technique_id, signal_source) pairs; return Sigma YAML rule strings.

    Args:
        pairs: List of (tid, src) — e.g. [("T1059", "src-os-log"), ...]
        design_name: Optional label embedded in rule titles.
        validate: If True and sigma-cli is installed, validate each rule.

    Returns:
        List of Sigma YAML strings (one per pair, same order).
    """
    rules: list[str] = []
    for tid, src in pairs:
        rule_dict = _build_rule(tid, src, design_name)
        rule_yaml = yaml.dump(
            rule_dict, default_flow_style=False, allow_unicode=True, sort_keys=False
        )
        if validate:
            _validate_with_sigma_cli(rule_yaml)
        rules.append(rule_yaml)
    return rules


def validate_rule(rule_yaml: str) -> bool:
    """Run sigma-cli check on a rule string. Returns True when valid or tool absent."""
    return _validate_with_sigma_cli(rule_yaml)


def _validate_with_sigma_cli(yaml_text: str) -> bool:
    """Check rule via sigma-cli if available; silently passes when not installed."""
    if not shutil.which("sigma"):
        return True
    try:
        result = subprocess.run(
            ["sigma", "check", "-"],
            input=yaml_text.encode(),
            capture_output=True,
            timeout=10,
        )
        return result.returncode == 0
    except Exception:
        return True


# ---------------------------------------------------------------------------
# ODC graph-facing wrapper (consumed by blueprint.py)
# ---------------------------------------------------------------------------

def generate_sigma_rules(graph: dict, design_name: str = "") -> dict:
    """Generate Sigma rules from an ODC design graph.

    Extracts uncovered (covered=false) technique × source combinations from
    the cmp-baseline node, then calls generate_rules().

    Returns dict with: rule_count, rules, exports (sigma_yaml, splunk_spl,
    elastic_kql, sentinel_kql), volume_estimate, generated_at.
    """
    nodes: list[dict] = graph.get("nodes", [])
    src_types = [n["type"] for n in nodes if n.get("type", "").startswith("src-")]

    pairs: list[tuple[str, str]] = []
    for node in nodes:
        if node.get("type") == "cmp-baseline":
            cfg = node.get("config_json") or {}
            for tech in cfg.get("techniques", []):
                if not tech.get("covered", True) and src_types:
                    for src in src_types:
                        pairs.append((tech["id"], src))
            break

    if not pairs and src_types:
        for src in src_types:
            pairs.append(("T1059", src))

    yaml_rules = generate_rules(pairs, design_name=design_name)
    combined_yaml = "\n---\n".join(yaml_rules) if yaml_rules else "# No uncovered techniques\n"

    return {
        "rule_count": len(yaml_rules),
        "rules": yaml_rules,
        "exports": {
            "sigma_yaml": combined_yaml,
            "splunk_spl": _to_splunk(yaml_rules),
            "elastic_kql": _to_elastic(yaml_rules),
            "sentinel_kql": _to_sentinel(yaml_rules),
        },
        "volume_estimate": estimate_log_volume(nodes),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# SIEM format converters
# ---------------------------------------------------------------------------
# These thin adapters delegate to the field-mapped exporters/ modules
# (ECS/CIM/Sentinel-table aware). They keep their historical names and
# list[str] -> str signatures so blueprint.py's export route and the
# generate_sigma_rules() response envelope stay unchanged.

def _to_splunk(yaml_rules: list[str]) -> str:
    """Convert Sigma YAML rules to a Splunk SPL script (CIM field-mapped)."""
    from tools.observability_canvas.exporters.splunk import batch_to_spl

    return batch_to_spl(yaml_rules)


def _to_elastic(yaml_rules: list[str]) -> str:
    """Convert Sigma YAML rules to Elasticsearch Query DSL JSON (ECS field-mapped)."""
    from tools.observability_canvas.exporters.elastic import batch_to_eql

    return batch_to_eql(yaml_rules)


def _to_sentinel(yaml_rules: list[str]) -> str:
    """Convert Sigma YAML rules to Microsoft Sentinel KQL queries (table-mapped)."""
    from tools.observability_canvas.exporters.sentinel import batch_to_kql

    return batch_to_kql(yaml_rules)


# ---------------------------------------------------------------------------
# Log volume / cost estimation
# ---------------------------------------------------------------------------

_SRC_DAILY_GB: dict[str, float] = {
    "src-app-log":       5.0,
    "src-os-log":        8.0,
    "src-network-log":   20.0,
    "src-cloud-log":     3.0,
    "src-container-log": 10.0,
    "src-db-audit":      2.0,
    "src-wef":           15.0,
    "src-flow":          50.0,
    "src-pcap":          200.0,
    "src-endpoint":      5.0,
    "src-metric":        1.0,
    "src-trace":         2.0,
    "src-vulnerability": 0.5,
    "src-iam":           1.0,
}

_SIEM_COST_PER_GB_MONTH: dict[str, float] = {
    "splunk":   150.0,
    "elastic":  95.0,
    "sentinel": 2.46,
}


def estimate_log_volume(nodes: list[dict], retention_days: int = 90) -> dict:
    """Estimate daily log ingestion volume and SIEM cost for ODC design nodes.

    Args:
        nodes: List of graph nodes from an ODC design.
        retention_days: Retention window used for storage cost projection.

    Returns:
        Dict with daily_gb, monthly_gb, retention_gb, platform cost breakdown,
        and convenience keys estimated_cost_{splunk,elastic,sentinel}.
    """
    daily_gb = sum(_SRC_DAILY_GB.get(n.get("type", ""), 0.0) for n in nodes)
    monthly_gb = daily_gb * 30
    retention_gb = daily_gb * retention_days

    platforms: dict[str, dict] = {}
    for platform, cost_per_gb in _SIEM_COST_PER_GB_MONTH.items():
        monthly_cost = monthly_gb * cost_per_gb
        retention_cost = (retention_gb * cost_per_gb) / 30
        platforms[platform] = {
            "monthly_cost_usd": round(monthly_cost, 2),
            "retention_cost_usd": round(retention_cost, 2),
            "cost_per_gb_month": cost_per_gb,
        }

    return {
        "daily_gb": round(daily_gb, 2),
        "monthly_gb": round(monthly_gb, 2),
        "retention_days": retention_days,
        "retention_gb": round(retention_gb, 2),
        "platforms": platforms,
        "estimated_cost_splunk":   platforms["splunk"]["monthly_cost_usd"],
        "estimated_cost_elastic":  platforms["elastic"]["monthly_cost_usd"],
        "estimated_cost_sentinel": platforms["sentinel"]["monthly_cost_usd"],
    }
