"""ODC IaC Generator — ODC Workflow Step 3.

Generates Terraform, Ansible, and validation artifacts for observability infrastructure.
Outputs JSON with artifact paths to stdout.
"""
import argparse
import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_ROOT))

_ARTIFACTS_DIR = _ROOT / "data" / "studio_artifacts" / "odc"

# ── Terraform resource blocks ────────────────────────────────────────────────

_TF_HEADER = '''\
# Observability Infrastructure — Generated by ICDEV™ ODC Workflow
# Canvas: odc
# Generated: {ts}
# DO NOT EDIT — regenerate via ODC Workflow

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
  required_version = ">= 1.6.0"
}}

provider "aws" {{
  region = var.aws_region
}}

locals {{
  common_tags = {{
    ManagedBy   = "icdev-odc"
    Environment = var.environment
    Canvas      = "odc"
  }}
}}

# ── KMS Key for Log Encryption ────────────────────────────────────────────────

resource "aws_kms_key" "odc_logs" {{
  description             = "ICDEV ODC log encryption key"
  deletion_window_in_days = 30
  enable_key_rotation     = true
  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Sid    = "AllowCloudWatchLogs"
        Effect = "Allow"
        Principal = {{
          Service = "logs.${{data.aws_region.current.name}}.amazonaws.com"
        }}
        Action   = ["kms:Encrypt", "kms:Decrypt", "kms:GenerateDataKey*", "kms:DescribeKey"]
        Resource = "*"
      }},
      {{
        Sid       = "AllowKeyAdministration"
        Effect    = "Allow"
        Principal = {{ AWS = "arn:aws:iam::${{data.aws_caller_identity.current.account_id}}:root" }}
        Action    = "kms:*"
        Resource  = "*"
      }},
    ]
  }})
  tags = local.common_tags
}}

resource "aws_kms_alias" "odc_logs_alias" {{
  name          = "alias/icdev-odc-logs"
  target_key_id = aws_kms_key.odc_logs.key_id
}}

# ── CloudWatch Log Groups ─────────────────────────────────────────────────────

resource "aws_cloudwatch_log_group" "app_logs" {{
  name              = "/icdev/${{var.environment}}/app"
  retention_in_days = var.retention_days
  kms_key_id        = aws_kms_key.odc_logs.arn
  tags              = local.common_tags
}}

resource "aws_cloudwatch_log_group" "security_logs" {{
  name              = "/icdev/${{var.environment}}/security"
  retention_in_days = var.retention_days
  kms_key_id        = aws_kms_key.odc_logs.arn
  tags              = local.common_tags
}}

# ── SNS Topic — Alert Notifications ─────────────────────────────────────────

resource "aws_sns_topic" "alerts" {{
  name = "icdev-odc-alerts-${{var.environment}}"
  tags = local.common_tags
}}

resource "aws_sns_topic_subscription" "alerts_email" {{
  topic_arn = aws_sns_topic.alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}}

# ── CloudWatch Metric Alarms ──────────────────────────────────────────────────

resource "aws_cloudwatch_metric_alarm" "high_cpu" {{
  alarm_name          = "icdev-${{var.environment}}-high-cpu"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 2
  metric_name         = "CPUUtilization"
  namespace           = "AWS/ECS"
  period              = 300
  statistic           = "Average"
  threshold           = 80
  alarm_description   = "CPU utilization above 80% for 10 minutes"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  ok_actions          = [aws_sns_topic.alerts.arn]
  tags                = local.common_tags
}}

resource "aws_cloudwatch_metric_alarm" "high_error_rate" {{
  alarm_name          = "icdev-${{var.environment}}-high-error-rate"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 2
  metric_name         = "HTTPCode_Target_5XX_Count"
  namespace           = "AWS/ApplicationELB"
  period              = 300
  statistic           = "Sum"
  threshold           = 10
  alarm_description   = "5xx error count above 10 in 10 minutes"
  alarm_actions       = [aws_sns_topic.alerts.arn]
  treat_missing_data  = "notBreaching"
  tags                = local.common_tags
}}

# ── CloudWatch Dashboard ──────────────────────────────────────────────────────

resource "aws_cloudwatch_dashboard" "ops" {{
  dashboard_name = "icdev-${{var.environment}}-ops"
  dashboard_body = jsonencode({{
    widgets = [
      {{
        type       = "metric"
        x          = 0
        y          = 0
        width      = 12
        height     = 6
        properties = {{
          title   = "CPU Utilization"
          metrics = [["AWS/ECS", "CPUUtilization", {{stat = "Average"}}]]
          period  = 300
          view    = "timeSeries"
        }}
      }},
      {{
        type       = "metric"
        x          = 12
        y          = 0
        width      = 12
        height     = 6
        properties = {{
          title   = "HTTP 5xx Errors"
          metrics = [["AWS/ApplicationELB", "HTTPCode_Target_5XX_Count", {{stat = "Sum"}}]]
          period  = 300
          view    = "timeSeries"
        }}
      }},
      {{
        type       = "log"
        x          = 0
        y          = 6
        width      = 24
        height     = 6
        properties = {{
          title   = "Application Log Errors (last 1h)"
          query   = "SOURCE '/icdev/${{var.environment}}/app' | fields @timestamp, @message | filter @message like /ERROR/ | sort @timestamp desc | limit 100"
          view    = "table"
          region  = var.aws_region
        }}
      }},
    ]
  }})
}}

# ── Amazon Managed Prometheus ─────────────────────────────────────────────────

resource "aws_prometheus_workspace" "odc" {{
  alias = "icdev-${{var.environment}}-prometheus"
  tags  = local.common_tags
}}

# ── SSM Parameter Store ───────────────────────────────────────────────────────

resource "aws_ssm_parameter" "odc_config" {{
  name  = "/icdev/odc/config"
  type  = "SecureString"
  value = jsonencode({{
    environment       = var.environment
    app_log_group     = aws_cloudwatch_log_group.app_logs.name
    security_log_group = aws_cloudwatch_log_group.security_logs.name
    sns_topic_arn     = aws_sns_topic.alerts.arn
    prometheus_endpoint = aws_prometheus_workspace.odc.prometheus_endpoint
    retention_days    = var.retention_days
  }})
  key_id = aws_kms_key.odc_logs.key_id
  tags   = local.common_tags
}}

# ── Data Sources ──────────────────────────────────────────────────────────────

data "aws_caller_identity" "current" {{}}
data "aws_region" "current" {{}}
'''

_TF_VARIABLES = '''\
# variables.tf — Generated by ICDEV™ ODC Workflow

variable "aws_region" {{
  type    = string
  default = "us-gov-west-1"
}}

variable "vpc_id" {{
  type        = string
  description = "VPC ID for observability infrastructure"
}}

variable "private_subnet_ids" {{
  type        = list(string)
  description = "Private subnet IDs"
}}

variable "artifacts_bucket" {{
  type        = string
  description = "S3 bucket for deployment artifacts"
  default     = ""
}}

variable "db_password" {{
  type      = string
  sensitive = true
  default   = ""
}}

variable "dw_password" {{
  type      = string
  sensitive = true
  default   = ""
}}

variable "environment" {{
  type    = string
  default = "dev"
}}

variable "alert_email" {{
  type        = string
  description = "Email address for alert notifications"
  default     = "ops@example.com"
}}

variable "retention_days" {{
  type        = number
  description = "Log retention period in days (minimum 90 per NIST SP 800-92)"
  default     = 90
}}
'''

_TFVARS_EXAMPLE = '''\
# terraform.tfvars.example — ODC Observability Infrastructure
# Copy to terraform.tfvars and fill in real values before running terraform apply

aws_region         = "us-gov-west-1"
vpc_id             = "vpc-xxxxxxxxxxxxxxxxx"
private_subnet_ids = ["subnet-xxxxxxxxxxxxxxxxx", "subnet-yyyyyyyyyyyyyyyyy"]
environment        = "dev"
alert_email        = "ops@example.com"
retention_days     = 90
'''

_ANSIBLE_PLAYBOOK = '''\
---
# Ansible Playbook — ODC Observability Agent Setup
# Generated: {ts}
# Run after: terraform apply

- name: ODC Observability Agent Configuration
  hosts: app_servers
  become: true
  gather_facts: true

  vars:
    cloudwatch_agent_version: "latest"
    prometheus_exporter_port: 9100
    log_group_app: "/icdev/{{ environment | default('dev') }}/app"

  tasks:
    - name: Download CloudWatch Agent
      ansible.builtin.get_url:
        url: "https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm"
        dest: /tmp/amazon-cloudwatch-agent.rpm
        mode: "0644"
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Install CloudWatch Agent (RPM)
      ansible.builtin.yum:
        name: /tmp/amazon-cloudwatch-agent.rpm
        state: present
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: Configure CloudWatch Agent
      ansible.builtin.copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {{
            "logs": {{
              "logs_collected": {{
                "files": {{
                  "collect_list": [
                    {{
                      "file_path": "/var/log/app/*.log",
                      "log_group_name": "{{ log_group_app }}",
                      "log_stream_name": "{{ inventory_hostname }}/app",
                      "timestamp_format": "%Y-%m-%d %H:%M:%S"
                    }},
                    {{
                      "file_path": "/var/log/secure",
                      "log_group_name": "/icdev/{{ environment | default('dev') }}/security",
                      "log_stream_name": "{{ inventory_hostname }}/secure"
                    }}
                  ]
                }}
              }}
            }},
            "metrics": {{
              "namespace": "ICDEV/App",
              "metrics_collected": {{
                "cpu": {{"measurement": ["cpu_usage_idle", "cpu_usage_user", "cpu_usage_system"]}},
                "disk": {{"measurement": ["used_percent"], "resources": ["*"]}},
                "mem": {{"measurement": ["mem_used_percent"]}}
              }}
            }}
          }}
        mode: "0644"

    - name: Start CloudWatch Agent
      ansible.builtin.service:
        name: amazon-cloudwatch-agent
        state: started
        enabled: true
      ignore_errors: true

    - name: Install Prometheus Node Exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/latest/download/node_exporter-linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz
        mode: "0644"
      ignore_errors: true

    - name: Configure log shipping to CloudWatch
      ansible.builtin.debug:
        msg: "Log shipping configured for {{ inventory_hostname }} to {{ log_group_app }}"

    - name: Verify observability agents
      ansible.builtin.debug:
        msg: "ODC observability agents configured on {{ inventory_hostname }}"
'''

_VALIDATION_SCRIPT = '''\
#!/usr/bin/env python3
"""ODC Observability Infrastructure Validation — Generated by ICDEV™ ODC Workflow
Generated: {ts}

Run after terraform apply to verify all observability resources are active.
Usage:
  pip install boto3
  python validate_{uid}.py --region us-gov-west-1 [--profile <aws-profile>]
"""
import argparse
import sys
import boto3


def check(label, ok, detail=""):
    status = "PASS" if ok else "FAIL"
    msg = "  [" + status + "] " + str(label)
    if detail:
        msg += " -- " + str(detail)
    print(msg)
    return ok


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--region", default="us-gov-west-1")
    parser.add_argument("--profile", default=None)
    parser.add_argument("--environment", default="dev")
    args = parser.parse_args()

    session = boto3.Session(region_name=args.region, profile_name=args.profile)
    passed = 0
    failed = 0
    env = args.environment
    print("\\n=== ODC Observability Validation ===\\n")

    # Check CloudWatch log groups
    try:
        cw = session.client("logs")
        groups = cw.describe_log_groups(logGroupNamePrefix="/icdev/" + env + "/")["logGroups"]
        ok = check("CloudWatch log groups (/icdev/" + env + "/)", len(groups) >= 2,
                   str(len(groups)) + " group(s) found")
        passed += ok
        failed += not ok
    except Exception as e:
        ok = check("CloudWatch log groups", False, str(e))
        passed += ok
        failed += not ok

    # Check CloudWatch alarms
    try:
        cw = session.client("cloudwatch")
        alarms = cw.describe_alarms(AlarmNamePrefix="icdev-" + env + "-")["MetricAlarms"]
        ok = check("CloudWatch alarms (icdev-" + env + "-*)", len(alarms) >= 1,
                   str(len(alarms)) + " alarm(s)")
        passed += ok
        failed += not ok
    except Exception as e:
        ok = check("CloudWatch alarms", False, str(e))
        passed += ok
        failed += not ok

    # Check SNS topics
    try:
        sns = session.client("sns")
        topics = sns.list_topics()["Topics"]
        ok = check("SNS alert topic", bool(topics), str(len(topics)) + " topic(s)")
        passed += ok
        failed += not ok
    except Exception as e:
        ok = check("SNS topics", False, str(e))
        passed += ok
        failed += not ok

    # Check Prometheus workspace
    try:
        amp = session.client("amp")
        workspaces = amp.list_workspaces()["workspaces"]
        ok = check("Prometheus workspace", bool(workspaces), str(len(workspaces)) + " workspace(s)")
        passed += ok
        failed += not ok
    except Exception as e:
        ok = check("Prometheus workspace", False, str(e))
        passed += ok
        failed += not ok

    print("\\n=== Result: " + str(passed) + " passed, " + str(failed) + " failed ===\\n")
    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
'''

_IAC_REPORT = '''\
# ODC IaC Generation Report
**Generated:** {ts}
**Project:** {project_id}
**Canvas:** odc

## Generated Artifacts

| Artifact | Path | Description |
|----------|------|-------------|
| Terraform Main | `{main_tf}` | CloudWatch, SNS, Prometheus, KMS |
| Terraform Variables | `{vars_tf}` | Variable declarations |
| Terraform tfvars | `{tfvars}` | Example variable values |
| Ansible Playbook | `{ansible_pb}` | CloudWatch agent + Prometheus exporters |
| Validation Script | `{validate_py}` | Post-deploy boto3 checks |
| This Report | `{report_path}` | IaC generation summary |

## Resources Provisioned

- `aws_cloudwatch_log_group` (app) — Application logs, {retention_days}-day retention, KMS encrypted
- `aws_cloudwatch_log_group` (security) — Security logs, {retention_days}-day retention, KMS encrypted
- `aws_cloudwatch_metric_alarm` (high_cpu) — CPU utilization > 80% for 10 min
- `aws_cloudwatch_metric_alarm` (high_error_rate) — HTTP 5xx count > 10 in 10 min
- `aws_cloudwatch_dashboard` — Operations dashboard with CPU, errors, and log widgets
- `aws_sns_topic` + subscription — Alert notifications via email
- `aws_prometheus_workspace` — Amazon Managed Prometheus for metrics collection
- `aws_kms_key` + alias — Log encryption key with auto-rotation
- `aws_ssm_parameter` — Encrypted observability configuration

## Apply Instructions

```bash
cp terraform.tfvars.example terraform.tfvars
# Edit terraform.tfvars — fill in vpc_id, alert_email
terraform init
terraform plan -var-file=terraform.tfvars
terraform apply -var-file=terraform.tfvars
python validate_{uid}.py --region us-gov-west-1 --environment dev
```

## Compliance

- Log retention: {retention_days} days (NIST SP 800-92 minimum: 90 days)
- Log encryption: KMS (NIST SC-28)
- Alert notifications: SNS email (NIST IR-6)

## Approval Required

**Approver Role:** `soc_lead`
Obtain SOC Lead sign-off before applying to production environments.
'''


def generate_iac(project_id: str) -> dict:
    _ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    tf_dir = _ARTIFACTS_DIR / "terraform"
    tf_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    uid = uuid.uuid4().hex[:8]

    main_tf = tf_dir / f"main_{uid}.tf"
    vars_tf = tf_dir / "variables.tf"
    tfvars = tf_dir / "terraform.tfvars.example"
    ansible_pb = _ARTIFACTS_DIR / f"ansible_playbook_{uid}.yml"
    validate_py = _ARTIFACTS_DIR / f"validate_{uid}.py"
    report_path = _ARTIFACTS_DIR / f"iac_report_{uid}.md"

    main_tf.write_text(_TF_HEADER.format(ts=ts), encoding="utf-8", newline="")
    vars_tf.write_text(_TF_VARIABLES, encoding="utf-8", newline="")
    tfvars.write_text(_TFVARS_EXAMPLE, encoding="utf-8", newline="")
    ansible_pb.write_text(_ANSIBLE_PLAYBOOK.format(ts=ts), encoding="utf-8", newline="")
    validate_py.write_text(_VALIDATION_SCRIPT.format(ts=ts, uid=uid), encoding="utf-8", newline="")

    report_md = _IAC_REPORT.format(
        ts=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        project_id=project_id,
        main_tf=main_tf.relative_to(_ROOT).as_posix(),
        vars_tf=vars_tf.relative_to(_ROOT).as_posix(),
        tfvars=tfvars.relative_to(_ROOT).as_posix(),
        ansible_pb=ansible_pb.relative_to(_ROOT).as_posix(),
        validate_py=validate_py.relative_to(_ROOT).as_posix(),
        report_path=report_path.relative_to(_ROOT).as_posix(),
        uid=uid,
        retention_days=90,
    )
    report_path.write_text(report_md, encoding="utf-8", newline="")

    return {
        "uid": uid,
        "main_tf": main_tf.relative_to(_ROOT).as_posix(),
        "vars_tf": vars_tf.relative_to(_ROOT).as_posix(),
        "tfvars": tfvars.relative_to(_ROOT).as_posix(),
        "ansible_pb": ansible_pb.relative_to(_ROOT).as_posix(),
        "validate_py": validate_py.relative_to(_ROOT).as_posix(),
        "report_path": report_path.relative_to(_ROOT).as_posix(),
    }


def main():
    parser = argparse.ArgumentParser(description="ODC IaC Generator")
    parser.add_argument("--project-id", default="default")
    parser.add_argument("--run-id", default="")
    parser.add_argument("--canvas", default="odc")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    try:
        result = generate_iac(args.project_id)

        output = {
            "gate": "PASS",
            "canvas": "odc",
            "artifacts": [
                {"name": "Terraform Main", "path": result["main_tf"], "type": "tf"},
                {"name": "Terraform Variables", "path": result["vars_tf"], "type": "tf"},
                {"name": "Terraform tfvars", "path": result["tfvars"], "type": "tf"},
                {"name": "Ansible Observability Agent Playbook", "path": result["ansible_pb"], "type": "yml"},
                {"name": "Validation Script", "path": result["validate_py"], "type": "py"},
                {"name": "IaC Generation Report", "path": result["report_path"], "type": "md"},
            ],
        }
        print(json.dumps(output))
        sys.exit(0)
    except Exception as exc:
        print(json.dumps({"gate": "FAIL", "canvas": "odc", "error": str(exc), "artifacts": []}))
        sys.exit(1)


if __name__ == "__main__":
    main()
