
# CUI // SP-CTI
"""Connector Forge Templates — inline Jinja2 connector skeletons (D-CF-3).

8 template string constants, one per protocol family.
Uses Jinja2 with string-replacement fallback for air-gap safety.
"""

# ---------------------------------------------------------------------------
# REST / SaaS API
# ---------------------------------------------------------------------------

REST_CONNECTOR_TEMPLATE = '''# CUI // SP-CTI
"""{{ display_name }} Connector — generated by Connector Forge.

Protocol: REST
Base: SaaSBaseConnector
Generated: {{ generated_at }}
"""
import logging
from typing import Any, Dict

from tools.databridge.connector import ConnectorCapabilities, ConnectorType  # noqa: F401
from tools.databridge.connectors.saas_base import SaaSBaseConnector
from tools.databridge.registry import register_connector

logger = get_logger("databridge.connectors.{{ connector_name }}")


@register_connector
class {{ class_name }}(SaaSBaseConnector):
    """{{ display_name }} connector (forge-generated)."""

    _connector_name = "{{ connector_name }}"
    _connector_type = ConnectorType.SAAS_API
    _capabilities = ConnectorCapabilities(
        supports_read={{ supports_read }},
        supports_write={{ supports_write }},
        supports_schema_inference=True,
        supports_incremental={{ supports_incremental }},
        max_batch_size={{ max_batch_size }},
        supported_formats=["arrow", "json"],
    )

    @property
    def connector_name(self) -> str:
        return "{{ connector_name }}"

    def _base_url(self, config: Dict[str, Any]) -> str:
        return config.get("base_url", "{{ base_url }}")

    def _auth_headers(self, config: Dict[str, Any]) -> Dict[str, str]:
        token = config.get("_resolved_secret") or config.get("api_key", "")
        return {"Authorization": f"Bearer {token}"}

    def _read_endpoint(self, table_name: str) -> str:
        endpoints = {{ endpoint_map }}
        return f"{self._base}/{endpoints.get(table_name, table_name)}"

    def _parse_response(self, resp_json: Any) -> tuple:
        if isinstance(resp_json, list):
            return resp_json, None
        if isinstance(resp_json, dict):
            data = (resp_json.get("data") or resp_json.get("results")
                    or resp_json.get("items") or [])
            next_cursor = resp_json.get("next") or resp_json.get("nextPageToken")
            return data, next_cursor
        return [], None

    def list_tables(self) -> list:
        return {{ table_names }}
'''

# ---------------------------------------------------------------------------
# GraphQL
# ---------------------------------------------------------------------------

GRAPHQL_CONNECTOR_TEMPLATE = '''# CUI // SP-CTI
"""{{ display_name }} Connector — generated by Connector Forge.

Protocol: GraphQL
Base: SaaSBaseConnector
Generated: {{ generated_at }}
"""
import json
import logging
from typing import Any, Dict, List, Optional

from tools.databridge.connector import ConnectorCapabilities, ConnectorType
from tools.databridge.connectors.saas_base import SaaSBaseConnector
from tools.databridge.registry import register_connector

logger = get_logger("databridge.connectors.{{ connector_name }}")

try:
    import requests as _requests
    HAS_REQUESTS = True
except ImportError:
    _requests = None
    HAS_REQUESTS = False


@register_connector
class {{ class_name }}(SaaSBaseConnector):
    """{{ display_name }} connector — GraphQL (forge-generated)."""

    _connector_name = "{{ connector_name }}"
    _connector_type = ConnectorType.SAAS_API
    _capabilities = ConnectorCapabilities(
        supports_read=True,
        supports_write={{ supports_write }},
        supports_schema_inference=True,
        max_batch_size={{ max_batch_size }},
        supported_formats=["arrow", "json"],
    )

    @property
    def connector_name(self) -> str:
        return "{{ connector_name }}"

    def _base_url(self, config: Dict[str, Any]) -> str:
        return config.get("base_url", "{{ base_url }}")

    def _auth_headers(self, config: Dict[str, Any]) -> Dict[str, str]:
        token = config.get("_resolved_secret") or config.get("api_key", "")
        return {"Authorization": f"Bearer {token}"}

    def _read_endpoint(self, table_name: str) -> str:
        return self._base

    def _parse_response(self, resp_json: Any) -> tuple:
        if isinstance(resp_json, dict):
            data = resp_json.get("data", {})
            if isinstance(data, dict):
                for key in data:
                    val = data[key]
                    if isinstance(val, list):
                        return val, None
                    if isinstance(val, dict) and "edges" in val:
                        nodes = [e.get("node", e) for e in val["edges"]]
                        cursor = val.get("pageInfo", {}).get("endCursor")
                        return nodes, cursor
            return [data] if data else [], None
        return [], None

    def list_tables(self) -> list:
        return {{ table_names }}
'''

# ---------------------------------------------------------------------------
# SOAP / WSDL
# ---------------------------------------------------------------------------

SOAP_CONNECTOR_TEMPLATE = '''# CUI // SP-CTI
"""{{ display_name }} Connector — generated by Connector Forge.

Protocol: SOAP/WSDL
Base: SoapBaseConnector
Generated: {{ generated_at }}
"""
import logging
from typing import Any, Dict, List, Optional

from tools.databridge.connector import ConnectorCapabilities, ConnectorType
from tools.databridge.connectors.soap_base import SoapBaseConnector
from tools.databridge.registry import register_connector

logger = get_logger("databridge.connectors.{{ connector_name }}")


@register_connector
class {{ class_name }}(SoapBaseConnector):
    """{{ display_name }} connector — SOAP (forge-generated)."""

    _connector_name = "{{ connector_name }}"
    _connector_type = ConnectorType.SOAP
    _capabilities = ConnectorCapabilities(
        supports_read=True,
        supports_write=True,
        supports_schema_inference=True,
        max_batch_size=1000,
        supported_formats=["arrow", "json"],
    )

    @property
    def connector_name(self) -> str:
        return "{{ connector_name }}"

    def _wsdl_url(self, config: Dict[str, Any]) -> str:
        return config.get("wsdl_url", "{{ base_url }}")

    def _operation_name(self, table_name: str) -> str:
        ops = {{ endpoint_map }}
        return ops.get(table_name, table_name)

    def list_tables(self) -> list:
        tables = super().list_tables()
        return tables if tables else {{ table_names }}
'''

# ---------------------------------------------------------------------------
# SQL / ODBC
# ---------------------------------------------------------------------------

SQL_CONNECTOR_TEMPLATE = '''# CUI // SP-CTI
"""{{ display_name }} Connector — generated by Connector Forge.

Protocol: SQL
Base: DataConnector (direct)
Generated: {{ generated_at }}
"""
import logging
import time
from typing import Any, Dict, List, Optional

from tools.databridge.connector import (
    ConnectorCapabilities, ConnectorRequest, ConnectorResponse,
    ConnectorType, DataConnector, SchemaDefinition, SchemaField,
)
from tools.databridge.registry import register_connector

logger = get_logger("databridge.connectors.{{ connector_name }}")


@register_connector
class {{ class_name }}(DataConnector):
    """{{ display_name }} connector — SQL (forge-generated)."""

    _connector_name = "{{ connector_name }}"
    _capabilities = ConnectorCapabilities(
        supports_read=True,
        supports_write={{ supports_write }},
        supports_schema_inference=True,
        supports_transactions=True,
        max_batch_size={{ max_batch_size }},
        supported_formats=["arrow", "json"],
    )

    def __init__(self) -> None:
        self._conn = None
        self._config: Dict[str, Any] = {}

    @property
    def connector_type(self) -> ConnectorType:
        return ConnectorType.DATABASE

    @property
    def connector_name(self) -> str:
        return "{{ connector_name }}"

    @property
    def capabilities(self) -> ConnectorCapabilities:
        return self._capabilities

    def connect(self, config: Dict[str, Any]) -> bool:
        self._config = config
        return True

    def disconnect(self) -> None:
        if self._conn:
            self._conn.close()
            self._conn = None

    def health_check(self) -> Dict[str, Any]:
        return {"status": "healthy" if self._conn else "unhealthy"}

    def read(self, request: ConnectorRequest) -> ConnectorResponse:
        return ConnectorResponse(status="ok", data=[], row_count=0)

    def infer_schema(self, table_name: str) -> SchemaDefinition:
        return SchemaDefinition(metadata={"source": self.connector_name})

    def list_tables(self) -> List[str]:
        return {{ table_names }}
'''

# ---------------------------------------------------------------------------
# FTP / SFTP
# ---------------------------------------------------------------------------

FTP_CONNECTOR_TEMPLATE = '''# CUI // SP-CTI
"""{{ display_name }} Connector — generated by Connector Forge.

Protocol: FTP/SFTP
Base: DataConnector (direct)
Generated: {{ generated_at }}
"""
import logging
import time
from typing import Any, Dict, List, Optional

from tools.databridge.connector import (
    ConnectorCapabilities, ConnectorRequest, ConnectorResponse,
    ConnectorType, DataConnector, SchemaDefinition, SchemaField,
)
from tools.databridge.registry import register_connector

logger = get_logger("databridge.connectors.{{ connector_name }}")


@register_connector
class {{ class_name }}(DataConnector):
    """{{ display_name }} connector — FTP/SFTP (forge-generated)."""

    _connector_name = "{{ connector_name }}"
    _capabilities = ConnectorCapabilities(
        supports_read=True,
        supports_write={{ supports_write }},
        supports_schema_inference=False,
        max_batch_size={{ max_batch_size }},
        supported_formats=["json"],
    )

    def __init__(self) -> None:
        self._config: Dict[str, Any] = {}

    @property
    def connector_type(self) -> ConnectorType:
        return ConnectorType.CLOUD_STORAGE

    @property
    def connector_name(self) -> str:
        return "{{ connector_name }}"

    @property
    def capabilities(self) -> ConnectorCapabilities:
        return self._capabilities

    def connect(self, config: Dict[str, Any]) -> bool:
        self._config = config
        return True

    def disconnect(self) -> None:
        pass

    def health_check(self) -> Dict[str, Any]:
        return {"status": "healthy"}

    def read(self, request: ConnectorRequest) -> ConnectorResponse:
        return ConnectorResponse(status="ok", data=[], row_count=0)

    def infer_schema(self, table_name: str) -> SchemaDefinition:
        return SchemaDefinition(metadata={"source": self.connector_name})

    def list_tables(self) -> List[str]:
        return []
'''

# ---------------------------------------------------------------------------
# Messaging
# ---------------------------------------------------------------------------

MESSAGING_CONNECTOR_TEMPLATE = '''# CUI // SP-CTI
"""{{ display_name }} Connector — generated by Connector Forge.

Protocol: Messaging
Base: DataConnector (direct)
Generated: {{ generated_at }}
"""
import logging
from typing import Any, Dict, List, Optional

from tools.databridge.connector import (
    ConnectorCapabilities, ConnectorRequest, ConnectorResponse,
    ConnectorType, DataConnector, SchemaDefinition, SchemaField,
)
from tools.databridge.registry import register_connector

logger = get_logger("databridge.connectors.{{ connector_name }}")


@register_connector
class {{ class_name }}(DataConnector):
    """{{ display_name }} connector — Messaging (forge-generated)."""

    _connector_name = "{{ connector_name }}"
    _capabilities = ConnectorCapabilities(
        supports_read=True,
        supports_write=True,
        supports_streaming=True,
        max_batch_size=100,
        supported_formats=["json"],
    )

    def __init__(self) -> None:
        self._config: Dict[str, Any] = {}

    @property
    def connector_type(self) -> ConnectorType:
        return ConnectorType.MESSAGING

    @property
    def connector_name(self) -> str:
        return "{{ connector_name }}"

    @property
    def capabilities(self) -> ConnectorCapabilities:
        return self._capabilities

    def connect(self, config: Dict[str, Any]) -> bool:
        self._config = config
        return True

    def disconnect(self) -> None:
        pass

    def health_check(self) -> Dict[str, Any]:
        return {"status": "healthy"}

    def read(self, request: ConnectorRequest) -> ConnectorResponse:
        return ConnectorResponse(status="ok", data=[], row_count=0)

    def infer_schema(self, table_name: str) -> SchemaDefinition:
        return SchemaDefinition(fields=[
            SchemaField(name="message_id", data_type="utf8"),
            SchemaField(name="content", data_type="utf8"),
            SchemaField(name="sender", data_type="utf8"),
            SchemaField(name="timestamp", data_type="utf8"),
        ])

    def list_tables(self) -> List[str]:
        return ["messages"]
'''

# ---------------------------------------------------------------------------
# Health (FHIR / HL7v2 / CDA)
# ---------------------------------------------------------------------------

HEALTH_CONNECTOR_TEMPLATE = '''# CUI // SP-CTI
"""{{ display_name }} Connector — generated by Connector Forge.

Protocol: Healthcare (FHIR/HL7)
Base: HealthBaseConnector
Generated: {{ generated_at }}
"""
import logging
from typing import Any, Dict, List, Optional

from tools.databridge.connector import ConnectorCapabilities, ConnectorType
from tools.databridge.connectors.health_base import (
    HealthBaseConnector, HealthProtocol,
)
from tools.databridge.registry import register_connector

logger = get_logger("databridge.connectors.{{ connector_name }}")


@register_connector
class {{ class_name }}(HealthBaseConnector):
    """{{ display_name }} connector — Healthcare (forge-generated)."""

    _connector_name = "{{ connector_name }}"
    _connector_type = ConnectorType.HEALTH
    _capabilities = ConnectorCapabilities(
        supports_read=True,
        supports_write=False,
        supports_schema_inference=True,
        supports_incremental=True,
        max_batch_size=1000,
        supported_formats=["arrow", "json"],
    )

    @property
    def connector_name(self) -> str:
        return "{{ connector_name }}"

    def _protocol(self) -> HealthProtocol:
        return HealthProtocol.FHIR_REST

    def _base_url(self, config: Dict[str, Any]) -> str:
        return config.get("base_url", "{{ base_url }}")

    def _auth_headers(self, config: Dict[str, Any]) -> Dict[str, str]:
        token = config.get("_resolved_secret") or config.get("api_key", "")
        return {"Authorization": f"Bearer {token}"}
'''

# ---------------------------------------------------------------------------
# Raw TCP
# ---------------------------------------------------------------------------

TCP_CONNECTOR_TEMPLATE = '''# CUI // SP-CTI
"""{{ display_name }} Connector — generated by Connector Forge.

Protocol: Raw TCP
Base: DataConnector (direct ABC)
Generated: {{ generated_at }}
"""
import logging
import socket
import time
from typing import Any, Dict, List, Optional

from tools.databridge.connector import (
    ConnectorCapabilities, ConnectorRequest, ConnectorResponse,
    ConnectorType, DataConnector, SchemaDefinition, SchemaField,
)
from tools.databridge.registry import register_connector

logger = get_logger("databridge.connectors.{{ connector_name }}")


@register_connector
class {{ class_name }}(DataConnector):
    """{{ display_name }} connector — Raw TCP (forge-generated)."""

    _connector_name = "{{ connector_name }}"
    _capabilities = ConnectorCapabilities(
        supports_read=True,
        supports_write=True,
        supports_streaming=True,
        max_batch_size=100,
        supported_formats=["json"],
    )

    def __init__(self) -> None:
        self._config: Dict[str, Any] = {}
        self._sock: Optional[socket.socket] = None

    @property
    def connector_type(self) -> ConnectorType:
        return ConnectorType.ON_PREM

    @property
    def connector_name(self) -> str:
        return "{{ connector_name }}"

    @property
    def capabilities(self) -> ConnectorCapabilities:
        return self._capabilities

    def connect(self, config: Dict[str, Any]) -> bool:
        self._config = config
        host = config.get("host", "localhost")
        port = int(config.get("port", 8080))
        try:
            self._sock = socket.create_connection((host, port), timeout=10)
            return True
        except Exception as exc:
            logger.error("TCP connect failed: %s", exc)
            return False

    def disconnect(self) -> None:
        if self._sock:
            self._sock.close()
            self._sock = None

    def health_check(self) -> Dict[str, Any]:
        return {"status": "healthy" if self._sock else "unhealthy"}

    def read(self, request: ConnectorRequest) -> ConnectorResponse:
        if not self._sock:
            return ConnectorResponse(status="error", errors=["Not connected"])
        start = time.time()
        try:
            if request.query:
                self._sock.sendall(request.query.encode("utf-8"))
            data = self._sock.recv(65536)
            rows = [{"raw_data": data.decode("utf-8", errors="replace")}]
            return ConnectorResponse(
                status="ok", data=rows, row_count=1,
                duration_ms=int((time.time() - start) * 1000),
            )
        except Exception as exc:
            return ConnectorResponse(
                status="error", errors=[str(exc)],
                duration_ms=int((time.time() - start) * 1000),
            )

    def infer_schema(self, table_name: str) -> SchemaDefinition:
        return SchemaDefinition(fields=[
            SchemaField(name="raw_data", data_type="utf8"),
        ])

    def list_tables(self) -> List[str]:
        return []
'''

# ---------------------------------------------------------------------------
# Template registry
# ---------------------------------------------------------------------------

TEMPLATE_MAP = {
    "rest_connector": REST_CONNECTOR_TEMPLATE,
    "graphql_connector": GRAPHQL_CONNECTOR_TEMPLATE,
    "soap_connector": SOAP_CONNECTOR_TEMPLATE,
    "sql_connector": SQL_CONNECTOR_TEMPLATE,
    "ftp_connector": FTP_CONNECTOR_TEMPLATE,
    "messaging_connector": MESSAGING_CONNECTOR_TEMPLATE,
    "health_connector": HEALTH_CONNECTOR_TEMPLATE,
    "tcp_connector": TCP_CONNECTOR_TEMPLATE,
}
