"""AppForge Build Reflex — create standalone child app from blueprint.

GREEN tier. Auto-builds Flask app with DB, seed data, professional UI.
Uses ICDEV™ child_app_generator patterns where possible.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from tools.daemon.base import utcnow_iso  # noqa: E402
from tools.db.storage import get_connection  # noqa: E402

APPS_DIR = BASE_DIR / "apps"


def run(config: Dict[str, Any], trust) -> Dict[str, Any]:
    """Build child app from architected challenge blueprint."""
    conn = get_connection()
    try:
        # Find architected challenge
        challenge = conn.execute("SELECT * FROM appforge_challenges WHERE status = 'architected' LIMIT 1").fetchone()
        if not challenge:
            return {
                "success": True,
                "metric_value": 0.0,
                "details": {"action": "none", "reason": "No architected challenge"},
            }

        challenge = dict(challenge)
        blueprint = json.loads(challenge.get("app_path", "{}"))
        if not blueprint:
            return {"success": False, "metric_value": 0.0, "details": {"error": "No blueprint found"}}

        app_name = blueprint["app_name"]
        app_dir = APPS_DIR / app_name
        port = blueprint["tech_stack"]["port"]

        # Mark as building
        conn.execute(
            "UPDATE appforge_challenges SET status = 'building' WHERE challenge_id = %s",
            (challenge["challenge_id"],),
        )
        conn.commit()

        # Generate app files
        _generate_app(app_dir, blueprint)

        # Update challenge record
        conn.execute(
            "UPDATE appforge_challenges SET status = 'built', app_path = %s, app_port = %s, built_at = %s "
            "WHERE challenge_id = %s",
            (str(app_dir), port, utcnow_iso(), challenge["challenge_id"]),
        )
        conn.commit()

        return {
            "success": True,
            "metric_value": 1.0,
            "details": {
                "action": "built",
                "challenge_id": challenge["challenge_id"],
                "app_name": app_name,
                "app_path": str(app_dir),
                "port": port,
                "files_created": _count_files(app_dir),
            },
        }
    finally:
        conn.close()


def _generate_app(app_dir: Path, blueprint: Dict[str, Any]) -> None:
    """Generate a complete Flask app from blueprint."""
    app_dir.mkdir(parents=True, exist_ok=True)
    (app_dir / "static" / "css").mkdir(parents=True, exist_ok=True)
    (app_dir / "static" / "js").mkdir(parents=True, exist_ok=True)
    (app_dir / "templates").mkdir(parents=True, exist_ok=True)
    (app_dir / "data").mkdir(parents=True, exist_ok=True)

    title = blueprint["title"]
    app_name = blueprint["app_name"]
    entities = blueprint["entities"]
    relationships = blueprint["relationships"]
    pages = blueprint["pages"]
    port = blueprint["tech_stack"]["port"]
    blueprint.get("pain_points", [])

    # models.py
    (app_dir / "models.py").write_text(_gen_models(entities, relationships), encoding="utf-8", newline="")

    # seed_data.py
    (app_dir / "seed_data.py").write_text(_gen_seed(entities, relationships, blueprint), encoding="utf-8", newline="")

    # app.py
    (app_dir / "app.py").write_text(_gen_app(title, app_name, entities, pages, port), encoding="utf-8", newline="")

    # templates
    (app_dir / "templates" / "base.html").write_text(_gen_base_template(title, pages), encoding="utf-8", newline="")
    for page in pages:
        slug = page.lower().replace(" ", "_")
        (app_dir / "templates" / f"{slug}.html").write_text(_gen_page_template(page, slug, entities), encoding="utf-8", newline="")

    # CSS
    vertical = blueprint.get("vertical", "")
    (app_dir / "static" / "css" / "app.css").write_text(_gen_css(vertical), encoding="utf-8", newline="")

    # JS
    (app_dir / "static" / "js" / "app.js").write_text(f"/* {title} — Generated by AppForge */\n", encoding="utf-8", newline="")

    # requirements.txt
    (app_dir / "requirements.txt").write_text("flask>=3.0\n", encoding="utf-8", newline="")


def _gen_models(entities: list[str], relationships: list[str]) -> str:
    """Generate models.py with entity tables + KG edges."""
    tables = []
    for entity in entities:
        tbl = entity.lower() + "s"
        tables.append(f"""
CREATE TABLE IF NOT EXISTS {tbl} (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    lat         REAL,
    lon         REAL,
    status      TEXT DEFAULT 'active',
    score       REAL DEFAULT 0.0,
    metadata    TEXT,
    created_at  TEXT DEFAULT (datetime('now'))
);""")

    tables.append("""
CREATE TABLE IF NOT EXISTS kg_edges (
    edge_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    source_type TEXT NOT NULL,
    source_id   TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id   TEXT NOT NULL,
    relation    TEXT NOT NULL,
    weight      REAL DEFAULT 1.0,
    metadata    TEXT,
    created_at  TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_kg_source ON kg_edges(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_kg_target ON kg_edges(target_type, target_id);""")

    schema = "\n".join(tables)

    return f'''"""Auto-generated models — AppForge."""

from pathlib import Path

DB_PATH = Path(__file__).parent / "data" / "app.db"

SCHEMA = """{schema}
"""

def get_connection():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = get_connection(str(DB_PATH))
    return conn

def init_db():
    conn = get_connection()
    try:
        conn.executescript(SCHEMA)
        conn.commit()
        try:
            from tools.db.storage import list_tables
            tables = list_tables(conn)
        except Exception:
            tables = [r[0] for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type=\'table\' ORDER BY name"
            ).fetchall()]
        return {{"status": "ok", "tables": tables}}
    finally:
        conn.close()
'''  # nosec B608 -- template content, not user input


def _gen_seed(entities: list[str], relationships: list[str], blueprint: Dict) -> str:
    """Generate seed_data.py with realistic demo data."""
    entity_seeds = []
    for entity in entities:
        tbl = entity.lower() + "s"
        entity_seeds.append(f'''
    # Seed {entity}
    for i in range(30):
        conn.execute(
            "INSERT OR IGNORE INTO {tbl} (id, name, description, lat, lon, score) VALUES (?,?,?,?,?,?)",
            (f"{entity.lower()}_{{uuid.uuid4().hex[:8]}}", f"{entity}-{{i+1:03d}}",
             f"Auto-generated {entity.lower()} entity", random.uniform(-40, 60),
             random.uniform(-120, 150), random.uniform(0.3, 0.95))
        )''')

    edge_seeds = []
    for rel in relationships[:5]:
        src = entities[0].lower() + "s"
        tgt = entities[min(1, len(entities) - 1)].lower() + "s"
        edge_seeds.append(
            f'''
    # Seed {rel} edges
    sources = [r[0] for r in conn.execute("SELECT id FROM {src} LIMIT 20").fetchall()]
    targets = [r[0] for r in conn.execute("SELECT id FROM {tgt} LIMIT 20").fetchall()]
    for s in sources:
        for t in random.sample(targets, min(3, len(targets))):
            conn.execute(
                "INSERT INTO kg_edges (source_type, source_id, target_type, target_id, relation, weight) "
                "VALUES (?,?,?,?,?,?)",
                ("{entities[0].lower()}", s, "{entities[min(1, len(entities) - 1)].lower()}", t,
                 "{rel}", random.uniform(0.3, 1.0))
            )'''  # nosec B608 -- template content, not user input
        )

    return f'''"""Auto-generated seed data — AppForge."""
import random
import uuid
from models import get_connection, init_db

def run_seed():
    result = init_db()
    print(f"DB initialized: {{result}}")
    conn = get_connection()
    try:
        # -- Entity seeds --{"".join(entity_seeds)}
        # -- Edge seeds --{"".join(edge_seeds)}
        conn.commit()
        print("Seed complete.")
    finally:
        conn.close()

if __name__ == "__main__":
    run_seed()
'''


def _gen_app(title: str, app_name: str, entities: list[str], pages: list[str], port: int) -> str:
    """Generate main Flask app."""
    routes = []
    for page in pages:
        slug = page.lower().replace(" ", "_")
        route = "/" if slug == "dashboard" else f"/{slug}"
        routes.append(f'''
@app.route("{route}")
def page_{slug}():
    return render_template("{slug}.html")
''')

    api_routes = []
    for entity in entities:
        tbl = entity.lower() + "s"
        api_routes.append(
            f'''
@app.route("/api/{tbl}")
def api_{tbl}():
    conn = get_connection()
    try:
        rows = [dict(r) for r in conn.execute("SELECT * FROM {tbl} ORDER BY score DESC LIMIT 500").fetchall()]
        return jsonify({{"{tbl}": rows, "total": len(rows)}})
    finally:
        conn.close()
'''  # nosec B608 -- template content, not user input
        )

    return f'''"""{title} — Generated by AppForge Daemon."""
import argparse
from flask import Flask, jsonify, render_template, request
from models import get_connection, init_db

app = Flask(__name__)
{"".join(routes)}
{"".join(api_routes)}
@app.route("/api/graph")
def api_graph():
    conn = get_connection()
    try:
        edges = [dict(r) for r in conn.execute(
            "SELECT * FROM kg_edges ORDER BY weight DESC LIMIT 300"
        ).fetchall()]
        node_set = {{}}
        for e in edges:
            for p in ("source", "target"):
                key = f"{{e[p+'_type']}}:{{e[p+'_id']}}"
                if key not in node_set:
                    node_set[key] = {{"id": key, "type": e[p+"_type"], "label": e[p+"_id"][:12]}}
        return jsonify({{"nodes": list(node_set.values()),
                        "links": [{{"source": f"{{e[\'source_type\']}}:{{e[\'source_id\']}}",
                                    "target": f"{{e[\'target_type\']}}:{{e[\'target_id\']}}",
                                    "relation": e["relation"], "weight": e["weight"]}} for e in edges]}})
    finally:
        conn.close()

@app.route("/api/stats")
def api_stats():
    conn = get_connection()
    try:
        stats = {{}}
        for tbl in [{", ".join(f'"{e.lower()}s"' for e in entities)}, "kg_edges"]:
            try:
                stats[tbl] = conn.execute(f"SELECT COUNT(*) c FROM {{tbl}}").fetchone()["c"]
            except Exception:
                stats[tbl] = 0
        return jsonify(stats)
    finally:
        conn.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="{title}")
    parser.add_argument("--port", type=int, default={port})
    parser.add_argument("--seed", action="store_true")
    args = parser.parse_args()
    init_db()
    if args.seed:
        from seed_data import run_seed
        run_seed()
    app.run(host="0.0.0.0", port=args.port)
'''  # nosec B608 -- template content, not user input


def _gen_base_template(title: str, pages: list[str]) -> str:
    """Generate base.html template."""
    nav_links = []
    for page in pages:
        slug = page.lower().replace(" ", "_")
        href = "/" if slug == "dashboard" else f"/{slug}"
        nav_links.append(
            f'<a href="{href}" class="nav__link {{% if active == \'{slug}\' %}}nav__link--active{{% endif %}}">{page}</a>'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{% block title %}}{title}{{% endblock %}}</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <link rel="stylesheet" href="/static/css/app.css">
    {{% block head %}}{{% endblock %}}
</head>
<body>
    <nav class="nav">
        <div class="nav__brand">
            <span class="nav__title">{title[:30]}</span>
        </div>
        <div class="nav__links">
            {"".join(nav_links)}
        </div>
        <div class="nav__status"><span class="status-dot status-dot--green"></span> Operational</div>
    </nav>
    <main class="main">{{% block content %}}{{% endblock %}}</main>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script src="/static/js/app.js"></script>
    {{% block scripts %}}{{% endblock %}}
</body>
</html>"""


def _gen_page_template(page: str, slug: str, entities: list[str]) -> str:
    """Generate individual page template."""
    if slug == "knowledge_graph":
        return f'''{{% extends "base.html" %}}{{% set active = "{slug}" %}}
{{% block content %}}
<div class="page-header"><h1>{page}</h1></div>
<div class="card"><div class="card__body"><svg id="kg-svg" width="100%" height="600"></svg></div></div>
{{% endblock %}}
{{% block scripts %}}
<script>
fetch('/api/graph').then(r=>r.json()).then(data => {{
    const svg = d3.select('#kg-svg');
    const w = svg.node().parentElement.clientWidth, h = 600;
    svg.attr('width', w).attr('height', h);
    const sim = d3.forceSimulation(data.nodes)
        .force('link', d3.forceLink(data.links).id(d=>d.id).distance(80))
        .force('charge', d3.forceManyBody().strength(-100))
        .force('center', d3.forceCenter(w/2, h/2));
    const g = svg.append('g');
    svg.call(d3.zoom().on('zoom', e => g.attr('transform', e.transform)));
    const link = g.append('g').selectAll('line').data(data.links).join('line')
        .attr('stroke', '#444').attr('stroke-width', d => d.weight * 2);
    const node = g.append('g').selectAll('circle').data(data.nodes).join('circle')
        .attr('r', 6).attr('fill', '#6366f1')
        .call(d3.drag().on('start',(e,d)=>{{sim.alphaTarget(0.3).restart();d.fx=d.x;d.fy=d.y}})
            .on('drag',(e,d)=>{{d.fx=e.x;d.fy=e.y}}).on('end',(e,d)=>{{sim.alphaTarget(0);d.fx=null;d.fy=null}}));
    node.append('title').text(d => d.type + ': ' + d.label);
    sim.on('tick', () => {{
        link.attr('x1',d=>d.source.x).attr('y1',d=>d.source.y).attr('x2',d=>d.target.x).attr('y2',d=>d.target.y);
        node.attr('cx',d=>d.x).attr('cy',d=>d.y);
    }});
}});
</script>
{{% endblock %}}'''
    elif slug == "map" or "map" in slug:
        return f'''{{% extends "base.html" %}}{{% set active = "{slug}" %}}
{{% block content %}}
<div class="page-header"><h1>{page}</h1></div>
<div id="app-map" style="height:calc(100vh - 200px);border-radius:8px;border:1px solid #2a2a40"></div>
{{% endblock %}}
{{% block scripts %}}
<script>
const map = L.map('app-map', {{center:[25,0],zoom:2}});
L.tileLayer('https://{{s}}.basemaps.cartocdn.com/dark_all/{{z}}/{{x}}/{{y}}{{r}}.png',{{maxZoom:18}}).addTo(map);
fetch('/api/{entities[0].lower()}s').then(r=>r.json()).then(data => {{
    (data['{entities[0].lower()}s']||[]).forEach(e => {{
        if(e.lat && e.lon) L.circleMarker([e.lat,e.lon],{{radius:5,color:'#6366f1',fillOpacity:0.7}})
            .bindPopup('<b>'+e.name+'</b><br>'+(e.description||'')).addTo(map);
    }});
}});
</script>
{{% endblock %}}'''
    else:
        return f'''{{% extends "base.html" %}}{{% set active = "{slug}" %}}
{{% block content %}}
<div class="page-header"><h1>{page}</h1></div>
<div class="stat-grid" id="stats-grid"></div>
<div class="card"><div class="card__body card__body--no-pad">
    <table class="table table--striped" id="data-table">
        <thead><tr><th>Name</th><th>Description</th><th>Score</th><th>Status</th></tr></thead>
        <tbody id="data-body"></tbody>
    </table>
</div></div>
{{% endblock %}}
{{% block scripts %}}
<script>
fetch('/api/stats').then(r=>r.json()).then(stats => {{
    document.getElementById('stats-grid').innerHTML = Object.entries(stats).map(([k,v]) =>
        '<div class="stat-card"><div class="stat-card__value">'+v.toLocaleString()+'</div><div class="stat-card__label">'+k+'</div></div>'
    ).join('');
}});
fetch('/api/{entities[0].lower()}s').then(r=>r.json()).then(data => {{
    const rows = data['{entities[0].lower()}s'] || [];
    document.getElementById('data-body').innerHTML = rows.slice(0,100).map(r =>
        '<tr><td>'+r.name+'</td><td>'+(r.description||'')+'</td><td>'+(r.score?r.score.toFixed(2):'—')+'</td><td>'+(r.status||'—')+'</td></tr>'
    ).join('');
}});
</script>
{{% endblock %}}'''


def _gen_css(vertical: str = "") -> str:
    """Generate professional dark theme CSS with vertical-specific accent colors."""
    # Vertical-specific color palettes
    VERTICAL_THEMES = {
        "Cybersecurity & InfoSec": {
            "accent": "#ef4444",
            "accent_light": "#f87171",
            "gradient": "135deg,#991b1b,#dc2626",
            "success": "#22c55e",
            "icon_bg": "rgba(239,68,68,0.12)",
        },
        "Healthcare & Life Sciences": {
            "accent": "#06b6d4",
            "accent_light": "#22d3ee",
            "gradient": "135deg,#0e7490,#06b6d4",
            "success": "#10b981",
            "icon_bg": "rgba(6,182,212,0.12)",
        },
        "Financial Services & Banking": {
            "accent": "#f59e0b",
            "accent_light": "#fbbf24",
            "gradient": "135deg,#b45309,#f59e0b",
            "success": "#22c55e",
            "icon_bg": "rgba(245,158,11,0.12)",
        },
        "Energy & Utilities": {
            "accent": "#22c55e",
            "accent_light": "#4ade80",
            "gradient": "135deg,#15803d,#22c55e",
            "success": "#06b6d4",
            "icon_bg": "rgba(34,197,94,0.12)",
        },
        "Transportation & Logistics": {
            "accent": "#3b82f6",
            "accent_light": "#60a5fa",
            "gradient": "135deg,#1d4ed8,#3b82f6",
            "success": "#22c55e",
            "icon_bg": "rgba(59,130,246,0.12)",
        },
        "Manufacturing & Industrial": {
            "accent": "#f97316",
            "accent_light": "#fb923c",
            "gradient": "135deg,#c2410c,#f97316",
            "success": "#22c55e",
            "icon_bg": "rgba(249,115,22,0.12)",
        },
        "Space & Aerospace": {
            "accent": "#8b5cf6",
            "accent_light": "#a78bfa",
            "gradient": "135deg,#6d28d9,#8b5cf6",
            "success": "#22c55e",
            "icon_bg": "rgba(139,92,246,0.12)",
        },
        "Agriculture & Environment": {
            "accent": "#10b981",
            "accent_light": "#34d399",
            "gradient": "135deg,#047857,#10b981",
            "success": "#f59e0b",
            "icon_bg": "rgba(16,185,129,0.12)",
        },
        "Defense & Intelligence": {
            "accent": "#6366f1",
            "accent_light": "#818cf8",
            "gradient": "135deg,#4338ca,#6366f1",
            "success": "#22c55e",
            "icon_bg": "rgba(99,102,241,0.12)",
        },
        "Government & Civic Tech": {
            "accent": "#64748b",
            "accent_light": "#94a3b8",
            "gradient": "135deg,#334155,#64748b",
            "success": "#22c55e",
            "icon_bg": "rgba(100,116,139,0.12)",
        },
        "Telecommunications": {
            "accent": "#0ea5e9",
            "accent_light": "#38bdf8",
            "gradient": "135deg,#0369a1,#0ea5e9",
            "success": "#22c55e",
            "icon_bg": "rgba(14,165,233,0.12)",
        },
        "Education & Research": {
            "accent": "#a855f7",
            "accent_light": "#c084fc",
            "gradient": "135deg,#7e22ce,#a855f7",
            "success": "#22c55e",
            "icon_bg": "rgba(168,85,247,0.12)",
        },
    }
    default_theme = {
        "accent": "#6366f1",
        "accent_light": "#818cf8",
        "gradient": "135deg,#4338ca,#6366f1",
        "success": "#22c55e",
        "icon_bg": "rgba(99,102,241,0.12)",
    }
    t = VERTICAL_THEMES.get(vertical, default_theme)

    # Read base CSS and replace accent colors
    try:
        base_css = (BASE_DIR / "apps" / "geosigint" / "static" / "css" / "app.css").read_text(encoding="utf-8")
        # Replace CSS custom properties with vertical-specific colors
        base_css = base_css.replace("--accent: #6366f1", f"--accent: {t['accent']}")
        base_css = base_css.replace("--accent-light: #818cf8", f"--accent-light: {t['accent_light']}")
        base_css = base_css.replace(
            "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)", f"linear-gradient({t['gradient']}20, #16213e 100%)"
        )
        return base_css
    except FileNotFoundError:
        # Fallback: inline minimal CSS if GeoSIGINT CSS not available
        return f"""
:root {{ --bg:#0f0f1a; --bg-card:#1a1a2e; --border:#2a2a40; --text:#e0e0e0;
  --text-muted:#888; --accent:{t["accent"]}; --accent-light:{t["accent_light"]};
  --success:{t["success"]}; --warning:#f59e0b; --error:#ef4444; --radius:8px; }}
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ background:var(--bg); color:var(--text); font-family:system-ui,sans-serif; font-size:14px; }}
.nav {{ display:flex; align-items:center; gap:24px; padding:0 24px; height:56px;
  background:linear-gradient({t["gradient"]}20,#16213e 100%); border-bottom:1px solid var(--border); position:sticky; top:0; z-index:100; }}
.nav__title {{ font-size:18px; font-weight:700; color:var(--accent-light); }}
.nav__links {{ display:flex; gap:4px; margin-left:32px; }}
.nav__link {{ padding:8px 16px; border-radius:6px; text-decoration:none; color:var(--text-muted); font-size:13px; }}
.nav__link:hover {{ color:var(--text); background:rgba(99,102,241,0.1); }}
.nav__link--active {{ color:var(--accent-light); background:rgba(99,102,241,0.15); }}
.nav__status {{ margin-left:auto; font-size:12px; color:var(--text-muted); }}
.status-dot {{ width:8px; height:8px; border-radius:50%; display:inline-block; }}
.status-dot--green {{ background:var(--success); box-shadow:0 0 6px var(--success); }}
.main {{ padding:24px; max-width:1600px; margin:0 auto; }}
.page-header {{ margin-bottom:24px; }}
.page-header h1 {{ font-size:24px; font-weight:700; }}
.stat-grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:16px; margin-bottom:24px; }}
.stat-card {{ background:var(--bg-card); border:1px solid var(--border); border-radius:var(--radius); padding:20px; }}
.stat-card:hover {{ border-color:var(--accent); }}
.stat-card__value {{ font-size:28px; font-weight:800; color:var(--accent-light); }}
.stat-card__label {{ font-size:12px; color:var(--text-muted); margin-top:4px; text-transform:uppercase; }}
.card {{ background:var(--bg-card); border:1px solid var(--border); border-radius:var(--radius); overflow:hidden; }}
.card__header {{ padding:14px 20px; font-weight:600; border-bottom:1px solid var(--border); }}
.card__body {{ padding:16px 20px; }}
.card__body--no-pad {{ padding:0; }}
.table {{ width:100%; border-collapse:collapse; font-size:13px; }}
.table th {{ text-align:left; padding:10px 14px; font-weight:600; font-size:11px;
  text-transform:uppercase; color:var(--text-muted); border-bottom:1px solid var(--border); background:rgba(0,0,0,0.2); }}
.table td {{ padding:8px 14px; border-bottom:1px solid rgba(255,255,255,0.04); }}
.table--striped tr:nth-child(even) td {{ background:rgba(255,255,255,0.02); }}
.table tr:hover td {{ background:rgba(99,102,241,0.06); }}
"""


def _count_files(directory: Path) -> int:
    """Count files in directory tree."""
    return sum(1 for _ in directory.rglob("*") if _.is_file())
