# SAM deployment configuration for INTaaS SaaS
version = 0.1

[default.deploy.parameters]
stack_name = "intaas-saas-dev"
resolve_s3 = true
s3_prefix = "intaas-saas"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"
confirm_changeset = false

[default.build.parameters]
use_container = true

[staging.deploy.parameters]
stack_name = "intaas-saas-staging"
resolve_s3 = true
s3_prefix = "intaas-saas"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=staging"
confirm_changeset = true

[prod.deploy.parameters]
stack_name = "intaas-saas-prod"
resolve_s3 = true
s3_prefix = "intaas-saas"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"
confirm_changeset = true
